pymatgen/symmetry/groups.py

A fractional position such as [0.99999999, 0, 0] might not be recognized as equivalent to [0., 0., 0.].
Solved it with np.round(a, decimals=10).

SpaceGroup.get_orbit avoids duplicated positions

---

pymatgen/matproj/rest.py
pymatgen/matproj/tests/test_rest.py

This pull request adds the convenience function `get_materials_id_references(<mp-id>)` and the according test in MPRester to make use of the new MP REST API [endpoint](https://github.com/materialsproject/materials_django/compare/89710d0bf172319455baa47419d7658010523465~1...master) `materials/mp-123/refs`. For the purpose of [pre](https://github.com/materialsproject/pymatgen/compare/master...tschaume:master#diff-6821d60ec5218f73aefdd5318abfbc7eR102)-release [testing](https://gist.github.com/tschaume/fa8d0fc7ed29fe972d2c) (dev or local), MPRester can now be initialized with the more general `endpoint` instead of `host`. Please advise if you can think of a better solution for the latter.

MPRester: add get_materials_id_references()

---

pymatgen/matproj/rest.py
pymatgen/matproj/tests/test_rest.py

This pull request adds the convenience function `find_structure()` and according unit test to MPRester making use of the respective MP REST API [endpoint](https://github.com/materialsproject/materials_django/compare/materialsproject:00ec866...materialsproject:c368a32) ([Usage](https://gist.github.com/tschaume/fa8d0fc7ed29fe972d2c)).

MPRester: add find_structure()

---

pymatgen/io/nwchemio.py

This pull request implements parsing the lattice parameters from NWChem's output, if present. If lattice parameters are found in the output, an instance of ``Structure`` is created instead of ``Molecule`` and pushed in a separate list.

Patch proposed in issue #203 (Lattice parameters are not extracted from NWChem output)

---

pymatgen/io/vaspio/tests/test_vasp_input.py
pymatgen/io/vaspio/vasp_input.py

It was producing TypeError when used due to it passing in Incar/Potcar/etc instances to the file.write method.
Also, none of the tests called this method, so I added one.

Fix VaspInput.write_input (TypeError)

---

pymatgen/io/cifio.py

Current parser for CIF format files forbids CIF data_* header to be prefixed with space, what is completely normal, according to IUCr's CIF syntax specification (http://www.iucr.org/resources/cif/spec/version1.1/cifsyntax).
MWE (test.cif):
```
data_test_1
data_test_2
```
MWE (python script):
```python
from pymatgen.io.cifio import CifParser
c = CifParser("test.cif")
c.as_dict()
```
should produce:
```python
OrderedDict([(u'test_1', {}), (u'test_2', {})])
```

Allowing CIF data_* header to be prefixed with spaces and tabulations.

---

pymatgen/io/vasp/outputs.py

When [using the GW routines for the determination of frequency dependent dielectric matrix](http://cms.mpi.univie.ac.at/vasp/vasp/Using_GW_routines_determination_frequency_dependent_dielectric_matrix.html), there are multiple dielectricfuction elements in vasprun.xml, distinguished by element comments, and the Vasprun class is keeping the last one, which is actually the 'screened Coulomb potential'.
This tries to add support for these additional dielectricfunction elements without breaking the default behaviour by 
1. if there is no comment (there is only one dielectricfunction element), keeping the previous behaviour
2. if an element with comment "INVERSE MACROSCOPIC DIELECTRIC TENSOR (including local field effects in RPA (Hartree))" exists, storing it in the default dielectric attribute …

Multiple dielectricfunction elements in vasprun.xml

---

pymatgen/io/aiida.py

I present a converter between AiiDA StructureData and pymatgen Molecule/Structure objects. Since testing requires a sophisticated environment, it is done at AiiDA side.
Please check whether the method names comply with the pymatgen's style.

Converter between AiiDA StructureData object and pymatgen Molecule/Structure objects

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Changed Xdatcar class and unit test so that last configuration in XDATCAR is also read. The expected number of configurations read from the test files was incorrect (3); each XDATCAR test file contains 4 configurations

Xdatcar class did not read last configuration

---

pymatgen/io/vasp/outputs.py

I've extended the constructor of Xdatcar to enable successful treatment of multiple consecutive preambles in XDATCAR. That case seems rare, but I've just encountered it.

Problem with multiple preambles in XDATCAR

---

pymatgen/core/periodic_table.py

The list of Z values for chalcogen elements contained 18 instead of 16.

Fixed chalcogen numbering

---

pymatgen/io/qchem.py
pymatgen/io/tests/test_qchem.py

* For QChem versions >=4.2 the solvent parameter section is named "solvent" instead "pcm_solvent"
* Fix use_pcm method in QcTask

fix qchem use_pcm method

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Add a "reciprocal_volume" setting for kpoints_settings in vasp sets. This supplements "grid_density" and "length" settings and allows one to set the k-point density using spacing in reciprocal space.
Note that I would suggest also making "force_gamma" one of the kpoints_settings (instead of a constructor to VaspInputSets). I am not sure why this aspect of selecting the kpoint mesh is treated differently than the others.

add a reciprocal density parameter to vasp sets

---

pymatgen/io/vasp/inputs.py

`Kpoints.__init__`  now sets `self.style`, thus using a setter method to automatically convert a given string `style` to the proper enum type if possible.
* `Kpoints.__init__` is more lenient about its input `style`
* `Kpoints.from_dict` is shortened
Alternative solution:
In `Kpoints.from_dict`, could change `Kpoints.supported_modes[generation_style]` to `Kpoints.supported_modes.from_string(generation_style)`, but it seems cleaner to remove that spot conversion entirely and delegate to `Kpoints.__init__`.

Make Kpoints init convert style string to enum

---

pymatgen/analysis/structure_analyzer.py

- Error faced: "AttributeError: specie" when running get_voronoi_polyhedra() for a site that has as its nearest neighbor (nn) a disorderd site. 
- Proposed fix: separate handling of disordered nn, get elements contained on the site, check if present in structure, and update the weighted polyhedra. 
- Attachment: example structure (as a dictionary) tested with
[structure_sd_1615854.json.zip](https://github.com/materialsproject/pymatgen/files/210750/structure_sd_1615854.json.zip)

handle disordered species

---

pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/tests/test_inputs.py

This pull request addresses [Issue #325](https://github.com/materialsproject/pymatgen/issues/325).
- Fixed the parsing of predictor-corrector data from an MD CONTCAR.
- Preamble (key, POTIM, thermostat parameters) for the predictor-corrector data is stored in Poscar.

Predictor-corrector parsing and storage

---

pymatgen/core/periodic_table.py

Some attribute data contains brackets, which raises an error when converting to a FloatWithUnit. 
* Fix: remove bracketed data
Element('P').melting_point = "(white P) 317.3 K"

handle bracketed data in attribute data for Elememt

---

pymatgen/core/periodic_table.py

Base 10 powers occur in "electrical_resistivity" and "coefficient_of_linear_thermal_expansion" which were not handled, thus returning a string instead of a FloatWithUnit object
* Fix: extract the factor and add it to the float, define the unit for the above two attributes (since such factors only seem to be present there), and return a FloatWithUnit object for these attributes. 
Example, the code,
from pymatgen import Element, FloatWithUnit
el = Element('Al')
print el.melting_point
print float(el.melting_point)
print el.melting_point.unit
print el.thermal_conductivity
print float(el.thermal_conductivity)
print el.thermal_conductivity.unit
print el.coefficient_of_linear_thermal_expansion
print float(el.coefficient_of_linear_thermal_expansion)
print …

handle base 10 powers that exist in two Element attributes

---

pymatgen/core/tests/test_periodic_table.py

Correct unit test of Al's electrical resistivity which should be 2.7e^-8 ohm m, and not 2.7 ohm m.

correct unit test of periodic_table.py

---

pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/tests/test_inputs.py

Allow [x,y,z] values for each ion in MAGMOM when LSORBIT or LNONCOLLINEAR is set.
This makes the "MAGMOM" value a list of lists for spin-orbit coupling calculations. Please see the tests.

enable setting 3d MAGMOM in incar for spin-orbit coupling calculations

---

pymatgen/io/vasp/inputs.py

Revision to properly handle the specific case when a _Structure_ that has predictor_corrector site_properties (e.g. obtained from a _Poscar_ parsed from MD CONTCAR) is reused to generate a new _Poscar_ and write inputs.
* Fix: Rather than raising a ValueError for missing predictor_corrector_preamble, a warning is raised and POSCAR is properly written excluding the entire predictor corrector chunk.
* This fix ensures that; for example, the existing MITMDVasp input sets work as before, with a Structure obtained from a previous MD run, without raising a "No predictor corrector preamble" error.

Minor fix in vaso.io.inputs

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Uses @xhqu1981's table parser for the elastic and piezo tensors.
* Elastic and piezo tensors read in separate methods using read_table_pattern
* Elastic and piezo tensors are stored in outcar.data, rather than as attributes of outcar
It looks like some parts of the lepsilon parsing methods should be refactored as well using the table_parsing method.  I can go ahead and refactor these as seems prudent from the code, but I don't know much about how these methods are used.

Refactor outcar

---

pymatgen/core/lattice.py

Removed glitch when attempting to (unsuccessfully) multiply a float carrying a length unit with a non-units carrying matrix in lattice.py.
The weird part was that for some structures that I'm currently testing the issue resulted in a true error and sometimes not.

Removed glitch 

---

pymatgen/io/vasp/inputs.py

* add read_velocities option in Poscar class method from_file
* check velocities when write a POSCAR file
I write a comment in case of there is a better way to solve the problem. The pull request solve the error of the example at the end of this message.
Actually, the problem comes from the site_properties property of the Structure class (see below). 
```py
@property
def site_properties(self):
"""
Returns the site properties as a dict of sequences. E.g.,
{"magmom": (5,-5), "charge": (-4,4)}.
"""
props = {}
prop_keys = set()
for site in self:
prop_keys.update(site.properties.keys())
for k in prop_keys:
props[k] = [site.properties.get(k, None) for site in self]
return props
```
That property returns the value None if you ask for a property which does not exist for the given site of the …

add read_velocities option in Poscar

---

pymatgen/io/vasp/inputs.py

Minor fix to INCAR that allows file parsing to read DIPOL key.
Fixes an issue where Incar.from_file was reading only first number in 3-tuple of DIPOL.

Added "DIPOL" to list_keys in incar

---

pymatgen/analysis/elasticity/elastic.py
pymatgen/analysis/piezo.py
pymatgen/analysis/tests/test_piezo.py

This PR refactors PiezoTensor to subclass TensorBase primarily so that it inherits the fit_to_structure and is_fit_to_structure methods, rather than implementing the symmetrization methods explicitly.  Note that, like ElasticTensor, PiezoTensor's default constructor now takes the 3x3x3 true tensor notation as input, and uses PiezoTensor.from_voigt to construct from the Voigt-notation 3x6 matrix.
* PiezoTensor subclasses TensorBase
* Removed PiezoTensor-specific symmetrization operations
* Fixed some typos in documentation of elasticity
* Updated Piezo unittests accordingly
PiezoTensor needs a few more methods associated with calculations on the MP website, i. e. maximum piezoelectric modulus and direction.

Refactor piezo

---

pymatgen/core/structure.py
pymatgen/io/cif.py

* Problem:
CifParser parses the attached cif file ([Al2CuO4_orig.cif.zip] https://github.com/materialsproject/pymatgen/files/278361/Al2CuO4_orig.cif.zip)
) as ordered, but the lines, 
Al,Cutet '0.615(5)Cu + 0.385(5)Al' .8a .-43m 0.125 0.125 0.125 1 ? '?'
Cu,Aloct '0.807(3)Al + 0.193(3)Cu' .16d ..-3m 0.5 0.5 0.5 1 ? '?'
in the cif file indicate disorder on these sites. 
* Proposed fix:
Parse the above lines with elements and occupancies to introduce disorder to the site.

correct handling of disordered structures that are incorrectly parsed as ordered by CifParser

---

pymatgen/io/gaussian.py

If the `core.physical_constants` module will be removed in pmg 4.0 as the module warns, this change or similar is necessary. Currently, a deprecation warning is given with as little as `from pymatgen import __version__`.
* `pymatgen.core.physical_constants` --> `scipy.constants`
* define `HARTREE_TO_ELECTRON_VOLT` locally
* Other constants (`h`, `c`, and `e`) used in file are already members of `scipy.constants`

internal pmg4 compat: use scipy.constants

---

pymatgen/symmetry/analyzer.py

_spacegroup_data["number"] is `long`. Can safely cast to `int` and match method signature.
Closes #421

Cast spacegroup_number to int

---

pymatgen/analysis/elasticity/tensors.py
pymatgen/analysis/elasticity/tests/test_tensors.py

Added  a Rotate_Tensor method to the TensorBase class which rotates a tensor from a given initial structure's basis to the final structure's basis, useful for comparing tensors from the primitive unit cell to the conventional cell or whatever final reference from we look at. Associated unit tests also added.

Added Rotate_Tensor method to TensorBase class which rotates a tensor… 

---

pymatgen/io/cif.py
pymatgen/io/tests/test_cif.py
test_files/PF_sd_1002871.cif
test_files/PF_sd_1011081.cif
test_files/PF_sd_1500382.cif
test_files/PF_sd_1601634.cif
test_files/PF_sd_1615854.cif
test_files/PF_sd_1622133.cif
test_files/PF_sd_1704003.cif
test_files/PF_sd_1811457.cif
test_files/PF_sd_1908491.cif
test_files/PF_sd_1928405.cif

While parsing 225k CIF files from the Springer materials/Pauling file DBs using CifParser, numerous errors were faced, which were earlier fixed at my end, but now I have tried to introduce those capabilities directly in CifParser. 
Here's a summary of changes made. They passed all the tests in test_cif.py (including the new ones added in this request) so hopefully that shouldn't throw any errors. Also, I am of course open to discussing if some of these changes should be implemented in a different/better way. 
* Feature: the following line in a CIF file,
T1(o) '0.75Si + 0.25Al' .4i .1 0.0098(1) 0.1747(1) 0.2113(1) 1 ? '?'
made the file unparsable due to unrecognizable label and symbol. The fix recognizes this as a disordered site with occupancies parsed from the symbol string "0.75Si + …

incorporate capabilities in CifParser to handle various errors faced while parsing CIFs from the Springer materials/Pauling file DBs

---

pymatgen/io/vasp/sets.py

get_structure_from_prev_run used to pop LDAU parameters in incar of the passed vasprun object in place. This resulted in missing LDAUU, LDAUJ and LDAUL parameters (all become empty lists) for all input sets created (e.g. MPStaticSet) with from_prev_calc methods.

Fixed missing LDAU params in input sets derived with from_prev_calc methods

---

pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py

Change the implementation of interpolate_lattices. Previously, the
parameters for the lattice (a, b, c, alpha, beta, gamma) were all
linearly interpolated to the parameters of the second structure. 
However, this can lead to various issues, including
that the interpolated volumes are not guarenteed monotonic. This is
resolved via interpolating the lattice matrices directly.

Change the implementation of Structure.interpolate_lattices.

---

pymatgen/phasediagram/entries.py
pymatgen/phasediagram/tests/test_entries.py

Fix PDEntry.from_dict to accommodate no-name entry dicts. Add a test for this.
I encountered this issue when using `monty.json.MontyEncoder` to `json.dumps` Pourbaix entries. I could ensure this dumps 'name's for each entry, but `PDEntry.from_dict` should also just accommodate no-name entries as `PDEntry.__init__` specifies.

Fix PDEntry.from_dict to accommodate no-name dicts

---

pymatgen/core/structure.py

This is a suggestion. I was using the format material_name_POSCAR for several of my materials and I needed to read them via Structure.from_file but I couldn't. With *POSCAR* file naming is more flexible than just POSCAR* which was previously.

using *POSCAR* in to and from_file functions to add more flexibility

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py
test_files/OUTCAR.icorelevel

Added a fix for the core state eigenenergies parsing, and also an additional test and an associated OUTCAR (GaAs from mp-2534 with ICORELEVEL=1) since none of the existing OUTCARs in test_files have core state eigenenergies with d-levels.
Fixes #447

Fixes parsing of core state eigenenergies #447 and adds additional test

---

pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
pymatgen/analysis/transition_state.py

* Added property ce_symbol in CoordinationGeometry (same as mp_symbol) in chemenv
* Fixed NEBAnalysis's piecewise polynomial construction for scipy versions > 0.18.

ce_symbol in chemenv and fix of piecewise polynomial in nebanalysis for scipy > 0.18

---

pymatgen/io/feff/outputs.py
pymatgen/io/feff/sets.py

* remove kwargs in inputsets: keep it simple
* fix parsing of the absorbing atom from the reciprocal space calculation outputs

feff updates

---

pymatgen/io/gaussian.py
pymatgen/io/tests/test_gaussian.py
test_files/molecules/H2O_gau_vib.out

* read in hessian matrix : need #P in route line
* read IR intensity, force constant and reduce mass
* compatibility break on frequency attributes of GaussianOutput object. Frequency is still a list for each frequency calculations and for each mode. But for each mode it contains a dictionary such as :
```py
{'IR_intensity': 97.3057,
'f_constant': 1.7649,
'frequency': 1662.8033,
'mode': [0.0, 0.07, 0.0, -0.42, -0.56, 0.0, 0.42, -0.56, 0.0],
'r_mass': 1.0834,
'symmetry': "A'"},
```

Frequency and hessian matrix from gaussian output files

---

pymatgen/electronic_structure/boltztrap.py
pymatgen/electronic_structure/tests/test_boltztrap.py

a few things are added to BoltztrapAnalyzer:
intrans as an input: it is a dictionary of inputs with which the boltztrap had been run before; it can be obtained via parse_intrans method from boltztrap.intrans file if BoltztrapAnalyzer is called via "from_files" method.
Justification:
when I call BoltztrapAnalyzer on a bunch of files that belong to a boltztrap run, I want to know if the run was on a normal band structure that was untouched or it was on a scissored band structure. In this way, we can also differentiate later in the database between the data from these two types of results.

adding parse_intrans method to BoltztrapAnalyzer to obtain scissor value, etc

---

pymatgen/io/vasp/sets.py

In the previous implementation only high-symmetry points are included in the KPOINTS file which result in a wrong band structure (I tested this on ZnS). So now, the from_prev_calc method either only adds the VBM and CBM k-points (mode=="Uniform") or add the entire high-symmetry k-points (mode =="Line")

High-symmetry k-points are added to IBZKPT from static

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

adding the option "gap" to the argument mode in MPHSEBSSet to distinguish between "uniform" and "gap" modes when ran from previous calculations. Also a test was added for the "gap" mode. Sometimes we want just to run the uniform k-points and don't need the CBM and VBM but the previous implementation didn't allow that.

adding the option "gap" to mode in MPHSEBSSet.from_prev_calc

---

pymatgen/analysis/defects/point_defects.py

<When interstitial is created with no valences dictionary, ignore charge assignment>
* When interstitial is created with no valences dictionary, ignore charge assignment
<Merge the Zeo++ python 3 changes and debug spglib errors>

Bug fixes for Interstitial creation with  no valence dictionary

---

pymatgen/electronic_structure/plotter.py

A new band structure plotter that puts band structure and DOS on the same plot, aligned.
* Band structures include spin polarization
* Element projections on band structures supported
* Element and orbital projections on DOS supported
* Code is relatively straightforward to use, understand and modify as needed
None
Things that could be done:
- support element projections for band structures with 4 or more elements (only 3 of those elements would actually be projected, the remaining elements ignored)
- support element+orbital projections for band structures

add BSDOS plotter

---

pymatgen/io/qchem.py
pymatgen/io/tests/test_qchem.py
test_files/molecules/pt_dft_180.0.qcout

I've added the opt section to the qchem input file, which allows for constraining bond lengths, torsion angles, etc. 
* Opt CONSTRAINT section added to qchem input files
* Opt section parser added
* unittest added
* unittest switch from unittest2 to unittest 
* only CONSTRAINT added to opt section as this point. Others opt options such as FIXED would need to added

opt section added allowing for torsion constraints

---

pymatgen/electronic_structure/boltztrap.py
pymatgen/electronic_structure/tests/test_boltztrap.py

- bands check works for metals
- update the write_proj function to use properly the Orbital enum and new projections format
- added the k_el option to the get_thermal_conductivity function 
(k_el = True  is the default output k_0 -PF*T, as before. If False k_0 is returned)
- fixed a bug in the FERMI mode
- included a check of ERROR msg in the boltztrap output inside the convergence loop of BoltztrapRunner
- fix kpt_line option for bands mode. Now it works  for both a list of fractional coords as arrays or a list of Kpoint objects.
- fix case lpfac > max_lpfac in case of convergence=False (fermi,bands,dos cases)

small update of boltztrap.py

---

pymatgen/analysis/elasticity/__init__.py
pymatgen/analysis/elasticity/elastic.py
pymatgen/analysis/elasticity/strain.py
pymatgen/analysis/elasticity/stress.py
pymatgen/analysis/elasticity/tensors.py

Minor reorganization and bug fixes.
* elasticity classes/functions can now be imported from the top-level module, i. e. `from pymatgen.analysis.elasticity import ElasticTensor`. 
* Minor bug fix concerning improper rotations with the option to exclude for TensorBase
* Added a test to deformation/strain conversion function

Minor elastic fix

---

pymatgen/electronic_structure/bandstructure.py

previously, if the conduction band minimum is equal to Fermi level, the code excludes it and return a neighbor data point.

update cbm module to make 0eV cbm discoverable

---

pymatgen/vis/structure_chemview.py
requirements-optional.txt

* A handy function  for quick visualization of pymatgen structures in jupyter notebook. 
Optional dependency on an external package called chemview (https://github.com/gabrielelanaro/chemview). Will raise a proper import error upon use if chemview is not installed.

visualize pymatgen structures in jupyter notebook

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Added a new function to the `Outcar` class to load in the average core potentials of each atom at all ionic steps. A test for this method was also added and is passing.
Some blank spaces at the end of lines were removed by vim python-mode- apologies for cluttering the pull request.

Method to load the averaged core potentials from OUTCAR

---

pymatgen/analysis/diffusion_analyzer.py
pymatgen/analysis/tests/test_diffusion_analyzer.py

Make DiffusionAnalyzer class compatible with NPT-AIMD diffusion analysis.
* Added a new attribute *lattices*. For NVT simulation, the attribute is a one-item list; for NPT simulation, the attribute includes all lattice matrix, which is used in *get_drift_corrected_structures()*.
* Use fractional coordinates instead of Cartesian coordinates.
* Minor change for the unit test
* Throw warning when *get_framework_rms_plot()* is called during NPT analysis.
None
None

Enable NPT-AIMD simulation

---

pymatgen/electronic_structure/boltztrap.py
pymatgen/electronic_structure/tests/test_boltztrap.py

- get_average_eff_mass upgrade: now it returns values for all the energies,
using doping_level=False like other functions
- small patch for DOS run_type

get_average_eff_mass improved and small patch for dos run_type

---

pymatgen/electronic_structure/boltztrap.py
pymatgen/electronic_structure/plotter.py
pymatgen/electronic_structure/tests/test_boltztrap.py

The function plot_fermi_surface of plotter module has been rewritten.
It now uses Mayavi package (mandatory) to calculate and potting the surface.
The dependency from ASE for reading CUBE files has been replaced with a new internal function.
It allows to plot fermi surfaces from cube file produces by both boltztrap (using BoltztrapAnalyzer.fermi_surface_data) or other softwares (reading the file with the read_cube_file function).
It plots different surfaces in different figures or all in one figure.
It returns both the last figure and the module mayavi in order to allow you to plot different data
in the same figure.
Color and transparency of surfaces are tunable.
Labels of kpoints will be shown in the Brillouin zone if a proper dictionary of kpoints coords is provided.

New function to plot fermi surfaces using Mayavi tool 

---

pymatgen/electronic_structure/plotter.py

This PR adds a new style of legend to the BSDOSPlotter, the rgb_legend, which is by default False. If enabled, it can add a colored RGB triangle (ternaries) or RB bar (binaries) to show how the various colors on projected plots map to element ratios.
Note that the alternate (default) style is a more conventional style of legend.
Some examples of the rgb_legend style are shown below
Also, thanks to Jan Pohls for sharing his code from which this was based.
None
* Unfortunately, as can be seen in the above diagrams, the band structure plots can overlap the legend diagrams in some systems. In the limited time I had to develop this, I was not able to develop a fix. e.g., simply adding a matplotlib rectangle Patch object to try to cover up the band structure and create more of a "legend" style …

Add rgb_legend style to BSDOSPlotter

---

pymatgen/symmetry/analyzer.py

In SpacegroupAnalyzer the defined value of symprec is not propagated to spglib when calling the get_ir_reciprocal_mesh function, that instead uses a default of 1e-5. This may lead to unexpected behaviours and inconsistencies between the obtained space group and the list of irreducible kpoints. This pull request fixes this problem passing self._symprec to the function. 
Notice that the get_ir_reciprocal_mesh function in spglib does not accept angle_tolerance as an argument.

Pass the user defined symprec to spglib.get_ir_reciprocal_mesh 

---

pymatgen/electronic_structure/plotter.py

This is just a subtle change to the BSDOS coloring (both in the plot as well as in the legend). RGB values are interpolated based on square values. The reasoning is explained in this video:
https://youtu.be/LKnqECcg6Gw
Thanks to Matt Horton for pointing this out.
The squared values indeed lead to more pleasing results as can be seen in the before/after shots below. A blind test of a colleague demonstrated that in the GaP plot in particular, more information was gleaned about the band structure projections using the new coloring. For the KTaO3 example it's clearest to see how the coloring changes in the legend, the actual plot looks similar.
Before:
After:
Before:
After:

BSDOS color interpolation update

---

pymatgen/electronic_structure/boltztrap.py

Symprec variable has been fixed:
- the default value now is 1e-3 consistent with other method in pymatgen
- it is also possible to pass a different symprec to BoltztrapRunner when
the list of kpoints has been generated with a different symprec.
This can be useful to cure the "factorization error" of BoltzTraP calculations.

Symprec variable fixed

---

pymatgen/electronic_structure/plotter.py

Various improvements to fancy BSDOSPlotter legend
* Uses a separate inset axis to plot legend
* This ensures the aspect ratio of legend stays consistent for different band structures
* It also visually separates the legend from the background better
* Now rgb_legend style is by default True
The plots now look like this:

Improvements to BSDOSPlotter legend

---

pymatgen/symmetry/bandstructure.py

This PR addresses the problem highlighted in issue #581 adding a warning if the lattice of structure does not match the one of the primitive standard.

Warning for non standard structures in HighSymmKpath

---

pymatgen/analysis/defects/point_defects.py
pymatgen/io/zeopp.py

Long pending modifications with respect to Zeo++ implemented.
* python3 compatibility for Zeo++ python bindings  
* SpagegroupAnalyzer.get_symmetrized_structure fails for dense voronoi points. Voronoi points are pruned if close before passing to SpgA
* Zeo++ installation instructions added 
<Zeo++>

Bug fixes in Interstitial class and Zeo++ python 3 compatibility

---

pymatgen/analysis/adsorption.py
pymatgen/analysis/tests/test_adsorption.py

Small update to adsorption module, fixes to structure generation for adsorbate structures
* AdsorbateSiteFinder can generate adsorption structures and pass arguments into the site finding function
* Relevant unittests added

fixes to generate_adsorption_structures and tests

---

pymatgen/electronic_structure/plotter.py

Dear master,
I wrote a new method named "get_projected_plots_dots_patom_pmorb" in plotter.py file. This is an extension of the old method "get_projected_plots_dots" and still in the class "BSPlotterProjected". Here are some features of this method:
- Get projections on specific atoms (e.g. Cu1, O3, Zn4) or on a group of the same-type atoms (e.g. Cu1+ Cu2+ Cu3) in computed structure.
- Get projections on specific individual orbitals (e. g. px, py, pz, dxy, dyz,...) or on sum of these orbitals (e.g. px+py, px+py+pz, s+px+py+pz,...)
- Get projections for selected branches of band-structure in the case you do not want to show all of them.
- Customize the size of the figure and the arrangement of all subfigures (columns and rows).
Best regards, 
Anh.

get_projected_plots_dots_patom_pmorb

---

pymatgen/analysis/reaction_calculator.py
pymatgen/analysis/tests/test_reaction_calculator.py
pymatgen/io/vasp/outputs.py
pymatgen/phasediagram/analyzer.py

Cleaned up the reaction balancing.
Changed string formatting of reactions to avoid superfluous zeros and decimals. Also made the reaction strings consistent with each other (the formatting of different methods was slightly different).
Redefined and documented how Reactions are balanced by default. This is backwards incompatible, but the previous default was not documented or intuitive.
Fixed some weird balancing issues, for example, balancing
Fe + Na + Li2O + Cl -> FeCl2 + Na2O + Xe + LiCl + Mn
used to return
2 Na + Li2O + 5 FeCl2 -> 5 Fe + 4 Cl2 + Na2O + 2 LiCl
now it returns
Fe + 2 Na + Li2O + 2 Cl2 -> FeCl2 + Na2O + 2 LiCl
which is more reasonable. (Though this is obviously a contrived example.)

Reaction Balancing

---

pymatgen/analysis/reaction_calculator.py
pymatgen/analysis/tests/test_reaction_calculator.py
pymatgen/phasediagram/analyzer.py
pymatgen/phasediagram/tests/test_pdanalyzer.py

* Refactor PDAnalyzer.get_element_profile to use get_critical_compositions instead of generating new PDs
* More helpful error message in Reaction for underdetermined reactants. I don't think there's a useful result to return in these cases.
* Better unittests for get_element_profile

Refactoring of PDAnalyzer.get_element_profile

---

pymatgen/electronic_structure/plotter.py

Sometimes long kpaths result in figures where kpoint labels overlap each other. Allowing user to change figure size can stretch the figure out so this does not occur. Defaults to previous default size dimensions (11, 8.5)  if user does not specify.
N/A
N/A

BSDOSPlotter figure size option

---

pymatgen/io/vasp/outputs.py

Hybrid band structures created with `linemode=True` now discard any projections for weighted k-points.
Fixes #602

Correct handling of band structure projections for hybrid calculations.

---

pymatgen/io/vasp/outputs.py

When fixing #602 I didn't check that the band structure had projections before discarding those corresponding to weighted k-points. As such trying to run `vr.get_band_structure()` when projections are not loaded results in an error.
This pull request fixes that bug.
However, this and #543 highlight the need for proper testing of the band structure functionality in pymatgen.

Fix bug in get_band_structure()

---

pymatgen/core/structure.py
pymatgen/electronic_structure/boltztrap.py

Current boltztrap run with the output only in console, there is few log for us to know what pymatgen have down.
So I add logging to run method and BoltztrapError class, i have test a little, and hope everything will work.

add logging to boltztrap

---

pymatgen/analysis/elasticity/elastic.py
pymatgen/analysis/elasticity/tensors.py
pymatgen/analysis/elasticity/tests/test_elastic.py

* Fixes an issue with subclass structure in new elastic tensors
* Renames central_diff_fit to diff_fit, since central difference stencils are no longer required
* Adds unit tests for elastic tensor expansion and subclasses

Fixes and additional unit tests for higher order elastic tensors

---

pymatgen/analysis/pourbaix/maker.py

In the case of Pourbaix diagrams for 3 or more elements, weights of multi-entries were incorrectly computed. Weights were fixed by using an algorithm based on the Rouche-Capelli Theorem.
No additional dependencies were introduced.

major changes for computing weights of multi-entries

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_outputs.py
pymatgen/io/vasp/tests/test_sets.py
test_files/OUTCAR.BaTiO3.polar

Modified Outcar __init__ method:
* Check for ISPIN = 2 and if so set self.spin = True
* Check for LNONCOLLINEAR = T and if so set self.noncollinear = True
* Check for LCALCPOL = T and if so run read_lcalcpol
Modified Outcar read_lcalcpol method:
* If self.spin = True, read spin polarized dipole moment to properties p_sp1 and p_sp2
Added tests to vasp.tests.test_outputs for changes to Outcar under test_polarization
Added tests to MPStaticSet for LCALCPOL flag.
Added test_files/OUTCAR.BaTiO3.polar for Outcar polarization test
More polarization related pull requests that use these functions coming soon.

Added to Outcar and MPStaticSet to support LCALCPOL VASP flag

---

pymatgen/core/operations.py
pymatgen/core/tests/test_operations.py
pymatgen/electronic_structure/core.py
pymatgen/electronic_structure/tests/test_core.py

Proposal for a simple `MagSymmOp` class. This subclasses `SymmOp`, adding a time reversal operator. It also includes an `operate_magmom()` method which acts to transform the magnetic moment on an atom when a magnetic symmetry operation is performed.
This is used for #508 and also in a new `MagneticSpaceGroup` class for a magnetic version of `symmetry/groups.py`, currently in development.
None
None

Proposal to add MagSymmOp class

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Currently, it's non-obvious how a user would add a custom `LDAUU` value to their `user_incar_settings` that would be used in the general case (regardless of what anions are in the input structure).
From my reading of `sets.py` it seems like if a user wants to set (e.g.) a custom `LDAUU` value for Fe, they would need to see if their structure is (e.g.) an oxide and then supply `user_incar_settings={'LDAUU':{'O':{'Fe':5}}}`. This seems non-obvious, and also would mean that `user_incar_settings` needs to be customized for every structure. The only other way I can see to do this is to add a `LDAUU` site_property but, again, this would require modification of every input structure.
This PR would add a fallback option, so that e.g. `user_incar_settings={'LDAUU':{'Fe':5}}` would work as expected …

Make it easier for user to submit custom LDAUU

---

pymatgen/electronic_structure/boltztrap.py

the default type of p.communicate() is bytes in python3, the log info will not display as we wish.

update info format for bolztrap.out

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

`Outcar.read_freq_dielectric()` had a typo when assigning the dielectic tensor components to full tensors, making the data stored in `self.dielectric_tensor_function` have asymmetric off-diagonal elements. This update fixes this.
* `read_freq_dielectric()` now generates symmetric dielectric tensors.

Fix for dielectric tensors read from OUTCAR not being symmetric

---

pymatgen/matproj/rest.py

MPRester users are having issues decoding SNL objects due to `pybtex` no longer being installed by default by pymatgen. This issue was raised before as #519. I would love to have `pybtex` required, but as an alternative, this PR adds a user warning to install extras.
* Emits `UserWarning` if cannot import `pybtex`
* Gives one-liner `pip install` command to ensure matproj.snl dependencies.

Warn MPRester user about need to install matproj.snl extras

---

pymatgen/analysis/ewald.py

Now if compute_forces is set to False, will allow __str__ method to print without error from trying to calculate self.forces.
- Bug fix with printing the EwaldSummation object with default value of compute_force
N/A
N/A

Avoid force calculation error when printing

---

pymatgen/symmetry/maggroups.py

Class retrieves a binary blob from the sqlite database and converts it to a byte `array`. At some point, the `array` constructors changed from accepting a string to accepting a buffer.
At present, I can't find a constructor that works in both Python 2.7 and Python 3.6, so have wrapped it in a try/except.
Apologies for this! Have set up proper Python 2.7 testing locally to catch this in future.

Fix MagneticSpaceGroup for Python 2.7

---

pymatgen/symmetry/maggroups.py

Nosetests supply label string as `unicode` type, which wasn’t being
caught by `if isinstance(…, str)` statement leading to no SQL query
being generated.

Fix MagneticSymmteryGroup for unicode arguments in Python 2.7

---

pymatgen/electronic_structure/plotter.py

Added color differentiation between plot_1 and plot_2 in plot_compare, an option to print a legend, and fixed a bug preventing plot_compare from ever succeeding. 
In BSPlotter.plot_compare(other_plotter), the indentation level of the block regarding the spin-down channel was incorrect, and the content of the block itself was incorrect, causing:
1. Spin-down BS to be evaluated only in one branch
2. The band number being used in-place of the k-point branch
Point 1 was merely incorrect, while point 2 would lead to an index-out-of-range error, and the plot to fail. This pull request fixes the syntax so that plot_compare works properly.

Glitch in BSPlotter.plot_compare

---

pymatgen/matproj/snl.py
pymatgen/matproj/tests/test_snl.py

Ensure SNL references is a string rather than any falsy value. Prevents downstream surprises for users who e.g. submit SNLs in bulk to Materials Project. Thank you @shyamd for discovering this.
* Type-check on SNL construction
* Add unit tests for "empty" references

Ensure SNL references is a string rather than any falsy value

---

pymatgen/io/cif.py
pymatgen/io/tests/test_cif.py
test_files/magnetic.disordered.example.CuMnO2.mcif
test_files/magnetic.example.NiO.mcif
test_files/magnetic.incommensurate.example.Cr.mcif
test_files/magnetic.ncl.example.GdB4.mcif

* Adds read support and partial write support for the magCIF standard (preliminary v1 dictionary available [here](http://comcifs.github.io/magCIF.dic.html)).
* This was developed as a separate class based on `CifParser`, but given that `CifParser` itself has seen recent changes, it seemed sensible to combine them now before they diverge too much.
* CifParser changes:
* Includes a new CIF `feature_flags` dictionary (extensible for other non-core CIF features), checks to see if a file is magCIF
* If magCIF, will try to place atoms:
* First by magnetic symmetry operations, if provided (most common case)
* If not, then by BNS symmetry group, if provided
* Will output a Structure with magnetic moments on site properties
* Note that this means disordered magnetic structures not currently …

Add magCIF support to CifParser and CifWriter

---

pymatgen/electronic_structure/boltztrap.py

Boltztrap runner tried to evaluate truth of doping variable to test if None or array.
Can't evaluate truth of an array in py2 directly
Fixed by testing if list and ensuring list size greater than 0

Fixed bug in boltztrap runner with alternate dopings

---

pymatgen/analysis/adsorption.py

From using plot_slab in the adsorption module, I was getting a 
`TypeError: 'zip' object is not subscriptable`
This error came from `lim[0]` where `lim` is a zip object. This was okay in Python 2, but in Python 3, the zip object cannot be indexed like this anymore.
Therefore, I have made a simple change by using putting them into a list and use list comprehensions instead. This change was tested and it works in my development environment.

Debug plot_slab from adsorption module

---

pymatgen/electronic_structure/boltztrap.py

Fixed the from_dict function which was previously passing variables to the constructor in order and was garbling up variables after DOS due to intrans being in the middle.
Fixed the linalg inversion in get_average_eff_mass to try and catch the linalg exception. This can be caused by a matrix of zeros, which can't be inverted. Why boltztrap spits this out, I don't know.

More boltztrap fixes

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py
test_files/OUTCAR.LOPTICS.vasp544

In VASP 5.4.4, there are two datasets given in OUTCAR for dielectric function (LOPTICS=True). One is "density-density" and the other is "current-current". The first data set has values of IMAGINARY and REAL as the old VASP version (e.g vasp.5.4.1). This push adds the feature of extracting the first dataset of VASP5.4.4 while keeping the functionality of old read_freq_dielectric.

add dielectric function parser for vasp5.4.4

---

pymatgen/io/pwscf.py

See http://www.quantum-espresso.org/wp-content/uploads/Doc/INPUT_PW.html#idm140629872670512
PWscf gives an error if the namelists are out of order. ATOMIC_SPECIES should come before ATOMIC_POSITIONS.

Fix ordering of ATOMIC_SPECIES and ATOMIC_POSITIONS

---

pymatgen/analysis/structure_analyzer.py
pymatgen/analysis/tests/test_structure_analyzer.py

* This PR extends the `get_dimensionality` method in `strucuture_analyzer.py`.
* Users can optionally pass max bond distances to correctly recognize the dimensionality of NaCl, which is problematic by default as commented in `get_dimensionality` by the original author.
* If the max bond distances are not supplied, original `get_max_bond_lengths` method works to detect them.
* This can be helpful if users want to ignore specific types of bonds.
* Unit tests are added to verify that
* CsCl is recognized as 1D using `get_max_bond_lengths` (default)
* CsCl is recognized as 3D by passing the max bond distance of Cs-Cl.
* Hope this helps!
None
None

You can supply max bond distances to recognize dimensionality of NaCl

---

pymatgen/analysis/elasticity/strain.py

Deletes legacy as_strain_dict method.  Should resolve #716 .

Remove old function

---

pymatgen/command_line/bader_caller.py
pymatgen/command_line/tests/test_bader_caller.py

Previously, the method used # of electrons as oxidation state, but the two should be opposite to each other.

fix inversed oxidation state decoration from bader

---

pymatgen/command_line/bader_caller.py
pymatgen/command_line/tests/test_bader_caller.py

* Can now automatically construct reference file from AECCAR0 and AECCAR2
* Can now calculate magnetic moments using Bader method
* Adds MSONable `BaderResult` to easily save results from Bader analysis
* Now detects version of `bader` binary, and warns if it's too old (there was previously a minor issue with regards to calculating vacuum charge with reference files)
* Adds helper method to automatically run Bader analysis on a typical VASP output directory, or from pymatgen Chgcar objects
* Fixes regression in `BaderAnalysis` from  #715 where analysis would fail if reference wasn't supplied
* Fixes headers ('min' is now 'min_dist', 'dist' is now 'atomic_vol')
None
None, though I might have renamed `BaderAnalysis` to `BaderCaller` because I think it makes more sense, but I left it as-is …

Bader update + tests for same (v2)

---

pymatgen/command_line/bader_caller.py
pymatgen/command_line/tests/test_bader_caller.py

Added a Convenient constructor that takes in the path name of VASP run to perform Bader analysis.
code cleanup in `bader_caller.py`, I'll leave this for @mkhorton to decide.

`BaderAnalysis.from_path`

---

pymatgen/analysis/elasticity/elastic.py
pymatgen/analysis/elasticity/tests/test_elastic.py
pymatgen/analysis/substrate_analyzer.py
pymatgen/analysis/tests/test_substrate_analyzer.py

Refactored the substrate analyzer code to be clearer and fixed some bugs along the way.
* ZSLGenerator now only implements the ZSL algorithm. It can be used for any sort of topological matching
* SubstrateAnalyzer takes on the brunt of generating different slabs of various miller indicies and feeding them to ZSLGenerator
* Fixed elastic energy being off by a factor of 10 due to units by using the units class
Note this still assumes the elastic tensor is in units of GPa.
* Fixed bug where the elastic tensor and the strain orientation might have been different by putting the strain in the IEEE orientation. Docs have been updated to state the elastic tensor should already be in the IEEE orientation.

Substrate analyzer refactor

---

pymatgen/symmetry/analyzer.py
pymatgen/symmetry/tests/test_analyzer.py

Closes materialsproject/pymatgen#746
New public functions:
* ``PointGroupAnalyzer.symmetrize_molecule``
* ``PointGroupAnalyzer.get_equivalent_atoms``
Changes in public functions:
* ``analyzer.cluster_sites`` now supports an optional boolean keyword argument ``give_only_index``, which defaults to ``False`` (previous behaviour)
* ``analyze.generate_full_symmops`` was optimised numerically and does not use recursion anymore. In the case of icosahedral point groups (tested on fullerene) the new implementation is 72 times faster.
New private functions (helper functions for ``PointGroupAnalyzer.get_equivalent_atoms``)
* ``PointGroupAnalyzer._get_eq_sets``
* ``PointGroupAnalyzer._combine_eq_sets``

ENH: Implemented get_symmetrised_molecule + helper functions; Improved performance of generate_full_symmops

---

pymatgen/analysis/quasiharmonic.py
pymatgen/analysis/tests/test_quasiharmonic_debye_approx.py

The Debye temperature can have anharmonic contributions which can be calculated through the Gruneisen parameter.
This change implements the anharmonic contribution by default (can be turned off) with updates to documentation to reflect the change.
Previous tests were updated to reflect the anharmonic contribution option.
For theoretical details see:
Moruzzi et al. Phys. Rev. B 37, 790–799 (1988). (Eq 20)
Shang et al. Comput. Mater. Sci. 47, 1040–1048 (2010). (Eq 18)
Result: 
@matk86 please take a look

QuasiharmonicDebyeApprox: Consider anaharmonic contribution to Debye temperature.

---

pymatgen/analysis/diffusion_analyzer.py
pymatgen/analysis/tests/test_diffusion_analyzer.py
pymatgen/util/plotting.py

- Add Haven ratio, charge diffusivity, etc. as new attributes in DiffusionAnalyzer.
- Add unittests for the new additions (for both NpT and NVT simulations).
- Minor bugfix in periodic heatmap (when vmin = vmax).

Add Haven ratio-related attributes to DiffusionAnalyzer

---

pymatgen/electronic_structure/plotter.py

BSDOSPlotter now has dos as an optional (instead of required) parameter. See Issue #795 
none
none

dos is optional in BSDOSPlotter. Pertains to #795

---

pymatgen/phonon/bandstructure.py

The method min_freq in the PhononBandStructure object returns the wrong q-point. In its current form, the method would return the q-point with the index of the band that contains the minimum instead of using the index of the minimum frequency.
Fix: Change self.qpoints[i[0]] in line 106 to self.qpoints[i[1]]

Bug fix min_freq() in phonon/bandstructure.py

---

.gitignore
pymatgen/io/qchem.py
pymatgen/io/tests/test_qchem.py
test_files/molecules/qchem_energies/hf_wb97xd_gen_scfman.qcout

In Qchem 5 there is new scf module called gen_scfman, unfortunately the scf output is slightly different from the default module. Also, I added .eggs/ to the git ignore file. I saw a few egg related ignore so hopefully that is alright.
* parse energies from gen_scfman output
*unittest added
There are other incompatibilities with the new output. I'm unsure how many exists but for instance the scf_iter_pattern no longer matches.
* find and fix other incompatibilities

Parsing energies from gen_scfman module in Qchem 5

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

MVLSlabSet.as_dict was failing due to a change in __init__ argument name without the corresponding assignment of attribute.  I'm not sure this is the best way to do it, but this seems to fix the issue.  Might want to check, @richardtran415.  Also added a unittest.

fix slab set as_dict issue and add unittest

---

pymatgen/util/plotting.py
pymatgen/util/tests/test_plotting.py

- Add argument "max_row" in period table heat map. That way one can control the number of rows shown in the heat map.
- Add unittests

New argument max_row in periodic heating map

---

pymatgen/analysis/phase_diagram.py
pymatgen/analysis/tests/test_phase_diagram.py
pymatgen/symmetry/analyzer.py
pymatgen/symmetry/bandstructure.py
pymatgen/symmetry/tests/test_analyzer.py
pymatgen/symmetry/tests/test_kpaths.py
test_files/orac_632475.cif

Modifications to account for space group naming conventions changes in spglib.
* Fix in pymatgen.symmetry.bandstructure.HighSymmKpath class
* Fix in pymatgen.symmetry.analyzer.SpacegroupAnalyzer class
* Tests for both modifications, this time generating structures within tests
* A few comments to explain modifications
```
from pymatgen import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
struct = MPRester().get_structure_by_material_id('mp-4587')
print len(struct)
#out: 4
sga = SpacegroupAnalyzer(struct, symprec=1e-2)
print sga.get_space_group_number()
print sga.get_space_group_symbol()
#out: Amm2
std_prim = sga.get_primitive_standard_structure()
print len(std_prim)
#out: 4 
print(std_prim.lattice.abc)
#out:  (3.7566910450291151, 3.7566910450291155, …
```

Kpath fix with on-the-fly structures for tests and some comments

---

pymatgen/analysis/phase_diagram.py

Fixes a performance regression that has caused the time taken by `import pymatgen` to rise by about 50%.
In short, palettable imports matplotlib, undoing all of pymatgen's hard work to avoid exactly that.

avoid importing palettable

---

pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/tests/test_inputs.py

* Fix formatting of lattice in `Poscar.get_string` to respect the `significant_digits` argument

use significant_digits in poscar lattice str

---

pymatgen/io/vasp/sets.py

Can we revert the constructor syntax of MVLSlabSet such that it takes a "structure" kwarg instead of a "slab"?  My reasoning for this is twofold:
* Input structures to MVLSlabSet aren't always slabs, e.g. when doing reference bulk calculations, but they are always structures
* Having "slab" as the input argument name changes the structure of the dictionary resultant from as_dict() such that it's different from every other input set, which makes it unwieldy when trying to do some db operations or modifications on the serialized object, for example.

Reverted slab argument to structure in MVLSlabSet

---

docs_rst/usage.rst

from a VASP POSCAR
The docs previously had this example for generating a
Structure object from a VASP POSCAR file:
```python
from pymatgen.io.vasp import Poscar
poscar = Poscar.from_file("POSCAR")
struct = poscar.struct
```
The correct attribute is `poscar.structure`.
This pull request updates the `usage` documentation file to reflect this.

Correct attribute used in example for generating a Structure object

---

pymatgen/analysis/structure_matcher.py
pymatgen/analysis/tests/test_structure_matcher.py
pymatgen/command_line/critic2_caller.py

Couldn't find this in pymatgen already. Patch to add a comparator which matches occupancies in StructureMatcher. Used for SQS generation, to match a disordered pymatgen Structure to its appropriate SQS template file.
(Also included another commit to delete a stray print statement in my previous PR...)
None
None

Add OccupancyComparator

---

pymatgen/command_line/enumlib_caller.py
pymatgen/command_line/tests/test_enumlib_caller.py

Tests for enumlib have been incorrectly skipped for a while if `enum.x` was present (they only ran if `multienum.x` was present, which is an old version).
When running these tests myself on current pymatgen, I get test failures -- `self.assertEqual(len(structures), 10)` will fail with `len(structures)==16` instead. I'm having trouble tracking down the reason for this test failure, I'm not sure if it's an issue with my enum install or whether it's a bug.
This PR fixes the test skip issue, and also adds initial support for makeStr.py (#814) -- makeStr.x is still used by default however. My sense is that makeStr.py is still a bit rough around the edges, so even though makeStr.x has been deprecated, I suggest we keep it as the default for the near future.

Request for enumlib tester (PR is to add makeStr.py support)

---

pymatgen/io/vasp/inputs.py

Bug in POSCAR parsing from file looking for POTCAR by name only
Misses extensions such as .gz .orig, .relax1.gz , etc. 
Fixed by looking for POTCAR in filename

Fix bug in POSCAR parsing

---

pymatgen/ext/tests/test_jhu.py

Should fix JHU servlet issue.  Was using a static INCAR from the test files, rather than generating it on the fly, and JHU updated their system to parse magmoms for symmetry.

fix jhu issue

---

pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_inputs.py
pymatgen/io/vasp/tests/test_outputs.py

- Fixed the POTCAR parsing bug in POSCAR again
- Updated the tests so they are appropriate conditioned for a test folder with multiple POSCARs and POTCARs
- Added in electrostatic potential parsing at each atom in OUTCAR
- Moved drift to an Outcar attribute
- Used a more sensible regex for parsing the drift

Parsing Updates and Bug Squashing

---

pymatgen/transformations/advanced_transformations.py
pymatgen/transformations/tests/test_advanced_transformations.py

Adds some new features for order-disorder transformation
* A new DiscretizeOccupanciesTransformation that will discretize the site occupancies in a structure, e.g., 0.62, 0.19, 0.19 to 0.6, 0.2, 0.2 - according to tunable tolerances.
* Test for above
* A new option for EnumerateStructureTransformation that lets you set max_disordered_sites instead of max_cell_size. The former can iterate over multiple max_cell_size values until either finding a solution or hitting the max number of disordered sites.
* Test for above
None

Order-disorder transformation tools

---

pymatgen/entries/computed_entries.py

This bug causes problems in evaluating if an elemental composition is an element. 
Fixed by switching to the logic used in PDEntry.

Fix a bug in is_element in computed entry

---

pymatgen/symmetry/analyzer.py
pymatgen/symmetry/tests/test_analyzer.py

Commit 42df22fe0d2488c539914f58ed90961411eaec46 added a `get_symmetry_operations` method to the `PointGroupAnalyzer` class. 
It also introduced a bug, where the symmetry operations returned only included those found from the initial analysis of a molecule, instead of the complete set of symmetry operations for the corresponding point group. 
This commit fixes this bug, and adds a more detailed test that checks a full set of symmetry operations is returned.

Bugfix for PointGroupAnalyzer get_symmetry_operations

---

pymatgen/core/structure.py

Was previously just returning the string instead of writing to file. Thanks @josuav1 for the report.

Fix empty file for Structure.to(filename=) for fmt='mcsqs'

---

pymatgen/ext/matproj.py

Mute MPRestError if the given criteria have no corresponding entries. 
* `rester.get_entries_in_chemsys` throws MPRestError if no entry matches the given criteria. For example, a query in chemical system C-O-N:
```python
from pymatgen.ext.matproj import MPRester
rester = MPRester()
mp_entries = rester.get_entries_in_chemsys(["C", "O", "N"])
```
Error message:
`MPRestError: local variable 'first' referenced before assignment. Content: b'{"valid_response": false, "version": {"pymatgen": "2017.11.9", "db": "2.0.0", "rest": "2.0"}, "traceback": "Traceback (most recent call last):\\n  File \\"/var/www/python/matgen/materials_django/rest/rest.py\\", line 91, in wrapped\\n    d = func(*args, **kwargs)\\n  File \\"/var/www/python/matgen/materials_django/rest/rest.py\\", line 182, in query\\n …

handle NoneType entries

---

pymatgen/transformations/standard_transformations.py

Replaced "round" by around in DiscretizeOccupanciesTransformation

Fix rounding errors in py2

---

pymatgen/cli/pmg_plot.py

fix `pmg plot --xrd POSCAR`
error message:
```plain
AttributeError: 'Namespace' object has no attribute 'xrd'
```

fix pmg plot --xrd

---

pymatgen/analysis/adsorption.py
pymatgen/analysis/tests/test_adsorption.py
pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py

* class method of AdsorbateSiteFinder, adsorb_both_surfaces() now uses symmetry operators to find a position on the other side of the slab for an adsorbate. This more generalized method will allow for adsorption of molecules on both surfaces. The method is also much more simplified compared to the previous version. This is useful for anyone trying to calculate an adsorbed slab without having slab polarity or if one wants to calculate surface energy (where both surfaces must be equivalent).
* class method of Slab, get_symmetric_site() finds a symmetrically equivalent point on the other side of the slab given a point.

method to symmetrically edit both sides of a slab

---

pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

Provides methods to retrieve MP surface data and to construct a Wulff shape given a material ID. Addresses #768.

Add MPRester methods for surface data and Wulff construction

---

pymatgen/core/reconstructions_archive.json
pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py

A new class has been added to surface.py: ReconstructionGenerator().
* ReconstructionGenerator takes in an initial structure (conventional ucell), a slab and vacuum size and a string for the name of the type of reconstruction the user desires to create and the index of termination (some reconstructions such as for the (111) diamond will only work for a specific termination). 
* The user can select from a set of reconstructions each with a unique name available in the reconstructions_archive.json file. This file contains a dictionary with the name being the key and the value being a dictionary containing information pertaining to creating a reconstruction. Anyone is encourage to continue adding on more reconstruction types given that they follow the format specified in the docs in order to …

ReconstructionGenerator()

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py
test_files/vasprun.xml.opticaltransitions

Added a new Vasprun parser to parse opticaltransitions tags printed in vasprun.xml after a BSE calculation. The new parser will output both the oscillator strength in (eV) and the probability of transition (dimensionless) 
None
N/A

Optical add vasprun

---

pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py
pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_outputs.py
pymatgen/io/vasp/tests/test_sets.py
test_files/vasprun.charged.xml

Added the ability for a structure to have an overall charge. This will default to the behavior in SiteCollection when overall charge is not specified: the structure's charge is the sum of the oxidation state of its sites. 
- IStructure and Structure contain an overall charge
- The generator functions such as make_supercell/__mul__ properly account for overall charge
- Vasp input sets will modify NELECT in INCAR when an overall charge is specified. 
- Vasprun compares nelect against potcars when available and sets charge if they are different.

Overall charge for structures

---

pymatgen/analysis/diffusion_analyzer.py
pymatgen/analysis/tests/test_diffusion_analyzer.py

The `DiffusionAnalyzer` `from_structures()` method calculates cartesian displacements using
c_disp = [np.dot(d, m) for d, m in zip(f_disp, l)]
`f_disp` has dimensions `[site, time step, axis]`.
`l` has dimensions `[time step, axis, axis]`
This means the lattice used for calculating the cartesian displacements is selected based on site number, not on time step.
Displacements calculated for NPT simulations therefore contain errors (equivalent to assuming NVT, and then taking a different lattice for each site).
This commit fixes this, by replacing the calculation of `c_disp` with
c_disp = []
for i in f_disp:
c_disp.append([np.dot(d, m) for d, m in zip(i, l[1:])])
The new calculation also addresses an off-by-one error, where the displacement at time step t was calculated using the lattice at …

Bug fix for DiffusionAnalyzer with NPT runs

---

pymatgen/analysis/pourbaix/analyzer.py
pymatgen/analysis/pourbaix/tests/test_analyzer.py
pymatgen/analysis/pourbaix/tests/test_plotter.py

Replaces pyhull halfspace usage with scipy.spatial.HalfspaceIntersection usage in pourbaix analysis module.  Also adds a few more unittests to the plotter and fleshes out the docstring in PourbaixAnalyzer.
Addresses #283.

Remove pyhull

---

pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

Get critical reactions ("kinks" in the mixing ratio where reaction products change) between two reactants. See the `pymatgen.analysis.interface_reactions` module for more info. Useful to generate pseudo-binary phase diagrams of two reactants. Also allows elemental reservoir open to system with _relative_ chemical potential with respect to pure substance. Work done with @yihanxiao92.

Add MPRester method to get interface reaction kinks

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py
pymatgen/io/vasp/vdW_parameters.yaml

Relax input set using SCAN and unittests have been added.
* Add `MVLScanRelaxSet`
* Enable van-der-Waals functional rVV10
* unittests
* minor reformatting

Add relax input set using SCAN

---

pymatgen/analysis/pourbaix/analyzer.py
pymatgen/analysis/pourbaix/tests/test_analyzer.py

Returns pourbaix_domain_vertices attribute to PourbaixAnalyzer.  Addresses #964.
* Adds the pourbaix_domain_vertices attribute back
* provides a more stable sort of the points bounding the pourbaix region to ensure consistency
* Adds test of functionality

updated analyzer to restore pourbaix_domain_vertices and added unittest

---

pymatgen/analysis/ewald.py
pymatgen/analysis/tests/test_energy_models.py
pymatgen/analysis/tests/test_ewald.py

Added charge cell correction to Ewald summation method. Ewald summation now exactly matches results for Ewald calculations from LAMMPS and GULP.
See discussion in #972 
None

Added charged cell correction to EwaldSummation

---

pymatgen/core/composition.py
pymatgen/core/tests/test_composition.py

Added a function that returns a copy of a Composition decorated using oxidation states determined from `oxi_state_guesses`. Also refactored the `oxi_state_guesses` to move the computation of likely oxidation states to a private utility function so that the guessing logic could return both the average oxidation states for each element and the oxidation states for each site.
As part of this modification, the `oxi_state_guesses` function now returns a tuple of operations rather than a list but is otherwise unchanged. I could easily modify the code to still return a list, but decided it was unnecessary since both collections are iterable and addressable.
* Added operation for adding guessed charges to Composition object
None

Add charges to Composition based on oxidation state guesses

---

pymatgen/analysis/chemenv/utils/chemenv_config.py
pymatgen/analysis/chemenv/utils/scripts_utils.py

Fixed access to materials project for get_environment. 
* Excluded the setup of the access to the materials project data base (not necessary)
* removed chemenv_configuration.has_materials_project_access because it is not defined
If the API_KEY is not supplied it raises an error. A treatment might be necessary.

Fix access to materials project

---

pymatgen/io/lammps/data.py
pymatgen/io/lammps/tests/test_data.py

Fix a bug where the molecule-ID column is edited when calling `LammpsData.structure` attribute.

Bug fix in lammps data

---

pymatgen/analysis/diffusion_analyzer.py

Commit c99dba04ebba648909ab5f71a7593f26cb388f11 introduces a bug in the `from_structures()` method if this is called from the `from_vaspruns()` method. This commit reverts this change.
In `from_vasprun()`, structures are collected as a generator function, using `get_structures()`. The `from_structures()` method, however, expects a list of structures, and tries to access `structures[0]`. This fails if a constructor has been passed in, instead of a list (as is the case with `from_vasprun()`).
This commit:
a) reverts the behaviour of `from_structures()` to explicitly store the first structure passed in.
b) generates a list of structures in `from_vaspruns()` before calling `from_structures()`, for 
consistency with the argument types in the `from_structures()` docstring.

Bug fix for DiffusionAnalyzer.from_vasprun()

---

pymatgen/io/vasp/outputs.py

VASP 5.4.4 introduced calculation of the dielectric constant based on the current-current response.
When using small values of the `CSHIFT` parameter (necessary to produce optical spectra with no broadening), this can result in anomalously large values of the current-current response, which VASP writes to the vasprun.xml files as `***********`.
I've updated the `Vasprun` parser to use the specific parsing method that can detect this bad behaviour.

Fix parsing of vasprun containing *

---

pymatgen/core/structure.py

Structure.get_primitive_structure()  previous uses .lattice instead of ._lattice when searching for primitive cells with certain lattice constraints. Switching to the latter will make it 17x faster.

Small fix to speed up primitive structure search under specific lattice constraints

---

pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
pymatgen/analysis/chemenv/utils/chemenv_config.py
pymatgen/analysis/chemenv/utils/tests/test_chemenv_config.py

Fixed the access to the materials project in a more thorough way and adapted the test accordingly. Moreover, a small bug in the reading in of the chemenv strategy was fixed. 
I introduced an additional dependency on SETTINGS in chemenv_strategies.py and its test test_chemenv_config.py.

fixes in the get_environment script

---

pymatgen/analysis/interface_reactions.py

import matplotlib can cause problems in headless systems.
I moved the import to inside the plot function, this way the import problem only shows if plotting is required.

Moved import matplotlib inside the plotting function in interface_reactions.py

---

pymatgen/analysis/local_env.py

VIRENN adds oxidation states to the input structure, causing a subtle bug in .get_periodic_image which was referencing the input structure instead of the oxi-state decorated structure.
None
None

Fix small bug in MinimumVIRENN get_nn_info

---

pymatgen/io/lammps/output.py
pymatgen/io/lammps/tests/test_output.py

Fix `unique_atomic_masses` in two methods.
None
This bug was reported in a user post in pmg google group. It was caused by rewriting `lammps.data`, but I would not take the blame because it would have been found if there were unit tests for those methods. So, if the developer/user is still using them, can you update your code and add comprehensive tests, please? Thank you.

Minor fix in lammps.output

---

pymatgen/electronic_structure/plotter.py

In the online documentation for [pymatgen.electronic_structure.plotter](http://pymatgen.org/pymatgen.electronic_structure.plotter.html), the "**Returns**" and "**Return type**" sections of some methods (cf. below) which return complicated ``dict``s are pretty much unreadable because [Sphinx's napoleon extension](http://www.sphinx-doc.org/en/stable/ext/napoleon.html) parses whatever precedes the first colon after ``Returns:`` as the method's return type. This PR aims to fix this by explicitly adding the return type as ``dict:`` and making some cosmetic changes to the rest of the ``Returns:`` description.
Affected methods:
- [BSPlotter.bs_plot_data](http://pymatgen.org/pymatgen.electronic_structure.plotter.html#pymatgen.electronic_structure.plotter.BSPlotter.bs_plot_data)
- …

Small doc fixes pertaining return types in electronic_structure.plotter

---

pymatgen/transformations/advanced_transformations.py

Previously transformation would fail if max cell size was set too small, now it will give a warning and increase max cell size instead.
None
None

Update MagOrderingTransformation error handling

---

pymatgen/command_line/enumlib_caller.py

As a temporary fix, missing site properties are now set to None when they’re not available, so at least the site property dictionary has the correct keys. This fixes the crashes that were observed in #1063 
* None
* A longer-term fix would be to map the ordered sites back onto the original disordered structure and pull the appropriate site properties from there. I don't need to do this right now, but if someone wants to improve EnumlibAdaptor in the future they can do this.

EnumlibAdaptor: fix missing site properties

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

This commit fixes incar write error and one example is shown below. This error is triggered if a structure contains elements in ["F", "O", "S"] but the most electro-negative element is not within the list.
Example:
```python
>>> from pymatgen.ext.matproj import MPRester
>>> from pymatgen.io.vasp.sets import MITRelaxSet
>>> rest = MPRester()
>>> SCl = rest.get_structures("SCl")[0]
>>> vis = MITRelaxSet(SCl)
>>> print(vis.incar)
TypeError
~/repos/pymatgen/pymatgen/io/vasp/sets.py in incar(self)
--> 341         has_u = hubbard_u and sum(incar['LDAUU']) > 0
TypeError: unsupported operand type(s) for +: 'int' and 'dict'
```

Fix incar list_key parse error

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py

Adds additional information about each facet to the `get_voronoi_polyhedra` method of `VoronoiNN`.
- Altered `get_voronoi_polyhedra` to compute a few other statistics
- Added option to `VoronoiNN` that changes whether solid angle is used to weigh neighbors, or one of these other statistics
None
I'm not sure whether these changes make the most sense here, or in one of the other Voronoi-related classes. It was just easiest for me to build it here.
PS. Borrowed code from @qi-max, who wrote similar methods into matminer.

Added additional statistics to VoronoiNN calculation

---

pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

For `MPRester.get_interface_reactions`, extend method signature to allow toggling of whether to use the convex hull energy for a given composition for the reaction energy calculation. If false (default), the energy of the ground state structure will be preferred; if a ground state cannot be found for a composition, the convex hull energy will be used with a warning message. Add a test for this.
@yihanxiao92 will amend [the example `matgenb` notebook](https://github.com/materialsvirtuallab/matgenb/blob/eb5b67bc1064cd96211117b23403c27fc36b7f6b/notebooks/2018-01-29-Interface%20Reactions.ipynb) to include this functionality. However, this does not block merging -- this is only to notify Yihan that this PR is done and that the notebook no longer lives in the pymatgen repo).

Amend API method to specify use of hull energy for interface rxn calc

---

pymatgen/analysis/local_env.py

Removed use of `deepcopy` in nearest neighbor calculation.
Aside: Turns out that this one line was 50% of the execution time of getting Nth nearest neighbor shells. I've learned my lesson.
None
None

Removed use of deep copy

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py

A series of changes to make the calculation of Voronoi-tessellation-based features in matminer faster.
* Optimization of `get_nn_shell_info` 
* Optimization of `get_voronoi_polyhedra`. No longer returns a dict indexed by `PeriodicSite`, which is very slow to modify. 
* Implemented `__hash__` and `__eq__` for NearNeighbors. Makes it easier to use LRU caches with these tools
* Faster implementation of `solid_angle`
* VoronoiNN now can return all polyhedron information as part of `get_nn_info`. Used to improve usefulness of cached results in matminer
None
Optional: Index output of `get_voronoi_polyhedron` by "site index" and "image". Right now, the key of the output dict is the facet number, which is not useful.

Changes to accelerate Voronoi-tessellation based features

---

pymatgen/electronic_structure/dos.py
pymatgen/electronic_structure/tests/test_dos.py

added FermiDos class that makes it very easy to calculate the fermi level at a given concentration (get_fermi) or the concentration (doping) at a given fermi level (get_doping). Also added tests for both methods.

add FermiDos for convenient fermi and doping calculations

---

pymatgen/analysis/diffusion_analyzer.py
pymatgen/analysis/reaction_calculator.py
pymatgen/core/lattice.py

Uses machine precision times the largest of the input array dimensions rather
than simply the machine precision as the `rcond` parameter to `numpy.linalg.lstsq`.
Adds `rcond=None` to all calls to `numpy.linalg.lstsq`.
* This suppresses a `FutureWarning` for numpy>=1.14 (pmg dep)
* The future default is [apparently](https://stackoverflow.com/a/44678023) more consistent with `scipy` and is "a good and robust default threshold."
However, I don't know if any current code _depends_ on the old default. I would hope not, and that code would break anyway with numpy 1.15.

Use future numpy default for rcond

---

pymatgen/io/ase.py

When translating PMG structures to ASE atoms, sometimes you want to use additional ASE Atoms kwargs. e.g., for myself I want to add a calculator in the ASE Atoms object when creating it from a PMG structure.
None
None

allow kwargs in ASE atoms converter

---

pymatgen/electronic_structure/dos.py
pymatgen/electronic_structure/tests/test_dos.py

add bandgap option for FermiDos enabling scissoring of the gap + testing. No scissoring by default.

add bandgap option for FermiDos

---

pymatgen/analysis/elasticity/elastic.py
pymatgen/analysis/elasticity/tensors.py
pymatgen/analysis/elasticity/tests/test_elastic.py

I've found that estimating the debye temperature of solids from the elastic tensor using the formulation from the longitudinal and transverse speed of sound is significantly more accurate than that of the isotropic young's modulus, so I've moved that to the default function and deleted both the old one and the GIBBS formulation, which is both somewhat unstable and very inaccurate as implemented.  Also cleaned up some trailing whitespace and codacy issues in the elasticity module.

updated debye temperature formulation

---

pymatgen/symmetry/analyzer.py

The `get_conventional_standard_structure` method currently unexpectedly switches a and c for tetragonal space groups if a = b = c. This is obviously not desirable and so has been removed, while still allowing for switching a and c if a != b = c (the original intention). 
None
This only removes unexpected behaviour for a = b = c, but doesn't determine which is the conventional c axis in that case.

Small bug in tetragonal conventional structure method when a = c

---

pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

Someone pointed out on the forum that the rester was returning different structures with `MPRester.get_entry_by_material_id` and `MPRester.get_structure_by_material_id`.  This is because `get_entry_by_material_id` will include the initial structure if `inc_structure=True` and only return the final structure if `inc_structure="Final"`.  This seems counterintuitive to me, since the final structure is the one that actually corresponds to the calculated energy, and the rest of the MPRester uses the final structure by default, so this PR changes the default `inc_structure=True` behavior to include the final structure and allows for initial structures to be requested by `inc_structure="initial"`.  Also added a test.

Mprest final struct

---

pymatgen/electronic_structure/plotter.py

Now, one can set ylim and get cbm and vbm markers at the same time with the BSPlotter. If I should do anything else, just let me know.

Add cbm and vbm marker in BSPlotter when ylim is set 

---

pymatgen/io/qchem_io/inputs.py
pymatgen/io/qchem_io/tests/test_inputs.py

Unnecessary ordered dictionaries were removed. This should fix testing issues
points
* OrderedDict removed from input.py
* OrderedDict removed from test_input.py

Ordered Dictionaries Removed

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py

This PR implements a new NearNeighbor method to the list already available in local_env.py
The method is my own custom algorithm for determining near neighbor. Briefly, it is based on post-processing Voronoi solid angle weights with additional considerations for site distance as well as optional preference for bonds with higher electronegativity difference.
Without any knowledge or "fitting", this method beat all other local_env methods currently in pymatgen on a benchmark test set of compounds including metals, minerals, and porous structures by a factor of two or more. The test set, which is still being expanded, is available here:
https://github.com/hillarypan/MaterialsCoord
The method is complete and usable. However, it is possible we might fine tune the method later on if we see any …

Implementation of a new NN method

---

pymatgen/io/vasp/outputs.py

`Outcar.read_lepsilon()` had a typo.

Fix a typo in Outcar.read_lepsilon()

---

pymatgen/analysis/local_env.py

A very minor fix - the parameter search_cutoff in the constructor of CrystalNN wasn't being used, this actually makes use of it.

fix to actually use search_cutoff

---

pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py

* enable molecule-like rotations of arbitrary sites by some angle around some axis at some anchor for pymatgen.core.Structure.
None
Nothing

Enable molecule-like rotations for structures.

---

pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

Add `MPRester` methods to get phonon dispersion, density of states, and ABINIT Derivative Data Base (DDB) output. Add unit test.

Add methods for getting phonon BS, DOS, and DDB output

---

.travis.yml
pymatgen/core/bond_lengths.json
pymatgen/core/bonds.py
pymatgen/core/tests/test_bonds.py

Add bond order property of a CovalentBond (Issue #1126) . Initially I plan to change `is_bonded` to return an int indicating bond order. After some reflection I think this is a bad idea:
* According to the semantics, `is_bonded` should return a Boolean instead of an int.
* In some cases, like in benzene, the bond order can not be described by an int.
So what I finally do is to build another function `get_bond_order` which returns a float indicating the bond order. The bond order is calculated by the ideal bond lengths of different bond orders and the actual site distance. For example, if C-C bond is 1.54 A and C=C bond is 1.34 A and we have a distance of 1.4 A (benzene). Then the bond order is 2 - (1.4 - 1.34) / (1.54 - 1.34) = 1.7. I think this is enough to provide some qualitative …

Add bond order property of a CovalentBond

---

pymatgen/analysis/magnetism/jahnteller.py
pymatgen/analysis/magnetism/tests/test_jahnteller.py

Fixes a broken multiplication. Without it, mu_so does not work correctly and always returns "None".

Small bug fix: Missing multiplication

---

pymatgen/analysis/elasticity/tensors.py
pymatgen/analysis/elasticity/tests/test_tensors.py

Additional functionality to Tensor class to allow for transformations corresponding to changes in structure basis.
* adds a method to the Tensor class that allows one to transform from the implicit basis of one structure to that of a second structure.
* added a method to refine rotation matrices generated for ieee standards, in cases the lattice vectors used to generate new bases are slightly non-orthogonal.  This ensures, for example, that invariants won't change upon applying the tensor transformation.
* Tests for both methods

Structure transform

---

pymatgen/io/tests/test_xyz.py
pymatgen/io/xyz.py

some float formats were not recognized when reading an xyz file. Only this one was read: 0.500e-09 and 0.7766e3. That floats were not recognized by the regex and are now read correctly: 
* 0.100E+01
* 0.100D+02
* 0.100d+2

extend the XYZ class

---

pymatgen/analysis/graphs.py
pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_graphs.py
pymatgen/analysis/tests/test_local_env.py
pymatgen/command_line/critic2_caller.py
pymatgen/command_line/tests/test_critic2_caller.py

Fixed a few minor bugs in pymatgen.analysis.graphs, now supports molecules too (including via NearNeighbor class; will box them first).
Added `get_local_order_parameters` and `get_bonded_structure` convenience methods to NearNeighbor base class. The former is adapted from Nils' code, moved here from analysis.graphs to avoid a circular import.
Added two new NearNeighbor classes:
* Critic2NN -- this uses sum of atomic charge densities (to calculate bonds from Chgcars, you still need to use Critic2Caller directly)
* CutoffDictNN -- a very basic NN I've found useful for testing
* None
* None

NearNeighbors + StructureGraphs: some bug fixes, convenience methods + tests

---

pymatgen/analysis/elasticity/elastic.py
pymatgen/analysis/elasticity/tests/test_elastic.py

Some of the methods in the elastic tensor classes get (incorrectly) unitized, which can lead to problems in postprocessing.  In the long term, I think the elastic tensor classes should be refactored to better support units, but in the short term I think it's probably best to scrub the quantities which have units until a more holistic approach can be implemented.  This PR does that and adds a few tests to ensure no unitized floats are returned by the relevant methods.

scrubbed units

---

pymatgen/transformations/standard_transformations.py
pymatgen/transformations/tests/test_standard_transformations.py

Fixed serialization issue as `Deformation` is not `MSONable`, with a proper test.
None
None

fix DeformStructureTransformation serialization

---

pymatgen/analysis/local_env.py

Fixes an issue where `MaterialsProjectCompatibility` raises an import error if optional dependency `networkx` not installed, due to use of analysis.local_env classes.
(we could also just make networkx a core dependency, it's quite light and pure Python; it's currently used for creating and analyzing graphs of bonds in crystals)

Move Critic2Caller import due to optional dependency / import error

---

pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

previous implementation would return 0 if kpoints is auto-generated and 1 otherwise both of which are not the expected behavior.

set nkpoints to the actual length of kpoint list

---

pymatgen/ext/tests/test_matproj.py

**do not merge** (see `TODO` below)
Tested values are changed in the new MP DB due to additional compounds
* Update non-existent compound for interface reactions test, as MnO3 exists in new MP db
* Update tested db entry values. Relax places=7 constraint on assertion.
* Test for expected icsd ids as a subset, as entry now matches more known ICSD IDs.
It is expected that this PR will **not** test successfully until the new MP DB is released. I will update this PR when tests should re-run and this PR merged.

Update MPRester tests in preparation of new MP DB release

---

pymatgen/electronic_structure/plotter.py

remove warning "Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead."

Update plotter.py to remove matplotlib warning

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Modifying OUTCAR's parsing logic. The big change is the addition of parsing of internal strain tensors from DFPT calcs. There is some additional logic for parsing the ionic portion of the dielectric and piezoelectric tensor if DFPT is on.

Add in some additional Parsing logic for DFPT into Outcar

---

pymatgen/core/lattice.py

* Updated parameter that throws NoneType error when checking if structure is valid
Fixes the following error:
File "/home/sivonxay/.conda-envs/cms/code/pymatgen/pymatgen/core/structure.py", line 299, in is_valid
all_dists = self.distance_matrix[np.triu_indices(len(self), 1)]
File "/home/sivonxay/.conda-envs/cms/code/pymatgen/pymatgen/core/structure.py", line 663, in distance_matrix
self.frac_coords)
File "/home/sivonxay/.conda-envs/cms/code/pymatgen/pymatgen/core/lattice.py", line 1057, in get_all_distances
v, d2 = pbc_shortest_vectors(self, fcoords1, fcoords2, return_d2=True)
File "/home/sivonxay/.conda-envs/cms/code/pymatgen/pymatgen/util/coord.py", line 213, in pbc_shortest_vectors
return_d2)
File "coord_cython.pyx", line 96, in pymatgen.util.coord_cython.pbc_shortest_vectors
File …

Updated parameter that throws NoneType error when checking if structure is valid

---

pymatgen/analysis/diffraction/neutron.py
pymatgen/analysis/diffraction/xrd.py
pymatgen/analysis/ewald.py
pymatgen/core/lattice.py
pymatgen/core/structure.py
pymatgen/core/tests/test_lattice.py
pymatgen/core/tests/test_structure.py

Adding the ability to output to all routines that determine nearest neighbors. Detecting which image a neighbor comes from given its coordinates (Cartesian or fraction) can be complicated for neighbors near the edges of cells, and this change allows algorithms to avoid needing to perform such operations.
None
~~Need to add the image outputs to neighbor finding routines in Structure. I'll be working on those shortly, but wanted to open a PR to run unit tests because changing Lattice touches many parts of pymatgen.~~

Add Supercell Image to Neighbor-Finding Routines

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/sets.py

Removed unnecessary int(round(...)) from two locations when computing the NELECT value. While for most cases this should be an integer, there are some cases where a fractional value is expected; one use case is pseudo-hydrogen, which has a fractional charge for passivating bonds.
None
- Possibly add a flag to turn this on/off
- An alternative would be to add some code which checks if nelect is close to an integer value before rounding: `if abs(round(nelect) - nelect) < 0.001: nelect = int(round(nelect))`

Allow fractional NELECT

---

pymatgen/core/grain_boundary_generator.py
pymatgen/core/tests/test_grain_boundary_generator.py
test_files/grain_boundary/Be_mp-87_conventional_standard.cif
test_files/grain_boundary/Bi_mp-23152_primitive.cif
test_files/grain_boundary/Br_mp-23154_conventional_standard.cif
test_files/grain_boundary/Cu_mp-30_conventional_standard.cif
test_files/grain_boundary/Cu_mp-30_primitive.cif
test_files/grain_boundary/Pa_mp-62_conventional_standard.cif

This generator provides two methods to generate grain boundaries (GBs) from bulk conventional cell (fcc, bcc can from the primitive cell), and works for Cubic, Tetragonal, Orthorhombic, Rhombohedral, and Hexagonal systems. The first one is to generate GBs from given parameters, which includes
GB plane, rotation axis, rotation angle. The second one is to generate GBs from given transformation matrices for each grain. It works for any general GB, including both twist, tilt GBs, etc.
It also contains functions that can generate all possible sigma values and from sigma value to generate rotation angles needed for the GB generator.

Add grain boundary generator

---

pymatgen/electronic_structure/dos.py
pymatgen/electronic_structure/tests/test_dos.py

when the value of doping concentration, c, is too low or too high, the get_fermi method may not converge in which case it raises error which is expected. To support a wider range of c even for a coarse CompleteDos with an energy range that is not wide enough, get_fermi_interextrapolated is introduced that supports c=0 or c=1e26 or c=-1e24, etc (all in 1/cm3).

add get_fermi_interextrapolated method to FermiDos

---

pymatgen/io/gb/grain_boundary_generator.py

Use pymatgen Spacegroup to analyze the symmetry of the structure. 
Uses can provide any cell they want (swap a, b, c or angles in tetragonal or hexagonal systems).

Optimize the symmetry analyzer

---

pymatgen/io/gb/grain_boundary_generator.py
pymatgen/io/gb/test/test_grain_boundary_generator.py

In this new version,
A new class method 'get_ratio' is added to help user obtain the axial ratio from the structure needed for GB generator. Users can also supply the ratio directly by making their own approximations.
In addition, a new tag 'max_search' is added. This is to avoid crash for large GB with large sigmas. The very low speed for large GB with large sigmas is mainly due to the very large max_search, which is to search for the 'best' lattice vectors for GB. The previous version sets 'max_search' as the value that can guarantee to find the 'best'. But most of the time, it is not necessary to use that big number. So this new tag can control this value, and speed up the process a lot.
One more thing that related to the speed for large GB is to label the coincidence sites. When the …

Add new feature to GB generator

---

pymatgen/analysis/tests/test_graphs.py

Previous pull request left one test for pymatgen.analysis.graphs.MoleculeGraph broken. This pull request fixes those broken tests.

Fixed broken tests for MoleculeGraph

---

pymatgen/analysis/pourbaix_diagram.py
pymatgen/analysis/tests/test_pourbaix_diagram.py

A legacy portion of the pourbaix code filtered ion-including MultiEntries from pourbaix diagrams when their reaction coefficients were lower than their attached concentration attribute, which I can't think of a good reason to do.  This resulted in pourbaix diagrams with high ion concentrations (e. g. > 0.5) filtering out ion entries.
* Changes pourbaix processing of multi-entries to filter ion entries based on reaction coefficient weights that are fixed, rather than concentration-based.
* Adds associated unit test to ensure that high concentration ion entries are not filtered arbitrarily

Pourbaix patch 1

---

pymatgen/analysis/gb/gb.py
pymatgen/analysis/gb/test/test_gb.py
pymatgen/transformations/advanced_transformations.py
pymatgen/transformations/tests/test_advanced_transformations.py

GrainBoundaryTransformation is used to generate grain boundary structure, which will be used in atomate grain boundary workflow.

Add GrainBoundaryTransformation and test in advanced_transformations

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Added a check for 0 weight kpoints in pymatgen.io.vasp.outputs.Vasprun.get_band_structure. This is useful for meta-GGA calculations. Addresses Issue #1214 .
N/A
N/A

check for 0 weight kpoints for hybrid-type band structures

---

pymatgen/command_line/tests/test_enumlib_caller.py
pymatgen/io/cif.py
pymatgen/io/tests/test_cif.py

Fixing #1228
* Change to TypeError, as this is the one we want to catch, `oxi_state` is set to `None`, not unset
* Remove unnecessary code

Use TypeError as oxi_state is set to None, not unset

---

pymatgen/io/lammps/outputs.py
pymatgen/io/lammps/tests/test_outputs.py

A memory friendly version of dump parser, reading a file line by line instead of reading the entire file into memory. Computers used to hang when dealing with GB size file, now parsing can be done in a few minutes w/ `pandas.read_csv`, tested to be faster than `numpy.loadtxt`.
None
None

Improved performance of dumps parsing

---

pymatgen/analysis/gb/__init__.py

`__init__.py` is generally unnecessary for including packages in editable installs of pymatgen in python 3, but seems to be necessary for non-editable installs (e. g. with pip or `python setup.py install`).  I think this should fix the issue.  Currently the pip-installed release doesn't include the analysis.gb module, which breaks transformations.  Might want to re-release as well.

add init to gb

---

pymatgen/core/structure.py

Determining whether a structure is equal to itself can be very expensive for large structures. A structure with 100 atoms can take seconds to verify, and the cost scales with the square of the number of atoms. This change adds a check in the equality operation if the "other" class refers to the same object in memory to drastically lower the cost of "x == x"
This problem has implications for the caching methods we use in matminer.
None
None

Added shortcut if structures is equal to self

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py

Fixes a bug with VoronoiNN. Under cases where an atom is not bonded to any other atoms in its own image of a unit cell, VoronoiNN will fail to analyze the NN environment of that atom. To fix this problem, we ensure that all sites are in the list of atoms to include in a tessellation
- Added a unit test that fails before this fix, and now passes
None
None

Fixes bug in VoronoiNN where atoms in unit cell are not bonded

---

pymatgen/io/lammps/data.py
pymatgen/io/lammps/tests/test_data.py

Fixed a bug where exported structure has Ni or Co in the composition. Thanks to the report by @ucsdlxg 
None
None

bug fix for exporting structure out of LammpsData

---

pymatgen/io/pwscf.py

Implement PWInput.as_dict() and PWInput.from_dict(pwinput_dict) methods to the PWInput class.
* as_dict method returns a dictionary with a dictionary-encoded Structure object, pseudopotential dictionary, input sections, and k points information
* from_dict method takes a dictionary from as_dict and returns a PWInput object

Add converters to and from dictionary

---

pymatgen/analysis/wulff.py

Got an error when trying to plot wulff shapes today.  I think there's a typo in one of the method calls in the get_plot method, this should fix.  Not sure why the unit test isn't throwing an error.

Minor bug fix in wulff.py

---

pymatgen/electronic_structure/bandstructure.py

Fixes a bug in the initialization of projections in bandstructure.py.  This was causing an error in the boltztrap module test.

Minor bug fix in bandstructure

---

pymatgen/io/cif.py
pymatgen/io/tests/test_cif.py

Fixes some minor issues with CIF Parser's get_bibtex_string when dealing with ICSD CIFs
- ensure bibtex gets single strings and not arrays when dealing with _loop fields
- properly formats author field when not supplied via _loop
- simple test for get_bibtex_string so we can monitor incase it breaks

Minor CIF Parser Fixes

---

pymatgen/core/composition.py
pymatgen/core/tests/test_composition.py

See the issue #1268
* Update Composition._parse_formula able to handle "@", that is usually used in Metallofullerene formula (e.g. Y3N@C80)
* Add test_Metallofullerene to test the updated parser

Update composition parser able to handle "@" #1268

---

pymatgen/core/molecular_orbitals.py
pymatgen/core/tests/test_molecular_orbitals.py

* Semantically, `MolecularOrbitals` should only handle compositions with integer-valued subscripts.
* The doc strings for this class have been updated to reflect the intended use.
* A feature has been added that raises a `ValueError` when non-integer subscripts are used.
(the issue of non-integer subscripts propagated into _matminer_, where this issue was first identified)

Non-integer subscripts in MolecularOrbitals class

---

pymatgen/analysis/local_env.py

Change default cutoff of `VoronoiNN` from 10.0 to 13.0. This fixes #1281 for all 85,000 materials currently in the materials project database.
I have also changed the way the max_cutoff is calculated. Previously, the max cutoff was incorrect for cells with angles not equal to 90 deg (e.g. for the example in #1281). The max cutoff is now set to the largest of the 4 cell diagonals. I'm not confident that my implementation is the cleanest way to do this but it works.
Lastly, I moved the `self._extract_cell_info()` call to within the try-catch block, as I found that just increasing the cutoff fixed this error in most cases (maybe all cases). Just to be sure, I altered the error handling to make sure the right error message is thrown.

Change default VoronoiNN cutoff

---

pymatgen/analysis/defects/core.py
pymatgen/analysis/defects/tests/test_core.py

Previously a Substitutional or Interstitial defect structure could be generated (from generate_defect_structure) with a velocity property which was not consistent with the initial bulk_structure. 
This PR fixes this issue for the Substitution and Interstitial objects and adds a unit test to ensure the fix works.

Fix defect_generate_structure issue with velocity site property

---

pymatgen/core/lattice.py
pymatgen/core/structure.py
pymatgen/core/surface.py
pymatgen/core/tests/test_lattice.py
pymatgen/core/tests/test_structure.py
pymatgen/core/tests/test_surface.py

Fixed bugs in `miller_index_from_sites` detailed in #1301. 
I also extended `miller_index_from_sites` to support passing more than 3 sites. In this case, the "best" plane that minimizes the distance from all atoms to the plane will be calculated using singular value decomposition. This behavior is the same as provided in the VESTA visualization tool.
Other changes include:
- Support for fractional or cartesian coordinates.
- Improvements in getting the integer miller index.
- The number of negative indexes is minimized. E.g. `(-1 -1 1)` -> `(1 1 -1)`.
- If there are negative indexes, the largest number should be possitivie. E.g. `(-2 1 0)` -> `(2 -1 0)`.
- Other improvements to reliability.
- Tests for the failing case described in #1301.
- Tests for finding the plane with more than 3 …

miller_index_from_sites now supports more than 3 sites

---

pymatgen/io/vasp/inputs.py

Fixes #1308, no test for this since cannot distribute VASP-owned POTCAR.

Fix for POTCARs with non-integer charge #1308

---

pymatgen/apps/battery/insertion_battery.py
pymatgen/apps/battery/tests/test_insertion_battery.py

fixed the accidental override of get_min_instability
I also realized that there is no test for the get_min_instability and get_max_instability functions, and I will write them as part of this pull request, I just want to let you know that a typo was made on the last one that was not caught by the tests.

fixed the accidental overide of get_min_instability

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py
pymatgen/core/periodic_table.py
pymatgen/core/tests/test_periodic_table.py

If a structure has oxidation states set, CrystalNN will try to use ionic radii instead of covalent/atomic radii.
* PeriodicTable has two new attributes per element: ``average_cationic_radius`` and ``average_anionic_radius``. These are used in the new CrystalNN, and for elements like N, P, S etc that can act as both anions and cations, it is useful to have an average radius that doesn't mix together the positive and negative valence states.
* CrystalNN: if ``distance_cutoffs`` are set, CrystalNN will throw a warning if oxidation states are not set, although it will still work without oxidation states (just generally poorer results)
* CrystalNN: if ``distance_cutoffs`` are set, CrystalNN will use oxidation state data from the structure to set better ionic radii for those distance cutoffs.

CrystalNN takes into account ionic radii

---

pymatgen/analysis/structure_prediction/dopant_predictor.py
pymatgen/analysis/structure_prediction/tests/test_dopant_predictor.py

Adds two functions to predict n- and p-type substitutional dopants using two methods:
- The difference in Shannon radii between the dopant and original site.
- The substitution probabilities defined in `SubstitutionPredictor`.
Related to materialsvirtuallab/matgenb#17.
An example usage of the code is:
```python
from pymatgen.core.structure import Structure
from pymatgen.analysis.structure_prediction.dopant_predictor import \
get_dopants_from_shannon_radii, get_dopants_from_substitution_probabilities
structure = Structure(
[3.24, 0, 0, 0, 4.83, 0, 0, 0, 4.84],
['O', 'O', 'O', 'O', 'Sn', 'Sn'],
[[0.5, 0.19, 0.80], [0.5, 0.80, 0.19], [0, 0.30, 0.30],
[0, 0.69, 0.69], [0.5, 0.50, 0.50], [0, 0, 0]]
)
structure.add_oxidation_state_by_guess() …
```

Add substitutional dopant predictor and tests

---

pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py
pymatgen/util/sequence.py
pymatgen/util/tests/test_sequence.py

Add a `bulk_query` method to `MPRester`, which wraps `query` to provide a better user experience for fetching a large sum of data across many materials. Fixes issue where user requests not too much data per material, but too much data overall in one query because the number of materials matching criteria is large.
* Chunk a query into multiple queries by first fetching a list of material ids satisfying the criteria.
* Re-try fetching chunks a configurable number of times in case of 5xx (e.g. timeout) errors.
* Improves user experience when fetching many material documents by providing a progress bar (uses `tqdm_notebook` if `tqdm` is installed and user is in Jupyter Notebook, falls back to plain `tqdm` if installed, and otherwise uses simple `print`-based progress indication.
* Puts …

Add query-chunking capability to MPRester.query

---

pymatgen/analysis/dimensionality.py
pymatgen/analysis/tests/test_dimensionality.py

Added a number of features relating to structure components.
* `get_structure_component_info` renamed to `get_structure_components`
* `get_structure_components` can now return the indices of the corresponding sites in the original structure.
* Can also return `MoleculeGraph` objects for any zero dimensional components.
A future PR will use this functionality to replace the `Graph.get_subgraphs_as_molecules` implementation (will currently will fail for some systems).

Structure component enhancements

---

pymatgen/core/surface.py

Added removal_list to store all indices to be removed, and call remove_sites only if all indices have equivalent sites for removal.
* Previous implementation removes site (and its equivalent) for each point during the loop, while not updating the symmetric structure used for reference. This could potentially lead to indices being off by 1 for each removal.

fixed symmetrically_remove_atoms() for multiple indices removal

---

pymatgen/analysis/defects/utils.py

The new merged coordinate sometimes likes outside the [0,1) range

Small bug fix

---

pymatgen/core/composition.py
pymatgen/core/tests/test_composition.py

to_data_dict['element'] returned <dict_keys> which is a generator and cannot be pickled

Bug fix in core.composition

---

pymatgen/core/composition.py
pymatgen/core/tests/test_composition.py

Composition.oxi_state_guesses currently has a `max_sites` option where, if possible, the composition will be reduced to at most this many sites to speed up oxidation state guesses. If the structure cannot be reduced to this many sites an error will be thrown. If `-1` is passed to `max_sites` the composition will be fully reduced. However, the current behavior does not indicate whether the composition has been reduced at all. This can lead to very long running times for large systems which cannot be reduced.
This PR allows setting `max_sites` to negative numbers less than -1. In this case, the structure will be fully reduced however an error will be thrown if the number of sites in the reduced structure is greater than `abs(max_sites)`. This allows one to fully reduce the composition but …

Add error throwing for negative max_sites in Composition.oxi_state_guesses

---

pymatgen/analysis/graphs.py

`graphs.py` currently has a call to `logging.basicConfig` to set the logging level. This will affect the top level logger rather than the module level logger. The code now sets the logging level of the module level logger.

Remove logging.basicConfig call in graphs.py

---

pymatgen/core/lattice.py

The `get_integer_index` function for miller indices now correctly returns integer indices when possible (if an integer index cannot be determined a floating point index is given).
E.g. `get_integer_index((2, 2, 0))` now gives `(1, 1, 0)` rather than `(1.0, 1.0, 0)`.

Fix integer miller indices

---

pymatgen/analysis/dimensionality.py
pymatgen/analysis/tests/test_dimensionality.py

Added the `inc_graph` option to `get_structure_components()` to allow returning of networkx graphs for structure components.
The graphs have their nodes indexed to match the returned component `Structure` objects rather than initial structure passed to `get_structure_components`.

Add option to return graph for structure components

---

pymatgen/ext/matproj.py

materialsproject.org without the www will be the preferred endpoint going forwards

Change default MPRester endpoint at request of @dwinston

---

pymatgen/electronic_structure/cohp.py
pymatgen/electronic_structure/tests/test_cohp.py

I have removed the methods get_cohp and get_icohp in CompleteCohp. They are now inherited from Cohp and give an array with the average cohp. Instead, I included get_cohp_by_label which gives a Cohp object that can now be easily plotted with CohpPlotter. Furthermore, I included tests. I am also planning to update the tutorial on how to plot COHP from Lobster.

Simplification of COHP Plotting

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Adds the function "get_parchg" to the Wavecar class. This function outputs a Chgcar object that corresponds to the charge density of the specified wavefunction. This emulates the PARCHG output from VASP, but it does not include augmentation from the PAWs.
* PARCHG from a Wavecar object
* For real wavefunctions, adds the ability to visualize the phase of the wavefunction.
N/A
N/A

PARCHG from WAVECAR

---

pymatgen/analysis/ferroelectricity/polarization.py
pymatgen/analysis/ferroelectricity/tests/test_polarization.py

VASP reports dipole moments in along Cartesian directions. This pull requests adds the ability to specify when creating a Polarization object whether ionic and electronic contributions to the polarization are given in Cartesian or lattice directions. The default for ionic contributions is lattice directions (since it is recommended to use the calc_ionic function as described in the documentation) and the default for electronic contributions is Cartesian (since these are read directly from VASP). I have added a test checking that the conversion between Cartesian to lattice directions is computed correctly and added additional documentation detailing these conventions.

Polarization cartesian fix

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py
pymatgen/analysis/vesta_cutoffs.yaml

Adds the VESTA bonding cut-offs as a preset to the CutOffNN class.
The cut-offs were taken from the style.ini file distributed with VESTA. These cut-offs seem to have been generated based on bond valence parameters but I'm not sure how exactly.

Add VESTA bonding preset to CutOffNN

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Based on discussions with @shyamd, @mkhorton and @tschaume, I've updated the default smearing parameters for NonSCF uniform calculations.
The parameters I've modified are:
- NEDOS now 2001 for uniform calculations.
- ISMEAR now -5 (tetrahedron method with Blöchl corrections) for uniform calculations.
This should give nicer looking density of states/optics plots.
For consistency, I think it is best to keep the parameters the same for metals and insulators . Down the line, we could apply additional broadening to reproduce experimental spectra (UPS, XPS, etc) using [galore](https://github.com/SMTG-UCL/galore).

Update MPNonSCFSet smearing parameters

---

pymatgen/io/lammps/data.py
pymatgen/io/lammps/tests/test_data.py

* Fix rotation operation for orthogonal box **not** originally aligned with Cartesian axes. 
* Fix `Topology` serialization caused by numpy data type.
None

Misc fixes for lammps data

---

pymatgen/analysis/structure_prediction/tests/test_volume_predictor.py
pymatgen/analysis/structure_prediction/volume_predictor.py

Issue #1295 mentions that DLSVolumePredictor can have very large errors in rare (but important) instances.
As no long-term solution is likely forthcoming, this PR allows the user to set bounds on how much the volume can change from the initial structure, with defaults of 50% to 150% of the original cell volume.
Unit tests have been updated.

DLS predictor - add limits

---

pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py

The current implementation of `from_dict` in `Molecule` fails if a `DummySpecie` is present: 
```
from pymatgen import Molecule
m = Molecule(species=["X"], coords=[[0,0,0]])
Molecule.from_dict(m.as_dict())
```
leads to the following error:
> 
> /pymatgen/pymatgen/core/structure.py in from_dict(cls, d)
>    2005                             if "oxidation_state" in sp else
>    2006                             Element(sp["element"]): sp["occu"]
> -> 2007                             for sp in site_dict["species"]})
>    2008             coords.append(site_dict["xyz"])
>    2009             siteprops = site_dict.get("properties", {})
> 
> /pymatgen/pymatgen/core/structure.py in <dictcomp>(.0)
>    2005                             if "oxidation_state" in sp else
>    2006 …

fix json serialization for Molecule with DummySpecie

---

pymatgen/io/vasp/inputs.py

```python
#!/usr/bin/env python3
import numpy as np
from pymatgen import Structure
from pymatgen.io.vasp import Poscar
N = 100000
s = Structure(np.array([[1,0,0],[0,1,0],[0,0,1]]), ['C']*N, np.zeros((N, 3)))
Poscar(s, velocities=np.zeros((N, 3)).tolist()).get_string()
```
Prepare to wait several millenia.
pymatgen has some bad cases of property abuse, but this takes the cake.  Writing a file had O(N^2) performance because `Poscar.selective_dynamics` is a property implemented in terms of another property that transposes a list of dicts for all atoms.
(and it *still* computes this transpose of dicts way more times than it should have to)

Fix outrageous performance bug in Poscar.get_string

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py

- fix behavior of `NearNeighbors._get_image` to deal with cases such that initial sites are not in unitcell(fix https://github.com/materialsproject/pymatgen/issues/1321)
An image is defined as displacement from original site in structure to a given site.
For example, if structure has a site at (-0.1, 1.0, 0.3), then (0.9, 0, 2.3) -> jimage = (1, -1, 2).
Note that this definition returns the same result with the previous implementation of `NearNeighbors._get_image` for atoms in unit cell(i.e. when fractional coordinates are contained in [0, 1)^3)

Fix NearNeighbors._get_image to work properly for sites not in unitcell

---

pymatgen/core/periodic_table.py

To prevent `TypeError: invalid file: PosixPath()`

Fix Python 3.5 compatibility

---

pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

Add a user-agent header of [conventional syntax](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) to identify pymatgen and its version to the MP server.
* Allows server, if it is running a later version of pymatgen than the user, to suggest upgrading (e.g. through adding a note in the response "warning" field).
* Allows server to collect statistics on pymatgen versions in active use for gathering MP data, and on what proportion of API use is via pymatgen.

[WIP] Add user-agent header to MPRester session requests

---

pymatgen/analysis/structure_matcher.py
pymatgen/analysis/tests/test_structure_matcher.py

The current OrderDisorderElementComparator will match in unexpected cases. E.g.,
1.  A structure with the fractional composition Sn0.2 O0.8 will match a structure with the composition Sn0.5 O0.5.
2.  A structure with a 50:50 Sn:Pb site would match with a structure with a 50:50 Sn:O site.
This PR fixes both scenarios and should allow proper matching of disordered structures to their ordered counterparts.

Implement new OrderDisorderElementComparator

---

pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py

Previously site properties in slabs were not passed to the new slab when getting an orthogonal c slab.

Propagate site properties to orthogonal slab

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

As discussed in #1453, currently the MPNonSCFSet k-point generation routines are incompatible with tetrahedron smearing for uniform calculations. Historically, this decision was made to enable compatibility with Boltztrap calculations.
As we are transitioning to using tetrahedron smearing for higher quality density of states, I have updated the MPNonSCFSet "uniform" mode to be compatible with tetrahedron smearing. In addition, I have added a "boltztrap" mode which reproduces the legacy behavior.
I have added tests for the new uniform behavior and for the old boltztrap behavior.

Add boltztrap mode to MPNonSCFSet

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Based on the discussion in #1464, I have added `override_from_prev_calc` methods to the VASP input sets that already define `from_prev_calc`. In each case, the old `from_prev_calc` method has been rewritten to use `override_from_prev_calc`. This new approach has several advantages, including:
- The `from_prev_calc` and `override_from_prev_calc` parameters are now consistent for every input set.
- There are now no duplicated parameters. Previously, some defaults were defined in both `__init__` and `from_prev_calc`, now they are all defined in `__init__`.
- The implementation in atomate should be significantly cleaner.
Some additional notes:
- Previously, some from_prev functions had a `standardize` keyword that would transform the structure to the standardized primitive cell. It seemed …

Add override_from_prev_calc to VASP input sets

---

pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py

Added the argument "ximages" to IStructure.interpolate. This allows you to define an arbitrary grid of interpolation points between the two lattices. This is useful for making configuration coordinate diagrams.
"nimages" was left intact to maintain backwards compatibility. "ximages" may not be the best name, feel free to change it to something more descriptive.
N/A
N/A

Interpolate ximages

---

pymatgen/electronic_structure/plotter.py

* Fix the rgb_label of 2 elements band structure
After fix: 
Before fix:

Fix the rgb_label of 2 elements band structure

---

pymatgen/analysis/defects/thermodynamics.py
pymatgen/electronic_structure/dos.py
pymatgen/electronic_structure/tests/test_dos.py

Currently, FermiDos objects are not MSONable for two reasons:
1. They have a strange constructor that requires a Dos object rather than energies, densities and a Fermi level like other Dos subclasses.
2. The nelecs variable is not stored, even as a private variable.
Ideally I'd correct the constructor but I don't want to break other peoples code. Instead, I've added custom to_dict and from_dict methods and fixed point 2.
I've also tied up the class, made it pep8 compliant and added type hinting.

Make FermiDos MSONable

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py

In the current master branch, `pymatgen.analysis.local_env.CovalentBondNN` returns AttributeError with the following code:
```
from pymatgen.core import Molecule
from pymatgen.analysis.local_env import CovalentBondNN
H2 = Molecule(['H', 'H'], [[0, 0, 0], [0, 0, 1.0]])
bonds = H2.get_covalent_bonds()
assert(len(bonds) == 1)
cbnn = CovalentBondNN()
mg = cbnn.get_bonded_structure(H2)
```
I find `CovalentBondNN.get_bonded_structure` calls `pymatgen.analysis.graphs.with_local_env_strategy` with defalut flag, and the latter returns not Molecule object but Structure object.
I fix a corresponding part and add test for `CovalentBondNN.get_bonded_structure`.

fix CovalentBondNN.get_bonded_structure

---

pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py

1. Fixed the return type of `get_all_neighbors` when no neighbors are found. It should return a list of length n, where each item is `[]` and n is the number of atoms
2. Fixed the `magnetism` test problem. It is an issue with coincide sites. The site with DummySpecie coincides with a normal site and now the `get_neighbors` can find the correct neighbors from the Dummy site. 
In the case where two identical sites exist in a structure, the `get_neighbors_old` will not find any neighbors using one of the site (small cutoff). However, if one site has a different specie, then the algorithm will be able to find neighbors. It does not seem to be physical since neighboring relationship is only spatial information and should have nothing to do with the Specie. Now I set `get_neighbors` to have the …

Bug fix for get_all_neighbors

---

pymatgen/core/sites.py

Quick fix, just a docstring typo. Previously the docstring for Site.coords said that the coordinates were fractional, but actually they are cartesian.

fix Site.coords docstring to say Cartesian instead of fractional

---

pymatgen/symmetry/maggroups.py

This fixes magnetic symmetry operations in pymatgen/symmetry/maggroups.py . 
* Fix 1 : Hexagonal magnetic spacegroups start at 143 instead of 168. This can be verified by VESTA.
* Fix 2 : When reshaping data from https://stokes.byu.edu/iso/magnetic_data.txt , the data should be read in columns instead of rows.
* None
* Verify that the `_parse_transformation(b)` is giving expected results. Before/after the fix it was giving results which are the same as reference, but in a slightly different format. I'm unsure if this is intentional.

Fix for magnetic space groups

---

pymatgen/analysis/interface.py
pymatgen/analysis/tests/test_interface.py

-Override the as_dict() and from_dict() functions from pymatgen.core.structure.Structure for proper serialization
- Cleaned up extraneous imports
- Fixed option to create copy with site properties (Previously documented as such, with no functionality)
- Override get_sorted_structure() from Structure. Not sure if this was the right way to fix the issue; the alternative is to make an Interface.from_sites() function, although one will likely never make an interface from a list of sites. 
- Unit tests

Fix serialization of Interface

---

pymatgen/apps/borg/hive.py
pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Updated run_type_method but phonoopy test giving error which is independent of my changes.
* Modified run_type_method in Vasprun class within outputs.py script to account for wider range of functionals/levels of theory.
* Added tests within test_outputs.py script in io/vasp/tests directory and new test files relevant to various functionals/levels of theory.
to be done
* Add functionality to account for Many-Body perturbation theory (GW, GoWo, scGW, etc.), the Random Phase Approximation (ACDFT/RPA), Time-Dependent DFT (TD-DFT) and Time-Dependent Hartree-Fock equations (TDHF) via the Bethe Salpeter and Casida equations (BSE), and other higher levels of theory.

Modified run_type in outputs.py.

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

This PR tries to fix the issue of #1513.
When running vasp with the LVEL flag enabled, two kpoint sets are written to the vasprun.xml file.
One quite far up in the file, containing the kpoints in the irreducible Brillouin zone, and one after the self-consistent calculation inside the electronvelocities tag which contains points in the full Brillouin zone.
Here, I only prevent that the kpoint variables read for the first set in Vasprun are overwritten by the second set. 
Also added a test that ensures that the kpoint dimension of the eigenvalues array is equal to the number of kpoints.
points
* Recover default behaviour, when LVEL flag in vasp calculation is set
A later feature PR should introduce new variables for the second …

Fix reading the SC K-Point set when LVEL flag is set.

---

pymatgen/analysis/adsorption.py
pymatgen/analysis/tests/test_adsorption.py

Updated _add_adsorbate_ to work with a copy of the adsorbate molecule and added the _translate_ keyword - if _True_, the molecule is translated to the origin before being added to the surface.
* Updated _add_adsorbate_ to work with a copy of the molecule passed as an argument. Previously, if _reorient_ was _True_ (it is by default), the molecule would be rotated in place. In the case of consecutive structure generation (such as in the adsorption workflow from atomate), the adsorbate would keep rotating after each structure generation.
* Added the option to translate the molecule to the origin before adding it to the surface. Previously, the position of the adsorbate was fully dependent on the position of the input molecule - which could lead to structures with adsorbates that are …

Add option to translate molecule to origin in add_adsorbate

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py
test_files/OUTCAR.LaSnNO2.polar

Fixes a rare bug in the Outcar.read_pseudo_zval method of pymatgen.io.vasp.outputs.  The new method doesn't make any assumptions about the POSCAR's title line, since this has no meaning in VASP.  If adding a new OUTCAR test file is unwanted, I can modify the existing OUTCAR.BaTiO3.polar to check this issue instead.  Thanks to @blondegeek for the help!
* Outcars now get their zval_dict keys from more reliable part of the OUTCAR

Pseudo_zval bugfix

---

pymatgen/io/shengbte.py
pymatgen/io/tests/test_shengbte.py
requirements-optional.txt
test_files/shengbte/CONTROL-CSLD_Si

@utf 
Initial commit for interfacing Pymatgen with ShengBTE. More features will be added later.
ShengBTE is a software package for solving the Boltzmann Transport Equation for phonons. It is capable of using 2nd and 3rd order interatomic force constants to calculate lattice thermal conductivities of bulk crystalline solids and nanowires. Full details can be found at the following link: https://doi.org/10.1016/j.cpc.2014.02.015
Added an IO for reading/writing/updating ShengBTE CONTROL files with Python dictionaries.
'f90nml' for reading FORTRAN namelists used as input for running ShengBTE.

Add ShengBTE IO Functions

---

pymatgen/cli/pmg.py
pymatgen/cli/pmg_potcar.py

Prompted by [user post](https://discuss.materialsproject.org/t/cli-error-occur-using-mpg-potcar-r/2429) to MP's forum.
There is no `spec` arg destination. Fixes this. Also, argparser help text indicates one directory only should be given, and `cli.pmg_potcar.proc_dir` appears to expect only one as well, so removes `nargs="+"` in the arg parsing.
Test? I ran with a mock `POTCAR.spec` file with just the symbol `Ag` in it and got the error
> ValueError: No POTCAR for Ag with functional PBE found
so I think it's getting to the right point in the application logic. I have no interest in writing a proper test for this.

Fix bug in `pmg potcar` command

---

pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py
pymatgen/ext/matproj.py

Added a new function in surface.py called get_symmetrically_equivalent_miller_indices which takes in a structure and Miller index and returns a list for the family of hkl. Useful for searching for Miller index specific entries on MPRester (surface data, GB data, Wsep) as the user does not need to enter the exact same Miller index as the one associated with an entry. Modified get_surface_data using this function to make it easier to obtain work of separation from GB data.
* Feature 1 get_equivalent_miller_indices(structure, miller_index)
* Fix 1: Can now get specific surfaces without needing the exact same Miller index
Some overlap between get_symmetrically_equivalent_miller_indices and get_symmetrically_distinct_miller_indices.

Get symmetrically equivalent Miller indices

---

pymatgen/analysis/wulff.py
pymatgen/core/lattice.py
pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py
pymatgen/ext/tests/test_matproj.py

Added unit testing for querying work of separation. Also moved get_recp_symmetry_operation function as a Lattice method. 
* I would prefer to have get_recp_symmetry_operation as a Lattice method since its more related to lattices and not just surfaces, however at the moment it requires a local import of Structure and SpacegroupAnalyzer to work which may be unwieldy?
* I want to make get_symmetrically_equivalent_miller_indices and get_symmetrically_distinct_miller_indices as a Lattice method as well, however there is the issue of getting Miller indices for trigonal systems which at the moment requires searching through the rhombohedral basis instead of the hexagonal basis to identify all the Miller indices. This is an issue because a lattice object won't know to look at a rhombohedral …

Moved some functions as a Lattice object method.

---

pymatgen/io/babel.py
pymatgen/io/tests/test_babel.py

As suggested in https://github.com/materialsproject/pymatgen/issues/1512#issuecomment-506859409, this PR adds a ``return_all_molecules`` option to ``BabelMolAdaptor``, which, when set to ``True``, will return one instance of the adaptor for each molecule found in a file. The previous behavior was to always return just the first molecule found and discard the rest, which this PR leaves as the default behavior for backwards-compatibility.
Fixes #1512.

Add return_all_molecules option to BabelMolAdaptor

---

pymatgen/core/xcfunc.py

The current implementation of `from_abinit_ixc` breaks for `ixc == 0`, which is the value ABINIT uses for "no XC functional". The proposed implementation just returns `None` instead of asking the dict explicitly.

Fix ixc == 0 in from_abinit_ixc

---

pymatgen/transformations/advanced_transformations.py
pymatgen/transformations/tests/test_advanced_transformations.py

@utf 
Fix for issue #1536 
- Fixed class attribute names to match keyword args in inits
- Revised PerturbSitesTransformation to have the correct format for a 'one-to-many' transformation
Potentially merge PerturbSitesTransformation (one-to-many transform) with PerturbStructureTransformation (one-to-one transform). Not sure about the best way to do this

WIP: Fixed MSONability CubicSupercellTransformation and PerturbSitesTransformation

---

pymatgen/analysis/bond_valence.py
pymatgen/analysis/tests/test_bond_valence.py

New Structure `get_neighbors` returns namedtuples which breaks usage of `calculate_bv_sum_unordered`. It appears `calculate_bv_sum` was fixed previously though.
* Fix `test_calculate_bv_sum_unordered`
* Add tests for both bv_sum functions (previously missing, hence why this bug existed)
* Cleaned up the docstrings for these two functions to match the implementation
There is probably a way to combine these into one function for a little less boilerplate, but that's maybe something for a future PR. This is just a minimum changes necessary fix.

Bond valence sum unordered function fix

---

pymatgen/apps/battery/conversion_battery.py

- added kwarg that allows unstable entry to be used in the constructor. This allows us to get a conversion voltage estimate any new cathode materials, not just ones on the convex hull.
- changed the output of all_pairs and adj_pairs to lists not iterators

Small change to conversion electrodes

---

pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
pymatgen/analysis/chemenv/coordination_environments/voronoi.py
pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py
pymatgen/analysis/diffraction/neutron.py
pymatgen/analysis/graphs.py
pymatgen/analysis/local_env.py
pymatgen/analysis/magnetism/analyzer.py
pymatgen/analysis/magnetism/jahnteller.py
pymatgen/command_line/critic2_caller.py
pymatgen/core/surface.py
pymatgen/electronic_structure/core.py
pymatgen/io/babel.py
pymatgen/io/nwchem.py
pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/sets.py
pymatgen/symmetry/maggroups.py
pymatgen/transformations/advanced_transformations.py
pymatgen/transformations/defect_transformations.py

* Fix docstrings with multi-line :param: and :return: directives not being rendered correctly. This was due to an (undocumented) quirk in sphinx discussed [here](https://stackoverflow.com/questions/32566466/multi-line-description-of-a-parameter-description-in-python-docstring). 
* I also fixed a few issues with the display of some numbered lists.
See screenshots of the incorrect rendering attached.
@shyuep - I've tested this with ```invoke make-docs```. Do you want me to commit the built docs as well, or just the code?

Fix multi-line :param: and :return: directives in docstrings

---

pymatgen/entries/computed_entries.py
pymatgen/ext/matproj.py

* By analogy to the `energy_per_atom` property, it would be useful for ComputedEntry objects to have an energy per formula unit property to unambiguously return the energy associated with a single formuala unit or reduced formula. The first commit adds this property
* `get_entries_in_chemsys` currently requires a list input e.g. ['Li','O'], but the `chemical_system` attribute of Composition returns a str separated by dashes e.g. 'Li-O'. To improve interoperability, it should be possible to pass the dash-separated string into `get_entries_in_chemsys` in addition to lists. The second commit makes this possible

Enhancements to ComputedEntry and MPRester

---

pymatgen/analysis/tests/test_fragmenter.py

When fixing the metal_edge_extender test to not use babel, I turned off the other fragmenter tests and forgot to turn them back on. This fixes that.

Turning back on fragmenter tests

---

pymatgen/util/plotting.py
pymatgen/util/tests/test_plotting.py

Add options to adjust the range of the colorbar and the size of the label in `periodic_table_heatmap`. The ability to adjust the scale is useful if you want to generate multiple plots for comparison to one another, and make sure they all use the same scale.
Also corrected some inaccuracies in the docstring.

Add options and docs to periodic_table_heatmap

---

pymatgen/electronic_structure/cohp.py
pymatgen/electronic_structure/tests/test_cohp.py

Hello!
I included an additional test to make sure that two lists that should have the same length actually have the same lengths. These lists are parameters for "get_summed_icohp_by_label_and_orbital_list". I have also included a test to make sure an error will be raised if they have different lengths. 
Best, 
JG

Include additional check to avoid problems for summed cohps

---

pymatgen/io/tests/test_xcrysden.py
pymatgen/io/xcrysden.py

Closes #1616 
The XCrySDen parser now imports from the `pymatgen.core.Element` module.

Fixed bug in XCrySDen parser failing to parse element symbols

---

setup.py

Fix macos compilation error by adding `-stdlib=libc++` link flag

fix c++ link args

---

pymatgen/core/lattice.py
pymatgen/core/tests/test_lattice.py
pymatgen/optimization/neighbors.cpp
pymatgen/optimization/neighbors.pyx
pymatgen/optimization/tests/test_neighbors.py

Small changes to revise details of how to treat mixed periodic boundary and non-periodic boundary in the general `find_points_in_spheres` function. 
If the structure has periodic and non-periodic boundary mixed case (2d material, 1d material etc) the find points in spheres function will not augment the non-periodic dimension. Previous one was not robust and needs to supply a large enough lattice to make it correct. This is fixed in this PR.

robust pbc considerations for get neighbors

---

pymatgen/analysis/local_env.py

The `MinimumVIRENN` near neighbors class relies on the `ValenceIonicRadiusEvaluator` which is extremely slow.
If using `MinimumVIRENN` to get the coordination of all sites in a structure, the `ValenceIonicRadiusEvaluator` class will be initialized once per site. This is very inefficient as `ValenceIonicRadiusEvaluator` calculates ionic radii for the whole structure simultaneously.
I've therefore enabled caching of the `ValenceIonicRadiusEvaluator` class using the `lru_cache` functionality in `functools`. In my testing, for some structures this result in a 10x speedup.

Use caching in MinimumVIRENN class

---

pymatgen/io/gaussian.py
pymatgen/io/tests/test_gaussian.py

This change makes it possible to write Gaussian input files without needing a geometry, 
which is useful in writing input files for restarting runs. 
None
None
highly recommended that you use the pre-commit hook provided in the pymatgen 
repository. Simply `cp pre-commit .git/hooks` and a check will be run prior to
allowing …

Added ability to make Gaussian input file without a geometry

---

pymatgen/electronic_structure/bandstructure.py
pymatgen/electronic_structure/tests/test_bandstructure.py
pymatgen/io/lobster.py
pymatgen/io/tests/test_lobster.py

Hello, 
There was a problem in LobsterBandStructureSymmLine due to the use of "Species". I have fixed this and reverted some changes in the tests that were done to account for this problem. Without the current pull request, plotting fatbands from Lobster isn't possible anymore. I have also included an additional test that might help to avoid such changes of tests in the future. 
I have also extended the Doscar class to also read in the integrated total density of states from Lobster. Tests have been added as well.
Best, 
JG
Run …

Fix broken plotting of fatbands from lobster and extension of Doscar class for lobster

---

pymatgen/io/vasp/outputs.py

To parse the connected numbers, modify the regular expression.
See Issue #1668

Fix regular expression in read_onsite_density_matrices in Outcar

---

pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py
pymatgen/util/typing.py

VASP now [recommends](https://www.vasp.at/wiki/index.php/KSPACING) setting KSPACING in the INCAR file rather than supplying KPOINTS manually. This PR updates the teterror handler to accommodate calculations that use KSPACING instead of an explicit KPOINTS file.
Currently, if a user adds KSPACING to user_incar_settings when initializing a VaspInputSet, the setting will be ignored and a KPOINTS file generated anyway. This PR ensures that the KSPACING setting passed to VASP as expected.
See also Custodian [#139](https://github.com/materialsproject/custodian/pull/139)
See also a [similar issue](https://gitlab.com/ase/ase/merge_requests/226/commits) recently fixed in ASE.

Respect KSPACING setting in the INCAR

---

pymatgen/io/ase.py
pymatgen/io/tests/test_ase.py

* Added ``pymatgen.Molecule`` support to ``AseAtomsAdaptor``:
* ``AseAtomsAdaptor.get_atoms()``now also accepts ``Molecule``s (previously, it would only accept ``Structure``s)
* New (static) method ``AseAtomsAdaptor.get_molecule()`` (analogous to the existing ``get_structure()``method, but returns ``Molecule``s instead of ``Structure``s)
* Slightly extended tests
Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/) on your local machine.
- Only one way to find out for sure...

Add pymatgen.Molecule support to AseAtomsAdaptor

---

pymatgen/analysis/gb/grain.py
pymatgen/analysis/gb/tests/test_grain.py

Current implementation sometimes returns a structure with fractional coordinates whose absolute value are greater than one. It is not wrong but inconvenient when it is used in external calculation modules (and also it seems many users think it as unexpected behavior).
(related to [#1693](https://github.com/materialsproject/pymatgen/issues/1693))
* `pymatgen.analysis.gb.grain.gb_from_parameters()` now returns a structure with fractional coordinates in [0, 1).
* A Test for fractional coordinates has been added to `test_gb_from_parameters()` to check the fractional coords within [0, 1).
on your local …

Force GrainBoundaryGenerator.gb_from_parameters to return fractional coords within unit cell

---

pymatgen/core/bond_lengths.json
pymatgen/core/tests/test_bonds.py

Added data for an sp2 N-N bonds in bond_lengths.json
Use value of 1.25 from the following source
http://www.wiredchemist.com/chemistry/data/bond_energies_lengths.html

Fix bug of missing sp2 N-N bond data

---

pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py
setup.py

Added a Structure method to construct neighbor list without using Neighbor class. Previously this is achieved by using `get_all_neighbors` method, which is much slower than the proposed methods.  It may become a problem when the structure is very large, e.g., >10,000 atoms.
Here I am adding a new method `get_neighbor_list` to `Structure`, that returns the full information about neighbors without the use of many python native objects. This new method returns a tuple of numpy array `(center_indices, points_indices, offset_vectors, distances)` as the neighbors. Here atom `center_indices[i]` has neighbor atom index `points_indices[i]` that is translated by `offset_vectors[i]` lattice vectors, and the distance between them is `distances[i]`.  
For a Mo structure with atom numbers of `1000` …

Add fast `Structure.get_neighbor_list` method

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

This morning @mkhorton @shyamd @kristinpersson and I decided to compute the KSPACING value based on the bandgap of the input material in our SCAN workflow. At the time I thought this functionality would be part of atomate, but later learned it needs to be in MPScanRelaxSet.
I also identified and corrected a potential bug / unintended behavior when a user tries to override KSPACING, ISMEAR, or SIGMA.

determine kspacing and smearing from bandgap in MPScanRelaxSet

---

pymatgen/io/vasp/outputs.py

* Fix 1: When writing CHGCAR files, if a full line is already output in the last step of the for loop, additional blank line is no longer added.

Bug fix: remove occasional blank line that makes CHGCAR unreadable

---

pymatgen/analysis/phase_diagram.py
pymatgen/analysis/tests/test_phase_diagram.py

Sorts elements determined from entries, if elements are not explicitly specified.  Adds test for to ensure that specified element order is respected and that unspecified element orderings result in the same ordering.  Addresses #1721 .

Element sorting in Phase Diagram

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Adds a boolean `potcar_spec` option to the `write_input` method of a `VaspInputSet`. When this option is enabled, `write_input` generates a POTCAR.spec file rather than a POTCAR file (similar to the existing `write_spec` method, which outputs a .zip file containing all the inputs.) The purpose of this option is to facilitate sharing of inputs and automated testing in environments where POTCAR files are not available due to licensing. 
In this particular case, I developed some tests for a new atomate workflow in which the input set utilized POTCAR files that are not distributed with pymatgen (see https://github.com/hackingmaterials/atomate/pull/345). It was not possible for the CI testing to call `write_input` on my inputset because of the missing POTCARs. A similar issue affects some of …

add potcar_spec option to write_input

---

pymatgen/electronic_structure/plotter.py

* Added a horizontal line at y=0 for the DOS plotter. This is helpful when we have spin polarized DOS plots.

DOS Horizontal Line

---

pymatgen/io/vasp/sets.py

This commit refactors 'write_input' so that 'get_vasp_input' is not called when `write_spec` is True. Avoiding the call to `get_vasp_input` is important for testing in systems where no POTCARs are installed. @utf was consulted on this fix as well. See https://github.com/hackingmaterials/atomate/pull/345

Refactor write_input() when potcar_spec=True

---

README.rst
pymatgen/io/tests/test_xyz.py
pymatgen/io/xyz.py

I just change two characters in the regex used to read XYZ files in order to allow more flexibility (again).
For example, I got some files such as:
```
32
C32-C2-1                                                                        
C     2.70450   1.16090  -0.14630     1     3    23     2
C     1.61930   1.72490  -0.79330     2     1     5    26
C     2.34210   1.02670   1.14620     3     1     8     6
C    -0.68690   2.16170  -0.13790     4     5    18     7
C     0.67160   2.15830   0.14350     5     4     2     6
```
The integers at the end of the lines correspond to the connectivity. Thus I change the regex in order to ignore this but read the xyz file. I add tests also.

XYZ reader

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

As discussed with @mkhorton, here an implemention of
an automatic setting for NEDOS for "uniform" mode in MPNonSCFSet.
It reads the max and min of eigenvalues from previous vasprun and use
a default energy step, called dedos, set at 0.005eV.
It works setting nedos=0 in from_prev_calc() method:
mpset = MPNonSCFSet.from_prev_calc(prev_static_dir,mode="uniform",nedos=0)  
Let me know if it's ok or it need to be implemented differently.

Automatic setting for NEDOS in MPNonSCFSet

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Recent changes to `write_input` contained a bug regarding cases in which there was no KPOINTS file. In such cases, `write_input` would still write an empty file, causing problems with downstream logic.

MPScanRelaxSet: fix bug and add write_input test

---

.travis.yml
pymatgen/analysis/bond_dissociation.py
pymatgen/analysis/fragmenter.py
pymatgen/analysis/functional_groups.py
pymatgen/analysis/graphs.py
pymatgen/analysis/local_env.py
pymatgen/analysis/molecule_matcher.py
pymatgen/analysis/tests/test_bond_dissociation.py
pymatgen/analysis/tests/test_fragmenter.py
pymatgen/analysis/tests/test_functional_groups.py
pymatgen/analysis/tests/test_graphs.py
pymatgen/analysis/tests/test_local_env.py
pymatgen/core/structure.py
pymatgen/core/tests/test_structure.py
pymatgen/io/babel.py
pymatgen/io/qchem/outputs.py
pymatgen/io/qchem/tests/test_outputs.py
pymatgen/io/tests/test_babel.py
requirements-optional.txt
setup.py

This PR addresses two major issues:
* The recent OpenBabel release 3.0.0 breaks the previous API in several ways, most notably in how the Python interface is imported
* A bug was found in which certain NearNeighbors classes failed to approrpriately detect bonds in molecules
With respect to the second change, all NearNeighbor classes now have properties describing if they can be used with Molecules, Structures, or both. MoleculeGraph and StructureGraph now prevent the user from using with_local_env_strategy with an inappropriate strategy.
Additionally, the bug which caused an automatic re-indexing of Molecules has been identified and fixed.
* openbabel 3.0.0
on your local …

Update OpenBabel; Fix NN classes, graph classes

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

* Parse NPLWV from OUTCAR file using the read_pattern method of Outcar class
* Parse numbers of plane waves at each kpoint from OUTCAR file using the read_table_pattern method of Outcar class

Parse NPLWV, NPLWVs at kpoints from OUTCAR-files into Outcar.data dictionary.

---

pymatgen/io/tests/test_zeopp.py
pymatgen/io/zeopp.py

Fixes minor bugs on Zeo++ interface.
* `from_parameters(structure.lattice.parameters)` -> `from_parameters(*structure.lattice.parameters)` (starred)
* `self._mol` does not exist in `pymatgen.io.xyz.XYZ` anymore. Replaced by `self._mols[0]`.
* Test for getting free sphere parameters skipped, as file `free_sph.cif` does not exist anymore. All other tests for the zeopp file are ok.

Minor fixes to Zeo++ interface

---

pymatgen/analysis/wulff.py

Replace all deprecated use of scipy for linear algebra with numpy in wulff.py.
@mkhorton I think this should fix the noisy py3test issue on CircleCi, as I didn't see the previous messages from my tests flooding CircleCi anymore, but I did see some errors in things like test_molecule_matcher.py, though I don't think that is related to this pull right?

Replace deprecated modules

---

pymatgen/vis/structure_vtk.py

* Bugfix for StructureVis.add_structure: New `get_neighbors` returns PeriodicNeighbor object.

get_neihgbours returns PeriodicNeighbor objects

---

pymatgen/io/lammps/data.py
pymatgen/io/lammps/tests/test_data.py

*The box size values in the CombinedData object is now automatically updated by the min/max values of the coordinates.

automatic box size overwrite

---

pymatgen/analysis/pourbaix_diagram.py
pymatgen/analysis/tests/test_pourbaix_diagram.py
pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

* Fixes issue where Pourbaix diagram was considering MultiEntries where reaction calculator finds a balanced reaction with no product.
* Fixes issue with MPRester PourbaixEntry processing due to Entry refactor.  Specifically, `_energy`/`uncorrected_energy` mix-up.
The regression test that I've added is heavier than I'd like (on an already too-heavy set of tests for the pourbaix_diagram module), I can create a more minimal test that encapsulates the issue more neatly, but will need a bit more time to do so, so figured I'd issue the PR in case the bug fixes are a priority.

Pourbaix fix

---

pymatgen/symmetry/groups.py
pymatgen/symmetry/tests/test_groups.py

This merge request addresses issues #1801 and #1802. I decided to add the #1801 fix to the SpaceGroup.from_int_number() method, which is not the lowest function with the hexagonal=True input. The respective unittests for each fix were also added.

Hexagonal Sym Issues

---

pymatgen/electronic_structure/plotter.py

* Reorder logic in BSPlotter, such that check for metal is only executed when needed.
* The current implementation causes trouble in my downstream usage of pymatgen, so I'd appreciate a merge.

Reorder check for metal

---

pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_local_env.py

The EconNN class was rewritten to properly reproduce the algorithm outlined in:
https://www.degruyter.com/view/j/zkri.1979.150.issue-1-4/zkri.1979.150.14.23/zkri.1979.150.14.23.xml
This improves the performance of the method, particularly when only considering bonding between sites of opposing charge (controlled using the new `cation_anion` option).
The method has a tolerance parameter that determines when to consider a site bonded. After trialling several values, it seems like the results are rather insensitive in the range 0.1–0.6. I've set it to the optimal value of 0.2 that I found for my [test set](https://github.com/hackingmaterials/materialscoord).

Rewrite EconNN implementation

---

pymatgen/io/vasp/outputs.py

Got frustrated while reading a 1.5 GB file, so I tried to speed it up. Changed a couple lines in VolumetricData.parse_file, and here's what I got on my computer:
* test_files/CHGCAR.Fe3O4: 655 ms -> 368 ms (1.78x speedup)
* test_files/CHGCAR.NiO_SOC.gz: 779 ms -> 495 ms (1.57x)
* test_files/LOCPOT: 28.8 ms -> 16.1 ms (1.79x)
* test_files/ELFCAR.gz: 40.6 ms -> 22.7 ms (1.79x)
* 384 MB CHGCAR: 19.8 s -> 10.9 s (1.82x)
* 1.5 GB AECCAR: 81 s -> 48.3 s (1.68x)
None.
None.
Run …

VolumetricData speedup

---

pymatgen/analysis/local_env.py

This PR is related to #1825 and aims to track down the source of the bug.
```
from pymatgen.core.structure import Structure
from pymatgen.analysis import local_env
from pymatgen.analysis.graphs import StructureGraph
with open("breaking-oqmd-4866.txt", 'r') as file:
str_ = file.read()
crystal = Structure.from_str(str_, fmt="json")
print(crystal)
StructureGraph.with_local_env_strategy(crystal, local_env.VoronoiNN())
```
[breaking-oqmd-4866.txt](https://github.com/materialsproject/pymatgen/files/4474164/breaking-oqmd-4866.txt)

[WIP] Edge Case of VoronoiNN() not finding neighbours when called by StructureGraph.with_local_env_strategy()

---

pymatgen/symmetry/analyzer.py

* Fixed description for SpacegroupOperations.are_symmetrically_equivalent(). Input set of sites requires a list of PeriodicSite objects (not a Site objects).
* None 
* n/a
highly recommended that you use the pre-commit hook provided in …

SpacegroupOperations Description Fix

---

pymatgen/symmetry/kpath.py
pymatgen/symmetry/tests/test_kpath_lm.py
test_files/AgO_kpath_test.cif

This PR fixes a small bug in the `KPathLM` class where the code would hang when assigning labels to each of the points in a k-path for some complex cases.

KPathLM labels bug fix

---

pymatgen/io/vasp/inputs.py

Change k-points / atom to k-points / number of atoms
As mentioned in https://github.com/materialsproject/pymatgen/issues/1841, the comment line in the Pymatgen-generated VASP KPOINTS file is somewhat misleading. This PR changes it from being # kpoints/atom to # kpoints/number of atoms in the comment line, which is also consistent with what's on the [Materials Project documentation](https://materialsproject.org/docs/calculations). This should make it clearer that the number of k-points would be higher for smaller systems.
Perhaps worth noting: there is still the very minor ambiguity in that [pymatgen.ext.jhu](https://pymatgen.org/pymatgen.ext.jhu.html) takes `kppra` as an input argument, whereas [`pymatgen.io.vasp.inputs.Kpoints.automatic_density()`](https://github.com/materialsproject/pyma …

Clearer description in generated KPOINTS comment line

---

pymatgen/phonon/plotter.py

The labels seem to be incorrect (see https://github.com/materialsproject/pymatgen/blob/72d336d2d17ac140058fdcb74eb3336125bb12b7/pymatgen/phonon/dos.py#L229-L236 and https://github.com/materialsproject/pymatgen/blob/72d336d2d17ac140058fdcb74eb3336125bb12b7/pymatgen/phonon/dos.py#L263-L270 respecitvely)

Fix labels in plot_thermodynamic_properties

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

* Add a `poscar` attribute to the `Elfcar` class patterned after the `Chgcar` constructor
* Fixes bug described in #1858 
@rkingsbury @mkhorton

Add poscar attribute to Elfcar modeled after Chgcar

---

pymatgen/phonon/plotter.py
pymatgen/phonon/tests/test_plotter.py

The frequency unit can only be changed for a single bandstructure plot: https://github.com/materialsproject/pymatgen/blob/604d59c93f21c4a180663bdc6cd64bf1329c5239/pymatgen/phonon/plotter.py#L329 This is missing for plot_compare. I also provided a test (although it is not very useful to compare a bandstructure object with itself).

Add "unit" to plot_compare in PhononBSPlotter

---

pymatgen/io/tests/test_xyz.py
pymatgen/io/xyz.py

The QM9 database uses a special format for scientific notation in their .xyz files, wherein e.g. `3.14e-6` would be represented `3.14*^-6`. This addresses issue #1875 (which was not a bug per se, but simply brushing up against unimplemented behavior).
- The XYZ file parser can now handle this formatting for coordinates.
* This means changing the regular expressions which detect coordinate lines, as well as a substitution from the '*^' notation to 'e' notation.
- This capability is unit tested.
- [N/A] Docstrings have been added in the [Google docstring …

Add support for *^ scientific notation for XYZ parser (Useful for QM9 Database)

---

setup.py

Hi, 
I forget to change the setup.py to reflect the correct folder structure of the new lobster module. Currently, the basis functions are not found when pymatgen is installed... (Is it maybe possible to check for this within an automatic test in the future?)
Best, 
JG

change setup.py

---

pymatgen/analysis/costdb_elements.csv
pymatgen/io/vasp/outputs.py

This PR includes two different changes (poor style, I know - but the Github UI makes it difficult to separate them into different PRs after the fact):
This update for scientific notation is very similar to #1836 , except it now supports the dielectric tensor section of the OUTCAR as well (instead of just plasma frequencies)
The unit test from #1836 should also cover this one
Added cost data to CSV file for He,H,Ar,Ne,Kr,Tc; remove duplicate O row.
There is no new code here, just a data file update.

two changes: parse scientific notation dielectric data, update cost information

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py
test_files/OUTCAR_merged_numbers2

* Fixed regular expression to parse density matrix
At Line 1476 -- 1490 in OUTCAR_merged_numbers2 file in test_files
-------------------------------------------------------
spin component  1
6.1320 -7.9985  9.9720  5.1366 -1.5481
-7.9985 11.2215-13.7153 -6.9893  2.1083 **(Parse this line was okay.)**
9.9720-13.7153 17.1305  8.6130 -2.6035   **(Parse this line was failed.)**
5.1366 -6.9893  8.6130  4.6441 -1.3773
-1.5481  2.1083 -2.6035 -1.3773  0.5186
spin component  2
0.2072  0.0820 -0.0441  0.0155  0.0005
0.0820  0.1381  0.0032  0.0204 -0.0103
-0.0441  0.0032  0.1180 -0.0734  0.0235
0.0155  0.0204 -0.0734  0.1874 -0.0333
0.0005 -0.0103  0.0235 -0.0333  0.0992
-------------------------------------------------------

Fix regular expression of read_onsite_density_matrices

---

pymatgen/command_line/critic2_caller.py

This fix is needed as symbol shows the POTCAR label e.g. "Ca_pv" while element its name "Ca",
Fix #1890

Fix zpsp to have element names as its keys

---

pymatgen/symmetry/kpath.py

Correct bugfix if `nb` happens to come out as zero for a particular branch.

Avoid division by zero if nb == 0

---

pymatgen/io/babel.py
pymatgen/io/lammps/utils.py
pymatgen/io/tests/test_xyz.py
pymatgen/io/xyz.py

* Fix: small changes to important statements to align with openbabel 3.0 syntax
* Fix: removed casting to ASCII bytecode that was causing errors
* Feature: added as_dataframe method for XYZ and associated unit tests
* added imports for numpy and pandas to XYZ
highly recommended that you use the pre-commit hook provided in the …

## fix openbabel 3.0 compatibility in lammps submodule

---

pymatgen/command_line/enumlib_caller.py

Enumlib has been migrated to github.
1. Update link of enumlib from Sourceforge to Github
2. Update the citations according to https://github.com/msg-byu/enumlib#brief-description

Update the download link and citations for enumlib

---

pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py

A recent bug fix (1a3ce601c932ed80db14930da6e2c11a8a246771) introduced an incompatibility of the `Slab` class with the atomate `TransformerFW` and therefore broke surface workflows. Specifically, the `Slab` class now assumes the `scale_factor` input is a numpy array, whereas the `TransformerFW` supplies a list `scale_factor`. This caused an error during serialisation of the Slab when `tolist()` was called on a list.
This PR casts the `scale_factor` to a numpy array during initialisation of the Slab.
I've added a test.

Fix serialisation of slabs with list scale_factor

---

pymatgen/io/qchem/outputs.py
pymatgen/io/qchem/tests/test_outputs.py

* Fixes issue #1905 
* All frequency information can now be correctly parsed even when Raman intensities are being calculated

Fixing QChem frequency parsing when calculating Raman intensities 

---

pymatgen/analysis/xas/spectrum.py
pymatgen/analysis/xas/tests/test_spectrum.py

* Add check for empty spectrum and negative intensities
* Fix the jump in intensities at the L2 and L3-edge junction by extrapolating L2-edge XANES
* Add tests

Add validation and extrapolation for XAS stitching

---

pymatgen/io/gaussian.py
pymatgen/io/tests/test_gaussian.py
test_files/molecules/acene-n_gaussian09_opt.out

Hi pymatgen community!
In gaussian log, there are geometries outputted either in "standard" or "input" orientation or both together. The current implementation assumed that "input orientation" is always outputted but that is not the case (try e.g. [g.txt](https://github.com/materialsproject/pymatgen/files/5019019/g.txt)) and I was getting an error.
I modified the code such that by default, if it's there, the `opt_structure` will be of "standard orientation" and otherwise "input orientation". This is reflected by the `standard_orientation` boolean attribute and the same convention was already used for the `structures` attribute.
Previous version was mainly modified by @gVallverdu, so ping to you in case you're curious.

gaussian std orientation bug fix

---

pymatgen/entries/compatibility.py
pymatgen/entries/tests/test_compatibility.py

The new Compatibility interface (see #1826) provides a boolean `clean` argument to `process_entries` that determines whether or not previously-applied corrections are discarded when `process_entries` is called. We set this to `False` by default, but this has proven to be a bad choice. Myself, @shyamd and @awvio have all made errors using the new `process_entries()` because repeated calls to `process_entries` resulted in corrections being applied multiple times (contrary to our expectations). 
This PR changes the default to `True` so that corrections will only be applied one time by default, even if `process_entries` is called multiple times on the same entry.

Make clean=True default in Compatibility.process_entries()

---

pymatgen/io/babel.py

Instead of checking whether supplied objects are instances of ``Molecule``, ``BabelMolAdaptor`` now checks whether they are ``IMolecule``s instead (which is a superclass of ``Molecule`` so the old check still works). This fixes #1923. …

Allow BabelMolAdaptor to convert IMolecules

---

pymatgen/entries/compatibility.py

Replaces the code that removes previous `EnergyAdjustment` from `ComputedEntry` with a more robust alternative. See #1922

simplify cleaning of EnergyAdjustment

---

pymatgen/core/periodic_table.py
pymatgen/core/tests/test_periodic_table.py

Previously, asking for the valence property on an Element with full shells that wasn't noble (e.g. column 2 or 12) would cause an error. This resolves that.
* Added a check for if the last orbital listed is fully-occupied and to choose that number as the valency
* Added a case to the tests to trigger this
none
- [ x ] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). 
- [ x ] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_ …

fix valence bug, add test

---

pymatgen/symmetry/kpath.py
pymatgen/symmetry/tests/test_kpath_hin.py

The abstract class of KPathSeek, KPathBase, expects a type of a reciprocal lattice as `pymatgen.core.lattice.Lattice`. This tiny PR fixes to cast a reciprocal lattice returned by `seekpath` into pymatgen's lattice class.

Fix type of reciprocal lattice in KPathSeek

---

pymatgen/analysis/ewald.py
pymatgen/analysis/tests/test_ewald.py

Fix `as_dict` in EwaldSummation to save `_acc_factor` and not `_accf`, to recreate the exact object as before. Previous tests did not catch this since the actual Ewald summation values remained within numerical tolerance (my bad for not catching this before).
highly recommended that you use the pre-commit hook provided in the …

fix saving _acc_factor instead of _accf

---

pymatgen/io/lammps/utils.py

Enhance `PackmolRunner` to work more robustly when called within for loops.
* Use context managers for opening the input file and running the subprocess to ensure that both are properly closed
* Replace `ScratchDir` with `TemporaryDirectory` to eliminate non-obvious file deletion
Re: bullet point 2 - when the `ScratchDir` class is called with `copy_to_current_on_exit=True`, it not only copies output files from the temporary to the current directory, but also DELETES any file in the current working directory that is not present in the temporary directory. This behavior is undocumented and made it impossible to use `PackmolRunner` to loop through a series of structures and place output files in a single directory (everything except the latest output would be deleted on each iteration).

PackmolRunner enhancements for safe looping

---

pymatgen/entries/computed_entries.py
pymatgen/entries/tests/test_computed_entries.py

By analogy with `energy` and `energy_per_atom`, add `per_atom` attributes for other energies of a `ComputedEntry`:
* `correction_per_atom`
* `correction_uncertainty_per_atom`
* `uncorrected_energy_per_atom`

add per_atom attributes to ComputedEntry

---

pymatgen/analysis/pourbaix_diagram.py
pymatgen/entries/compatibility.py
pymatgen/entries/tests/test_compatibility.py
pymatgen/ext/matproj.py
pymatgen/ext/tests/test_matproj.py

The recent introduction of the `solid_compat` kwarg to `get_pourbaix_entries` began triggering a `DeprecationWarning` when the module was imported, because the kwarg defaulted to an instance of `MaterialsProjectCompatibility()`. This commit changes the interface slightly to avoid instantiating the class on import and therefore avoid triggering the `DeprecationWarning` until `get_pourbaix_entries` is actually called.
* `MaterialsProjectAqueousCompatibility` now accepts `None`, `Compatibility()`, or `Compatibility` as the `solid_compat`
* `MaterialsProjectAqueousCompatibility` now defaults to `solid_compat=MaterialsProjectCompatibility` (was previously `None`)
* allow `get_pourbaix_entries` to accept str as the `chemsys` argument (e.g. "Fe-Cr") for consistency with `get_entries_in_chemsys` …

address DeprecationWarning triggered by get_pourbaix_entries

---

pymatgen/io/vasp/outputs.py
test_files/POTCAR.spec

To facilitate testing in the absence of proprietary POTCAR files, `InputSet` have the option to write a `POTCAR.spec` file instead of an actual POTCAR. However, when a `POTCAR.spec` file is present, `Vasprun.get_potcars()` tries to read it, resulting in an error.
This PR causes Vasprun.get_potcars() to ignore POTCAR.spec when present. See also a related atomate PR which requires this change: https://github.com/hackingmaterials/atomate/pull/454

Ignore POTCAR.spec in Vasprun

---

pymatgen/analysis/defects/thermodynamics.py

There's a small bug in the `DefectPhaseDiagram.suggest_larger_supercells()` method (line 390 in `pymatgen/analysis/defects/thermodynamics.py`, where the current code is:
```python
for tl, chgset in self.transition_level_map.items():
```
which gives the wrong variables of Defect-Name, {Transition-Level: Charge-set}. It should be:
```python
for tl, chgset in self.transition_level_map[def_type].items():
```
(it's within the `for def_type in self.defect_types:` loop), which gives the correct variables of which gives the wrong variables of Transition-Level, Charge-set.
See below for a quick demonstration of the bug, and the result when fixed:

Fix suggest_larger_supercells bug

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

A common pattern in many of the MP VASP input sets is to store the input kwargs in the constructor and then access them using `self.kwargs.get` in the `incar` and `kpoint` functions. Unfortunately, this can lead to discrepancies between the actual attributes of the input set and the data stored in the `kwargs` variable.
For example, the following causes an error:
```python
static_set = MPStaticSet(structure, user_incar_settings=None)
static_set.incar()
```
This is surprising since the default value of `user_incar_settings` in the `VaspInputSet` constructor is `None`, and the following code works fine.
```python
static_set = MPStaticSet(structure)
static_set.incar()
```
The issue arises because the `incar` and `kpoints` functions call `self.kwargs.get("user_incar_settings", {}).keys()` …

Remove self.kwargs.get pattern in MP input sets

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

`Outcar.as_dict` method fails if the OUTCAR doesn't contain the average electrostatic potential at atomic cores. This can occur if `ICORELEVEL = 1` is set. I've fixed this behaviour and added a test. 

Fix outcar serialization

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

This PR fixes a recently discovered bug in which the `Vasprun.run_type` of a calculation in which `METAGGA=None` would not be set correctly.

fix bug in GGA run_type when METAGGA=None

---

pymatgen/analysis/tests/test_graphs.py

test file is MoS2_single.pdf not MOS2_single.pdf
"MOS2_single.pdf" triggers an error: "No such file or directory: 'MOS2_single.pdf'" from `os.remove(test_file)`

fix MoS test filename in test_graph.py

---

pymatgen/electronic_structure/bandstructure.py

fix: typo in get_cbm docstring

---

pymatgen/symmetry/bandstructure.py

This PR contains a small bug fix for the `HighSymmKpath` class. Currently, the k-path from this class produced by the Hinuma et al. convention is not properly transformed into the basis of the reciprocal lattice of the input structure in all cases. This has been fixed, and a warning has been added to tell the user to use `KPathSeek` if they would like the path in the original author-intended basis. 
to type …

HighSymmKpath Hinuma setting bug fix

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

* created method to estimate NBANDS for VASP input set
* simplified `nelect` property
* added tests

method to estimate NBANDS + tests

---

pymatgen/entries/__init__.py
pymatgen/entries/computed_entries.py
pymatgen/entries/tests/test_computed_entries.py

For **entry-equality branch**, to be reviewed by @mkhorton:
Solves the normalization issue by adding an optional composition parameter so that composition is not taken directly from the structure object. Also cleaned up a ton of other things! 
This doesn't yet do the major entry refactor.

Remove custom entry normalize methods, solve via optional composition

---

pymatgen/analysis/diffraction/tests/test_xrd.py
pymatgen/analysis/diffraction/xrd.py
pymatgen/core/composition.py

* Fix 1: attempting to create a XRDCalculator instance with an integer wavelength (e.g. 1, when wavelength is 1 Angstrom) throws a KeyError.  Made changes to the __init__ method to accept integers for wavelength.  Also raise TypeError if wavelength is neither of float, int or str.  Added test to test if TypeError is raised.
- [x ] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). The easiest way to handle this
your code to PEP8 …

Fix KeyError when initializing XRDCalculator with integer wavelength

---

pymatgen/io/vasp/outputs.py
pymatgen/io/vasp/tests/test_outputs.py

Added the ability to parse the projected magnetisation from VASP calculations that include spin-orbit coupling or non-collinear magnetism.
For calculations that include orbital projections (`LORBIT = 11`), the projections are written to the vasprun.xml file in the same format as in the PROCAR file (https://www.vasp.at/wiki/index.php/PROCAR). The format of the projections depends on the other calculation parameters:
- For spin-paired calculations (`ISPIN = 1`): There is only one spin channel present.
- For spin-polarised calculations (`ISPIN = 2`): There are two spin channels present.
- For non-collinear or SOC calculations: There are 4 spin channels present.
In the last case, the first spin channel is the usual projection of the wavefunctions onto the atomic orbitals. The last 3 spin …

Parse projected magnetisation from non-collinear calculations

---

pymatgen/io/gaussian.py
pymatgen/io/tests/test_gaussian.py

Hi pymatgen community!
I would like to use the Gaussian input generator for post-processing runs, such as this one 
~~~
%chk=g.chk
%oldchk=../g.chk
#P chkbasis geom=allcheck guess=(only,read) pop=naturalorbital
test
~~~
This would read the geometry, functional, basis set, charge and multiplicity from `../g.chk` and perform natural orbital analysis.
This PR enables this by making 
* functional and basis set are not outputted when set to `None`
* if geometry is `None`, then charge or multiplicity set to `None` will not be displayed
I also added a test for this and I had to modify an existing test.

Gaussian: allow None for functional, bset, charge and multiplicity

---

pymatgen/core/structure.py

`Structure.get_neighbor_list` claims to be orders of magnitude faster than `get_all_neighbors` which probably refers to `get_all_neighbors_old`. It's actually only about 2-3x faster than `get_all_neighbors`.

correct get_neighbor_list speed claim

---

docs_rst/compatibility.rst

Drafting an update of the Compatibility guide as requested by @mkhorton in
https://github.com/materialsproject/pymatgen/issues/2083#issuecomment-791597868
Note …

docs: update compatibility guidance

---

pymatgen/analysis/graphs.py
pymatgen/analysis/local_env.py
pymatgen/analysis/tests/test_graphs.py

A fix to the graphs class that enforces a new convention to ensure duplicate edges are not added. This will only happen in rare instances normally (namely, small unit cells with NearNeighbor strategies where the cut-off is >> the length of a chemical bond).
Tagging @jmmshn @kim-jiyoon
While this convention fixes the present issue, I'm not convinced it's sufficient in all cases and will give it some further thought. It includes the mp-683887 6 Å cut-off example as a test-case but not the bow-tie example.

Add convention to remove duplicate edges when i==j in StructureGraph + test

---

pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py

`SlabGenerator._get_c_ranges()` takes in a `bonds` dictionary and returns a set of tuples of fractional z-coordinates of neighboring (nearest) atoms if they have distinct z-coordinates. This set is then used in the `SlabGenerator.get_slabs()` method in order to calculate the total number of broken bonds. The issue with the current version is that the tuples are stored in a `set()` which can only have unique elements so all but one of the bonds between say z_coord1 and z_coord2 are ignored.
I tested this by simply generating Si(111) slabs, calculating the number of bonds broken reported by pymatgen, and comparing them by what I expect from looking at the slabs in VESTA. 
Here's the code I used to generate the slabs;
```
from pymatgen.core.surface import SlabGenerator
from …
```

Fix for correct bonds_broken in slab generation

---

pymatgen/electronic_structure/bandstructure.py
pymatgen/electronic_structure/tests/test_bandstructure.py

Use `np.ndarray.tolist()` method instead of python `list()` to convert k-point coordinates in `pymatgen.electronic_structure.bandstructure.Kpoint.as_dict()`.
This fixes issue #2112, where numpy numerical types (e.g. numpy.float64) exist in the result of `Kpoint.as_dict()`.

Use numpy tolist method in electronic_structure.bandstructure.Kpoint.as_dict

---

pymatgen/electronic_structure/dos.py
pymatgen/electronic_structure/tests/test_dos.py

Use `np.ndarray.tolist()` method instead of python `list()` to convert density of state (`Dos`, `FermiDos`, `CompleteDos`) energies and densities in their `as_dict()` methods.
This fixes an issue where numpy numerical types (e.g. numpy.float64) exist in the results of {`Dos`, `FermiDos`, `CompleteDos`}`.as_dict()`.
This allows these objects to be saved and stored more easily by [mincePy Sci](https://github.com/muhrin/mincepy_sci).

Use numpy tolist() in DOS-family object as_dict() methods

---

pymatgen/entries/compatibility.py

resolves #2118 by leaving config path as None if custom path not given. Raises ValueError is a custom path given but the file does not exist.

#2118 Stop MP2020Corrections saving hardcoded path

---

pymatgen/core/surface.py
pymatgen/core/tests/test_surface.py

This pull request contains an improvement for analyzing surface symmetry of slabs. A slab now has symmetrically equivalent surfaces if (hkl) is a mirror plane, if [hkl] is a screw axis or if the slab has inversion symmetry.
* Modifications to is_symmetric() Slab class method. If slab contains inversion symmetry, the (hkl) plane is a mirror plane, or there is a screw axis about [hkl], the surfaces of the slab are symmetrically equivalent.
* Test for generating slabs that don't need inversion
* Remove really inefficient Slab class method for checking equivalent surfaces have_equivalent_surfaces()
* Modify SlabGenerator class method nonstoichiometric_symmetrized_slab() to use is_symmetric() when generating slabs

Symmetrically equivalent surfaces in slabs

---

pymatgen/entries/compatibility.py
pymatgen/entries/tests/test_compatibility.py

Ensures that energy corrections applied to each anion have unique names (e.g., N vs. Cl vs. Br).
If this is not the case, then in a compound with multiple corrected anions like `C2NCl`,  `Compatibility` will apply a correction to the first anion, then think the second is a duplicate, warning
```
warnings.warn(
2021-05-01T11:22:13.8878461Z /users/home/ghrunner/actions-runner/_work/_tool/Python/3.8.7/x64/lib/python3.8/site-packages/pymatgen/entries/compatibility.py:579: UserWarning: Entry mp-567221 already has an energy adjustment called MP2020 anion correction, but its value differs from the value of -0.718 calculated here. This Entry will be discarded.
```
Also makes some tweaks to oxidation state detection to work better with the Builders.

Ensure all MP2020 corrections have unique names; tweak oxi state detection

---

pymatgen/symmetry/structure.py

Wyckoff letters are meaningless without the context of the spacegroup, current SymmetrizedStructure __str__ doesn't include the spacegroup so I've added it in - this is purely a cosmetic change.

Add spacegroup details to SymmetrizedStructure string 

---

pymatgen/analysis/diffraction/core.py

Introducing a new optional style for the hkl labels in diffraction patterns (see example figure below).
The default style was not changed.  However, I would recommend making this new more-compact style the default because it prevents overlap of labels as in https://matgenb.materialsvirtuallab.org/2013/01/01/Calculating-XRD-patterns.html (a similar image can be seen here at the bottom)
```python
from pymatgen.core import Lattice, Structure
from pymatgen.analysis.diffraction.xrd import XRDCalculator
import matplotlib.pyplot as plt
a = 4.209
latt = Lattice.cubic(a)
struct = Structure(latt,  ["Cs", "Cl"], [[0, 0, 0], [0.5, 0.5, 0.5]])
c = XRDCalculator()
```
1. The new more-compact style:
```python
c.show_plot(struct, annotate_peaks='compact')
```
2. The current default style (previously: …

Add new compact style for hkl annotations to peaks in diffraction patterns

---

pymatgen/ext/matproj.py

Hey guys,
Python 3.6+ seems to abolish `Exception.message`.  
This PR addresses this problem.  
It does not seem to be easy to write a unittest to reproduce this without imposing a large load on MP.  
Here is a working example.  
- Current implementation
```python
import re
from pymatgen.ext.matproj import MPRestError
try:
raise MPRestError("error status code 000")
except MPRestError as e:
match = re.search(r"error status code (\d+)", e.message)
if match:
print(e)
```
```
MPRestError                               Traceback (most recent call last)
<ipython-input-3-83f89fe43bab> in <module>
2 try:
----> 3     raise MPRestError("error status code 000")
4 except MPRestError as e:
MPRestError: 
During handling of the above exception, another exception occurred:
AttributeError …
```

Python 3.6+ behavior of Exception.message

---

pymatgen/analysis/pourbaix_diagram.py
pymatgen/analysis/tests/test_pourbaix_diagram.py

* Updates PourbaixEntry.from_dict to invoke entries other than IonEntries using MontyDecoder, rather than hard-coding PDEntry.
* I initially had a bigger refactor which changed the ways Ions/IonEntries are invoked, but I'm a little worried about backwards compatibility of a core refactor, so I'm issuing this one for now.
* Addresses #2146
[pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by …

add test and fix for computed entries

---

pymatgen/io/qchem/outputs.py
pymatgen/io/qchem/tests/test_outputs.py
test_files/molecules/new_qchem_files/basis_not_supported.qout

Adds detection of basis set not supported error to `QCOutput`. This error will cause the calculation to fail before it even starts, so it is treated similarly to the existing `input_file_error`.

add basis_not_supported error to QCOutput

---

pymatgen/electronic_structure/bandstructure.py
pymatgen/electronic_structure/tests/test_bandstructure.py
pymatgen/symmetry/bandstructure.py

* Path type names in `HighSymmKpath` changed from short form ('sc', 'hin', and 'lm') to long form ('setyawan_curtarolo', 'hinuma', 'latimer_munro'). 
* Proper `from_dict` method added to `Kpoint` class in `from pymatgen.electronic_structure.bandstructure`.

Bandstructure path name changes and Kpoint from_dict

---

pymatgen/entries/compatibility.py

Add pymatgen `PBar` to applying compatibility settings to help impatient users like myself. I have by default suppressed the progress bar and added a boolean verbose flag to turn it on.
Changes made are superficial therefore no new tests added.

Add progress bar to applying compatibility settings

---

pymatgen/core/__init__.py

When both a .pmgrc.yaml and environment variables are specified, any pmg environment variable will not be read into `pymatgen.core.__init__`'s `SETTINGS`.
E.g., I have a `PMG_MAPI_KEY` as an environment variable and my .pmgrc.yaml does not contain that key - it looks like
```
#.pmgrc.yaml
MAPI_DB_VERSION:
LAST_ACCESSED: '2021_05_13'
LOG: {'2021_05_13': 6}
```
`PMG_MAPI_KEY` will not be found in `SETTINGS`. 
This PR assumes this is not the desired behavior. `SETTINGS` here are now loaded as the union of env vars and pmgrc.yaml values, with the priority being pmgrc.yaml in case of a setting being defined in both sources.
If the desired behavior is in fact to void env variables for `SETTINGS` if .pmgrc.yaml exists, please close this PR. 
Before a pull request can be merged, the following …

reorder SETTINGS load priority

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Change rmin formula to match Eq. 25 from the paper.

Fix KSPACING formula in MPScanRelaxSet

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Set EDIFF = 1e-5 when `lepsilon = True` in `MPStaticSet`. Note that this is [already used in atomate](https://github.com/hackingmaterials/atomate/blob/128a754000533029ce2b3d1faf3eb06aabe6f88b/atomate/vasp/firetasks/write_inputs.py#L378), I'm just moving the configuration to the input set itself.

Use tighter EDIFF for DFPT calculations

---

pymatgen/io/qchem/outputs.py
pymatgen/io/qchem/tests/test_outputs.py
test_files/molecules/new_qchem_files/lebdevpts.qout

Detect `need to increase the array of NLebdevPts` error in `QCOutput` that can occur when computing RESP charges. Detecting this error is necessary to enable a handler in custodian. See [custodian #170](https://github.com/materialsproject/custodian/pull/170)

QChem: detect NLebdevPts error in QCOutput

---

pymatgen/analysis/pourbaix_diagram.py
pymatgen/analysis/tests/test_pourbaix_diagram.py
pymatgen/entries/__init__.py
pymatgen/entries/compatibility.py
pymatgen/entries/computed_entries.py
pymatgen/ext/matproj.py

Default `PourbaixDiagram` to use `filter_solids=True` for consistency with the MP website and discussion in #2173. 
In addition:
* Fix a bug in `MaterialsProjectAqueousCompatibility` introduced by e8028b0cfe783f8628c9090da07ff6e435244f6c
* add type hinting to `PourbaixDiagram` and make a few type hinting fixes to `Entry` classes (necessary to make mypy happy on `PourbaixDiagram`).
* Deprecate the `include_unprocessed_entries` kwarg to `PourbaixDiagram.as_dict`. This was necessary in order to make serialization work properly after switching to `filter_solids=True` by default. To me, it appears this kwarg was a sort of workaround to allow a user to effectively decide whether to filter solids at the serialization / deserialization stage. In my mind, it makes more sense for the user to make …

Pourbaix: default to filter_solids=True

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Add a guard statement and a test to ensure that the KSPACING value calculated by `MPScanRelaxSet` never exceeds the range 0.22 - 0.44. 
This is a follow up to #2163. After that PR was merged I noticed from our atomate tests of the SCAN workflow that if a material's bandgap was sufficiently large >9 eV or so, it could actually reverse the sign of KSPACING, leading to large negative values that broke the logic. This PR fixes that bug and will be needed to keep atomate tests passing.

enforce KSPACING cap in MPScanRelaxSet

---

pymatgen/analysis/phase_diagram.py

matplotlib is deprecating the old way to setup 3d plots used by the "matplotlib" backend in PDPlotter. This was giving me deprecation warnings in the testing scripts so I've replaced the calls with the more up to date api usage. I have tested the backend and it still works as before for 4d gibbs simplicies.

fix: update matplotlib 3daxes to use modern api.

---

pymatgen/analysis/defects/corrections.py
pymatgen/analysis/defects/defect_compatibility.py
pymatgen/analysis/defects/tests/test_corrections.py
pymatgen/analysis/defects/tests/test_defect_compatibility.py

This is a bugfix for two significant errors in the BandFillingCorrection class for defects.
I have attached a PDF, notebook and corresponding data to demonstrate the errors, and how these are now fixed with this PR. I have changed the value in the BandFillingCorrection test to match the correct value as well, and have attached a PDF & notebook for this, calculating this correction manually to verify that it is the correct result.
* **Fix 1**: Fix the potential alignment shifting of the band extrema.
* **Fix 2**: Fix the eigenstate occupancy spinfactor calculation, so that spin-orbit coupling (SOC) calculations can be parsed correctly (previously giving a spurious doubling of the occupancies in these cases).
I have added a new test for the BandFillingCorrection with a SOC defect …

Bugfix for defect BandFillingCorrection

---

pymatgen/analysis/interfaces/substrate_analyzer.py
pymatgen/analysis/interfaces/tests/test_substrate_analyzer.py
pymatgen/analysis/interfaces/tests/test_zsl.py
pymatgen/analysis/interfaces/zsl.py

This should fix #2198 , which was a bug introduced in the interfaces reorganization where the substrate analyzer was constructing matches to return, but not actually returning them... DOH!
I've added a test to check for this in the future. 
Edit: Should be #2198. Thanks @bernstei

Fix substrate analyzer not actually returning objects

---

pymatgen/analysis/phase_diagram.py

* Bug fix for entry_ID phase diagram plotting bug described in this Issue: #2219 

Fix entry_id not displaying on hovertext for plots of CompoundPhaseDiagram and GrandPotentialPhaseDiagram 

---

pymatgen/alchemy/tests/test_materials.py
pymatgen/analysis/chemenv/connectivity/tests/test_environment_nodes.py
pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometry_finder.py
pymatgen/analysis/chemenv/coordination_environments/tests/test_read_write.py
pymatgen/analysis/chemenv/coordination_environments/tests/test_structure_environments.py
pymatgen/analysis/chemenv/coordination_environments/tests/test_voronoi.py
pymatgen/analysis/chemenv/coordination_environments/tests/test_weights.py
pymatgen/analysis/chemenv/utils/tests/test_chemenv_config.py
pymatgen/analysis/structure_prediction/tests/test_substitution_probability.py
pymatgen/analysis/structure_prediction/tests/test_substitutor.py
pymatgen/analysis/tests/test_graphs.py
pymatgen/analysis/tests/test_path_finder.py
pymatgen/analysis/tests/test_surface_analysis.py
pymatgen/command_line/tests/test_critic2_caller.py
pymatgen/core/tests/test_surface.py
pymatgen/io/abinit/tests/test_inputs.py
pymatgen/io/abinit/tests/test_netcdf.py
pymatgen/io/abinit/tests/test_pseudos.py
pymatgen/transformations/tests/test_advanced_transformations.py

* use PymatgenTest.TEST_FILES_DIR with all tests
Required to enable tests to run separately from the source, for instance for CI testing of packaging for Linux distributions,
see https://github.com/materialsproject/pymatgen/issues/2025

Configured test files dir

---

pymatgen/core/composition.py

should fix a bug in the automatic documentation markup for `Composition.contains_element_type`

indent list for `Composition.contains_element_type` documentation

---

pymatgen/analysis/local_env.py

The `get_nn_info` routines of many nearest-neighbor flavors in `pymatgen.analysis.local_env` recomputed the original periodic image of sites although this information was already stored on the `PeriodicNeighbor` objects (at least it seems so to me - correct me if I'm wrong).
This resulted in O(N^2) instead of O(N) computational complexity (for structures beyond a certain size, almost all time was spent there).
This PR
* Changes the `get_nn_info` methods to reuse the information from the `PeriodicNeighbor` objects (1st commit)
* Introduces a faster implementation of `get_all_nn_info` for the `CutoffDictNN` (2nd commit)
The 2nd commit involves some code duplication and is perhaps not absolutely necessary.
It results in further substantial speedup, however.
Example to demonstrate the speedup …

Speed up nearest-neighbor routines & structure graph generation

---

pymatgen/analysis/chempot_diagram.py
pymatgen/analysis/interface_reactions.py
pymatgen/analysis/phase_diagram.py
pymatgen/analysis/tests/test_interface_reactions.py
pymatgen/util/plotly_interface_rxn_layouts.json

* Add: support for Plotly: calling `plot()` now provides a `backend` option for choosing matplotlib or Plotly.
* Add:`GrandPotentialInterfacialReactivity` class to separate code based on the use of grand potential phase diagrams (this greatly decreases the complexity of the `__init__` args) and is a more inherited approach in general
* Add: `get_dataframe()` method for plotting possible reactions in a Pandas dataframe. Users would typically have to write/copy boilerplate code to do this each time
* Fix: Better matplotlib plotting, included annotations 
* Fix: Cleaner, more readable code …

Refactor `interface_reactions` module, add support for Plotly

---

pymatgen/ext/optimade.py
pymatgen/ext/tests/test_optimade.py

OPTIMADE uses the `response_fields` URL parameter to select the response fields, this PR removes an extraneous URL parameter that is added when using a raw OPTIMADE filter through `OptimadeRester`.
Addresses and closes #2243 (cc @mkhorton)
~Haven't added any tests as I don't think this extension is being tested at the moment~
your code to PEP8 conventions and removes most issues. Then run …

Remove bad param when setting OPTIMADE response fields

---

pymatgen/electronic_structure/dos.py
pymatgen/io/vasp/outputs.py

* The docs for `pymatge.io.vasp.outputs.Outcar` are missing many of the attributes. For instance, it wasn't clear to me until I read the code that the `Outcar()` object has a `total_mag` keyword. I've update the docstring to include the missing attributes.
* The docs for `pymatgen.electronic_structure.dos.get_element_spd_dos` have an incorrect description of the `Returns` dictionary. This has been updated. Note: There are still some aesthetic issues with the docs, as mentioned in #2292.

Docstring updates: Fix missing Outcar attributes and update elemental_dos_dos string

---

pymatgen/analysis/local_env.py

follow-up on @mkhorton 's comments

update docstring of CutOffDictNN

---

pymatgen/analysis/tests/test_pourbaix_diagram.py
pymatgen/core/composition.py
pymatgen/core/ion.py
pymatgen/core/tests/test_ion.py
pymatgen/util/string.py
pymatgen/util/tests/test_string.py

This PR contains some miscellaneous bugfixes and enhancements for the `Ion` class.
* Fixes #2281 
* Partially address #2204 by overloading `get_reduced_formula_and_factor` to provide special formula handling for ions. The `reduced_formula` for hydroxide, hydrogen peroxide, acetate, acetic acid, and small alcohols are now more consistent with the way these species are usually written.
* Implement a `utils.string.charge_string` method to make the representation of ion charges more consistent across `formula`, `reduced_formula`, etc.
* Make representation of `Ion` formulae more consistent. By default, charges are now always appended in brackets, with the sign preceding the magnitude, e.g. `Na[+1]` or `SO4[-2]`. This provides unambiguous differentiation between stoichiometric coefficients and …

Ion bugfixes and enhancements

---

pymatgen/core/periodic_table.py
pymatgen/core/structure.py

`Structure().replace_species` doc string should make it clear that original structure is modified in place.

Replace-species

---

README.rst
docs/_modules/pymatgen/analysis/aflow_prototypes.html
docs/_modules/pymatgen/analysis/prototypes.html
docs/_modules/pymatgen/analysis/quasiharmonic.html
docs/_modules/pymatgen/command_line/critic2_caller.html
docs/_modules/pymatgen/ext/crystalsai.html
docs/_modules/pymatgen/ext/matproj.html
docs/index.html
docs/introduction.html
docs/pymatgen.analysis.prototypes.html
docs/pymatgen.analysis.quasiharmonic.html
docs/pymatgen.analysis.solar.slme.html
docs/pymatgen.command_line.critic2_caller.html
docs/pymatgen.ext.crystalsai.html
docs/pymatgen.ext.matproj.html
docs/references.html
docs_rst/introduction.rst
docs_rst/references.rst
pymatgen/analysis/prototypes.py
pymatgen/analysis/quasiharmonic.py
pymatgen/analysis/solar/slme.py
pymatgen/command_line/critic2_caller.py
pymatgen/ext/crystalsai.py
pymatgen/ext/matproj.py
test_files/abinit/mgb2_nscf.abo
test_files/abinit/mgb2_nscf.log
test_files/abinit/mgb2_scf.abo
test_files/abinit/mgb2_scf.log
test_files/abinit/sic_relax.abo
test_files/cp2k/cp2k.out

* URLs are changed to https://doi.org/ in accordance with https://www.doi.org/doi_handbook/2_Numbering.html#htmlencoding.
Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) …

Update DOI URLs

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

Per the VASP manual (https://www.vasp.at/wiki/index.php/LHFCALC), hybrid calculations should only be run with ALGO = All, Damped, or Normal (never Fast or VeryFast despite no clear error written in the output). This PR implements a `BadInputSetWarning` if LHFCALC = True and Algo is not one of the three supported options.

Add warning if improper ALGO is used for hybrid calculations

---

pymatgen/core/structure.py

When you create supercell I think the expected behavior should be that the sites in the SC sit in the unit-cell.
Currently, the behavior is:
```
Full Formula (Si2)
Reduced Formula: Si
abc   :   3.866974   3.866975   3.866975
angles:  60.000006  60.000002  60.000010
Sites (2)
---  ----  -----  -----  -----
0  Si    0.875  0.875  0.875
1  Si    0.125  0.125  0.125
Full Formula (Si8)
Reduced Formula: Si
abc   :   5.468729   5.468729   5.468728
angles:  90.000014  90.000001  90.000001
Sites (8)
---  ----  -----  -----  -----
0  Si    0.875  0.875  0.875
1  Si    1.375  1.375  0.875
2  Si    1.375  0.875  1.375
3  Si    0.875  1.375  1.375
4  Si    0.125  0.125  0.125
5  Si    0.625  0.625  0.125
6  Si    0.625  0.125  0.625
7  Si    0.125  0.625  0.625
```
The additional flag should fix this …

wrap SC to unit cell

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

This PR implements a simple `BadInputSetWarning` if `LASPH = False` (or is not set) yet the user is running a meta-GGA/hybrid/DFT+U/vdW-DF calculation.

Add warning if LASPH != True for meta-GGA/hybrid/vdW/+U

---

pymatgen/ext/optimade.py
pymatgen/ext/tests/test_optimade.py

Closes #2314 by adding the `additional_response_fields` argument when generating SNLs from OPTIMADE requests.
Note that the CI system will run all the above …

Add ability to request additional OPTIMADE fields

---

pymatgen/core/tests/test_trajectory.py
pymatgen/core/trajectory.py

In the current implementation of the write_Xdatcar in Trajectory the lattice is either written only once if `constan_lattice==True` or never if `constan_lattice==False`. Fix to write it multiple times if the lattice is not constant.
Added a specific check in the tests.

fix write Trajectory XDATACAR with variable lattice

---

pymatgen/io/vasp/MPSCANRelaxSet.yaml
pymatgen/io/vasp/tests/test_sets.py

@rkingsbury and @mkhorton: Some elements that are currently in the VASP PAW .54 PBE library have defined pseudopotentials but aren't in the `MPScanRelaxSet.yaml` file because they never existed in the original PAW PBE set used in the GGA calculations on MP. This change won't influence anything in your R2SCAN workflow because: a) The jobs would have never run with these elements since no pseudopotentials were defined; b) none of these elements exist on MP right now because of the aforementioned statement.
Most of the elements I added have only one PAW PBE potential to use. In the case of multiple, I used the VASP-recommended set.
I know this breaks the hash for `MPScanRelaxSet.yaml`. It would need your blessing.

Add missing elements to MPScanRelaxSet PBE .54 potentials

---

pymatgen/io/vasp/sets.py
pymatgen/io/vasp/tests/test_sets.py

I have made a few additional clarifications to `pymatgen.io.vasp.sets`, primarily with regards to the handling of magnetic moments as a follow-up to #2301:
1. Clearer docstrings. This is rather self-explanatory.
2. Only print the warning about low magnetic moments on Co if the value is <= 1. If someone were to modify the default config to have high-spin Co, there is no longer a need for this warning. I had done this, and I found it somewhat bothersome.
3. If the user provides an integer for the magnetic moment, e.g. `site["magmom"] = 1`, then convert this to a float when `get_valid_magmom_struct()` is run. Previously, Pymatgen would crash when creating an `Incar()` object if the structure had an integer magnetic moment due to the lines below. …

Clearer handling of magmom flag

---

pymatgen/command_line/bader_caller.py
pymatgen/io/vasp/inputs.py
pymatgen/io/vasp/tests/test_inputs.py

This PR creates a new automatic k-point generation scheme, `automatic_density_by_lengths`, which allows the user to specify a density of k-points in each dimension (rather than just for the entire volume). This is particularly important for slab calculations, because you almost always want 1 k-point in the vacuum dimension but don't want the vacuum space volume to influence your k-point generation otherwise.
For instance, doing `automatic_density_by_lengths(struct, [50, 50, 1])` would specify a k-point density of 50/a x 50/b x 1/c, with each rounded up to the next integer.
This is a more general implementation of the k-point scheme used in `MVLSlabSet` (reproduced below) and can be found in several papers from the Persson group, such as [this …

Add new automatic kpoint scheme that normalizes by lattice lengths

---

pymatgen/analysis/diffraction/xrd.py

The double slashes were being misinterpreted in the current version of the documentation.
* Replaced double backslases with ` \` as the `\\` was escaping and leading to no character bring printed in the rst math docstring.
Run …

Removed double slashes for RST inline math
