pymatgen/io/vasp/outputs.py
Implements materialsproject/pymatgen#219, after adding Shyue's corrections and rebasing.
=> Add class for parsing WAVEDERF file

pymatgen/analysis/defects/charge_defects_analyzer.py, pymatgen/analysis/defects/dilute_solution_model.py, pymatgen/command_line/sxdefectalign_caller.py
New branch to contribute code related to charged defects.
Initial code commits include place holder for Freysoldt correction, defect analyzer.
=> Charged defects

pymatgen/command_line/sxdefectalign_caller.py
This is first working version of sxdefectalign calling script. I had to comment out the @requires command to get it to work for me...? Also note that this script can just be run once if you don't care about potential alignment screening...(just call .get_singlecorrection)
=> create draft of sxdefectalign calling script

pymatgen/io/nwchem.py, pymatgen/io/tests/test_nwchem.py
* Support parsing gradients (forces) from nwchem output files.
* Unittests are added and tested.
=> Support parsing gradients (forces) from nwchem output files.

pymatgen/io/gaussian.py, pymatgen/io/tests/test_gaussian.py, test_files/molecules/CH2O_CO2.log
The class ``GaussianOutput`` now supports parsing:
* Frequencies
* Normal modes
* Cartesian forces
Python 3 compatible.
Unit tests are added.
=> Enhance: GaussianOutput

pymatgen/io/gaussian.py, pymatgen/io/tests/test_gaussian.py
* User-specified basis sets can be used to do Gaussian calculations.
* Tests are added.
* Python3 compatible.
=> Add keyword ``gen_basis`` to `GaussianInput``

pymatgen/entries/MPCompatibility.yaml, pymatgen/entries/compatibility.py, pymatgen/entries/tests/test_computed_entries.py
add S correction and unit test.
=> S Correction

pymatgen/analysis/substrate_analyzer.py
Added in documentation for all substrate analyzer methods including full description of argument list.
=> Additional Documentation on Substrate Analyzer

examples/ChemEnv : How to automatically identify coordination environments in a structure.ipynb, pymatgen/analysis/chemenv/utils/tests/test_coordination_geometry_utils.py
Fixed test of orthogonal vectors in Plane (was working on my workstation, machine-precision error). I hope it now works on the Ci
=> Small fix of the test_orthonormal_vectors

pymatgen/analysis/pourbaix/maker.py
add a safe guard to monitor whether ion phase appear when requesting a Pourbaix Diagram
=> add a safe guard to monitor whether ion phase appear when requesting a Pourbaix Diagram

pymatgen/io/lammps/data.py, pymatgen/io/lammps/output.py
tested with python.3.4.3 and 2.7 on ubuntu 14.04
=> py3k fixes

pymatgen/io/vasp/inputs.py
made a mistake in the conditional statement
=> bug fix in incar magmom for soc

pymatgen/io/vasp/sets.py
join the directory name to the filename.
=> minor bug fix in get_vasprun_outcar

pymatgen/io/vasp/sets.py
* make reciprocal_density the default option to set kpoints
* add more checks for structure standardizations.
* add small_gap multiply
update prev incar with structure dependent lda+u params. magmom seems ok.
=> update Derived input sets.

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
* add ldau params to the structure site_properties in `vasp.sets.get_structure_from_prev_run`
* enable writing ldau params from site_properties in `vasp.sets.DictVaspInputSet.get_incar`
* unittests
=> enable writing ldau params from site_properties

pymatgen/analysis/structure_analyzer.py
There were inconsistencies regarding unsuccessful set-up of the spherical coordinate system.
=> Removed a bug in OrderParameters class of structure_analyzer.py

pymatgen/symmetry/analyzer.py
* addresses issue #400 
* split the the conditional statements
=> fix rotational symmetry operations check in pointgroupanalyzer 

pymatgen/io/vasp/sets.py
change attribute name to support automatic serialization
=> change attribute name to support automatic serialization

pymatgen/entries/compatibility.py
Fix anion correction when S and O are both anions. No corrections on polysulfides for now, which means they are destabilized. 
None
None
=> fix anion correction when S and O are both anions

pymatgen/__init__.py, pymatgen/optimization/__init__.py, pymatgen/optimization/linear_assignment_python.py, pymatgen/util/__init__.py, pymatgen/util/coord_utils.py, pymatgen/util/coord_utils_python.py, setup.py
Removed os.path.abspath because this was preventing installation from the extracted tar.gz source when running setup.py install under Windows OS (not sure if it manifests on Linux). The setup() function should only need relative paths.
Please test this under Mac OS X / Linux to confirm the changes do not impact installation on these systems.
Thanks and kind regards,
Liam Deacon
=> Fixed absolute path installation issue

pymatgen/io/feff/inputs.py
* add cluster attribute to Atoms and refactor input file generation
=> minor io.feff update

pymatgen/io/feff/inputs.py, pymatgen/io/feff/tests/test_inputs.py
* bug fix and minor refactoring in Atoms
* add more unittests
=> io.feff updates

pymatgen/io/vasp/outputs.py
<Incorporated options to select structures, concatenate new structures with existing one and write the Xdatcar class into a file>
* Added  functionality to provide the starting and ending ionic step, to enable removal of structures in NVT AIMD before equilibration.
* Created a function concatenate new structures from a file into existing Xdatcar. Helps in concatenating multiple Xdatcars  obtained through restart into a single Xdatcar class.
* Created a function to write the structures in Xdatcar class into a file.
The default behavior of Xdatcar was not modified only additional optional parameters were introduced in the `__init__` function. So it must not affect any other testcase or code where Xdatcar class is used
<None>
1. Concatenate function needs validation to ensure that the new …
=> Developed new functionalities for Xdatcar class in pymatgen.io.vasp module

pymatgen/io/feff/sets.py, pymatgen/io/feff/tests/test_sets.py, test_files/La4Fe4O12.cif
* support for size dependent feff runs(real v reciprocal)
*  add unittest
=> feff updates

pymatgen/electronic_structure/plotter.py
Adding colors to get_elt_projected_plots to make these plots more readable specially in compounds with more than 3 elements where other colored plots are not available.
Coming up with better color combination later.
=> improve readability of get_elt_projected_plots with colors.

pymatgen/electronic_structure/bandstructure.py
=> fix from_dict() after bs dict() with MontyEncoder

pymatgen/analysis/defects/point_defects.py, pymatgen/analysis/defects/tests/test_point_defects.py
An alternative interstitial finder was add, which works on the basis of a systematic structure-motif search in the unit cell by spanning a grid and using local order parameters for motif recognition.  The interstitial finder is used in the Python Charged Defect Toolkit (PyCDT).
Additional structure motifs can be added if there are well-defined criteria that are efficiently computable.
=> Alternative interstitial finder

pymatgen/io/vasp/tests/test_sets.py
sorry I didn't update the tests before. It was failing because now we are adding more k-points in the Line-mode
=> test passed locally. The number of k-points are supposed to be 203 now

pymatgen/io/gaussian.py, pymatgen/io/tests/test_gaussian.py
Read all resumes blocks in a gaussian output file and return them as a list of strings.
=> read the resume block of gaussian output file

pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/elasticity/tests/test_elastic.py
Energy density conversion factor was off by a decimal place
Fixed the conversion factor to be easier to read
Updated the test and double checked it with another calculation
=> Fixed energy density

pymatgen/analysis/ewald.py
Speeds up Ewald summation by doing more in-place math
=> Speed up Ewald summation

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
* Fix user_incar_settings update issue in MPNonSCFSet and MPSOCSet and add corresponding unittest
=> fix user_incar_settings bug in MPNonSCFSet and MPSOCSet

pymatgen/electronic_structure/bandstructure.py
Reverts materialsproject/pymatgen#550
=> Revert "update cbm module to make 0eV cbm discoverable"

pymatgen/io/fiesta.py
modified BSE ouptut from the Fiesta code so modified reg pattern for BSEoutput
=> modified BSE ouptut : modified reg pattern

pymatgen/analysis/pourbaix/maker.py
PourbaixDiagram Py3 Compatibility
=> PourbaixDiagram Py3 Compatibility

pymatgen/phasediagram/analyzer.py, pymatgen/phasediagram/tests/test_pdanalyzer.py, pymatgen/util/coord_utils.py, pymatgen/util/tests/test_coord_utils.py
Adds method to get critical compositions in tieline, and line intersections with a simplex
=> PDAnalyzer.get_critical_compositions()

pymatgen/electronic_structure/boltztrap.py
* the url of boltztrap needs update
* the output should be "error in factorization" not "STOP error in factorization" at least in the version 1.2.5
=> Correct error in factorization and update url of bolztrap

pymatgen/phasediagram/analyzer.py, pymatgen/phasediagram/maker.py, pymatgen/phasediagram/tests/test_pdanalyzer.py
Better testing with GrandPotentialPhaseDiagrams in PDAnalyzer.get_critical_compositions
=> PDAnalyzer update

pymatgen/analysis/eos.py, pymatgen/analysis/tests/test_eos.py
* add 'numerical eos': the equation of state employed in the quasiharmonic Debye model described in Cormac's paper: 10.1103/PhysRevB.90.174107.
* refactor and cleanup eos.py module
=> Equation of state updates

pymatgen/cli/pmg_plot.py
* file argument to saving dos plot is fixed.
=> Bug fix in saving dos_plot

pymatgen/analysis/eos.py, pymatgen/analysis/tests/test_eos.py
* got rid off ase crap(only the EOS wrapper class retained for backward compatibility)
* more object oriented implementation: makes it easier for adding more eoses
* added more unittests
=> major refactor of eos

pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/elasticity/tensors.py, pymatgen/analysis/elasticity/tests/test_elastic.py
Recent TOEC PR reverted some changes from previous PR.  This adds them back and adds a unittest for the missing functionality.
=> Minor fixes to elastic fitting

pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/tests/test_inputs.py
Add "LANGEVIN_GAMMA" to list_keys in class Incar.
NA
NA
=> add list_keys to Incar

pymatgen/analysis/path_finder.py
Implement Daniil's speedup suggestion
See issue #610
=> pathfinder speedup

pymatgen/analysis/diffusion_analyzer.py
* Minor bug fix for fraction coordinates and Cartesian coordinates conversion.
=> minor bug fix

pymatgen/analysis/defects/point_defects.py, pymatgen/analysis/structure_analyzer.py
Removed mutable default parameters in class OrderParameters and class StructureMotifInterstitial.
=> Removed mutable default parameters.

pymatgen/util/io_utils.py
<Short few sentences, and summary of the major changes in bullet 
points>
* Feature 1
* Feature 2
* Fix 1
* Fix 2
<List all new dependencies needed. While adding dependencies that bring
function, is frowned upon. If you are putting anything here, you should
provide a justification why that dependency is needed. Especially
frowned upon are circular dependencies, e.g., depending on derivative
modules of pymatgen such as custodian or Fireworks.>
<If this is a work-in-progress, write something about what else needs 
to be done>
=> Test if self.__name exists

pymatgen/transformations/defect_transformations.py, pymatgen/transformations/tests/test_defect_transformations.py
Fix typo in generating string representation of transformation.
* Fix typo
* Add unit test
=> Fix typo in generating string representation of transformation

pymatgen/io/tests/test_qchem.py
Fix INCAR QUAD_EFG tag parsing
=> Fix INCAR QUAD_EFG tag parsing

pymatgen/analysis/elasticity/strain.py
Minor bugfix
* Ensures deformations attribute of deformed structure set is a list
=> Minor bugfix - ensure deformations is a list

pymatgen/analysis/structure_analyzer.py
The alternative tetrahedral (tetalt) and octahedral (octalt) order parameter cannot become negative by construction and are therefore preferable to the original ones.
=> Introduced variants of tetrahedral and octahedral order parameter 

pymatgen/io/pwscf.py, test_files/sio2.pw.in
* Added method from_file to PWInput.
* Enabled PWInput type list.
* Enabled to read tags shown like "list(index) = val"
* PWInput changes
* pseudo (dict) not required.
* For spin polarization calculation 
(nspin=2), Site.properties for each site in Structure class will be needed.
However, for non-polarization calculation, pseudo(dict) is also OK.
* Added test file for PWInput
* test_files/sio2.pw.in
None
None
=> Add from_file method to PWInput

pymatgen/io/pwscf.py
Fixed a bug in PWInput.from_string()
=> Fixed a bug in PWInput.from_string()

pymatgen/electronic_structure/core.py, pymatgen/electronic_structure/tests/test_core.py
=> Bug fix for Magmom class + tests for same

pymatgen/io/cif.py, pymatgen/io/tests/test_cif.py
Now handles float/list magmoms correctly in addition to Magmom class.
=> Bug fix for CifWriter with write_magmoms=True

pymatgen/ext/jhu.py
Should fix the appveyor test.  Windows seems to have some issues with the temporary files and monty context manager, so I tried removing the context manager with monty.ScratchDir and that seemed to work.  I'm not able to test in my environment yet (don't have Windows), but will set up for the future.
=> Jhu kpoints appveyor fix

pymatgen/ext/matproj.py
ingore pymatgen[matproj.snl] warning when use python3
=> ingore pymatgen[matproj.snl] warning when use python3

pymatgen/io/lammps/output.py
<Short few sentences, and summary of the major changes in bullet 
points>
* Feature 1
* Feature 2
* Fix 1
* Fix 2
<List all new dependencies needed. While adding dependencies that bring
function, is frowned upon. If you are putting anything here, you should
provide a justification why that dependency is needed. Especially
frowned upon are circular dependencies, e.g., depending on derivative
modules of pymatgen such as custodian or Fireworks.>
<If this is a work-in-progress, write something about what else needs 
to be done>
=> bug fix in lammps output.py

pymatgen/electronic_structure/boltztrap.py, pymatgen/electronic_structure/tests/test_boltztrap.py
Made BoltztrapRunner MSONable 
Makes it easier to store and pass this object around.
=> Make BoltztrapRunner MSONable

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
* Adds a dipole correction to the slab incar params based on the center of mass for MVLSlabSet
* Updated unittest
=> Mvl slabset update

pymatgen/io/vasp/sets.py
Sorry, failed to merge last commit.  Should fix bug in CI tests.
=> fix bug in MVLSlabSet init

pymatgen/command_line/bader_caller.py, pymatgen/command_line/tests/test_bader_caller.py
* Updated tests for Bader caller
=> (Wait for CI before merge) New tests for Bader caller

pymatgen/command_line/bader_caller.py
BaderAnalysis is able to process all input files if they are gzipped
A classmethod similar to current `bader_analysis_from_path` to instantiate the class with given path
=> Support gzipped files for BaderAnalysis

pymatgen/io/lammps/input.py, pymatgen/io/lammps/tests/test_input.py
=> minor bug fix in lammspinput

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
See issue page / commit message for details.
=> Fix for #754

pymatgen/command_line/bader_caller.py, pymatgen/command_line/tests/test_bader_caller.py
Added parsing of charge densities from Bader partitioned Chgcars 
Cuts out extra 0's from the atomic charge densities to save space
=> Parsing charge densities for each atom

pymatgen/entries/compatibility.py, pymatgen/entries/tests/test_compatibility.py
This makes the compatibility objects MSONable and adds the appropriate test
=> MSONable Compatability

pymatgen/core/surface.py, pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py
Added a simple method to SpaceGroupAnalyzer to check if a structure has Laue class symmetry (centrosymmetric). Also renamed symmetrize_slab() in the SlabGenerator class to nonstoichiometric_symmetrized_slab().
* added is_laue to SpaceGroupAnalyzer
* renamed symmetrize_slab() in the SlabGenerator class to nonstoichiometric_symmetrized_slab()
=> very simple change to SpacegroupAnalyzer, added is_laue(). 

pymatgen/symmetry/analyzer.py
Not sure why, but this import line has been causing problems for me.  Doesn't appear to be used in the module.
=> minor bugfix

pymatgen/core/periodic_table.py, pymatgen/core/tests/test_periodic_table.py
New static method in Element class that plots periodic heatmap (credit to Richard Tran). This is to address Issue #769.
=> Static method that makes the periodic heatmap

pymatgen/io/lammps/data.py, pymatgen/io/lammps/tests/test_data.py
`LammpsData` now supports charged structure from oxidation states.
=> Implement set_charge for structure

pymatgen/io/vasp/outputs.py
=> fix parsing BSE vasprun error

pymatgen/analysis/interface_reactions.py, pymatgen/analysis/tests/test_interface_reactions.py
Fixed code style in interface_reaction module.
* Modified docstring to conform to pymatgen standard.
* Modified code style to conform to PEP 8 requirements.
=> Code style fix

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
Add `MVLNPTMDSet` class
* Add MVLNPTMDSet for AIMD input set in NpT ensemble
* Add unittest
* Minor docstring change
=> Add MVLNPTMDSet with unittest

pymatgen/entries/compatibility.py
=> typo: gas<-->anion in docstrings

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
Added parsing of drift from the OUTCAR
=> Drift in Outcar

pymatgen/io/atat.py
Hopefully this should fix it. I wrote a bad test though really, because it was failing even with a correct output...
=> ATAT ordering fix

pymatgen/io/vasp/inputs.py
Reverts materialsproject/pymatgen#869
=> Revert "Fix bug in POSCAR parsing"

pymatgen/core/structure.py
Add more filename wildcards for mcsqs input
=> Add more filename wildcards for mcsqs input

pymatgen/entries/tests/test_computed_entries.py
Should have included this with the previous PR #882 
* Added a test for is_element in computed entry
=> Added Test for is_element

pymatgen/electronic_structure/core.py, pymatgen/io/cif.py, pymatgen/io/tests/test_cif.py, test_files/Mn3Ge_IR2.mcif
See http://comcifs.github.io/magCIF.dic.html for more information
Fixes issue 1 of 2 in #886
=> Adds aliases for common keys in magCIF standard

pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py
=> Fix Structure.remove_spin() when applied to elements not species

pymatgen/electronic_structure/boltztrap.py
to avoid wasting CPU hours when finding Fermi level is not converging (specially at high concentrations), I introduced a timeout option defaulting to 2 hours.
=> add timeout for BoltztrapRunner default to 7200 seconds

pymatgen/analysis/adsorption.py, pymatgen/analysis/tests/test_adsorption.py, pymatgen/core/reconstructions_archive.json, pymatgen/core/surface.py
* Added instructions for generating the fcc_100_missing_row_1x2 and fcc_100_missing_row_1x1 slabs.
* Return slabs after adsorbing both sides
=> More reconstructions and fix bug in adsorb_both_sides

pymatgen/io/abinit/tasks.py, pymatgen/phonon/bandstructure.py, pymatgen/phonon/tests/test_bandstructure.py
* Implemented as_phononwebsite and write_phononwebsite functions to export the phonon dispersion to the phononwebsite: http://henriquemiranda.github.io/phononwebsite/
* Implemented band_reorder to order the eigenvalues and according to the similarity of the eigenvectors using the estimate_band_connection from phonopy by Atsushi Togo:
https://atztogo.github.io/phonopy/
=> Method in PhononBandStructure class to write json to phononwebsite

pymatgen/apps/battery/insertion_battery.py
Fixed the sign of calculated voltage of `InsertionVoltagePair` when anion is intercalated.
* Fix the wrong sign of the calculated voltage (revised script, line 431)
* Minor formatting.
=> fix voltage sign for anion voltage profile

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
Updates to MVLScanSet
- compromised on NELM
- ensure LDAU is False
=> Updates to MVLScanSet

pymatgen/electronic_structure/cohp.py, pymatgen/io/tests/test_lmto.py, pymatgen/io/tests/test_lobster.py
Minor clean-up for COHP-related modules.
* Removed unnecessary imports and variables.
* Replaced type with isinstance methods.
=> Minor COHP clean-up

pymatgen/analysis/pourbaix/analyzer.py, pymatgen/analysis/pourbaix/tests/test_analyzer.py
Small bug fix that affects region shading for pourbaix stable domains.
=> Pourbaix rev

pymatgen/analysis/defects/point_defects.py, pymatgen/analysis/defects/tests/test_point_defects.py
Add site finder using Voronoi Tessellation algorithm
* Added `TopographyAnalyzer` class
* Added `VoronoiPolyhedron` class and `calculate_vol` method.
* Unittest for LiFePO4 case
* Minor formatting
None
=> Add site finder using Voronoi Tessellation algorithm

pymatgen/phonon/dos.py, pymatgen/phonon/plotter.py, pymatgen/phonon/tests/test_dos.py, pymatgen/phonon/tests/test_plotter.py
* Extract thermodynamic properties from the integration on a phonon DOS
* Plotter of the thermodynamic properties
* option to change units in phonon BS and DOS plotters
* tests
=> Thermodynamic properties from phonon DOS

pymatgen/phonon/plotter.py
This PR completes the PR #996 about the units in the PhononBSPlotter.
A few lines were missing in the previous one. Sorry for the bothering.
=> units for phonon BS

tasks.py
points
* Feature 1
* Feature 2
* Fix 1
* Fix 2
* List all new dependencies needed. While adding dependencies that bring
to be done
=> Clean up tasks.py

tasks.py
points
* Feature 1
* Feature 2
* Fix 1
* Fix 2
* List all new dependencies needed. While adding dependencies that bring
to be done
=> Trivial commit for testing.

pymatgen/util/string.py, pymatgen/util/tests/test_string_utils.py
Add htmilify, unicodify to string utils for formula formatting + tests
None
None
=> Add htmilify, unicodify to string utils for formula formatting + tests

pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_local_env.py
points
* Feature 1
* Feature 2
* Fix 1
* Fix 2
* List all new dependencies needed. While adding dependencies that bring
to be done
=> added BrunnerNN class that uses Brunner's method to calculate near neighbors

pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_local_env.py
Modified VoronoiNN that only considers neighbors with at least 50% weight of max(weight).
=> modified version of VoronoiNN 

pymatgen/analysis/interface_reactions.py
Fix documentation wording for parameter use_hull_energy.
=> fix documentation wording.

pymatgen/command_line/enumlib_caller.py
The `curr_sites` variable needed to be extended by `sites` during each
iteration of the loop. This meant that the wrong spacegroup number was being calculated which is why, in some instances, the target spacegroup number was never reached.
Fixes one issue in #1063
None
None
=> EnumlibAdaptor: fix for trying to pop empty list

pymatgen/analysis/tests/test_phase_diagram.py
add test_formed_formula in ReactionDiagramTest
=> add test_formed_formula in ReactionDiagramTest

pymatgen/io/vasp/outputs.py
* Fix the Bug handling 0 during writing VolumetricData
before fix
-..000000000EE+01
after fix 
0.00000000000E+01
=> Bug handling 0 during writing VolumetricData

pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_local_env.py
Added a method for computing information about arbitrary nearest-neighbor shells of a particular site.
- Also added utility method for computing neighbors for all sites in a structure
None
None. 
Tagging @Qi-max, who I discussed this PR with and might use this operation for matminer.
=> Added ability to compute Nth nearest neighbors

pymatgen/analysis/local_env.py
Since I'm the only one using it (see issue #1108)
=> taking out _cns

pymatgen/io/qchem_io/inputs.py, pymatgen/io/qchem_io/tests/test_inputs.py
Added PCM (polarizable continuum model) and solvent sections in QChem input and in corresponding unit tests
* PCM section now included in input
* Solvent section also included in input
=> Added PCM and Solvent sections to QChem input and tests

pymatgen/util/provenance.py
Update the remarks max to Twitter circa 2017 (280 character total)
=> Update SNL remarks to 2017

pymatgen/util/provenance.py
Reverts materialsproject/pymatgen#1132
=> Revert "Update SNL remarks to 2017"

pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_local_env.py
This PR improves the accuracy of CrystalNN, particularly for layered systems.
* Intelligent search cutoff (prevent Voronoi errors for large layer distances)
* Redo weighting scheme to penalize large solid angles resulting from open structures
* change distance cutoffs to be absolute rather than relative
* change x_diff parameter behavior to activate more quickly
* support for zero-coordinated sites
* allow fingerprints to smoothly go to zero values
* minor code refactoring
=> v2 of CrystalNN

pymatgen/analysis/interface_reactions.py, pymatgen/analysis/tests/test_interface_reactions.py
Normalize reaction formula. Also provide reaction energy per reaction formula in kJ/mol.
* Reaction formula is normalized by the second reactant.
* Reaction energy in kJ/mol for per mol of normalized reaction is calculated in get_kinks method.
=> Normalize reaction and reaction energy per reaction

pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_local_env.py
Also added a corresponding unit test and checked that it fails if I revert to previous version. @WardLT should double-check.
=>  Fixed issue in solid_angles function to deal with co-planar configurations (i.e., where denominator become zero).

metadata.yml
see FAQ's at https://www.osti.gov/doecode/faq  
metadata can be updated as needed
=> adding pymatgen to DoeCode

pymatgen/io/gb/grain_boundary_generator.py, pymatgen/io/gb/test/test_grain_boundary_generator.py
Move gb generator to pymatgen.io.gb.
=> change gb location

pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_local_env.py
Adds the ability to determine which neighbors in VoronoiNN are adjacent.
None
None
=> Added ability to determine which Voronoi neighs are adjacent

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
Added support for spin polarized WAVECARs.
N/A
N/A
=> added spin polarization support

pymatgen/ext/tests/test_matproj.py
* test getting supported properties
* test aliasing
Guards against #1252
=> Add test for MPRester.get_task_data

.circleci/config.yml
- circleci edited to compile boltztrap
=> circleci fixed

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
Changed
VolumetricData(object) -> VolumetricData(MSONable)
added tests for as_dict and from_dict
=> added parsing of volumetric data as dictionaries

pymatgen/apps/battery/insertion_battery.py
* updated the artificial shift in energy to the non-working-ion elements so that we can always have a convex hull of with just the working-ion changing
* made the dicts for adj_pairs and all_paris return the actual list and not just the iterator.
=> Insertion batt js

pymatgen/analysis/eos.py
=> Fix for BirchMurnaghan EOS

pymatgen/core/tensors.py, pymatgen/io/abinit/flows.py, pymatgen/io/abinit/launcher.py, pymatgen/io/abinit/nodes.py, pymatgen/io/abinit/tasks.py, pymatgen/io/abinit/utils.py, pymatgen/io/abinit/works.py, pymatgen/io/abinit/wrappers.py, pymatgen/util/plotting.py
Reverts materialsproject/pymatgen#1329
=> Revert "Tools for EPH calculations"

pymatgen/analysis/ferroelectricity/polarization.py, pymatgen/analysis/ferroelectricity/tests/test_polarization.py
=> Ferroelectric np.matrix deprecation fix

pymatgen/analysis/graphs.py, pymatgen/analysis/tests/test_graphs.py
Ensure `jimage` kwarg is respected in `get_connected_sites`
=> Fix bug in analysis.graphs

pymatgen/analysis/tests/test_eos.py
=> Add additional EOS test data

pymatgen/core/tests/test_periodic_table.py
=> fix: missing "import numpy"

.circleci/config.yml, .travis.yml, appveyor.yml, pymatgen/ext/matproj.py
To support setting the MPRester endpoint via an env variable (for testing purposes).
=> Update MPRester to load endpoint from PMG_MAPI_ENDPOINT

pymatgen/analysis/defects/tests/test_utils.py, pymatgen/analysis/defects/utils.py
* fixed the floating point problem that causes the sites to fall outside the first BZ
* Store the average charge density instead of the total charge density around each local minima
=> Insert site group

docs_rst/team.rst
Updating the team list. Please suggest any additional changes.
=> Update Team List

pymatgen/analysis/ferroelectricity/polarization.py, pymatgen/analysis/ferroelectricity/tests/test_polarization.py, pymatgen/core/lattice.py, pymatgen/core/tests/test_lattice.py
=> move convert_cart_to_latt to method get_lattice_coords of Lattice class

pymatgen/analysis/graphs.py, pymatgen/analysis/tests/test_graphs.py
Fix https://github.com/materialsproject/pymatgen/issues/1384
=> fix relabel_nodes parameter in StructureGraph.remove_nodes

pymatgen/analysis/interface_reactions.py, pymatgen/analysis/tests/test_interface_reactions.py
Modified the equation normalization, and added convexity tests for the reaction energy plot.
* The returned equations for the interface app are now normalized in such a way that the coefficients of reactants reflect their molar ratios during the mixing.
* Add rigorous tests for the convexity of the reaction energy plot.
=> Interface reaction app revision

pymatgen/analysis/tests/test_interface_reactions.py
Fixed bug in test_interface_reactions.py file.
(Note: the other error from the tests are not from this pull request.)
=> fixed bug in test_interface_reactions file

pymatgen/electronic_structure/cohp.py, pymatgen/electronic_structure/tests/test_cohp.py
I have added a method to CompleteCohp that allows to plot summed COHPs easily (get_summed_cohps_by_labellist). And, I have included a new parameter in the method  get_icohp_dict_of_certain_site of IcohpCollection that allows to filter for certain bonding partners. Of course, I have also added new unit tests. I hope this is okay.
=> New/adapted method for handling COHPs/ICOHPs

pymatgen/analysis/dimensionality.py
The paper cited in the "get_dimensionality_larsen" function has been published.  I have replaced the arXiv reference with the published one.
I have also made a two small changes to the function, which improves the speed by 2-3x.
=> Updated publication info for dimensionality module

pymatgen/command_line/tests/test_critic2_caller.py, pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/tests/test_bandstructure.py, pymatgen/electronic_structure/tests/test_cohp.py, pymatgen/io/tests/test_lobster.py
I have adapted some of my new tests so that the CircleCI tests will hopefully pass. 
I also had some problems when running "test_cohp.py" and other files locally because there was no "@version" key in my dicts.
=> Repair failing tests

pymatgen/electronic_structure/tests/test_bandstructure.py, pymatgen/io/tests/test_lobster.py, pymatgen/io/vasp/tests/test_outputs.py
I replaced all AssertDictEqual tests with other tests. I hope this fixes the current test problems.
=> Fix for fatband tests

pymatgen/analysis/nmr.py, pymatgen/analysis/piezo.py, pymatgen/analysis/piezo_sensitivity.py, pymatgen/symmetry/sitesymmetries.py
WIP
Added piezo_sensitivity and site_symmetry packages under analysis. Site_symmetries allow for users to get the point symmetries of atomic sites and symmetry operations relating sites. Piezo sensitivity allows for random generation of piezoelectric components and the calculation of the piezoelectric tensor from components
Needs to be unit tested and style formatted. Not quite sure if this is the appropriate place for the packages but these are still heavily work in progress.
=> [WIP] Piezo Sensitivity and Site symmetries packages added

pymatgen/electronic_structure/plotter.py
Segmented drawing different branches of band structure in BSDOSPlotter. Look nicer between two discontinuous k-path branches
* After fix
* Before fix
=> Segmented drawing different branches of band structure

pymatgen/core/composition.py, pymatgen/core/tests/test_composition.py
=> Add strict option to Composition and valid property

pymatgen/io/lobster.py, pymatgen/io/tests/test_lobster.py, setup.py
After using pip install, "BASIS_PBE_54.yaml" was not found. I have changed the "setup.py" to correct this.
=> Fix pip install

pymatgen/io/lobster.py, pymatgen/io/tests/test_lobster.py
Small BugFix in the lobsterin class to also change LWAVE from False to True when writing a new INCAR. I also adapted the tests. 
I am sorry for the very frequent bug fixes at the moment. I hope this will be one of the last ones for now.
=> Another small update to Lobsterin class

pymatgen/ext/matproj.py, pymatgen/ext/tests/test_matproj.py
This solves issue #1503 by implementing get_xas_data method in MPRester.
* Add get_xas_data method in MPRester
* Add unittest 
* none
* none
=> add get_xas_data method

pymatgen/ext/matproj.py, pymatgen/ext/tests/test_matproj.py
* add grain boundary MPRester to query grain boundary structure and energy data
* add unittest
=> add grain boundary MPRester

pymatgen/io/vasp/outputs.py
This change was made due to the fact that FortranFile can not read records with the number of
entries exceeding int32 limits (filesize >~ 2GB).
=> Waveder reading changed from FortranFile to directly reading binary.

pymatgen/io/lobster.py, pymatgen/io/tests/test_lobster.py
Hello again, 
I am sorry. I have already found a small bug in the bandoverlaps class. It should be fixed now and I have also adapted the tests to avoid this problem in the future.
=> Fix bug in bandoverlaps class

pymatgen/transformations/standard_transformations.py
_apply_transformation()_ now returns _num_to_return_ entries as described in the doctoring.
=> Fix number of returned entries in apply_transformation

pymatgen/entries/computed_entries.py, pymatgen/ext/matproj.py
Reverts materialsproject/pymatgen#1555
=> Revert "Enhancements to ComputedEntry and MPRester"

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
Hello! 
I have written a LobsterSet to create VASP inputs that can be used for lobster calculations later and I have also created tests. 
Please let me know if I have followed all conventions for VASP sets. Also, let me know if I have overlooked something. The relationships between classes in this module are quite complex due to the many class-subclass relationships.
Best,
JG
=> New vasp set

pymatgen/io/vasp/incar_parameters.json, pymatgen/io/vasp/inputs.py
Simplified checks for 'list' type parameters in INCAR
=> Incar params fix

pymatgen/core/tests/test_trajectory.py, pymatgen/core/trajectory.py, pymatgen/io/vasp/sets.py
- Fixed issue with slicing, wherein only fully specified slices work. example: traj[0 : -1 : 10] worked, but traj[ : : 10] and traj[ : -1 : 10] did not work.
- Added property to keep track of information of each time step such as Temperature, Pressure, and Energy. This variable is called 'frame_property', but if a better name is proposed, I have no problem changing it.
- Added more tests for slicing, site properties, and frame properties
=> Fixed some minor bugs in Trajectory and more features

pre-commit, pymatgen/analysis/bond_valence.py, pymatgen/analysis/defects/utils.py, pymatgen/analysis/energy_models.py, pymatgen/analysis/local_env.py, pymatgen/analysis/structure_analyzer.py, pymatgen/analysis/structure_prediction/volume_predictor.py, pymatgen/core/structure.py, pymatgen/core/surface.py
* Introduced PeriodicNeighbor and Neighbor helper classes. These are essentially sites with attributes like distance, index and image (for PeriodicNeighbor) and skips all the usual checks for Sites.
* Greatly speeds up get_all_neighbors by not having checks (which are unnecessary since the NN sites are constructed in a controlled environment).
* One backwards incompatible thing introduced is that we have to rename Neighbor.distance to Neighbor.nn_distance. distance is actually a method name in Site/PeriodicSite. All uses within Pymatgen have been fixed.
* @mkhorton and @chc273 Pls review.
* None
Before a pull request can be merged, the …
=> NN speedup

pymatgen/io/lobster.py, pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
Modification in lobsterin class to make the choice of the basis even more flexible. This is needed for future developments. 
I also included tests to do so.
* Feature 1 supports A, but not B.
- [] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) 
efficient if you already fix most …
=> Modification in lobsterin class

pymatgen/io/lammps/data.py, pymatgen/io/lammps/tests/test_data.py
* Fix: Fixed the previous behavior that the CombinedData initializes by destructively using the input LammpsData objects, which causes errors when reusing those LammpsData.
=> fix previous destructive usage of input LammpsData

pymatgen/ext/tests/test_matproj.py
GGA NSCF Line tasks were de-blessed for the tested materials
=> fix nomad test

pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
Hello,
I am fixing a bug that was introduced in this pull request: 
https://github.com/materialsproject/pymatgen/commit/80aa5047cc0925cc1178d85aa691ebb7c51eebde#r36189539
I have not written a test yet but we are working on it. For now, I would like to fix the functionality.
Best, 
JG
=> Fix bug in ChemEnv

pymatgen/core/molecular_orbitals.py
Adds units and reference for atomic orbital dataset
=> Add missing information to docstrings

pymatgen/analysis/chemenv/connectivity/connected_components.py
Bad check on a peculiar case (which in the latest version of the connected component code, could actually not occur anymore) that was actually wrong in other cases. => removed that check.
=> Fixed minor issue in connected_components.

pymatgen/analysis/local_env.py
Extremely small change - just adds docstrings in pymatgen/analysis/local_env.py
=> Added docstrings to new NearNeighbors properties make the linters happy

pymatgen/io/vasp/sets.py
Fix #1752 in validate_potcar_hashes.
=> Bugfix for validate_potcar_hashes

pymatgen/core/sites.py
* Feature 1
* Feature 2
* Fix 1
* Fix 2
* List all new dependencies needed and justify why. While adding dependencies that bring
to be done
* Feature 1 supports A, but not B.
Before a pull request can be merged, the …
=> fix sites's doc (delete duplication)

pymatgen/symmetry/bandstructure.py, pymatgen/symmetry/kpath.py, pymatgen/symmetry/tests/test_kpath_hin.py, pymatgen/symmetry/tests/test_kpath_lm.py, pymatgen/symmetry/tests/test_kpath_sc.py, pymatgen/symmetry/tests/test_kpaths.py, requirements-optional.txt, test_files/LaMnO3_magnetic.mcif
This pull request introduces support for generating high-symmetry k-paths using two additional conventions. Namely, the SeeK-path convention by Hinuma and coworkers [Y. Hinuma, et al. Band structure diagram paths based on crystallography, Comp. Mat. Sci. 128, 140 (2017)], and a new "on-the-fly" convention out of the Persson group that is soon to be published. 
Below is a summary of the code changes:
* New KPath classes added to handle high-symmetry k-path generation.
* Existing HighSymmKpath code to generate paths using the convention by Setyawan and Curtarolo converted to a KPath class.
* New HighSymmKpath class added which calls k-path generation classes, and provides methods for amalgamating and comparing path data across conventions.
It should be noted that the default HighSymmKpath …
=> [WIP] New KPath and HighSymmKpath classes

pymatgen/transformations/advanced_transformations.py
`CubicSupercellTransformation` had some unnecessary complexity for diagonal only transformations. This PR implements a more optimised method.
=> Optimize CubicSupercellTransformation for diagonal transformations

pymatgen/core/tests/test_units.py, pymatgen/core/units.py
=> Units k cal

pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_local_env.py
Changed the JMolNN tolerance parameter to match the that used by the JMol source code.
=> Fix JMolNN tolerance

pymatgen/ext/matproj.py, pymatgen/ext/tests/test_matproj.py
Merge pending changes to materialsproject.org and subsequent checking.
The intent of this PR is to better notify users of `MPRester` what the Materials Project database version is, and to notify the user if this version changes.
=> MPRester database version checking and logging

pymatgen/io/vasp/VASPIncarBase.yaml, pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
* Feature 1
* Feature 2
* Fix 1
* Fix 2
* List all new dependencies needed and justify why. While adding dependencies that bring
to be done
* Feature 1 supports A, but not B.
Before a pull request can be merged, the …
=> Default Co to low spin.

.gitignore, .pre-commit-config.yaml, docs_rst/contributing.rst, pymatgen/analysis/defects/core.py, pymatgen/analysis/defects/tests/test_core.py, pymatgen/analysis/defects/tests/test_utils.py, pymatgen/analysis/defects/utils.py, pymatgen/core/units.py, setup.cfg
- Added ChargeInsertionAnalyzer class and tests
- Reformatted and ignoring .pre-commit-config.yaml
=> added insertion site code and tests

pymatgen/analysis/phase_diagram.py
3D phase diagram plots have fonts that are so small they are nearly illegible. This PR has minor changes to aesthetics that take full use of the space in the plot and increase font size.
* Larger fonts for component labels
* Changed 3D plot layout to make full use of the figure
None
* List all new dependencies needed and justify why. While adding dependencies that bring
None …
=> imporve legibility of 3D phase diagram plot

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
=> fix IVDW bug in Vasprun.run_type

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
update `PhaseDiagramError` message to tell users which elements are missing.
=> More Informative Message with PhaseDiagramError

.gitignore
Taken from https://github.com/github/gitignore
=> Ignore typical virtual environment file/directory names

pymatgen/entries/compatibility.py
Update docstring of `MaterialsProject2020Compatibility` with final published version of manuscript
=> update MP2020 publication details

pymatgen/ext/optimade.py, pymatgen/ext/tests/test_optimade.py, pymatgen/util/sequence.py
Preparing new features in advance of OPTIMADE lesson on Tuesday.
The main feature added in this PR is for `pymatgen.ext.optimade.OptimadeRester` to allow querying multiple providers simultaneously. It also adds more logging and reporting/user experience improvements.
There are several TODOs added inside the code, mainly related to more robust error handling and more closely following (or requiring) conformance with the OPTIMADE specification.
=> Updates to OPTIMADE REST interface

docs_rst/addons.rst, pymatgen/core/structure.py
This add-on (www.pypi.org/project/pymatgen-io-fleur) provides functionality for reading writing files used
by the FLEUR code (www.flapw.de)
* Added entry for IO namespace package for the fleur code to the addons page
* Added the IO functionality of the addon to the ``Structure`` methods ``to``, ``from_file`` and ``from_str``
* Adds a format for the XML input file of Fleur (read-only), which is chosen for files named ``inp*.xml``
* Adds a format for the input file for the input generator of Fleur which can also be written out
None
is to run the following in the **correct …
=> Add `pymatgen-io-fleur` addon to addons page

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
=> Add caching to all GH workflows

pymatgen/analysis/interfaces/__init__.py, pymatgen/core/__init__.py, pymatgen/io/lobster/__init__.py, pymatgen/io/vasp/__init__.py, setup.cfg
~Closes #2359.~ Closes nothing.
#2359 was closed in d7cfd8a4a6a00fce1860f1a4d2ed0a3830520dbc.
=> flake8 add per-file-ignores = __init__.py: F401

pymatgen/io/lobster/inputs.py
=> Fix Lobsterin()._get_potcar_symbols()

README.rst
- uniform shield.io readme badges
- brought onto 1 line
- fix GH CI badge
- add PyPI download badge
=> Fix readme badges

pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py
=> Store the actual charge and spin_mult in structure.as_dict()

dev_scripts/chemenv/strategies/multi_weights_strategy_parameters.py, pymatgen/analysis/defects/dilute_solution_model.py, pymatgen/analysis/diffusion_analyzer.py, pymatgen/analysis/phase_diagram.py, pymatgen/cli/pmg_query.py, pymatgen/command_line/bader_caller.py, pymatgen/command_line/enumlib_caller.py, pymatgen/command_line/vampire_caller.py, pymatgen/core/periodic_table.py, pymatgen/core/structure.py, pymatgen/core/tests/test_periodic_table.py, pymatgen/core/xcfunc.py, pymatgen/electronic_structure/boltztrap.py, pymatgen/io/abinit/abiobjects.py, pymatgen/io/abinit/abitimer.py, pymatgen/io/abinit/inputs.py, pymatgen/io/cif.py, pymatgen/io/gaussian.py, pymatgen/io/lammps/data.py, pymatgen/io/lmto.py, pymatgen/io/pwscf.py, pymatgen/io/tests/test_lmto.py, pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/outputs.py, pymatgen/io/xcrysden.py, pymatgen/transformations/advanced_transformations.py, pymatgen/transformations/standard_transformations.py
Same as #2379 but using `flynt`'s  `--aggressive` flag and more careful checking of changes.
=> flynt --aggressive

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, setup.py
Since Nov 2021, `setup-python` GitHub action supports automatic `pip` dependency caching:
https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching
=> Use setup-python automatic pip caching in CI

.github/workflows/release.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, docs_rst/compatibility.rst, pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py, pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/interface_reactions.py, pymatgen/analysis/tests/test_interface_reactions.py, pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, pymatgen/io/vasp/sets.py
Follow up to #2397 and #2401.
Deletes some more code [@shyuep said is very old](https://github.com/materialsproject/pymatgen/pull/2397#issuecomment-1025976675).
=> Remove more deprecated stuff

pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py
=> Ensure SpacegroupAnalyzer.get_crystal_system() raises ValueError on neg space groups

pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py
Also adds a test for this.
Closes #2437.
=> Fix Structure.from_file() for .yml ext

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/vasp/outputs.py
Add some more type hints in `electronic_structure/plotter.py`, `bandstructure.py`, `io/vasp/outputs.py`.
=> Type hints

.github/workflows/lint.yml, pymatgen/alchemy/materials.py, pymatgen/transformations/transformation_abc.py
945d8daabe type annotations for pymatgen/alchemy/materials.py
3c3e9417fb type annotations for pymatgen/transformations/transformation_abc.py
696ecd20d2 remove `fetch-depth: 0` from lint actions/checkout
=> Alchemy type hints

pymatgen/analysis/diffraction/neutron.py, pymatgen/analysis/diffraction/xrd.py, pymatgen/analysis/wulff.py, pymatgen/apps/borg/hive.py, pymatgen/cli/pmg_config.py, pymatgen/core/bonds.py, pymatgen/core/periodic_table.py, pymatgen/core/structure.py, pymatgen/core/surface.py, pymatgen/core/units.py, pymatgen/core/xcfunc.py, pymatgen/electronic_structure/boltztrap.py
Plus a few type hints and f-strings.
=> Fix bad `ValueError` message in `SimpleVaspToComputedEntryDrone.assimilate()`

pymatgen/analysis/defects/__init__.py, pymatgen/util/plotly_chempot_layouts.json
1. Change the background color on the chemical potential plots (for dark backgrounds)
2. Added warning that the `pymatgen.analysis.defects` module will be replaced with a namespace package.
=> Minor changes

pymatgen/io/core.py
Tiny addition to documentation. This was a gotcha for me.
=> small documentation addition

pymatgen/symmetry/kpath.py
Minor English corrections and improved descriptions/reduced ambiguity
"can be incorrect" should be "may be incorrect"
The "lattice" is infinite in all dimensions and remains unchanged; only the "cell" or "lattice vectors" are reduced
Other minor improvements for clarity/ease-of-reading
=> Fix English errors in messages, descriptions, etc.

CHANGES.rst, pymatgen/analysis/defects/core.py, pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py
Closes #2587.
Related #2584.
Also adds tests for `IStructure.__eq__()`.
=> Fix edge cases in Structure equality

docs_rst/addons.rst
Add https://github.com/janosh/pymatviz to https://pymatgen.org/addons.
=> Add "External tools" section to `docs_rst/addons.rst`

pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py, pymatgen/analysis/chemenv/coordination_environments/voronoi.py, pymatgen/analysis/diffraction/neutron.py, pymatgen/analysis/diffraction/tem.py, pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/ewald.py, pymatgen/analysis/local_env.py, pymatgen/analysis/structure_matcher.py, pymatgen/analysis/surface_analysis.py, pymatgen/analysis/tests/test_quasiharmonic_debye_approx.py, pymatgen/analysis/xas/spectrum.py, pymatgen/core/lattice.py, pymatgen/core/periodic_table.py, pymatgen/core/sites.py, pymatgen/core/structure.py, pymatgen/core/tensors.py, pymatgen/core/units.py, pymatgen/core/xcfunc.py, pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/core.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/abinit/abiobjects.py, pymatgen/io/abinit/pseudos.py, pymatgen/io/core.py, pymatgen/io/vasp/outputs.py, pymatgen/io/xtb/inputs.py, pymatgen/io/xyz.py, pymatgen/transformations/site_transformations.py, pymatgen/util/provenance.py, setup.cfg
Since they're auto-defined by python as `not __eq__()`.
=> Remove `__ne__` methods

pymatgen/analysis/chemenv/coordination_environments/structure_environments.py, pymatgen/electronic_structure/core.py
Follow up to #2601.
Fixes `pymatgen/electronic_structure/tests/test_core.py:131: AssertionError`.
=> Fix CI AssertionError: `False` is not `True` in `self.assertTrue(Magmom([0, 0, 10]) == 10)`

pymatgen/io/vasp/outputs.py
I noticed some errors in the documentation of WSWQ.
Also added a `data` field to make combining the real/imag parts easier.
=> Better docs for WSWQ

pymatgen/analysis/diffraction/tem.py
Signed-off-by: chunweizhu <c_w_zhu@163.com>
* fix the bugs when runing `TEMCalculator` 
* List all new dependencies needed and justify why. While adding dependencies that bring
significantly useful functionality is perfectly fine, adding ones that
function, is frowned upon. Provide a justification why that dependency is needed.
If this is a work-in-progress, write something about what else needs
to be done
* Feature 1 supports A, but not B. …
=> Fix some bugs for tem.py

pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py, pymatgen/analysis/chempot_diagram.py, pymatgen/analysis/phase_diagram.py, pymatgen/cli/pmg_config.py, pymatgen/core/structure.py, pymatgen/ext/matproj.py, pymatgen/io/vasp/help.py
=> Fix AttributeError: 'set' object has no attribute 'sort' from PatchedPhaseDiagram(keep_all_spaces=True)

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/entries/correction_calculator.py
=> Fix PatchedPhaseDiagram raises ValueError on empty spaces set

.pre-commit-config.yaml, CHANGES.rst, docs_rst/team.rst, metadata.yml, pymatgen/analysis/interfaces/substrate_analyzer.py, pymatgen/analysis/phase_diagram.py, pymatgen/analysis/piezo_sensitivity.py, pymatgen/analysis/tests/test_local_env.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/command_line/bader_caller.py, pymatgen/command_line/chargemol_caller.py, pymatgen/command_line/tests/test_mcsqs_caller.py, pymatgen/core/interface.py, pymatgen/core/structure.py, pymatgen/entries/compatibility.py, pymatgen/entries/mixing_scheme.py, pymatgen/io/core.py, pymatgen/io/cp2k/outputs.py, pymatgen/io/cp2k/sets.py, pymatgen/io/feff/tests/test_inputs.py, pymatgen/io/lobster/lobsterenv.py, pymatgen/io/qchem/outputs.py, pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/sets.py, pymatgen/io/zeopp.py, pymatgen/transformations/advanced_transformations.py, pymatgen/transformations/tests/test_advanced_transformations.py, setup.cfg
Including new test case in cda8604.
=> Add `on_error` kwarg to `PhaseDiagram.get_decomp_and_e_above_hull()`

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
Refactor existing ones to `pytest`.
=> ~2x number of PatchedPhaseDiagrams tests

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
- `__len__`
- `__getitem__`
- `__setitem__`
- `__delitem__`
- `__iter__`
- `__contains__`
=> PatchedPhaseDiagram magic methods

.github/workflows/lint.yml, .pre-commit-config.yaml, pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/core/structure.py, pymatgen/entries/compatibility.py, setup.cfg
=> Test methods downstream from `PD.get_decomp_and_e_above_hull_on_error()` can also ignore errors

pymatgen/analysis/chemenv/connectivity/tests/test_connected_components.py, pymatgen/analysis/chemenv/connectivity/tests/test_environment_nodes.py, pymatgen/analysis/chemenv/connectivity/tests/test_structure_connectivity.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_chemenv_strategies.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometries.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometry_finder.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_structure_environments.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_voronoi.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_weights.py, pymatgen/analysis/chemenv/utils/chemenv_config.py, pymatgen/analysis/chemenv/utils/tests/test_chemenv_config.py, pymatgen/analysis/chemenv/utils/tests/test_coordination_geometry_utils.py, pymatgen/analysis/chemenv/utils/tests/test_func_utils.py, pymatgen/analysis/chemenv/utils/tests/test_math_utils.py, pymatgen/analysis/tests/test_path_finder.py, pymatgen/ext/matproj.py, pymatgen/ext/tests/test_cod.py, pymatgen/ext/tests/test_matproj.py, pymatgen/ext/tests/test_optimade.py, pymatgen/symmetry/tests/test_groups.py, pymatgen/symmetry/tests/test_maggroups.py, pymatgen/symmetry/tests/test_settings.py, pymatgen/vis/tests/__init__.py, test_files/Zr_Vasprun/test_vasprun.py
=> Fix _MPResterLegacy tests in pymatgen/ext/tests/test_matproj.py failing due to new API key

pymatgen/core/__init__.py, pymatgen/core/tests/test_settings.py, pymatgen/symmetry/tests/test_analyzer.py
Add new test module `pymatgen/core/tests/test_settings.py` to cover `_load_pmg_settings()`.
=> Test `_load_pmg_settings()`

.github/workflows/test-linux.yml, pylintrc, pymatgen/core/__init__.py
Following on the heels of #2698.
This PR was triggered by taking another look at `_load_pmg_settings()` due to the error reported in #2705. Don't think the error there has anything to do with #2698 though.
=> Better error handling in `_load_pmg_settings()`

MANIFEST.in, pymatgen/command_line/gulp_caller.py, pymatgen/io/abinit/netcdf.py, pymatgen/util/__init__.py, setup.py
Following discussion in https://github.com/materialsproject/pymatgen/pull/2738#issuecomment-1319346557, this PR removes the `MANIFEST.in` file since it pulled a lot of unnecessary files like `.mypy_cache` and `docs/*`, `docs_rst/*`, `dev_scripts/` into the source distribution. It's job is taken over by `setup.py` with slight modifications.
<details>
<summary>Old `SOURCES.txt` (1452 lines after removing `.mypy_cache` lines</summary>
```txt
.gitattributes
.gitignore
.pre-commit-config.yaml
CHANGES.rst
CITATION.cff
CONTRIBUTING.rst
LICENSE.rst
MANIFEST.in
README.md
SECURITY.md
metadata.yml
pylintrc
pyproject.toml
setup.cfg
setup.py
tasks.py
.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md …
```
=> rm `MANIFEST.in`

pymatgen/analysis/molecule_matcher.py, setup.py
Will look like this in the [PyPI side bar](https://pypi.org/project/pymatgen):
=> Add `setup.py` `project_urls`

pymatgen/io/lobster/outputs.py, pymatgen/io/lobster/tests/test_lobster.py
- Updated corresponding test cases
=> Fix lobster out doc

pymatgen/util/io_utils.py
Presumed unused. Atomic commit for easy revertability in case still needed.
=> del class AtomicFile, _maketemp(), ask_yesno()

.pre-commit-config.yaml, dev_scripts/chemenv/test_algos.py, dev_scripts/chemenv/test_algos_all_geoms.py, pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_read_write.py, pymatgen/analysis/interfaces/zsl.py, pymatgen/analysis/topological/spillage.py, pymatgen/analysis/xps.py, pymatgen/core/lattice.py, pymatgen/core/tests/test_lattice.py, pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_inputs.py, pymatgen/io/vasp/tests/test_outputs.py, pyproject.toml
Also, fix variable name clash `shell == shell` in `pymatgen/analysis/xps.py` and fix CI failure following e4bde8e400.
=> Breaking: Rename `gen_sl_transform_matricies->gen_sl_transform_matrices`

.pre-commit-config.yaml, pymatgen/analysis/chemenv/coordination_environments/tests/test_weights.py, pymatgen/analysis/chemenv/utils/tests/test_coordination_geometry_utils.py, pymatgen/analysis/chemenv/utils/tests/test_func_utils.py, pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, pymatgen/core/tests/test_tensors.py, pymatgen/entries/tests/test_exp_entries.py, pymatgen/io/babel.py, pymatgen/util/tests/test_provenance.py, pyproject.toml, tasks.py, test_files/.pytest-split-durations
813019427e add `return_trajectory` option to `Structure.relax()`
64dee2a8ba test new option in `test_relax_with_observer()`
db0871a327 convert vars to snake case
=> Enable Structure relaxations with TrajectoryObserver

pymatgen/analysis/structure_matcher.py, pymatgen/core/composition.py, pymatgen/core/lattice.py, pymatgen/core/operations.py, pymatgen/core/periodic_table.py, pymatgen/core/structure.py, pymatgen/core/units.py, pymatgen/core/xcfunc.py
A lot of functions have undocumented arguments. This PR adds doc strings description for some of them.
=> Fix D417 in `pymatgen/core`

pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, test_files/bad-unicode-gh-2947.mcif
=> Ignore bad unicode characters in Structure.from_file()

dev_scripts/chemenv/get_plane_permutations_optimized.py, dev_scripts/update_pt_data.py, pymatgen/analysis/adsorption.py, pymatgen/analysis/bond_valence.py, pymatgen/analysis/chemenv/connectivity/tests/test_environment_nodes.py, pymatgen/analysis/chemenv/connectivity/tests/test_structure_connectivity.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometries.py, pymatgen/analysis/chemenv/utils/tests/test_coordination_geometry_utils.py, pymatgen/analysis/chemenv/utils/tests/test_graph_utils.py, pymatgen/analysis/chempot_diagram.py, pymatgen/analysis/cost.py, pymatgen/analysis/diffraction/tests/test_tem.py, pymatgen/analysis/dimensionality.py, pymatgen/analysis/elasticity/strain.py, pymatgen/analysis/ewald.py, pymatgen/analysis/local_env.py, pymatgen/analysis/path_finder.py, pymatgen/analysis/pourbaix_diagram.py, pymatgen/command_line/enumlib_caller.py, pymatgen/core/tests/test_tensors.py, pymatgen/core/trajectory.py, pymatgen/io/res.py, pymatgen/symmetry/maggroups.py, pymatgen/util/graph_hashing.py, pyproject.toml
678627b72 remove unused type ignore
484d133be ruff auto doc str format
0ba2f868d drop B031 from ruff ignore
579ac1e3e rename single-letter and non-snake-case vars
2dee11169 self.assertArrayEqual -> assert
=> `self.assertArrayEqual->assert`

docs_rst/contributing.rst
=> Link /addons from new subsection on /contributing page

dev_scripts/regen_libxcfunc.py, pymatgen/alchemy/filters.py, pymatgen/analysis/energy_models.py, pymatgen/analysis/local_env.py, pymatgen/analysis/magnetism/heisenberg.py, pymatgen/analysis/structure_prediction/substitution_probability.py, pymatgen/apps/borg/hive.py, pymatgen/cli/pmg_config.py, pymatgen/core/__init__.py, pymatgen/core/tensors.py, pymatgen/core/tests/test_units.py, pymatgen/ext/matproj.py, pymatgen/io/abinit/abiobjects.py, pymatgen/io/abinit/abitimer.py, pymatgen/io/abinit/inputs.py, pymatgen/io/abinit/netcdf.py, pymatgen/io/abinit/pseudos.py, pymatgen/io/abinit/tests/test_netcdf.py, pymatgen/io/cif.py, pymatgen/io/cp2k/inputs.py, pymatgen/io/fiesta.py, pymatgen/io/lammps/outputs.py, pymatgen/io/qchem/outputs.py, pymatgen/phonon/bandstructure.py, pymatgen/transformations/advanced_transformations.py
ff12ac5a4 rename dict vars `d` -> `dct`
502158daa re-export `DummySpecie` + `SiteCollection` from `pymatgen.core`
=> Re-export `SiteCollection` + `DummySpecies` from `pymatgen.core`

pymatgen/core/lattice.py, pymatgen/core/sites.py, pymatgen/core/structure.py, pymatgen/entries/compatibility.py, pymatgen/symmetry/structure.py, pymatgen/symmetry/tests/test_analyzer.py
Closes #2398.
d86e0b0f8 MaterialsProjectCompatibility issue silencable deprecation warning
e7a644539 SymmetrizedStructure type hints
=> MaterialsProjectCompatibility issue deprecation warning

pymatgen/io/jarvis.py, pymatgen/io/tests/test_jarvis.py, pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py, pymatgen/util/coord.py
Closes #3040.
@arosen93 Do you have a good test case for this by any chance?
=> Fix LMAXMIX default in VASP INCAR now set based on element blocks in structure

pymatgen/core/sites.py, pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py
=> Better error message to clarify Structure.species only supported for ordered

pymatgen/alchemy/materials.py, pymatgen/alchemy/tests/test_materials.py, pymatgen/analysis/chemenv/utils/tests/test_func_utils.py, pymatgen/core/composition.py, pymatgen/core/tests/test_bonds.py, pymatgen/core/tests/test_composition.py, pymatgen/io/abinit/abiobjects.py, pymatgen/io/qchem/inputs.py, pymatgen/io/qchem/outputs.py, pymatgen/io/vasp/outputs.py
8011095ce single line None assignment
697dec8eb more precise error message testing
0f1256ca8 breaking: change Composition bad key error type from TypeError to KeyError
=> Breaking: change `Composition` bad key error type from `TypeError` to `KeyError`

pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/tests/test_bandstructure.py
=> Add `test_apply_scissor_(insulator|spin_polarized)`

pymatgen/electronic_structure/tests/test_plotter.py
=> Fix `DosPlotterTest.test_get_plot_limits()` assert floats equal not using `approx`

pymatgen/analysis/molecule_matcher.py, pymatgen/analysis/tests/test_molecule_matcher.py, pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, pymatgen/io/gaussian.py, pymatgen/util/testing.py, pyproject.toml
Closes #3090 
I really just moved the method. It's not sophisticated yet but maybe someone can build on this implementation. I therefore left a todo.
=> Move `get_zmatrix` from `GaussianInput` to `Molecule`

pymatgen/analysis/gb/grain.py
Minor misspell fix in error message
=> fixed misspell in GB error message

pymatgen/analysis/graphs.py, pymatgen/analysis/local_env.py, pymatgen/analysis/tests/test_graphs.py
=> Fix unexpected error message in `MoleculeGraphTest.test_construction`

dev_scripts/update_pt_data.py, pymatgen/alchemy/filters.py, pymatgen/analysis/adsorption.py, pymatgen/analysis/bond_valence.py, pymatgen/transformations/standard_transformations.py, pymatgen/transformations/tests/test_advanced_transformations.py, pymatgen/transformations/tests/test_standard_transformations.py, pymatgen/util/convergence.py, pymatgen/util/coord.py, pymatgen/util/due.py, pymatgen/util/num.py, pymatgen/util/plotting.py, pymatgen/util/provenance.py, pymatgen/util/string.py, pymatgen/vis/structure_chemview.py, pymatgen/vis/structure_vtk.py, pyproject.toml
e511f9a14 rename single-letter var names i -> idx
66d546abb fix doc string issues
e907c315e deprecate pymatgen/util/convergence.py
=> Deprecate `pymatgen.util.convergence`

pymatgen/analysis/interfaces/tests/test_substrate_analyzer.py, pymatgen/analysis/interfaces/tests/test_zsl.py, pymatgen/analysis/interfaces/zsl.py
Closes https://github.com/materialsproject/pymatgen/issues/2457.
=> Fix for missing lattice matches in ZSLGenerator

pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_chemenv_strategies.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometry_finder.py, pymatgen/analysis/chemenv/utils/tests/test_chemenv_config.py, pymatgen/analysis/tests/test_interface_reactions.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/core/tests/test_structure.py, pymatgen/electronic_structure/tests/test_dos.py, pymatgen/entries/tests/test_entry_tools.py, pymatgen/io/lobster/tests/test_lobsterenv.py, pymatgen/io/phonopy.py, pymatgen/io/tests/test_packmol.py, pymatgen/io/tests/test_phonopy.py, pymatgen/transformations/tests/test_site_transformations.py, pymatgen/util/provenance.py, pymatgen/util/tests/test_provenance.py, pymatgen/util/tests/test_string.py, pyproject.toml
Also fix remaining violations.
=> Enable `ruff` `PT011`

pymatgen/entries/compatibility.py, pymatgen/entries/tests/test_compatibility.py
=> Fix "Incompatible POTCAR" error on ComputedEntries with oxidation states

pymatgen/analysis/interface_reactions.py, pymatgen/analysis/magnetism/heisenberg.py, pymatgen/analysis/surface_analysis.py, pymatgen/analysis/wulff.py, pymatgen/command_line/gulp_caller.py, pymatgen/command_line/mcsqs_caller.py, pymatgen/core/periodic_table.py, pymatgen/core/structure.py, pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/boltztrap2.py, pymatgen/electronic_structure/cohp.py, pymatgen/electronic_structure/dos.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/tests/test_cif.py, pymatgen/phonon/bandstructure.py, pymatgen/phonon/dos.py, pymatgen/util/convergence.py, setup.py
Originally added in #3056 to fix CI.
=> Revert `mp-api<0.34.0` pin

pymatgen/core/structure.py, pymatgen/io/xyz.py, tests/io/test_xyz.py
428fa7a80 refactor class XYZ
a63aa2f23 cover edge cases in class XYZTest
=> Test `class XYZ` edge cases

.github/workflows/test.yml, docs/index.md, docs/team.md, pymatgen/core/molecular_orbitals.py, pymatgen/io/abinit/abiobjects.py
2f5896ab4 blacken-docs index.md
4b24b4641 /team page move world map below initial viewport since takes time to load
2d401d4f6 fix codecov: download coverage artifacts to .coverage where they'll be discovered
=> Fix codecov

pymatgen/core/structure.py, tests/core/test_structure.py
91e174654 add `Structure.elements` property (calling `Composition.elements`)
6ad901c8f add `TestIStructure.test_formula`
fdff89389 add `TestIStructure.test_elements`
=> Add `Structure.elements` property

pymatgen/core/structure.py, pyproject.toml, tests/core/test_structure.py
3c92cd50e add @abstractmethod `copy()` to `SiteCollection`
41e121471 add `in_place: bool = True` to `SiteCollection.replace_species` and return modified structure
5ddc5c4d1 `mypy` `disable_error_code = "annotation-unchecked"`
48fe06288 add `TestIStructure.test_replace_species()`
=> Add keyword `in_place: bool = True` to `SiteCollection.replace_species`

pymatgen/analysis/chemenv/utils/scripts_utils.py, tests/io/vasp/test_sets.py, tests/transformations/test_standard_transformations.py
f56656470 make `test_from_boundary_distance` more concise
eb5835b90 snake_case vars
=> More concise `test_from_boundary_distance` 

pymatgen/core/sites.py
Typo in Docs for PeriodicsSite
=> Typo in Docs for PeriodicsSite

pymatgen/alchemy/transmuters.py, pymatgen/analysis/elasticity/strain.py, pymatgen/electronic_structure/bandstructure.py, tests/core/test_lattice.py, tests/core/test_surface.py, tests/files/.pytest-split-durations, tests/io/exciting/test_inputs.py, tests/io/vasp/test_sets.py
Thanks @SophiaRuan for catching!
=> Fix `TestMPScanStaticSet.test_as_from_dict()`

pymatgen/core/structure.py, pymatgen/io/cif.py, tests/io/test_cif.py
=> Fix `CifParser.get_structures(check_occu=False)`

pymatgen/io/ase.py
There was a code comment I added in the ASE Atoms Adapter that was slightly inaccurate. This PR will just save future me a bit of headache by correcting it.
=> Fix code comment in ASE adapter

CHANGES.md, docs/CHANGES.md, docs/assets/metadata.yml, docs/team.md, pymatgen/io/ase.py
I changed my username and did a find-and-replace to update it where it's mentioned in Pymatgen.
=> Update @arosen93 to @Andrew-S-Rosen

pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py, pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py, pymatgen/analysis/chemenv/utils/func_utils.py, pymatgen/analysis/chemenv/utils/graph_utils.py, pymatgen/analysis/magnetism/heisenberg.py, pymatgen/analysis/pourbaix_diagram.py, pymatgen/core/operations.py, tests/core/test_operations.py
=> Fix copy-paste error making `MagSymmOp.as_xyzt_string` class method

README.md, docs/index.md
=> Readme notice regarding updated pymatgen publication

pymatgen/electronic_structure/plotter.py, pymatgen/phonon/plotter.py
=> Fix `AttributeError` in `BSPlotter.get_plot()`

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, pymatgen/analysis/structure_analyzer.py, pymatgen/core/lattice.py, pymatgen/io/abinit/abitimer.py, pymatgen/util/num.py, tests/util/test_num.py
=> Delete unused or numpy-provided routines from `pymatgen.util.num`

pymatgen/core/structure.py, pymatgen/io/vasp/inputs.py, tests/core/test_structure.py, tests/io/vasp/test_inputs.py
036770c99 improve StructureError msg on species/coord length mismatch
20c8b1693 fix TestPotcar.test_write polluting git repo on failure
=> Fix `TestPotcar.test_write` polluting git repo on failure

pymatgen/command_line/chargemol_caller.py, tests/command_line/test_chargemol_caller.py
b3708bc9c fix doc string indentation
c1aa37107 deduplicate which("chargemol")
dfd2a560b refactor "Multiple files detected" warning
8e0b09967 use single dict assert instead of individual key asserts
=> Chargemol minor refactor

.github/workflows/release.yml, pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/core/structure.py, tests/core/test_structure.py
0bf11ebc7 bump pypa/cibuildwheel to v2.16.2
b5e375814 add apply_strain() arg inplace: bool=True
1209f2a17 test struct.apply_strain(inplace=False)
=> Add `inplace: bool=True` arg to `Structure.apply_strain()`

pymatgen/analysis/chemenv/connectivity/connected_components.py, pymatgen/core/structure.py, tests/core/test_structure.py, tests/symmetry/test_analyzer.py
2c7b64198 add Structure.to_(conventional|primitive|cell) methods
c2534c92d core/test_structure.py add add test_to_primitive and test_to_conventional
=> Add `Structure.to_(conventional|primitive|cell)` methods

pymatgen/io/fiesta.py, tests/analysis/diffraction/test_tem.py, tests/io/test_fiesta.py
Bring API in `pymatgen/io/fiesta.py` in line with rest of `pymatgen`. It's a breaking change but straightforward to fix and presumably very limited number of users.
=> Breaking: snake_case `FiestaInput` keywords and class attributes

pymatgen/core/structure.py, tests/core/test_structure.py
=> Add `SiteCollection.to_ase_atoms()`

pymatgen/io/vasp/sets.py, tests/io/vasp/test_sets.py
Related PR https://github.com/materialsproject/atomate2/pull/561
=> Mirror atomate2 fix and improve `MPScanRelaxSet.test_kspacing` edge case coverage

pymatgen/analysis/cost.py, pymatgen/core/xcfunc.py, pymatgen/entries/entry_tools.py, pymatgen/io/abinit/abitimer.py, pymatgen/io/abinit/inputs.py, pymatgen/io/abinit/pseudos.py, pymatgen/io/cif.py, pymatgen/io/vasp/sets.py, pymatgen/util/provenance.py, tests/core/test_periodic_table.py, tests/core/test_structure.py, tests/core/test_trajectory.py, tests/electronic_structure/test_plotter.py, tests/entries/test_entry_tools.py, tests/io/feff/test_inputs.py, tests/io/feff/test_sets.py, tests/io/lobster/test_inputs.py, tests/io/qchem/test_sets.py, tests/io/test_shengbte.py, tests/io/vasp/test_outputs.py, tests/io/vasp/test_sets.py, tests/phonon/test_bandstructure.py, tests/phonon/test_ir_spectra.py
Also, fix `MPScanRelaxSet` not using `bandgap_tol` kwarg.
=> Write test-created files to temporary directory, don't pollute test dir

pymatgen/io/phonopy.py, pymatgen/phonon/plotter.py, tests/core/test_structure.py, tests/phonon/test_plotter.py
Thanks @JaGeo for noticing! 👍 Added better testing to make sure this won't regress in the future and clearer doc string to avoid confusion.
=> Fix legend label order in `PhononBSPlotter.plot_compare()`

pymatgen/electronic_structure/boltztrap.py, pymatgen/electronic_structure/dos.py, pymatgen/phonon/dos.py, pymatgen/util/coord.py, tests/electronic_structure/test_dos.py, tests/phonon/test_dos.py, tests/util/test_coord.py
4ee30c175 add PhononDos.r2_score method
50d7c2e63 add TestPhononDos.test_r2_score
547cb669e better get_linear_interpolated_value err msg
=> Add `PhononDos.r2_score` method

pymatgen/phonon/__init__.py, tests/phonon/test_init.py
42b658b97 add `pymatgen/phonon/__init__.py` convenience imports
4c651752d `test_convenience_imports()`
=> Phonon convenience imports

pymatgen/analysis/elasticity/elastic.py, tests/analysis/elasticity/test_elastic.py
Add diffusive thermal conductivity empirical model as proposed by [Agne et al.](https://pubs.rsc.org/en/content/articlelanding/2018/EE/C7EE03256K)
=> Add diffusive thermal conductivity model proposed by Agne et al.

pymatgen/analysis/local_env.py, pymatgen/analysis/structure_analyzer.py, pymatgen/command_line/gulp_caller.py, pymatgen/core/interface.py, pymatgen/core/structure.py, pymatgen/ext/cod.py, pymatgen/io/ase.py, pymatgen/io/cp2k/utils.py, pymatgen/io/jarvis.py, pymatgen/io/zeopp.py, pymatgen/symmetry/analyzer.py, pymatgen/transformations/standard_transformations.py, tests/analysis/test_local_env.py, tests/core/test_structure.py, tests/transformations/test_advanced_transformations.py
b06a0adbb return `self` in `SiteCollection.remove_oxidation_states()`
185711cd0 `test_remove_oxidation_states()` `assert struct_out is struct_specie`
=> Return `self` in `SiteCollection` spin/oxi state add/remove methods

pymatgen/electronic_structure/plotter.py, tests/electronic_structure/test_plotter.py
Closes #3647.
slightly improve `BSPlotterProjected` test coverage
=> Fix `BSPlotterProjected.get_projected_plots_dots_patom_pmorb` fix set & list intersect

pymatgen/entries/mixing_scheme.py
Reduce default verbosity for libraries dependent on pymatgen.
=> mixing scheme: change default for verbose

.github/workflows/test.yml, dev_scripts/update_pt_data.py, docs/apidoc/conf.py, pymatgen/analysis/magnetism/analyzer.py, pymatgen/analysis/phase_diagram.py, pymatgen/command_line/gulp_caller.py, pymatgen/core/periodic_table.py, pymatgen/core/trajectory.py, pymatgen/entries/computed_entries.py, pymatgen/io/abinit/pseudos.py, pymatgen/io/abinit/variable.py, pymatgen/io/ase.py, pymatgen/io/cif.py, pymatgen/io/lammps/inputs.py, pymatgen/io/nwchem.py, pymatgen/symmetry/analyzer.py, setup.py, tests/core/test_trajectory.py, tests/io/pwmat/test_inputs.py, tests/io/test_ase.py
addresses the underlying cause of why the issue reported by @kavanase in https://github.com/materialsproject/pymatgen/pull/3752#issuecomment-2142954988 was only caught after pypi release
=> Add CI run without `'optional'` deps installed

src/pymatgen/analysis/local_env.py
Added more documentation in response to #3888
=> Added Note about StructureGraph and lattice translations

pyproject.toml, src/pymatgen/symmetry/analyzer.py, src/pymatgen/symmetry/kpath.py, src/pymatgen/symmetry/maggroups.py, src/pymatgen/symmetry/structure.py, tests/analysis/test_local_env.py
=> Dedup `numpy`dependency in `pyproject`

src/pymatgen/transformations/advanced_transformations.py
Reverts materialsproject/pymatgen#3986
=> Revert "Minor change for step_size in CubicSupercellTransformation.apply_transformation "

pyproject.toml, src/pymatgen/analysis/chemenv/utils/scripts_utils.py, src/pymatgen/analysis/functional_groups.py, src/pymatgen/analysis/magnetism/heisenberg.py, src/pymatgen/analysis/phase_diagram.py, src/pymatgen/command_line/vampire_caller.py, src/pymatgen/core/lattice.py, src/pymatgen/core/structure.py, src/pymatgen/core/surface.py, src/pymatgen/electronic_structure/cohp.py, src/pymatgen/entries/mixing_scheme.py, src/pymatgen/io/cp2k/outputs.py, src/pymatgen/io/lammps/data.py, src/pymatgen/io/lammps/outputs.py, tests/analysis/test_adsorption.py, tests/analysis/test_interface_reactions.py, tests/io/vasp/test_sets.py
minor fix in `src/pymatgen/io/cp2k/outputs.py` `parse_energy_file`
=> Fix ruff PD901 and prefer `sum` over `len`+`if`

pyproject.toml, src/pymatgen/alchemy/filters.py, src/pymatgen/alchemy/materials.py, src/pymatgen/alchemy/transmuters.py, src/pymatgen/analysis/adsorption.py, src/pymatgen/analysis/bond_valence.py, src/pymatgen/analysis/chemenv/connectivity/connected_components.py, src/pymatgen/analysis/chemenv/coordination_environments/voronoi.py, src/pymatgen/analysis/interfaces/zsl.py, src/pymatgen/analysis/piezo_sensitivity.py, src/pymatgen/core/composition.py, src/pymatgen/ext/matproj_legacy.py, src/pymatgen/io/fiesta.py, src/pymatgen/io/icet.py, src/pymatgen/io/vasp/outputs.py, src/pymatgen/transformations/advanced_transformations.py
fix a dozen functions/methods that document return values but didn't actually return anything
=> Fix all `ruff` DOC202

src/pymatgen/analysis/solar/slme.py
This fixes some bugs in the `slme` code:
- Avoids overwriting the input data, which was leading to SLME results changing every time the function was (repeatedly) called.
- Removes some hard-coded settings for the plot and adds some labels
=> SLME Bug Fixes

src/pymatgen/io/vasp/inputs.py, tests/files/io/vasp/inputs/KPOINTS_gamma, tests/io/vasp/test_inputs.py
- Fix comment pass in `Kpoints` in auto/gamma/Monkhorst modes, to close #4130
=> Fix comment pass in `Kpoints` constructors 

src/pymatgen/apps/borg/hive.py, src/pymatgen/apps/borg/queen.py, src/pymatgen/io/gaussian.py, tests/apps/borg/test_hive.py
- Fix `borg.hive.SimpleVaspToComputedEntryDrone.assimilate` ValueError when core file missing, to fix #4132
- Add unit test
- Improve type annotation
=> Fix `borg.hive.SimpleVaspToComputedEntryDrone.assimilate` ValueError when core file missing

src/pymatgen/core/operations.py, src/pymatgen/io/cif.py, tests/io/test_cif.py
- Fix P1 SymmOp string for `CifParser.get_symops`, to close #4230
=> Fix P1 SymmOp string for `CifParser.get_symops`

src/pymatgen/analysis/eos.py, src/pymatgen/analysis/prototypes.py, src/pymatgen/core/structure.py, src/pymatgen/util/provenance.py, tests/analysis/test_prototypes.py
- Migrate some type annotation tweaks from #4100, make it easier to review
- Fix #4286
=> Migrate some type annotation tweaks from #4100
