materialsproject/pymatgen

pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py
As discussed in greater detail in #2330, this PR provides a new keyword option (`keep_site_properties`) in various `structure.symmetry.analyzer` functions to keep the site properties on the sites after a transformation. The docstring makes it clear that this may lead to undesirable side-effects as a result of the transformation, such as a loss of long-range magnetic ordering or antiferromagnetism.
=> Provide an option to keep site properties when calling spglib

README.rst
The CI status badge isn't loading on the README because the test workflow got renamed. This should fix it.
=> Fix CI status badge

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
- Addresses https://github.com/materialsproject/pymatgen/commit/9cfef441c16fd4c68290b80bb0383d52a0a8c0fe#r64164646 by reverting the type-check on the MAGMOM key-value pair.
=> Don't perform dict type-check on the MAGMOM flag in io.vasp.sets (fixes downstream Atomate issue)

pymatgen/io/ase.py, pymatgen/io/tests/test_ase.py
This hopefully should be my last update in my quest to enhance the `AseAtomsAdaptor`. 
In this PR:
1. Oxidation states are now passed from Pymatgen structure/molecule objects to ASE atoms objects. Since these aren't `site_properties`, they never got transferred. This is the main change.
2. Charges passed from Pymatgen to ASE now get assigned "intelligently" in the ASE Atoms object such that the ASE-recommended `atoms.get_charges()` function retrieves them.
3. Several new tests have been added to the test suite, most importantly a check that doing Atoms --> Structure --> Atoms as well as Structure --> Atoms --> Structure result in identical objects before/after the transformation cycle. This is an important check that was missing, as it's very easy for a property to be lost in the …
=> Pass oxidation states between Pymatgen structure/molecule and ASE Atoms

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
Override `Entry.__repr__` in `PDEntry` to include the `name` if its not the fallback value of reduced composition.
**Before**
```py
PDEntry("LiFeO2", 53, name="mp-757614")
>>> PDEntry : Li1 Fe1 O2 with energy = 53.0000
```
**After**
```py
PDEntry("LiFeO2", 53, name="mp-757614")
>>> PDEntry : Li1 Fe1 O2 (mp-757614) with energy = 53.0000
PDEntry("LiFeO2", 53)
>>> PDEntry : Li1 Fe1 O2 with energy = 53.0000
```
Added a test for both cases.
We could also do
```py
PDEntry mp-757614 : Li1 Fe1 O2 with energy = 53.0000
```
if preferred.
=> PDEntry.__repr__ include name attr if not fallback value

.pre-commit-config.yaml, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/entries/compatibility.py
`Compatibility.process_entry()` needlessly does its work twice to check if it got a result. More EAFP to use `try/except`.
=> Compat.process_entry

pymatgen/electronic_structure/dos.py, pymatgen/io/vasp/tests/test_outputs.py
Addresses #2408.
If a VASP calculation is carried out with ISPIN=1, the `Vasprun('vasprun.xml').complete_dos.spin_polarization` property throws a `KeyError`. This PR makes it so that `None` is returned instead.
The `.spin_polarization` property also had no tests. I added them.
=> Return None for complete_dos.spin_polarization if ISPIN=1

ADMIN.rst, CONTRIBUTING.rst, README.rst, docs_rst/compatibility.rst, docs_rst/contributing.rst, docs_rst/introduction.rst
Update readme and docs in all places stating `pymatgen` still supports py37.
=> Update docs to say min python is 3.8

setup.py
Move cython to `setup_requires`. Allows for availability to be checked before attempting to build native extensions. Avoiding #2426
your code to PEP8 conventions and removes most issues. Then run
[pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by
Note that the CI system will run …
=> Move cython to setup_requires

CITATION.cff, README.rst
GitHub supports adding citation metadata to repos. This PR moves instructions on how to cite `pymatgen` from readme into the `CITATION.cff` file which GH uses to then display citations in BibTeX and APA formats in the side bar.  See [docs for details](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).
Looks like this:
=> Add CITATION.cff

pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometry_finder.py, pymatgen/analysis/chemenv/utils/defs_utils.py
I am adding a small parameter to switch off the ChemEnv citation print. This will make it easier to use ChemEnv in other program packages. I am also updating the citation of ChemEnv.
I am tagging @davidwaroquiers  here, so that he knows.
Let me know if I should do anything additionally.
=> Allow to switch off print of ChemEnv citation

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
Only change appears to be that [runtime was updated from node v14 to v16](https://github.com/actions/checkout/releases/tag/v3.0.0).
=> Bump `actions/checkout` in GitHub CI to v3

pymatgen/io/abinit/abiobjects.py, pymatgen/symmetry/groups.py, test_files/Zr_Vasprun/test_Vasprun.py
Closes #2470.
@jacksund Sorry about that. But thanks for the detailed error report!
=> Fix circular import in `pymatgen.symmetry.groups`

pymatgen/apps/battery/battery_abc.py
Suspect some interaction with `dataclasses` and `pydantic` but root cause of bug is still unclear.
Notifying @munrojm (can you add some context to this PR in case it helps others?) and also notifying @janosh since it relates to whether we should have these imports everywhere by default or not.
=> Remove `from __future__ import annotations` in electrode base class due to bug

pymatgen/electronic_structure/boltztrap2.py, pymatgen/electronic_structure/plotter.py
I fix two bugs:
- the units of vbm and cbm in the BztInterpolator were wrong and leading to a wrong energy range.
- BSPlotter in case of metallic bands and zero_to_efermi=False was broken.
=> bug fix for bsplotter and bztInterpolator

pymatgen/electronic_structure/dos.py
Fixes a typo in the docstrings for the new `CompleteDos` properties I introduced in #2455.
=> Fix DOS docstring

pymatgen/electronic_structure/dos.py
Removed a redundant mathematical operation in the `CompleteDos` properties. The line `energies = dos.energies - dos.efermi` was included in two places. I deleted the second instance.
https://github.com/materialsproject/pymatgen/blob/040c45a68f7c787e062078aca28c3532c7c817e9/pymatgen/electronic_structure/dos.py#L860-L864
Apologies for not catching this during the previous docstring cleanup.
=> Remove redundant operation

pymatgen/analysis/structure_matcher.py
- Speed up `StructureMatcher.group_structures` by skipping redundant transformations on given structures.
`group_structures` calls `fit` or `fit_anonymous` to compare two structures in a given list. Every time `fit` or `fit_anonymous` are called, the structures are reduced by searching their primitive cell and performing Niggli reduction (if specified). However, these reductions can be skipped because we can perform the reductions on given structures at once. This PR introduces `skip_structure_reduction` flag to remove the duplicated reductions in `group_structures`.
I have confirmed the following test case with 16 structures is about 4x faster than before (0.2039 s -> 0.0593 s).
```python
import os
import json
from time import time
from pymatgen.analysis.structure_matcher import …
```
=> Speed up to group structures by equivalence

.pre-commit-config.yaml, docs_rst/contributing.rst
Improvement of settings for `pylint` in `.pre-commit-config.yaml`, continuation of https://github.com/materialsproject/pymatgen/pull/2492 (@janosh, thank you for telling me the snippet!)
- I have confirmed `pylint` is now automatically installed when pre-commit hooks are called.
- Adding instructions to set up optional dependencies in docs.
=> Improvement of pre-commit hook settings for `pylint` 

docs_rst/conf-normal.py, docs_rst/conf.py, pymatgen/analysis/elasticity/tests/test_elastic.py, pymatgen/analysis/tests/test_path_finder.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/ext/tests/test_cod.py, pymatgen/ext/tests/test_crystalsai.py, pymatgen/ext/tests/test_jhu.py, pymatgen/ext/tests/test_matproj.py, pymatgen/ext/tests/test_optimade.py, pymatgen/io/cp2k/tests/test_sets.py, pymatgen/io/lobster/tests/test_lobster.py, pymatgen/io/lobster/tests/test_lobsterenv.py, pymatgen/io/qchem/tests/test_inputs.py, pymatgen/symmetry/tests/test_groups.py, pymatgen/symmetry/tests/test_kpath_lm.py, pymatgen/symmetry/tests/test_kpath_sc.py
Boring part of this PR: Fix some flake8 violations.
Worth reviewing are changes to
- `PathFinderTest.test_image_num()`
- dulong-petit test case in `ElasticTensorExpansionTest.test_thermal_expansion_coeff()`
=> Clean up tests

pymatgen/io/core.py, pymatgen/io/tests/test_core.py
* Added functionality to write the __str__ contents of an object in the contents of one of the InputSet's files, if this object is not an instance (subclass) of InputFile.
* Added unit tests for InputFile and InputSet.
* Fixed MSONable for InputSet when kwargs are given.
None
=> Fixed MSONable + InputSet's str(object)

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
JSON reconstruction bug:
The problem is: Because MSONables from_dict was replaced, there is no recursive reconstruction of the objects when you hit `el_ref` .  When you do `as_dict` -> `from_dict`  in python everything looks fine.
but the object was never completely serialized.
If you completely serialized it like putting it into as json file or database then you cannot reconstruct the phase diagram.
=> fixed deserialization of phase diagrams

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

pymatgen/apps/battery/plotter.py
Change VoltageProfilePlotter.get_plotly_figure() so connecting vertical lines are not drawn in voltage profile. These vertical lines are misleading for interpreting voltage profile plots. 
@mkhorton this change was discussed with Kristin at the Jun 13 meeting on the current state of the battery code infrastructure. Please let me know if any revisions are needed but otherwise I think this PR is ready to merge.
=> Remove vertical lines from VoltageProfilePlotter.get_plotly_figure()

pymatgen/symmetry/analyzer.py
Just a small fix for some recently added docstrings.
=> Fix typos in pymatgen.symmetry.analyzer docstrings

pymatgen/core/periodic_table.py, pymatgen/core/tests/test_periodic_table.py
Adds an `Element.from_name` convenience function to make it possible to init an `Element` from its long name, in addition to existing methods based on symbol (default), atomic number (`Element.from_Z`), or row and group (`Element.from_row_and_group``)
```
>>> Element.from_name('Sodium')
Element Na
```
=> Element: add from_name()

pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometry_finder.py, pymatgen/analysis/chemenv/coordination_environments/voronoi.py
This pull-request allows to change the voronoi_distance cutoff in ChemEnv. Otherwise, molecules in too large boxes cannot be investigated. I have added a test and a warning for users in case the cutoff is too small. (Issue found by @rlaplaza)
=> allow to change voronoi_distance_cutoff in ChemEnv

pymatgen/core/ion.py, pymatgen/core/tests/test_ion.py
`Ion.oxi_state_guesses()`  currently inherits from `Composition`, and generally fails to provide useful information unless the user specifies the `target_charge` (which is an optional kwarg):
```
>>> i=Ion.from_formula('SO4-2')
>>> i.oxi_state_guesses()
[]
```
This PR overloads the parent method such that `target_charge` is always set equal to the net charge on the `Ion` object. All other kwargs are passed to the parent method.
```
>>> i=Ion.from_formula('SO4-2')
>>> i.oxi_state_guesses()
({'S': 6.0, 'O': -2.0},)
```
Other minor changes to `test_ion.py` were made to satisfy the `pylint` pre-commit hooks
=> Ion: pass charge to oxi_state_guesses

pymatgen/symmetry/bandstructure.py
Tidies up and makes messages/warnings/errors/descriptions clearer and more consistent
Incorrect use of "respectively" fixed
Made terminology and formatting consistent (e.g., k-path vs kpath)
It's conventional (ha-ha!) to abbreviate "Latimer and Munro convention" to "Latimer-Munro convention", and so on
Meaning of "author-intended" unclear, so details added
=> Improve messages and warnings

pymatgen/io/core.py, pymatgen/io/tests/test_core.py
This pull request fixes two items in `InputSet`:
1. `__iter__` was previously iterating an iterator over `self.inputs.items()` rather than `self.inputs`. This was not a correct implementation (see example for implementing a `dict`-like class from `MutableMapping` [here](https://stackoverflow.com/questions/21361106/how-would-i-implement-a-dict-with-abstract-base-classes-in-python)) and prevented `__eq__` from working properly
2. After fixing item 1), I realized that the built-in `__eq__` method was only comparing the `inputs` and not the kwargs. Therefore, I added a custom `__eq__` method to ensure that `InputSet` are considered equal only if both the `inputs` and all kwargs are equal.
Note that a small change in some of the pre-existing tests was required due to the changed behavior of …
=> InputSet: implement equality method and fix __iter__

pymatgen/io/vasp/outputs.py
- Do not report not converted warnings on MD runs.
=> Remove not converted warning for MD run

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
The current value of the parsed charge for Vasprun.structure is more positive if NELECT is higher.
If we used the electron -> negative charge convention then this expression should have the other sign
=> changed charge convention

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
The current code does not decorate the initial and final structures in `Vasprun` with the charge.  This affects Atomate2 
https://github.com/materialsproject/atomate2/issues/154
=> Apply the structure charge to initial and final structure

pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/chemenv/utils/defs_utils.py, pymatgen/analysis/chempot_diagram.py, pymatgen/analysis/functional_groups.py, pymatgen/analysis/interface_reactions.py, pymatgen/analysis/nmr.py, pymatgen/analysis/surface_analysis.py, pymatgen/analysis/xps.py, pymatgen/command_line/critic2_caller.py, pymatgen/core/surface.py, pymatgen/electronic_structure/boltztrap.py, pymatgen/entries/compatibility.py, pymatgen/ext/cod.py, pymatgen/ext/matproj.py, pymatgen/io/vasp/sets.py, pymatgen/symmetry/kpath.py, pymatgen/symmetry/settings.py
Also replaces unicode character U+2013 "–" with regular minus sign U+002d "-" as the latter is more commonly used in source code.
=> Brillouin sone -> Brillouin zone

pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py
In physical simulations it is often desirable to make use of the lattice symmetries to save computational time. The 'get_ir_reciprocal_mesh' function (which is basically an interface to spglib) returns an irreducible mesh and the weight, which just tells how many other kpoints a given irreducible kpoint is mapped to. 
This function does the same, but instead of returning the irreducible kpoints and their weights it returns the full grid and the mapping that is used to generate the irreducible grid. This is useful if physical objects are calculated that do not include a summation over all kpoints, because in that case the weight of an irreducible kpoint is not enough and the mapping is needed to relate any kpoint to the irreducible mesh. 
It would be nice if that function could also return …
=> Added 'get_ir_reciprocal_mesh_map'-method

pymatgen/core/structure.py
Ran into an obscure bug where `other` was a length-18 string and `self` was a structure with 18 atoms
* Check that the structure being compared against has a lattice parameter before trying to access the lattice parameter.
* None
None
- [ X] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). The easiest way to handle this
your code to PEP8 …
=> Structure __eq__ bugfix

pymatgen/symmetry/structure.py
This should fix the underlying serialization bug related to this PR:
https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion/pull/264
I think the other PR 
https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion/pull/312
still fails if `symm_structure` is provided due to this bug.
=> fixed serialization bug

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
The previous absorption coefficient lack a 2*pi constant. It is corrected in this PR and the results compare well with experiments.
=> Update absorption coefficient

pymatgen/core/periodic_table.py
The electron affinity description is  duplicate with ionization energy. Updated the definition according to wiki (https://en.wikipedia.org/wiki/Electron_affinity).
=> Correct doc description of electron affinity

pymatgen/transformations/advanced_transformations.py, pymatgen/transformations/tests/test_advanced_transformations.py
I have added an additional option to the CubicSupercellTransformation to only return cells with three 90 degree angles. I think this might be useful for tasks where supercells are required.
I have also added two test cases and documentation.
=> Add option for 90 degree "cubic" supercells

docs_rst/addons.rst
The link in the docs was mistakenly interpreted as relative inside the pymatgen documentation. Also added `rel/`, which will always point to the documentation for the latest version of the code
=> Correct link to Fleur website in addon entry for `pymatgen-io-fleur`

pymatgen/ext/matproj.py, pymatgen/ext/tests/test_matproj.py
=> Fix `MPRester.get_entry_by_material_id()` for missing ID

pymatgen/analysis/structure_matcher.py, pymatgen/core/tests/test_bonds.py, pymatgen/core/tests/test_composition.py, pymatgen/core/tests/test_ion.py, pymatgen/core/tests/test_lattice.py, pymatgen/core/tests/test_molecular_orbitals.py, pymatgen/core/tests/test_operations.py, pymatgen/core/tests/test_periodic_table.py, pymatgen/core/tests/test_sites.py, pymatgen/core/tests/test_spectrum.py, pymatgen/core/tests/test_structure.py, pymatgen/core/tests/test_surface.py, pymatgen/core/tests/test_tensors.py, pymatgen/core/tests/test_trajectory.py, pymatgen/core/tests/test_units.py, pymatgen/entries/tests/test_mixing_scheme.py, pymatgen/util/coord.py, pymatgen/util/testing.py, setup.cfg
@shyuep What's your stance on converting `pymatgen` tests from `unittest` to `pytest`?
I find `pytest`'s functional style to be more concise and easier to read than `unittest`.
=> unittest2pytest pymatgen/core/tests --write --nobackups

pymatgen/symmetry/groups.py, pymatgen/symmetry/tests/test_groups.py
I added a method to the SpaceGroup class that returns both the orbit (like the 'get_orbit'-method does) as well as the symmetry operations that generate it. As opposed to 'get_orbit' the method makes sure that the first element of the orbit is the point that has been passed to the function. Therefore the first element in the list of generators that are returned is always the identity operation. 
A test making sure that this is always true has been implemented. 
The above functionality is useful if a physical property (e.g. angular momentum) that needs to obey the crystal symmetry is assigned to a given site. The user can then generate the corresponding  properties of the other sites of the orbit by using the generators of the orbit. 
It would be probably nice to implement this for …
=> Added 'get_orbit_and_generators'-method to SpaceGroup to class.

pymatgen/electronic_structure/dos.py
I changed
```python
from scipy.ndimage.filters import gaussian_filter1d
```
to
```python
from scipy.ndimage import gaussian_filter1d
```
in `pymatgen.electronic_structure.dos` since the former is deprecated.
=> Fix deprecation warning on scipy gaussian_filter1d function

pymatgen/util/coord.py
Fixes #2632 
Importing pbc_diff directly fails due to a circular import. This doesn't seem to impact the code or tests since other modules are imported first. E.g. running the following works fine:
```python
from pymatgen.core import Composition
from pymatgen.util.coord import pbc_diff
```
The issue arrises because the `pymatgen.util.coord` module imports `ArrayLike` from `pymatgen.util.typing` for type hinting. This module in turn imports `Composition` which then tries to import `pbc_shortest_vectors` thus creating the circular import.
This PR avoids the issue by using postponed annotations and the `TYPE_CHECKING` constant. See: https://peps.python.org/pep-0563/
Unfortunately, I can't add a test as the bug is very specific to the order imports occur which is outside the control of a …
=> Fix circular import

pymatgen/io/lobster/lobsterenv.py, pymatgen/io/lobster/tests/test_lobsterenv.py
Minor addition to Lobster graph edge properties
* Store ICOHPlist bond key in graph edge properties. Helps in getting further information from 'Lobsterpy' package
=> store bond keys of ICOHP in graph edge prop

docs_rst/addons.rst
Descriptions of the external tools got mixed up. Switched the LobsterPy and the QuAcc description.
=> Fix descriptions in external tools

.github/workflows/test-linux.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
While parsing a large OUTCAR file coming from an MD simulation I realized that a lot of time was taken by the `read_table_pattern` to extract the number of plane waves for kpoints. The quantitiy appears early in the file, but for very long simulations the execution of the regex on the rest of the file can be very slow and pointless. 
I added the option to stop the parsing of the table patterns at the first occurence and used it for the case of the plane waves.
=> improve outcar parsing

.gitattributes, pymatgen/optimization/neighbors.pyx
The paths in `.gitattributes` work the same as in `.gitignore`. So to exclude HTML, rST and test files from the GitHub language calculation, were currently missing a few wildcards to include more deeply nested files.
This change should turn the language composition bar into almost pure Python (once GH had time to recompute).
Related https://github.com/materialsproject/atomate2/pull/148.
=> Fix GitHub language calculation

.gitattributes, pymatgen/analysis/path_finder.py, pymatgen/cli/pmg_analyze.py, pymatgen/electronic_structure/boltztrap2.py, pymatgen/entries/mixing_scheme.py, pymatgen/symmetry/bandstructure.py, pymatgen/symmetry/tests/test_groups.py
I missed a few large HTML and test files in #2651:
```txt
dev_scripts/NIST Atomic Ionization Energies Output.html
test_files/cohp/bandOverlaps.lobster.1
test_files/cohp/bandOverlaps.lobster.2
test_files/cohp/bandOverlaps.lobster.new.1
test_files/cohp/bandOverlaps.lobster.new.2
test_files/cohp/lobsterin.1
test_files/cohp/lobsterin.2
test_files/cohp/lobsterin.3
```
Yet more wildcards in `.gitattributes` to the rescue.
One interesting thing I learned it that linguist overrides do not change how files are treated when performing a repo search for a specific language. E.g. using language qualifier `l=roff` will still return those files in the search results, even though they are treated as vendored by linguist.
=> Fix GitHub language statistics - take 2

pymatgen/ext/matproj.py
=> Always use _MPResterLegacy  if len(api_key) != 32

pymatgen/io/core.py, pymatgen/io/tests/test_core.py
Remove the `__eq__` method from `InputSet`, per discussion in #2665 (and will replace that PR).
Flagging @utf in case this change will affect development of VASP `InputSet` in `atomate2`.
=> InputSet: remove __eq__ method

pymatgen/io/cif.py, pymatgen/phonon/tests/test_thermal_displacements.py, pymatgen/phonon/thermal_displacements.py
I have extended the ThermalDisplacementMatrices class. It can now also read cif files in P1 format, produce structures including Ucif as site_property (handy for sorting structures and thermal displacement properties, for example), and print VESTA files in P1 space group including vectors indicating the directionality of two different sets of computed displacement parameters.
While doing so, I have refactored the classes parsing the cif files a tiny bit. In general, I found it very hard to reuse any of the code in there as this warning state of the class would require me to make instances of classes. While I understand the purpose of saving the warnings like this, it has this drawback. Otherwise, most of the methods in there could be static methods.
=> Extension ThermalDisplacementMatrices class

pymatgen/analysis/phase_diagram.py
Occurs when importing `from pymatgen.ext.matproj import MPRester` in Jupyter.
Rest of warning: `pymatgen/analysis/phase_diagram.py:26`: Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console).
=> Fix `TqdmExperimentalWarning`: Using `tqdm.autonotebook.tqdm` in notebook mode

.github/workflows/test-linux.yml, .github/workflows/test-mac.yml, .github/workflows/test-win.yml, pymatgen/core/trajectory.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/lammps/outputs.py
The most important Python version to run CI is the lowest supported (currently 3.8). Running in higher versions means we won't catch some SyntaxErrors e.g. from modern type annotations like `lst: list[int] = [1, 2, 3]` (which [I think was the reason](https://github.com/materialsproject/pymatgen/runs/8157637404?check_suite_focus=true) for bumping to 3.10?). Such errors would now pop up at runtime for people below Python 3.10.
If we want to test later Python versions too (e.g. due to upcoming 3.11 release), we should setup a matrix strategy.
=> Run CI in lowest supported Python version

pymatgen/phonon/plotter.py, pymatgen/phonon/tests/test_plotter.py
A method that allows users to plot the atom-resolved phonon band structures. The contribution from each type (or group) of atoms is calculated based on the magnitude of the eigendisplacements.  Support 2 (rb), 3 (rgb) and 4 (cmyk) unique groups of atoms.
So far I just used the existing NaCl example for testing, let me know if more cases are needed!
matplotlib.pyplot.plt —> essential for the colored plot
matplotlib.collections.LineCollection —> essential for the colored plot
pymatgen.electronic_structure.plotter.BSDOSPlotter —> For creating the color line and color triangle
1. Make a color legend for the 4-color case.
2. Allow projecting band based on eigenvectors instead of eigendisplacement?
I would appreciate any suggestions from you! Thanks.
=> Added get_proj_plot() method in phonon.plotter.PhononBSPlotter class

pymatgen/io/vasp/optics.py
Serialization of complex ndarray is not supported by MSONable.
So any large object with complex numbers that need to be serialized should have the real and imaginary part split into two different arrays.
=> Split CDER to real and imag parts

.github/workflows/lint.yml, .github/workflows/test-linux.yml, metadata.yml, pymatgen/alchemy/tests/test_filters.py, pymatgen/alchemy/tests/test_materials.py, pymatgen/alchemy/tests/test_transmuters.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_chemenv_strategies.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometries.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometry_finder.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_read_write.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_structure_environments.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_voronoi.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_weights.py, pymatgen/analysis/chemenv/utils/tests/test_chemenv_config.py, pymatgen/analysis/chemenv/utils/tests/test_coordination_geometry_utils.py, pymatgen/analysis/chemenv/utils/tests/test_func_utils.py, pymatgen/analysis/chemenv/utils/tests/test_graph_utils.py, pymatgen/analysis/chemenv/utils/tests/test_math_utils.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/entries/tests/test_compatibility.py, pymatgen/entries/tests/test_computed_entries.py, pymatgen/entries/tests/test_correction_calculator.py, pymatgen/entries/tests/test_entry_tools.py, pymatgen/entries/tests/test_exp_entries.py, setup.cfg
The `text-linux` and `lint` CI workflows currently run twice for every PR due to being triggered both by push and PR to _any_ branch:
```yml
name: Testing Linux
on: [push, pull_request]
```
We can run only once, thereby saving time, CI budget and energy (esp. with `test-linux` which takes long), by triggering only on push/PR to `master`:
```yml
on:
push:
branches: [master]
pull_request:
branches: [master]
```
=> No double CI runs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, pymatgen/analysis/phase_diagram.py, pymatgen/apps/battery/tests/test_insertion_battery.py, pymatgen/core/tests/test_structure.py, pymatgen/core/tests/test_trajectory.py, pymatgen/ext/tests/test_cod.py, pymatgen/ext/tests/test_matproj.py, pymatgen/ext/tests/test_optimade.py, pymatgen/symmetry/tests/test_groups.py, pymatgen/symmetry/tests/test_kpath_hin.py, pymatgen/symmetry/tests/test_kpath_lm.py, pymatgen/symmetry/tests/test_kpath_sc.py, pymatgen/symmetry/tests/test_kpaths.py, pymatgen/symmetry/tests/test_maggroups.py, pymatgen/symmetry/tests/test_settings.py, pymatgen/symmetry/tests/test_site_symmetries.py, pymatgen/util/num.py, pymatgen/util/tests/test_typing.py, pymatgen/util/typing.py
```py
if TYPE_CHECKING:  # needed to avoid circular imports
from pymatgen.analysis.phase_diagram import PDEntry
from pymatgen.entries import Entry
from pymatgen.entries.computed_entries import ComputedEntry, ComputedStructureEntry
EntryLike = Union[Dict[str, Any], Entry, PDEntry, ComputedEntry, ComputedStructureEntry]
```
=> Define `EntryLike` in `pymatgen/util/typing.py`

pymatgen/cli/pmg_config.py, pymatgen/core/__init__.py, pymatgen/io/vasp/inputs.py
@shyuep @mkhorton `_load_pmg_settings()` currently reads env vars first and then overrides them with `.pmgrc.yaml`. It's usually the other way around.
This gives users no way to override on a case by case basis. E.g.
```sh
PMG_MAPI_KEY=xxxxxxxxxxxxxxxx python -c 'from pymatgen.ext.matproj import MPRester; MPRester().query("mp-1234", ["formula"])'
```
will be identical to
```py
python -c 'from pymatgen.ext.matproj import MPRester; MPRester().query("mp-1234", ["formula"])'
```
Following [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), I think we should swap this around and let env vars override `.pmgrc.yaml`.
=> Let env vars override `.pmgrc.yaml` in `_load_pmg_settings()` and make `~/.config` new default location for `.pmgrc.yaml`

pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/tests/test_inputs.py
First of all, thank you so much for the development of pymatgen!
Due to the missing regex option of `(?s)` (https://docs.python.org/3/library/re.html#re.S, which makes the `.` special character match any character at all, including a newline), "Atomic configuration" in POTCAR (52 and 54) was actually not parsed. I think this part is sometimes useful for, e.g., estimating a reasonable NBANDS value. My pull request fixes the issue above. In more detail:
- `re.search` for this is slightly simplified.
- The change above adds "nentries" and "Orbitals" to PSCTR. In `get_potcar_hash`, these two keys are excluded to keep the same hash values as before.
- A new test `test_psctr` is added to check if the parsing is done correctly.
=> Fix parsing of "Atomic configuration" in POTCAR

pymatgen/entries/compatibility.py, tasks.py
Following discussion initiated by @sgbaird and @mkhorton in https://github.com/materialsproject/pymatgen/pull/2708#issuecomment-1292477362.
@shyuep I'm not familiar with `invoke`. The function I added `check_egg_sources_txt_for_completeness()` is not `@task` decorated. it's simply called by the `release` task. Every other function in `tasks.py` seems to be. Is that a requirement?
=> Add `check_egg_sources_txt_for_completeness()` to `tasks.py`

pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, pymatgen/io/tests/test_packmol.py, pymatgen/util/provenance.py
@shyuep @mkhorton It's a breaking change but was wondering if we could swap the order of kwargs `fmt` and `filename` in `Structure.to()`.
https://github.com/materialsproject/pymatgen/blob/25768faa7aa0a34ee4357a92bc92ae41ef21bc1d/pymatgen/core/structure.py#L2421-L2427
The annoying thing about having `fmt` first is that the most common use case (imo writing to file) of `to()` raises an error:
```py
from pymatgen.core import Lattice, Structure
structure = Structure(
lattice=Lattice.cubic(5),
species=("Fe", "O"),
coords=((0, 0, 0), (0.5, 0.5, 0.5)),
)
struct.to("struct.json")
>>> ValueError: Invalid format: `struct.json`
```
I did a quick look through the code base and didn't find any cases where `fmt` was passed as positional arg so don't think this would break much.
```py
struct.to("json") …
```
=> Breaking: swap `fmt` and `filename` in `Structure.to()`

.github/workflows/release.yml, README.rst
The changes in c2124293 broke `.github/workflows/release.yml` causing
> Error: No file in /Users/runner/work/pymatgen/pymatgen matched to [**/requirements.txt], make sure you have checked out the target repository
=> Fix release workflow

pymatgen/core/tensors.py, pymatgen/core/tests/test_tensors.py
A recent change (1bdd1b7c6f5b12079c48cc06a6e6443bec070ed3) broke tensor mapping by making the default tensor and value lists immutable tuples. Tests didn't catch this because there was no tests for creating a tensor mapping starting from an empty mapping.
This PR fixes the bug and adds a new test. If possible, please could you release a new version with this bug fix as currently atomate, atomate2, amset, and other packages are broken.
=> Fix tensor mapping

.pre-commit-config.yaml, pymatgen/io/lobster/inputs.py, pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py, setup.py, test_files/Co8.cif
Closes #2723.
Maybe there's a smarter fix than fb2fc72f09bbccba12cc4d6b1d47d146840a62e4? Just returning two empty tuples for rotations and translations from `SpacegroupAnalyzer._get_symmetry()` if `spglib.get_symmetry()` returned `None` for now.
=> Fix TypeError in SpacegroupAnalyzer.get_symmetrized_structure() if spglib returns no symmetries

.pre-commit-config.yaml, pymatgen/io/lobster/inputs.py, pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/sets.py, pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py, setup.py, test_files/Co8.cif
This pr deals with the failure of writing .cif format structures by VaspInputSet. I encountered an error of `'PosixPath' object has no attribute 'lower'` when using the `write_input` method with `include_cif=True`. After casting the PosixPath to str, this problem is solved.
=> VaspInputSet couldn't write cif structures

pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py
Do not introduce zero `magmoms` in `SpacegroupAnalyzer` following changes in spglib >= 2. See #2725 
- With this change, the exception tested in the unit test added in #2724 is not raised.
Note that the CI system will run all the above checks. But it will be much more efficient if you already fix most
errors prior to submitting the PR. We highly recommended installing `pre-commit` hooks. Simply `pip install -U pre-commit && pre-commit install` in the repo's root directory. Afterwards linters will run before every commit and abort if any issues …
=> Do not introduce zero magmoms in SpacegroupAnalyzer

pymatgen/analysis/chemenv/connectivity/connected_components.py, pymatgen/analysis/diffraction/core.py, pymatgen/analysis/structure_analyzer.py, pymatgen/core/trajectory.py, pymatgen/entries/compatibility.py, pymatgen/io/vasp/inputs.py, pymatgen/symmetry/tests/test_maggroups.py
Closes #2730.
Relevant commit in this PR is d1f6f9277dab6cabf6340eab5d5cb653fe43abe6.
=> Document rare structure dependence of MaterialsProjectCompatibility corrections

pymatgen/electronic_structure/cohp.py, pymatgen/io/lobster/outputs.py, pymatgen/io/lobster/tests/test_lobster.py
The value returned by extremum_icohpvalue() method from `Icohplist.icohpcollection` instance was wrong for ICOBILIST.lobster file.
- Fixed the above stated issue
- Updated the tests to ensure these values are returned correctly
=> Fix extremum_icohpvalue() for  ICOBILIST.lobster files

.github/workflows/test.yml
Use [`build`](https://github.com/pypa/build) to release wheels.
I notice the current workflow to use `python setup.py sdist bdist_wheel` to build wheels, which will not follow `build-system` in `pyproject.toml`. I recommend the official PEP-517 build frontend, [`build`](https://github.com/pypa/build). The dependencies are not required to be manually installed any more.
build documentation: https://pypa-build.readthedocs.io/en/stable/index.html
=> use `build` to build packages

pymatgen/io/lobster/outputs.py, pymatgen/io/lobster/tests/test_lobster.py
There was typo in document generated. Thus fixed  those
=> Fix lobsterout.get_doc() typo

pymatgen/analysis/path_finder.py
=> Fix loose endpoints in `NEBPathfinder.string_relax()`

pymatgen/io/lobster/inputs.py
Added new parameter tag for writing orthonormalized DOSCAR
- Added this keyword
=> Added missing keyword from LOBSTER 4.1 to lobsterin generation class

pymatgen/io/vasp/inputs.py
Fix typo in documentation of default significant digits for Poscar get_string method
=> Fix typo in Poscar get_string

pymatgen/analysis/phase_diagram.py
- Fix cbar label position
- Update label (colours were only valid for the default colormap)
before and after:
=> Colorbar label for PDPlotter

pymatgen/analysis/structure_matcher.py, pymatgen/io/lobster/lobsterenv.py, pymatgen/util/coord_cython.pyx
`coord_list_mapping_pbc()` in `pymatgen/util/coord_cython.pyx` raises
```py
AttributeError: module 'numpy' has no attribute 'int'
```
https://github.com/materialsproject/pymatgen/blob/d947703cbacd78c8f9bdab7c97b2bb131758c795/pymatgen/util/coord_cython.pyx#L254
=> Fix `coord_list_mapping_pbc()`

pymatgen/analysis/chemenv/coordination_environments/structure_environments.py, pymatgen/core/composition.py
As discussed in https://github.com/materialsproject/pymatgen/issues/2788, one way of fixing the ChemEnv error in the tests would be converting the PeriodicNeighbor object in a PeriodicSite object. I have implemented this. It might however affect the execution speed.
If someone else, manages to fix the as_dict from PeriodicNeighbor in a cheaper way, I would prefer this, of course.
=> One attempt to fix ChemEnv error in tests

pymatgen/analysis/diffraction/tem.py, pymatgen/analysis/dimensionality.py, pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/elasticity/strain.py, pymatgen/analysis/functional_groups.py, pymatgen/analysis/gb/grain.py, pymatgen/analysis/graphs.py, pymatgen/analysis/interface_reactions.py, pymatgen/analysis/local_env.py, pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_functional_groups.py, pymatgen/analysis/tests/test_wulff.py, pymatgen/apps/battery/analyzer.py, pymatgen/core/composition.py, pymatgen/core/structure.py, pymatgen/electronic_structure/boltztrap.py, pymatgen/entries/correction_calculator.py, pymatgen/ext/optimade.py, pymatgen/io/abinit/abitimer.py, pymatgen/io/lammps/utils.py, pymatgen/io/lobster/lobsterenv.py, pymatgen/io/phonopy.py, pymatgen/io/vasp/outputs.py, pymatgen/symmetry/bandstructure.py, pymatgen/symmetry/kpath.py, pymatgen/util/coord.py, pymatgen/util/plotting.py
b3bbaf04f5 replace set methods `(union|intersection|difference)` with arithmetic operators
5f8a9fc3d2 standardize type names in doc strings: `string`->`str`, `integer`->`int`, etc.
6f99428d65 fix `Molecule.insert()` doesn't return what the doc str says
=> Fix `Molecule.insert()`

pymatgen/core/structure.py
AFAIK, a site.species in Structure can be either an Element or a Species obj.
The Element obj does not have an "oxi_state" attribute and the current function handle
this case setting the oxi_state value to zero. 
But it fails when a site.species is a Species obj with an oxi_state set to None.
This is the case when a spin is added to a structure (via e.g. add_spin_by_site()) or
when using the MagOrderingTransformation .
The edit to the function proposed here handles this case and should solve the issue #2673
=> Fixed charge function for Structure obj (also fix for #2673)

dev_scripts/chemenv/get_plane_permutations_optimized.py, dev_scripts/chemenv/test_algos.py, pymatgen/analysis/chemenv/connectivity/connected_components.py, pymatgen/analysis/chemenv/connectivity/connectivity_finder.py, pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py, pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py, pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/chemenv/coordination_environments/structure_environments.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometries.py, pymatgen/analysis/chemenv/coordination_environments/tests/test_weights.py, pymatgen/analysis/chemenv/coordination_environments/voronoi.py, pymatgen/analysis/chemenv/utils/chemenv_config.py, pymatgen/analysis/chemenv/utils/func_utils.py, pymatgen/analysis/eos.py, pymatgen/analysis/local_env.py, pymatgen/analysis/phase_diagram.py, pymatgen/electronic_structure/boltztrap.py, pymatgen/electronic_structure/plotter.py, pymatgen/ext/optimade.py, pymatgen/io/core.py, pymatgen/io/cp2k/utils.py, pymatgen/io/nwchem.py, pymatgen/io/packmol.py, pymatgen/io/pwscf.py, pymatgen/io/shengbte.py, pymatgen/transformations/advanced_transformations.py, setup.cfg, tasks.py
https://github.com/PyCQA/flake8-bugbear/releases/tag/23.1.14
=> Unignore flake8 B028 and fix occurrences

pymatgen/electronic_structure/dos.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/tests/test_outputs.py
Currently the Density of states data is extensive (at lease when you use `Vasprun.complete_dos`).
This proposed change allow you to use call `Vasprun.complete_dos_normalized` to get the density of states in units of states $/ \text{eV} / \mathbb A^3$
=> Normalized DOS

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
When I try to plot a pre-computed phase diagrams that are retrieved via get_phase_diagram_from_chemsys() method,
> phaseDiagram = mpr.get_phase_diagram_from_chemsys('Li-Fe-O')
> plotter = PDPlotter(phaseDiagram)
a KeyError raises as shown below, which arises from the inconsistence on object stored in el_refs dictionary, i.e., the keys stored in phaseDiagram.el_refs are **str** object (_dict_keys(['O', 'Fe', 'Li'])_), instead of the **Element** object (_dict_keys([Element O, Element Fe, Element Li])_).
The pre-computed phase diagrams in database might not be updated conveniently. So, I add some codes in pymatgen.analysis.phase_diagram.PhaseDiagram class, to update keys in elemental reference dictionary to Element object, in case it loads a pre-computed phase diagram. A corresponding test …
=> KeyError of Elemental references in pre-computed phase diagram

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
I committed some codes to raise a specific ValueError exception and hint a specific reason message for the attempt to build a phase diagram with no entries. A corresponding unittest was also added.
Scenario:
In the cases that there are not enough entries to form a complete phase diagram, the processing operation of the mixing scheme would fail and might return an empty list, i.e., entryList = []. That would cause an error in PhaseDiagram class when computing data, as shown below. To raise a specific exception is necessary.
Run:
> entryList = MaterialsProjectDFTMixingScheme().process_entries(entryList, clean=True)
> phase_diagram = PhaseDiagram(entryList)
Errors:
>Generating mixing state data from provided entries.
D:\Anaconda\envs\pymatgen2023\Lib\site-packages\pymatgen\entries\mixing_sche …
=> Raise ValueError when trying to create PhaseDiagram without entries

pymatgen/analysis/diffraction/tem.py, pymatgen/analysis/disorder.py, pymatgen/analysis/phase_diagram.py, pymatgen/analysis/structure_prediction/tests/test_substitution_probability.py, pymatgen/analysis/surface_analysis.py, pymatgen/apps/battery/battery_abc.py, pymatgen/apps/battery/conversion_battery.py, pymatgen/io/cp2k/outputs.py, pymatgen/io/vasp/inputs.py
`get_element_profile` fix:
The entries returned is given as `dict_keys` but that's rarely what people want.
- Return a list of entries instead.
- Also return the critical composition, which is usually useful information.
electrode fixes:
- Linting on some docs
- require framework formula for the `from_steps` constructor.
=> Minor fix to `get_element_profile`

pymatgen/ext/optimade.py
Currently `OptimadeRester` defaults to an outdated list of OPTIMADE database URLs (several of which fail) and the design of the class is such that refreshing these aliases can only be done post-init which means they will not be used if the user providers their own filtered list of aliases, without doing some extra work.
This PR refreshes the vendored list of aliases (which should be much more stable now since their initial addition 2 years ago), and also adds the option to refresh the aliases on initialization of the class.
This currently effects the pymatgen OPTIMADE tutorials at https://github.com/Materials-Consortia/optimade-tutorial-exercises.
=> Manually update OPTIMADE database aliases and add option to refresh on init

pymatgen/ext/optimade.py, pymatgen/ext/tests/test_optimade.py
Closes #2852 by properly quoting OPTIMADE query URLs without using f-strings.
Also fixes an issue where `chemical_formula_hill` was not queryable.
=> Fix OPTIMADE client generated filters and URLs

pymatgen/ext/optimade.py
One more fix related to #2852 -- response fields also should not have quotes around the entire field. This was caught by a test that directly queries MP, which was (also incorrectly) returning data that didn't quite match rather than an error, e.g.:
https://optimade.materialsproject.org/v1/structures?filter=(elements%20HAS%20ALL%20%22Ga%22,%20%22N%22)%20AND%20(nelements=2)&response_fields=%22species_at_sites,cartesian_site_positions,species,lattice_vectors,nsites%22
vs what should happen if you incorrectly format the response fields:
[https://optimade.odbx.science/v1/structures?response_fields="id"](https://optimade.odbx.science/v1/structures?response_fields=%22id%22)
=> Fix typo in OPTIMADE client: remove quotes in response fields

pymatgen/core/ion.py
Fixed the handling of O-H containing compositions, where the string 'HO' was replaced by 'OH' directly in the reduced formula. This will cause certain materials, e.g. HSbO2, to have the wrong reduced formula of SbOH2.
This fix then adds a condition that the composition must have an equal number of H and O to be handled that way.
=> fix reduced formula in Ion

docs_rst/installation.rst, pymatgen/analysis/interfaces/coherent_interfaces.py, pymatgen/analysis/interfaces/tests/test_zsl.py, pymatgen/analysis/interfaces/zsl.py, pymatgen/core/surface.py, pymatgen/symmetry/analyzer.py, pymatgen/util/numba.py, setup.py
I noticed SubstrateAnalyzer was perhaps a bit on the slow side. There are a few optimizations here: for a test set of 100 structures, these took the evaluation time down from ~43 minutes down to 193 seconds.
Optimizations include some caching, particularly of calls to spglib, since these are expensive and often repeated multiple times for the same structure (e.g., in tensor operations for IEEE conversion). I also optionally allow the use of `numba` here, which provides an additional ~3x improvement.
=> Optimizations for SubstrateAnalyzer

.pre-commit-config.yaml, pymatgen/analysis/interfaces/zsl.py, pymatgen/analysis/structure_matcher.py, pymatgen/analysis/tests/test_ewald.py, pymatgen/analysis/tests/test_structure_analyzer.py, pymatgen/core/__init__.py, pymatgen/io/lobster/tests/test_lobster.py, pymatgen/io/tests/test_gaussian.py, pymatgen/io/tests/test_nwchem.py, pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/tests/test_outputs.py, pymatgen/symmetry/analyzer.py, pyproject.toml
Following private discussion about unicode issues when reading POTCARs and @mkhorton mentioning `codecs.open` is potentially.
=> Replace `codecs.open` with `io.open` for reading `PotcarSingle`

.github/workflows/lint.yml, pymatgen/optimization/neighbors.pyx
=> Fix TypeError: a bytes-like object is required, not 'list' when passing triplet of bools to `find_points_in_spheres()` `pbc` kwarg 

pymatgen/analysis/phase_diagram.py, pymatgen/analysis/tests/test_phase_diagram.py
Closes #2885.
933d3eb2e4 fix ValueError: not enough values to unpack (expected 2, got 0)
f654d9f32c add test to prevent regression
=> Fix ValueError: not enough values to unpack in PDPlotter if no unstable entries in PD

pyproject.toml
I'm not 100% sure how the current version numbering is updated for `pymatgen` but it's not able to update the number properly for forks.  The forks seem to keep a much older version number (from before the forking)
This creates problems if you have the forked repo as a dependency in a requirement.txt file.
This should fix that issue.
=> auto version

pymatgen/analysis/magnetism/heisenberg.py, pymatgen/io/lammps/data.py, pymatgen/io/qchem/outputs.py
Closes #2914.
Replace calls to df.append() with pd.concat() and df.iteritems() with df.items().
=> Fix breaking changes from pandas v2

pymatgen/io/gaussian.py, pymatgen/io/tests/test_gaussian.py
This fixes the issue that the Gaussian input file fails to read multiple lines. 
- When the route input has multiple lines as below, GaussianInput.from_string() fails around the parsing of the route. This was due to inappropriate line counting when the route is separated in multiple lines.
- few lines of code were added to parse the route and route_index.
- test files for routes with multiple lines.
Example of Gaussian input (header only) with multiple lines of the route that failed.
```
%nprocshared=28
%mem=60GB
%chk=test.chk
pseudo=read
```
Note that the CI system will run all the above checks. But it will be much more efficient if you already fix most errors prior to submitting the PR. We highly recommended …
=> fix on reading multiple route in Gaussian input file

.pre-commit-config.yaml, dev_scripts/chemenv/get_plane_permutations_optimized.py, dev_scripts/chemenv/plane_multiplicity.py, pymatgen/analysis/graphs.py, pymatgen/analysis/tests/test_graphs.py, pymatgen/entries/mixing_scheme.py, pymatgen/entries/tests/test_mixing_scheme.py
Not sure when these errors first started showing. Fixed in
- 2e48d23
- 2ca5798
=> Fix CI errors

pymatgen/analysis/wulff.py
Closes #2900.
Since matplotlib does not allow us to set auto_add_to_figure=True in Axes3D anymore passed ver. 3.6.0, I had to add the ax object to the Figure in order for it to properly display. Should now be backward/forward compatible for all versions of matplotlib.
=> Fixed Wulff shape for new versions of matplotlib

pymatgen/analysis/tests/test_wulff.py, pymatgen/analysis/wulff.py
Follow-up to #2950. Improves the `get_plot()` test to make sure a regression causing an empty figure doesn't go unnoticed again.
=> Test figure returned by WulffShape.get_plot() contains single Axes3D

pymatgen/io/cp2k/outputs.py
```py
if ("UKS" or "UNRESTRICTED_KOHN_SHAM" or "LSD" or "SPIN_POLARIZED") in self.data["dft"].values():
return True
```
`"UKS" or "UNRESTRICTED_KOHN_SHAM" or "LSD" or "SPIN_POLARIZED"` short-circuits to `"UKS"` and so won't return `True` even if `"UNRESTRICTED_KOHN_SHAM"` or `"LSD"` or `"SPIN_POLARIZED"` are present.
=> Fix `Cp2kOutput.spin_polarized()` likely not doing what author intended

pymatgen/io/vasp/MPAbsorptionSet.yaml, pymatgen/io/vasp/MPHSERelaxSet.yaml, pymatgen/io/vasp/MPRelaxSet.yaml, pymatgen/io/vasp/MPSCANRelaxSet.yaml, pymatgen/io/vasp/MVLGWSet.yaml, pymatgen/io/vasp/MVLRelax52Set.yaml
=> Change Yb pseudo-potential on all VASP input sets: Yb_(2->3)

pymatgen/analysis/chemenv/coordination_environments/tests/test_read_write.py, pymatgen/io/core.py, pymatgen/io/tests/test_core.py
Both copy and deepcopy are currently broken for the `InputSet` object. This PR implements dunder methods to fix both. There very well may be a more elegant solution but I couldn't find it!
- Feature 1: `__copy__` and `__deepcopy__` dunder methods
=> fix recursion error by adding copy and deepcopy dunder methods

pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometry_finder.py, pymatgen/analysis/chemenv/utils/tests/test_graph_utils.py, pymatgen/analysis/tests/test_interface_reactions.py, pymatgen/analysis/tests/test_local_env.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/core/tests/test_composition.py, pymatgen/core/tests/test_lattice.py, pymatgen/core/tests/test_libxcfunc.py, pymatgen/core/tests/test_trajectory.py, pymatgen/core/xcfunc.py, pymatgen/electronic_structure/tests/test_plotter.py, pymatgen/entries/tests/test_compatibility.py, pymatgen/entries/tests/test_mixing_scheme.py, pymatgen/io/abinit/tests/test_pseudos.py, pymatgen/io/lammps/tests/test_data.py, pymatgen/io/qchem/tests/test_inputs.py, pymatgen/io/qchem/tests/test_outputs.py, pymatgen/io/tests/test_packmol.py, pymatgen/io/tests/test_wannier90.py, pymatgen/io/vasp/tests/test_outputs.py, pymatgen/io/vasp/tests/test_sets.py, pymatgen/symmetry/tests/test_analyzer.py, pymatgen/util/testing.py, pymatgen/util/tests/test_string.py, pyproject.toml
Another small step in a larger overhaul of the testing side of `pymatgen`.
=> Enable `flake8-pytest-style` via `ruff`

pymatgen/util/coord_cython.pyx
The `pbc_shortest_vectors` function leaks all memory allocated to store the fractional coordinates of surrounding periodic sites. As a result, memory consumption keeps creeping up when (heavily) calling the function, see [this memory profile](https://github.com/materialsproject/pymatgen/files/11433457/v2023.5.8.pdf) of a script of mine which made me aware of the problem. The suggested modifications completely eliminate the issue, [curtailing the memory consumption](https://github.com/materialsproject/pymatgen/files/11433643/fixed.pdf) of the same script.
With the suggested minimal modifications, additional memory is only allocated (and freed accordingly) when needed - that is, when periodic boundary conditions are applied selectively.
=> Fix for memory leak in pbc_shortest_vectors

pymatgen/io/vasp/optics.py, pymatgen/io/vasp/tests/test_optics.py
Hi!
Firstly, thanks to the developers for the recent addition of the `pymatgen.io.vasp.optics` module, it's been very very useful! 🙌
This is just a small fix for a suspected typo in handling `ismear` in the `delta_func()` and `step_func()` functions. `ISMEAR` is zero for Gaussian smearing, and indeed in the docstrings for `get_epsilon()` it states: `ismear: Smearing method (only has 0:gaussian, >0:Methfessel-Paxton)`. However, in the current version of the code:
```python
def delta_func(x, ismear):
"""Replication of VASP's delta function"""
if ismear < -1:
raise ValueError("Delta function not implemented for ismear < -1")
if ismear == -1:
return step_func(x, -1) * (1 - step_func(x, -1))
if ismear < 0:
return np.exp(-(x * x)) / np.sqrt(np.pi)
return delta_methfessel_paxton(x, ismear)
``` …
=> Suspected Typo Fix in `pymatgen.io.vasp.optics`

.pre-commit-config.yaml, docs_rst/conf-normal.py, docs_rst/conf.py, pymatgen/alchemy/materials.py, pymatgen/alchemy/transmuters.py, pymatgen/analysis/structure_matcher.py, pymatgen/apps/battery/analyzer.py, pymatgen/apps/battery/plotter.py, pymatgen/apps/borg/queen.py, pymatgen/cli/pmg_analyze.py, pymatgen/command_line/chargemol_caller.py, pymatgen/command_line/gulp_caller.py, pymatgen/core/ion.py, pymatgen/core/libxcfunc.py, pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/boltztrap.py, pymatgen/electronic_structure/boltztrap2.py, pymatgen/electronic_structure/cohp.py, pymatgen/electronic_structure/dos.py, pymatgen/electronic_structure/plotter.py, pymatgen/electronic_structure/tests/test_boltztrap.py, pymatgen/entries/compatibility.py, pymatgen/ext/cod.py, pymatgen/ext/matproj.py, pymatgen/io/vasp/outputs.py, pymatgen/symmetry/analyzer.py, pymatgen/symmetry/groups.py, pymatgen/symmetry/kpath.py, pymatgen/symmetry/maggroups.py, pyproject.toml
1273014de ignore some `ruff` doc string errors and fix all remaining
a6dd53e72 `ruff` enable doc rules in pre-commit
c349a806c fix `mypy` error
dea2aa043 2nd try fix `mypy`
d3e4d2b57 prefix unused func args with underscore
f7b4a5006 `ruff` enable `flynt` rules
=> Enable ruff doc rules in CI

pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, pymatgen/ext/tests/test_optimade.py
ffae4ea4e support writing structures to compressed JSON files
ba9918395 check structure equality writing and reading from .json.gz .json.bz2 .json.xz .json.lzma
Related: #2994 helps with reducing test file sizes
=> Support writing structures to compressed JSON (.json.gz .json.bz2 .json.xz .json.lzma)

pymatgen/ext/matproj.py, pymatgen/ext/tests/test_matproj.py
Both the new and legacy versions of `MPRester` accepted `api_key=None` to be passed as an argument, triggering a fallback to the settings version of the key. The new behavior of the dynamic `MPRester` is to attempt to use the `None` value directly, i.e., without checking for an externally configured value.
This PR simply adjusts the behavior so that `api_key=None` will still trigger a settings lookup.
=> Lookup `MPRester` API key in settings if `None` provided as arg

pymatgen/io/ase.py, pymatgen/io/lammps/data.py, pymatgen/io/tests/test_ase.py
Closes #3011.
71e888dd9 refactor LammpsData.get_string()
a1d3509b6 refactor ase import, AseAtomsAdaptor.get_atoms() check is_struct
a21543c71 fix ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() when structure.selective_dynamics has type np.array
bf56232bb add cases testing selective_dynamics as list and array to test_get_structure_dyn()
=> Fix `ValueError` when `structure.selective_dynamics` has type `np.array`

pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py, pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/graphs.py, pymatgen/analysis/phase_diagram.py, pymatgen/analysis/surface_analysis.py, pymatgen/command_line/tests/test_mcsqs_caller.py, pymatgen/core/composition.py, pymatgen/core/ion.py, pymatgen/core/operations.py, pymatgen/core/periodic_table.py, pymatgen/core/structure.py, pymatgen/core/tests/test_composition.py, pymatgen/core/tests/test_ion.py, pymatgen/core/tests/test_operations.py, pymatgen/core/tests/test_structure.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/lmto.py, pymatgen/io/lobster/lobsterenv.py, pymatgen/symmetry/analyzer.py, pymatgen/symmetry/structure.py, pymatgen/transformations/tests/test_advanced_transformations.py, pymatgen/util/string.py, pymatgen/util/tests/test_string.py
Also use modern `f"{float:+}"` for explicit `+` signs.
=> Tweak variable names

pymatgen/entries/mixing_scheme.py, pymatgen/io/abinit/abitimer.py, pymatgen/io/abinit/pseudos.py, pymatgen/io/cp2k/inputs.py, pymatgen/io/cp2k/outputs.py, pymatgen/io/cp2k/sets.py, pymatgen/io/cp2k/tests/test_inputs.py, pymatgen/io/cp2k/tests/test_sets.py, pymatgen/io/lammps/data.py, pymatgen/io/lammps/tests/test_data.py, pymatgen/io/lammps/tests/test_generators.py, pyproject.toml
c535f4979 ruff unignore PD011 (pandas-use-of-dot-values)
7d3eba415 drop .values where not needed, else replace with .to_numpy(), noqa false positives
`pandas.DataFrame().values` is deprecated and slated for removal in a future `pandas` version.
=> Unignore `ruff` `PD011`

pymatgen/io/vasp/sets.py
This is a quick fix to allow direct initialisation of the `DictSet` class, which was possible before but broke in https://github.com/materialsproject/pymatgen/pull/2972 due to the `Yb_2` check querying `self.CONFIG`, which is only defined if `DictSet` was being initialised from a subclass and not directly. 
This fixes this behaviour by checking the `config_dict` which is a required input parameter so always defined (same as `self.CONFIG` if initialising from a subclass), and also updates this with the `user_potcar_settings` before checking, in case the user has explicitly specified to avoid the `Yb_2` `POTCAR`. 
Demo in the attached notebook and PDF!
[pymatgen_DictSet_fix.zip](https://github.com/materialsproject/pymatgen/files/11628196/pymatgen_DictSet_fix.zip)
=> Update `DictSet` to allow direct initialisation

pymatgen/transformations/advanced_transformations.py
Remove superfluous structure argument docstring from `SQSTransformation` init
Ensure:
Tip: Install `pre-commit` hooks to auto-check before every commit:
```sh
```
=> DOC: remove "structure" from init

pymatgen/entries/compatibility.py, pymatgen/entries/tests/test_compatibility.py
Small change to the way `MaterialsProjectAqueousCompatibility` corrects energies for materials containing `H2O`.
As [described by a user on MatSci](https://matsci.org/t/mpaqueouscompatibility-applies-hydrate-correction-to-non-hydrate-materials/47360/2), the current way of detecting whether a material contains 'H2O' can lead to false positives for formulas like `Li2O2H2`, causing this material to be corrected as if it were a hydrate when in fact it is not.
Here, I change the detection of hydrates to be based on `reduced_composition` instead of `composition` to avoid such false positives.
Tests appear to pass, but flagging @montoyjh and @as2362 in case there are concerns about how this will impact Pourbaix Diagrams. This should cause the energies of some -OH phases to change a bit because …
=> MPAqueousCompatiblity: compute hydrate correction using reduced rather than full composition

pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py
Closes #3023. CC'ing @janosh and @munrojm.
=> Don't do a hard `bandgap==0` check in the r2SCAN workflow

pymatgen/core/tests/test_structure.py, pymatgen/ext/tests/test_optimade.py, pymatgen/io/vasp/sets.py, pymatgen/io/vasp/tests/test_sets.py, pymatgen/util/string.py
Follow up to #3031 adding a test to make sure we don't regress again. I just realized we had 0 tests for `DictSet` before. While writing some, I noticed `DictSet.as_dict()` is also broken. Not only since https://github.com/materialsproject/pymatgen/pull/2972, even before due to not storing the `validate_magmons` init kwarg on instances.
`VaspInputSet.potcar_functional` was renamed to `VaspInputSet.user_potcar_functional` to fix `DictSet.as_dict()` which otherwise errors
```py
NotImplementedError: Unable to automatically determine as_dict format from class. MSONAble requires all args to be present as either self.argname or self._argname
```
@shyuep Is this justifiable? `DictSet.as_dict()` is not very important and renaming `potcar_functional` -> `user_potcar_functional` might incur a lot …
=> Breaking: rename VaspInputSet.(potcar_functional->user_potcar_functional) and start testing `DictSet`

.pre-commit-config.yaml, dev_scripts/chemenv/explicit_permutations.py, dev_scripts/chemenv/strategies/multi_weights_strategy_parameters.py, pymatgen/analysis/bond_valence.py, pymatgen/analysis/local_env.py, pymatgen/core/tests/test_structure.py, pymatgen/electronic_structure/cohp.py, pymatgen/electronic_structure/tests/test_cohp.py
Also use modern f-string syntax.
=> `IcohpValue.__str__` don't `return None`

pymatgen/analysis/pourbaix_diagram.py, pymatgen/analysis/tests/test_pourbaix_diagram.py
Closes #2943.
The Pourbaix diagram was generating multi-entries with the wrong composition because of Reaction coefficient handling. This fixes the issue by using the explicit list of reaction coefficients, rather than the hash retrieval, and adds a regression test that fails previously but passes now.
=> `PourbaixDiagram` wrong composition bug fix

.github/workflows/test.yml, .pre-commit-config.yaml
=> Migrate GHA release job to PyPI trusted publishing

pymatgen/core/periodic_table.py
The description of `electronegativity` in periodic_table.py is not clear and a bit confusing as there are different types of `electronegativity` (see https://en.wikipedia.org/wiki/Electronegativity). Specified the `electronegativity` as `Pauling electronegativity`.
=> Update doc in periodic_table.py

pymatgen/core/structure.py
Caused by
```py
for idx, specie in enumerate(species):
sites.append(Site(specie, coords[idx], properties=prop))
```
where `species` is `dict`, not list so to get value, must be `species[idx]`, not `specie`.
=> Fix `ValueError: Unexpected atomic number Z=0`

pymatgen/symmetry/tests/test_kpath_lm.py
HI @janosh ,
I removed and simplified the tests. I am still not sure why there is an "or" for the other tests. In my opinion, the result should be always the same for one structure.
It's also redundant to test if g has a certain k-point and then later on tests if point g has the same kpoint or point xyz has a certain k-point.
=> Update test_kpath_lm.py, remove and simplify tests

pymatgen/io/ase.py, pymatgen/io/tests/test_ase.py
Tests were set to skip if `ase` not importable (now removed so we catch this in the future).
@arosen93 `sys.path.insert(0, getsitepackages()[0])` is admittedly an ugly hack but, like you said, preferable over a breaking module rename.
=> Fix `ase` tests not running due to `pymatgen/io/ase.py` shadowing `ase` package

pymatgen/io/ase.py
When interconverting between `Atoms` and `Structure`/`Molecule`, the key ordering in the `.todict()` representation changes. This PR fixes this trivial non-issue.
=> Cosmetic fixes to `AseAtomsAdaptor` dictionary key ordering

pymatgen/io/lobster/lobsterenv.py, pymatgen/io/lobster/tests/test_lobsterenv.py
I improved the documentation of the LobsterEnv module which was triggered by our updates to LobsterPy (https://github.com/JaGeo/LobsterPy/pull/81) and suggestions by @ajjackson
@janosh : happy to hear additional thoughts from you.
=> Improvements to the documentation of the Lobsterenv module

pymatgen/core/composition.py, pymatgen/core/tests/test_composition.py
This PR fixes an error in the **hill_formula** property of the Composition object, which occurs in cases where C, H, and other element/s with symbol ordering alphabetically before H are present at the same time. In such a case, H should be placed directly after C, but this is not implemented nor tested in the current version.
- Fixed the property to match the description.
- Implemented additional tests.
Sidenote: @ml-evs This fix should help eliminate compatibility issues with the OPTIMADE _chemical_formula_hill_ field (except for the presence/lack of empty spaces).
=> Fix hill_formula Composition property

pymatgen/analysis/gb/grain.py, pymatgen/analysis/tests/test_fragmenter.py, pymatgen/core/lattice.py, pymatgen/core/periodic_table.py, pymatgen/core/sites.py, pymatgen/core/tests/test_composition.py, pymatgen/core/tests/test_lattice.py, pymatgen/core/tests/test_operations.py, pymatgen/core/tests/test_periodic_table.py, pymatgen/core/tests/test_sites.py, pymatgen/core/tests/test_spectrum.py, pymatgen/core/tests/test_units.py, pymatgen/io/gaussian.py, pymatgen/util/coord.py
Closes #3078.
Todo: Check why test failure was not caught in our CI. `openbabel` not installed correctly?
=> Fix `test_babel_pc_with_ro_depth_0_vs_depth_10`

pymatgen/io/abinit/pseudos.py, pymatgen/io/cp2k/inputs.py, pymatgen/io/vasp/inputs.py
=> Set `hashlib.md5(usedforsecurity=False)` when computing POTCAR hashes

pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py
=> BUG: force contiguous calling find_points_in_spheres

pymatgen/analysis/molecule_matcher.py, pymatgen/analysis/tests/test_molecule_matcher.py, setup.py
=> Fix `openbabel` import to unskip `MoleculeMatcherTest`

pymatgen/analysis/graphs.py
In line 2602 and 2603, `g` is `MultiDiGraph` and has no attribute `node`.
Major changes:
- fix 1: change g.node to g.nodes
```sh
```
=> fix AttributeError in MoleculeGraph.draw_graph_to_file

pymatgen/core/periodic_table.py, pymatgen/core/sites.py
Uses functools.cache to speed up the conversion of arbitrary objects into Element | Species | DummySpecies.
- One thing to keep in mind is that returned objects are not necessarily unique anymore, they could be returned again through the cache.
- Arguments to `get_el_sp` must be `Hashable`, luckily this seems to be the case
Major updates:
- feature 1: massive speed up for get_el_sp
Ensure:
Tip: Install `pre-commit` hooks to auto-check before every commit:
```sh
```
=> Add a cache to speed up get_el_sp

.github/workflows/test.yml, .pre-commit-config.yaml, pymatgen/analysis/elasticity/tests/test_elastic.py, pymatgen/analysis/tests/test_surface_analysis.py, pymatgen/apps/borg/tests/test_hive.py, pymatgen/command_line/mcsqs_caller.py, pymatgen/command_line/tests/test_enumlib_caller.py, pymatgen/core/structure.py, pymatgen/io/tests/test_cif.py, pymatgen/io/vasp/tests/test_inputs.py, pymatgen/io/vasp/tests/test_outputs.py, pymatgen/symmetry/groups.py, pymatgen/symmetry/tests/test_groups.py, pymatgen/transformations/tests/test_advanced_transformations.py, pymatgen/util/tests/test_graph_hashing.py, setup.py
Not sure why but `SpaceGroup` didn't have a `repr` yet.
=> `SpaceGroup.__repr__`

docs_rst/addons.rst
The core functionality of [pymatgen.io.openmm](https://github.com/orionarcher/pymatgen-io-openmm) is in place so I thought I'd add it to the the add ons page.
=> Add `pymatgen.io.openmm` package to `addons.rst`

pymatgen/alchemy/materials.py, pymatgen/core/structure.py, pymatgen/io/cif.py, pymatgen/io/tests/test_cif.py, setup.py
Major changes:
- feature 1: Read site labels from cif file and store these under `Structure.site_properties`.
Closes #3135
```sh
```
=> Read site labels from cif file

pymatgen/io/vasp/tests/test_inputs.py
Added basic test to make sure that the written POTCAR file is readable by VASP.
in response to Issue #3068
=> explicit test POTCAR

docs_rst/usage.rst, pymatgen/cli/pmg_config.py, pymatgen/entries/compatibility.py, pymatgen/entries/mixing_scheme.py, pymatgen/io/vasp/inputs.py
Closes #3152
90a7c076d rename `PMG_DISABLE_POTCAR_CHECKS` to `PMG_POTCAR_CHECKS`
0729fc3f9 fix setting `bool` and `None` through `pmg` config CLI
0ef9ae7d2 document existence of `PMG_POTCAR_CHECKS` in all doc strings for `check_potcar: bool = True`
=> Rename `PMG_DISABLE_POTCAR_CHECKS` to `PMG_POTCAR_CHECKS`

pymatgen/core/sites.py, pymatgen/core/structure.py, pymatgen/core/tests/test_sites.py, pymatgen/core/tests/test_structure.py, pymatgen/electronic_structure/tests/test_cohp.py, pymatgen/io/cif.py, pymatgen/io/lobster/tests/test_lobster.py, pymatgen/io/tests/test_cif.py
This PR follows up from #3136 which was reverted because of CI test failures, see https://github.com/materialsproject/pymatgen/pull/3136#issuecomment-1624198814 . This PR addresses these issues.
Major changes:
- feature 1: Read site labels from cif file and store these under `Structure.site_properties`.
Closes #3135
```sh
```
=> Read site labels from cif file (2)

pymatgen/analysis/magnetism/analyzer.py, pymatgen/analysis/magnetism/tests/test_analyzer.py
Fixes bug briefly mentioned in #3070, where recent spin property changes resulted in the `MagneticStructureEnumerator` failing. This is apparently due to creating structures where only some `Species.spin` properties are defined, causing `CollinearMagneticStructureEnumerator` to fail. For example, if you input this structure into the analyzer right now, it would fail:
```
Structure Summary
Lattice
abc : 2.948635277547903 2.948635277547903 5.107186113702927
angles : 73.22134511903964 90.0 120.00000000000001
volume : 36.2558565
A : 2.085 2.085 0.0
B : 0.0 -2.085 -2.085
C : -2.085 2.085 -4.17
pbc : True True True
PeriodicSite: Ni,spin=-5 (0.0000, 2.0850, -2.0850) [0.5000, 0.0000, 0.5000]
PeriodicSite: Ni,spin=5 (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: O (0.0000, 0.0000, …
```
=> Bug fix: `CollinearMagneticAnalyzer` should not fail when `Species.spin = None`

pymatgen/core/sites.py, pymatgen/core/structure.py, pymatgen/core/tests/test_sites.py, pymatgen/core/tests/test_structure.py, pymatgen/ext/optimade.py, test_files/.pytest-split-durations
This PR fixes some issues with labels and adds new tests for previously unspecified behaviour.
Major changes:
- `Site.label` (and derivatives) defaults to `.species_string` instead of `None`
- Add label attribute to `Neighbor` and `PeriodicNeighbor`
Closes #3166
Closes #3160
```sh
```
=> Fix issues with labels

pymatgen/core/composition.py, pymatgen/core/ion.py, pymatgen/electronic_structure/bandstructure.py, pymatgen/ext/optimade.py, pymatgen/io/abinit/pseudos.py, pymatgen/io/cif.py, pymatgen/io/lmto.py, pymatgen/io/tests/test_cif.py
Closes #3174.
Doesn't actually change the default behavior of `CifParser.get_structures()`. That seemed too breaking. Instead adds a new kwarg
```py
on_error: Literal["ignore", "warn", "raise"] = "warn"
```
which is a step towards better error messages on parse errors when set to "error".
=> Add `CifParser.get_structures(on_error='warn')`

.pre-commit-config.yaml, pymatgen/analysis/adsorption.py, pymatgen/analysis/chemenv/connectivity/connected_components.py, pymatgen/analysis/chemenv/connectivity/tests/test_connected_components.py, pymatgen/analysis/chemenv/utils/scripts_utils.py, pymatgen/analysis/dimensionality.py, pymatgen/analysis/graphs.py, pymatgen/analysis/local_env.py, pymatgen/analysis/structure_prediction/dopant_predictor.py, pymatgen/analysis/surface_analysis.py, pymatgen/analysis/tests/test_phase_diagram.py, pymatgen/analysis/tests/test_surface_analysis.py, pymatgen/command_line/tests/test_critic2_caller.py, pymatgen/core/bonds.py, pymatgen/core/periodic_table.py, pymatgen/core/sites.py, pymatgen/core/structure.py, pymatgen/core/tensors.py, pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/boltztrap.py, pymatgen/electronic_structure/boltztrap2.py, pymatgen/electronic_structure/plotter.py, pymatgen/entries/tests/test_mixing_scheme.py, pymatgen/ext/tests/test_optimade.py, pymatgen/io/abinit/inputs.py, pymatgen/io/lobster/lobsterenv.py, pymatgen/io/qchem/outputs.py, pymatgen/io/qchem/sets.py, pymatgen/io/tests/test_cif.py, pymatgen/transformations/advanced_transformations.py
Auto fix 64 cases of `RUF015` and `PERF102`.
=> `ruff . --fix`

pymatgen/io/pwscf.py, pymatgen/io/tests/test_pwscf.py
The proc_val function modifies the value of string variables (changes 'd' for 'e'). For example, smearing = 'cold' becomes smearing = 'cole'. It is solved by using a local variable.
Major changes:
Added  a local variable
```
val_replace = val.replace("d", "e")
return smart_int_or_float(val_replace)
```
```sh
```
=> Fix a bug in pwscf.py. The proc_val function modifies string values.

pymatgen/core/units.py, pymatgen/io/adf.py, pymatgen/io/babel.py, pymatgen/io/cif.py, pymatgen/io/cp2k/inputs.py, pymatgen/io/exciting/inputs.py, pymatgen/io/feff/inputs.py, pymatgen/io/fiesta.py, pymatgen/io/gaussian.py, pymatgen/io/lammps/inputs.py, pymatgen/io/lammps/outputs.py, pymatgen/io/lmto.py, pymatgen/io/nwchem.py, pymatgen/io/pwscf.py, pymatgen/io/vasp/inputs.py, pymatgen/io/xcrysden.py, pymatgen/io/xr.py, pymatgen/io/xyz.py, pymatgen/io/zeopp.py
Fix a bug introduced in #3158. A lot of `from_string` methods should be `classmethod`.
```sh
```
=> lots of `from_string` should be `classmethod`

pymatgen/symmetry/analyzer.py, pymatgen/symmetry/tests/test_analyzer.py
With the new changes that set the default `Sepcies.spin` to `None`, I fixed the logic for setting zero magmoms in `SpacegroupAnalyzer` to check for `None` values as well.
```sh
```
=> BUG: fix setting zero magmoms

pymatgen/symmetry/kpath.py, pymatgen/util/plotting.py, pymatgen/util/tests/test_plotting.py
This PR tries to `from pymatviz import ptable_heatmap_plotly` in `periodic_table_heatmap()`. If successful, all arguments are passed to that function along with deprecation messages for args that have different names in `pymatviz.ptable_heatmap_plotly` vs `pymatgen.util.plotting.periodic_table_heatmap`.
It explicitly doesn't add `pymatviz` as a new dependency of `pymatgen` to avoid circularity.
**Before**
**After**
**Code**
```py
import pandas as pd
from pymatgen.util.plotting import periodic_table_heatmap
df_ptable = pd.read_csv(
"https://github.com/janosh/pymatviz/raw/main/pymatviz/elements.csv", comment="#"
).set_index("symbol")
periodic_table_heatmap(df_ptable.atomic_mass.to_dict(), cmap="viridis")
```
=> Prefer `pymatviz` interactive plotly version of periodic table heatmap if available

pymatgen/core/composition.py, pymatgen/core/tests/test_composition.py, pymatgen/core/units.py
Closes #3181.
1d3ff8467 include oxidation states in `Composition.__repr__`
26b3b5b98 delete unused `doctest.testmod() if __name__ == "__main__"`
d2aed40d1 add tests for `Composition.__repr__` and `__str__`
=> Better Composition `repr`

pymatgen/analysis/tests/test_structure_matcher.py, pymatgen/core/composition.py, pymatgen/core/periodic_table.py, pymatgen/core/tests/test_composition.py, pymatgen/entries/compatibility.py, pymatgen/entries/tests/test_compatibility.py, test_files/.pytest-split-durations
Closes #3185.
`Element in Composition` is currently `False` if that `Element` appears in `Composition` as a `Species` with an oxidation state.
This PR changes the `__contains__` method to return `True` for `x in Composition` if
1. `x` exactly matches a `Species` (both element symbol and oxidation state) in the composition (same as before) 
2. _or_ if `x` is an `Element` and a `Species` with matching element symbol is present, regardless of oxidation state (returned `False` before).
It does not change behavior for the reverse, i.e. if a `Species` is not in the `Composition`, only its `Element` without oxidation state, then we still return `False`.
This is strictly speaking a breaking change but an improvement over previous behavior as it prevents unexpected behavior like `Element('O/S') in …
=> Breaking: Return True for `Element in Composition` if `Species.symbol` matches `Element`

pymatgen/io/vasp/sets.py
As suggested by @matthewkuner and @arosen93. See discussion following https://github.com/materialsproject/pymatgen/pull/3041#issuecomment-1650336881.
=> Revert `LMAXMIX` "fix" added in #3041

.github/workflows/test.yml, pymatgen/command_line/bader_caller.py, pymatgen/command_line/tests/test_bader_caller.py, pymatgen/io/vasp/outputs.py
You can now use
```py
BaderAnalysis(bader_exe_path="/abs/path/to/bader")
```
to run `bader` anywhere on your system without any `PATH` modification shenanigans.
TODO: Promote `atomate2.SETTINGS.VASP_RUN_BADER: bool`  to accept a string so users only need to specify `bader_exe_path` once in their `atomate2` config.
=> Add `bader_exe_path` keyword to `BaderAnalysis` and run `bader` tests in CI

pymatgen/core/tests/test_structure.py, pymatgen/io/lammps/tests/test_inputs.py, pymatgen/io/tests/test_packmol.py, pymatgen/io/tests/test_template_input.py, pymatgen/phonon/tests/test_thermal_displacements.py
60ff0cbb3 don't use tempfile.TemporaryDirectory() in tests, prefer PymatgenTest.tmp_path auto-used fixture
b8a0f633c fix broken test_files paths in TestPackmolSet
2013d15b4 skip failing TestPackmolSet.test_random_seed due to openbabel not installed
b3c6150c3 only skip pymatgen/io/tests/test_packmol.py if packmol not installed
=> Unskip and fix `packmol` tests

pymatgen/analysis/gb/grain.py, pymatgen/core/lattice.py, pymatgen/core/sites.py, pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, pymatgen/io/cif.py, pymatgen/io/res.py, pymatgen/io/tests/test_cif.py, pymatgen/io/vasp/inputs.py
This PR follows up from #3137 and makes sure that labels are propagated correctly throughout structure, for example, when making supercells, inserting/deleting sites, applying translations/rotations, etc.
This PR also fixes a bug where the labels were incorrectly assigned when the CIF contains multiple species with different names.
Major changes:
- feature 1: Propagate labels in operations on structure
- fix 1: Correctly generate labels when cif contains multiple species with same name
```sh
```
=> Propagate labels through various Structure operations

.pre-commit-config.yaml, pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py, pymatgen/analysis/wulff.py, pymatgen/apps/battery/conversion_battery.py, pymatgen/command_line/tests/test_gulp_caller.py, pymatgen/io/abinit/inputs.py, pymatgen/io/lobster/lobsterenv.py, pymatgen/io/lobster/outputs.py, pymatgen/io/nwchem.py, pymatgen/io/xtb/inputs.py
4e1bb4b74 delete self-assignments
13ef1f80d del unused w_area_has_intersection_smoothstep
=> Delete variable self assignments

pymatgen/analysis/local_env.py, pymatgen/core/structure.py, pymatgen/core/tests/test_structure.py, pymatgen/transformations/standard_transformations.py
Most notable user-facing change: add `in_place: bool = True` keyword to `Structure.make_supercell()` and return the supercell.
a70f4c4c5 add `Structure/Molecule.sites` setter, move `@property` to SiteCollection
7f510ca35 don't use implementation detail `(Structure|Molecule)._sites`
c5052a223 rename `StructureTest.structure` attr to `struct`
28a895fcb add `IStructureTest.test_sites_setter`
185d2cb7c fix mypy
94f4413a7 test `translate/rotate_sites` `IndexError` if "list index out of range"
2ffd3bb67 tweak doc strings
f482ba0f3 test inverse `translate_sites` operations leave structure unchanged
7197592b6 `Structure.make_supercell()` add `in_place: bool = True` keyword and return supercell structure
638c095de test `make_supercell` `in_place=True` and `False`
=> Improve `Structure` tests

.gitattributes, pymatgen/analysis/chemenv/coordination_environments/voronoi.py, pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py, pymatgen/analysis/dimensionality.py, pymatgen/analysis/eos.py, pymatgen/analysis/graphs.py, pymatgen/analysis/reaction_calculator.py, tests/analysis/test_graphs.py
8039195ac refactor TestStructureGraph.test_draw use PymatgenTest.tmp_path
824296fff BalancedReaction don't create unnecessary lists
874baa587 .gitattributes fix tests/files/ path causing wrong repo language statistics
Should say 100% Python. GH linguist misclassifies our test files. This PR ignores test files altogether.
=> Fix GitHub language statistics after test files migration

pymatgen/io/vasp/inputs.py, tests/io/vasp/test_inputs.py
=> Fix `automatic_density_by_lengths` and add tests for it

pymatgen/analysis/phase_diagram.py, tests/analysis/test_phase_diagram.py
4c99bea5b add `PhaseDiagram.get_reference_energy()`
4ad0f93d3 add test for `PhaseDiagram.get_form_energy_per_atom()`
b45dd043e add `TestPhaseDiagram.test_get_reference_energy()`
=> Add `PhaseDiagram` method `get_reference_energy` 

pymatgen/analysis/bond_valence.py, tests/analysis/test_bond_valence.py, tests/files/.pytest-split-durations
546b6904e list offending elements in `BVAnalyzer.get_valences` err msg
294f0332e test err msg in `TestBVAnalyzer.test_get_valences()`
=> list offending elements in `BVAnalyzer.get_valences` error message

pymatgen/io/core.py, pymatgen/io/cp2k/inputs.py, pymatgen/io/feff/inputs.py, pymatgen/io/lammps/data.py, pymatgen/io/lammps/inputs.py, pymatgen/io/lmto.py, pymatgen/io/qchem/inputs.py, pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/outputs.py, tests/io/cp2k/test_inputs.py, tests/io/feff/test_inputs.py, tests/io/lammps/test_data.py, tests/io/lammps/test_inputs.py, tests/io/test_core.py, tests/io/vasp/test_inputs.py, tests/io/vasp/test_outputs.py
Closes #3230.
e703c43f0 restore accidentally deleted io.core.InputFile.from_string (fixes #3230)
2b52712f8 add io.core type hints
ded857431 deprecate get_string methods in favor of get_str
=> Deprecate `get_string()` methods in favor of `get_str()`

pymatgen/core/structure.py, pymatgen/io/xyz.py, pymatgen/util/convergence.py, tests/analysis/test_reaction_calculator.py, tests/core/test_structure.py, tests/io/qchem/test_utils.py
Previously if `filename` was passed, `Structure/Molecule.to(filename="some/file.json|cif|yaml|poscar|...")` would return `None`. No performance cost from always returning the same string that was written to file. Simplifies implementation and testing, and can be useful in rare cases.
96f7084f5 fix some ruff PERF401
580b76099 fix test_calculate_chgnet() for next chgnet release
2781937fd always return string from Structure.to() regardless of filename kwarg
a6f960956 update TestIStructure.test_to_from_file_string
3d4b3065d same for Molecule.to()
98b6ba999 update TestIMolecule.test_to_from_file_string
2ee87bb3c improve class XYZ logic for setting self._mols
=> `Structure/Molecule.to()` now always return same string written to file

pymatgen/core/lattice.py, pymatgen/io/lammps/data.py, tests/core/test_lattice.py
16be0518e add `Lattice` property `params_dict`
47699ef57 use new prop in `Lattice.as_dict`
069852f6d test keys in `TestLattice.test_to_from_dict`
41a424db4 add `TestLattice.test_parameters`
=> Add `Lattice` property `params_dict`

pymatgen/analysis/chemenv/utils/scripts_utils.py, pymatgen/analysis/structure_prediction/substitutor.py, pymatgen/apps/battery/analyzer.py, pymatgen/core/periodic_table.py, pymatgen/core/structure.py, pymatgen/io/vasp/outputs.py, pymatgen/transformations/advanced_transformations.py, tests/alchemy/test_filters.py, tests/analysis/chemenv/coordination_environments/test_structure_environments.py, tests/analysis/magnetism/test_analyzer.py, tests/analysis/test_bond_valence.py, tests/analysis/test_energy_models.py, tests/core/test_periodic_table.py, tests/core/test_structure.py, tests/io/vasp/test_sets.py
4b9033a0e remove deprecated kwarg `properties` from `Species`+`DummySpecies`
38b30a340 snake_case vars
48b8f1678 fix `Structure.add_spin_by_element` and `add_spin_by_site`
4ffc37130 fix tests that used `Species(properties={...})`
33283b0fb update `Substitutor.pred_from_structures` doc str
7ba3245f5 fix `MagOrderingTransformation._add_dummy_species`
=> Breaking: remove deprecated keyword `properties` from `Species` 

pymatgen/io/vasp/outputs.py
`if self.incar not in ["CHI"]` looks like a mistake here. Thanks @matthewkuner for catching.
https://github.com/materialsproject/pymatgen/blob/13e46fdf65ecdb60ddd491dd640f236ed3c5ce7a/pymatgen/io/vasp/outputs.py#L608
=> Fix `Vasprun.converged_electronic` check if `ALGO=CHI` in `INCAR`

pymatgen/core/structure.py, tests/core/test_structure.py
Closes #3265.
I briefly checked for other `Molecule` attributes that are currently static but might need to change when modifying in place but didn't find any.
=> Fix `nelectrons` not updating when replacing species in `Molecule`

pymatgen/apps/battery/conversion_battery.py, pymatgen/core/libxcfunc.py, pymatgen/core/periodic_table.py, pymatgen/electronic_structure/cohp.py, pymatgen/entries/computed_entries.py, pymatgen/io/abinit/abitimer.py, pymatgen/io/vasp/inputs.py, pymatgen/io/wannier90.py, pymatgen/symmetry/analyzer.py, pymatgen/transformations/advanced_transformations.py, pymatgen/transformations/site_transformations.py, pymatgen/transformations/standard_transformations.py, tests/apps/battery/test_conversion_battery.py, tests/core/test_libxcfunc.py, tests/entries/test_computed_entries.py, tests/io/vasp/test_sets.py
33af062fc use self-documenting f-string in reprs
07b1256f4 `TestLibxcFunc` add `test_repr`
03dc9318b use python behavior that `__str__` falls back to  `__repr__` if not defined
=> `__str__` to `__repr__`

pymatgen/core/ion.py, tests/core/test_ion.py
`Ion.reduced_formula` does not correctly handle dissolved gas molecules, such as `O2`, for example:
```
>>> Ion.from_formula('O2').get_reduced_formula_and_factor()
('O', 2)
>>> Ion.from_formula('O2').formula
'O2 (aq)'
>>> Ion.from_formula('O2').reduced_formula
'O(aq)'
```
This PR modifies `Ion.get_reduced_formula_and_factor` to correctly report dissolved formulas of dissolved gases H2, N2, O2, F2, Cl2, and O3. It also updates the docstrings of `formula` and `reduced_formula`.
=> Ion: handle dissolved gas formulas

pymatgen/core/structure.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/lammps/inputs.py, pymatgen/io/vasp/sets.py, tests/electronic_structure/test_plotter.py, tests/io/qchem/test_outputs.py, tests/io/vasp/test_sets.py
159493440 add keyword `bandgap_tol: float = 1e-4` to `MPScanRelaxSet`
6decb99da add `test_bandgap_tol()` to `TestMPScanRelaxSet`
=> Add keyword `bandgap_tol: float = 1e-4` to `MPScanRelaxSet`

pymatgen/io/vasp/optics.py, tests/analysis/chemenv/coordination_environments/test_read_write.py
`np.linspace` ensures the array size is numerically stable. See the [`numpy.arange` warning](https://numpy.org/doc/stable/reference/generated/numpy.arange.html).
=> `np.(arange->linspace)` in `io/vasp/optics.py` `get_delta`, `get_setp` and `epsilon_imag`

pymatgen/io/vasp/sets.py, tests/io/vasp/test_sets.py
13883af9c use str.split for INHERITED_INCAR_PARAMS
9d6ee83cb add MatPESStaticSet init type hints
a89090aaf move ValueError Unrecognized {xc_functional=} to top
aeebf008f refactor MatPESStaticSet def incar(self) -> Incar:
bfd947676 leave user-defined ALGO if set, always apply LADU if xc_functional.upper().endswith("+U") and restore removing GGA tag if xc_functional.upper() == "R2SCAN"
5b7ab3fa3 fix test_functionals
=> MatPESStaticSet restore GGA tag removal if xc_functional.upper() == "R2SCAN"

.github/workflows/lint.yml, .pre-commit-config.yaml, dev_scripts/update_pt_data.py, pymatgen/alchemy/materials.py, pymatgen/alchemy/transmuters.py, pymatgen/cli/pmg_structure.py, pymatgen/core/operations.py, pymatgen/core/periodic_table.py, pymatgen/io/cssr.py, pymatgen/io/feff/inputs.py, pymatgen/io/fiesta.py, pymatgen/io/gaussian.py, pymatgen/io/nwchem.py, pymatgen/io/packmol.py, pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/outputs.py, pymatgen/io/zeopp.py, pymatgen/symmetry/settings.py, tasks.py, tests/core/test_operations.py, tests/io/test_gaussian.py
f01d38d14 rename variables: `toks->tokens`
42b7451e1 deprecate overlooked `from/as_..._string` methods (these were missed in https://github.com/materialsproject/pymatgen/issues/3230 and https://github.com/materialsproject/pymatgen/pull/3158 due to extra characters between `from_..._str`.
=> Deprecate overlooked `from/as_..._string` methods

pymatgen/io/vasp/inputs.py, pymatgen/io/vasp/sets.py, tests/io/vasp/test_inputs.py
The function `Kpoints.automatic_density_by_length()` takes in a sequence of values, e.g. `[50, 50, 1]`, to set the k-point density for each dimension. However, the function does not raise any kind of error if a sequence of dimensions != 3 is supplied.
This PR adds a `ValueError` if the `len` is != 3, along with a test for it.
```sh
```
=> Add an input arg check for `Kpoints.automatic_density_by_lengths`

pymatgen/io/gaussian.py, tests/files/.pytest-split-durations, tests/io/test_gaussian.py
Closes #3306.
013a1da58 add _parse_hessian method to GaussianOutput
55031490b snake_case vars
35c952e86 fix typo in test name: paramaters->parameters
=> Fix IndexError when parsing Hessian from Gaussian frequency job

CHANGES.md, docs/CHANGES.md, docs/_modules/pymatgen/analysis/substrate_analyzer.html, docs/_modules/pymatgen/analysis/topological/spillage.html, tests/io/cp2k/test_outputs.py, tests/io/test_adf.py, tests/io/test_ase.py, tests/io/test_fiesta.py, tests/io/test_xr.py, tests/io/test_xyz.py, tests/io/vasp/test_inputs.py, tests/util/test_coord.py
d3dbd5097 fix typo matricies -> matrices
ebad8c2d0 fix `TestVaspInput.test_write()` polluting repo dir
58925e5a9 `def setup()` -> `def setUp()`
=> Consistent casing setup -> setUp on all test classes

pymatgen/analysis/wulff.py, pymatgen/util/plotting.py, tests/analysis/test_wulff.py
Closes #3328.
As suggested by @goodwilling in https://github.com/materialsproject/pymatgen/issues/3328#issuecomment-1722076836. Thanks! 👍 
Applies to `BSPlotter.plot_brillouin()` and `WulffShape.get_plot()`.
=> Use `ax = fig.add_subplot(projection='3d')` to create `Axes3D`

pymatgen/analysis/interfaces/coherent_interfaces.py, tests/analysis/interfaces/test_coherent_interface.py
Closes #3334.
Fix accidental breaking change introduced in https://github.com/materialsproject/pymatgen/pull/3253 by reinstating explicit `atol=1e-08` (default for `np.allclose` whereas `np.testing.assert_allclose` sets this to 0).
=> Fix breaking change to `CoherentInterfaceBuilder.get_interfaces`

pymatgen/core/structure.py, pymatgen/io/ase.py
Addendum to #3264, notifying @gpetretto, @janosh.
Two things I think we missed in #3264:
* A formal `@property` so that we get a docstring for the new `IStructure.properties`
* An edge-case for backwards compatibility. While I strongly recommend people _do not_ use pickle as an archival format, nevertheless this is a very core pymatgen class, and I don't want to break people's workflows if they upgrade. Specifically, if you pickle a `Structure` from a previous pymatgen version, and then un-pickle it with the new pymatgen version, the `__init__` will not be called, so the `.properties` instance variable is never set: this will then break code that relies upon it, like `as_dict()`. Luckily, adding the `@property` interface allows us to trivially catch this edge case.
=> Add `properties` @property/docstring to `IStructure`

setup.py
=> Bump min `numpy` to v1.25.0

pymatgen/analysis/molecule_matcher.py
Thanks @munrojm for reporting. [This change](https://github.com/materialsproject/pymatgen/blame/4bff21d33625bc9f7077c7b4eb06098d1f50277c/pymatgen/analysis/molecule_matcher.py#L146) (although it improved code readability) caused errors in emmet CI.
=> Revert `openbabel.OBAlign()` in `molecule_matcher.py` to use positional args for `includeH`, `symmetry`

pymatgen/alchemy/materials.py, pymatgen/electronic_structure/boltztrap2.py, pymatgen/entries/computed_entries.py, pymatgen/ext/optimade.py, pymatgen/io/ase.py, pymatgen/io/vasp/outputs.py, tests/alchemy/test_filters.py, tests/command_line/test_gulp_caller.py, tests/ext/test_matproj.py, tests/files/.pytest-split-durations, tests/io/test_ase.py, tests/io/vasp/test_inputs.py, tests/io/vasp/test_sets.py
d919b591a fix typos
c1c9a1041 fix for loop overwriting hist variable in TransformedStructure.from_snl
596a56eea fix TestVasprun.test_update_potcar using wrong PotcarSingle hash: md5_computed_file_hash should be md5_header_hash
=> Fix `TestMPResterNewBasic` + `AseAtomsAdaptor` test errors and `TransformedStructure.from_snl` overwriting `hist` variable

.pre-commit-config.yaml, CHANGES.md, docs/CHANGES.md, setup.py, tasks.py
Adresses https://github.com/materialsproject/pymatgen/pull/3370#issuecomment-1746038525.
=> Fix missing `pymatgen/io/vasp/potcar_summary_stats.json.gz` in `setup.package_data`

.github/workflows/release.yml, pymatgen/alchemy/filters.py, pymatgen/core/structure.py, pymatgen/symmetry/analyzer.py, tests/test_pkg.py
```py
def test_egg_sources_txt_is_complete():
"""Check that all source and data files in pymatgen/ are listed in pymatgen.egg-info/SOURCES.txt."""
with open(src_txt_path) as file:
sources = file.read()
for src_file in sources.splitlines():
assert os.path.exists(src_file), f"{src_file!r} does not exist!"
for ext in ("py", "json", "json.gz", "yaml", "csv"):
for filepath in glob(f"pymatgen/**/*.{ext}", recursive=True):
if "/tests/" in filepath or filepath.endswith("dao.py"):
continue
if filepath not in sources:
>                   raise ValueError(
f"{filepath} not found in {src_txt_path}. check setup.py package_data for outdated inclusion rules."
)
E                   ValueError: pymatgen\alchemy\filters.py not found in pymatgen.egg-info/SOURCES.txt. check setup.py package_data for outdated …
```
=> `release.yml` add option to publish to TestPyPI

pymatgen/core/spectrum.py, pymatgen/io/lammps/data.py, pymatgen/io/lammps/generators.py, pymatgen/io/lammps/inputs.py, pymatgen/io/lammps/outputs.py, pymatgen/io/lammps/sets.py, pymatgen/io/lammps/utils.py, pymatgen/util/coord.py
Major changes:
- Added (some) type annotations to `io/lammps` and fixed some typos.
=> Add type annotations to io/lammps

pymatgen/io/vasp/inputs.py, tests/io/vasp/test_inputs.py
=> Add `test_potcar_summary_stats()`

pymatgen/analysis/chemenv/utils/scripts_utils.py, pymatgen/command_line/mcsqs_caller.py, pymatgen/io/cif.py, pymatgen/io/feff/sets.py, tests/files/.pytest-split-durations, tests/io/test_atat.py, tests/io/test_cif.py
=> Add `mode: Literal["w", "a", "wt", "at"] = "w"` keyword to `CifWriter.write_file()`

pymatgen/io/vasp/MatPESStaticSet.yaml, tests/io/vasp/test_sets.py
`LMAXMIX` is used to expand the charge densities up to spherical harmonics of order $Y_{lm}$ with $l$ = LMAXMIX, $l$ = 2 for p-block, 4 for d-block, 6 for f-block, etc.
Internal benchmarking by @esoteric-ephemera found little run time cost but improved energies from `LMAXMIX = 6`. See pages 7 and 8 in [2023-09-27-kaplan-bench-vasp-params.pdf](https://github.com/materialsproject/pymatgen/files/12873823/2023-09-27-kaplan-bench-vasp-params.pdf).
=> `MatPESStaticSet.yaml` set `LMAXMIX: 6`

pymatgen/io/lammps/data.py, pymatgen/io/lammps/inputs.py, pymatgen/io/lammps/outputs.py, pymatgen/io/lammps/sets.py, pymatgen/phonon/bandstructure.py, pymatgen/phonon/dos.py, pymatgen/phonon/ir_spectra.py, pymatgen/phonon/thermal_displacements.py
Major changes:
- Revert `Self` usage from #3393 and #3379 as mentioned by @janosh
=> Fix type annotations in phonon/ and lammps/

pymatgen/electronic_structure/cohp.py
This PR removes an out-dated warning from the cohp module.  It would be great if this could be merged. Thanks!
=> Remove warning in cohp module

pymatgen/symmetry/structure.py, tests/io/test_cif.py
Hi all, this is a small PR that makes sure labels are passed when a `SymmetrizedStructure` is initialized. This follows-up on earlier work in #3183 
Major changes:
- fix 1: Propagate site labels through `SymmetrizedStructure()`
```sh
```
=> Propagate site labels in `SymmetrizedStructure()`

.pre-commit-config.yaml, pymatgen/core/composition.py, tests/core/test_composition.py, tests/core/test_sites.py, tests/entries/test_compatibility.py, tests/io/exciting/test_inputs.py, tests/transformations/test_standard_transformations.py
Closes #3425.
Follow up to https://github.com/materialsproject/pymatgen/pull/3184 since that turns out to only have been a partial fix for not applying anion corrections to `ComputedEntries` with oxidation states.
The bug comes from `Composition` indexing behaving differently for `Elements`/`str` vs. `Species`. Currently:
```py
comp = Composition({"Li+": 2, "Mn3+": 2, "O2-": 4})
comp["Li"] == 0
```
This PR changes `comp["Li"]` to return 2 instead, i.e. return all species with matching symbol, regardless of oxidation state. Currently `comp["O"]` returns 0 and so no oxide correction is applied.
This is breaking. E.g. currently
```py
comp = Composition({"Mg": 1, "Mg2+": -1}, allow_negative=True)
comp["Mg"] == 1
```
which will change to return 0.
=> Breaking: return sum of `Species` with matching `Element` in `Composition.__getitem__`

pymatgen/ext/optimade.py
*Apropos* of nothing in particular... here is PR that makes some updates to the OPTIMADE client (and maybe starts a discussion about its future).
Major changes:
- Refreshes the baked-in OPTIMADE providers list with the latest new APIs
- Expands upon some of the docstrings
Happy to talk about how we could integrate the models and client at optimade-python-tools if that would be preferable. It would allow for async pulling data from all databases, pre-flight validating filters and validating responses (dangerous stuff for some databases...) and the code here could focus on just making sure the returned objects work with pymatgen. Should be releasing o-p-t v1.0 (https://github.com/Materials-Consortia/optimade-python-tools/issues/1831) before the end of the year which will support pydantic v2 …
=> Refresh OPTIMADE aliases and update docstrings

pymatgen/electronic_structure/plotter.py, tests/electronic_structure/test_bandstructure.py
Was plotting all element-projected band structures in the same subplot of a 2x2 figure.
=> Fix `BSPlotterProjected.get_elt_projected_plots` 

pymatgen/alchemy/materials.py, pymatgen/analysis/chemenv/utils/scripts_utils.py, pymatgen/core/structure.py, pymatgen/io/cif.py, pymatgen/io/feff/inputs.py, tests/analysis/magnetism/test_analyzer.py, tests/analysis/magnetism/test_jahnteller.py, tests/core/test_structure.py, tests/ext/test_matproj.py, tests/io/feff/test_inputs.py, tests/io/feff/test_sets.py, tests/io/test_cif.py, tests/io/test_core.py, tests/transformations/test_advanced_transformations.py
`CifParser.get_structures('some.cif')[0]` and `Structure.from_file('some.cif')` currently return different cells. And `primitive=True` seems like a bad default. Cell reduction seems like something the user should request explicitly.
This came up in the MP ingestion of new ICSD structures added since 2019 with @esoteric-ephemera.
@shyuep @mkhorton Let me know if you disagree.
=> Deprecate `CifParser.get_structures()` in favor of new `parse_structures` in which `primitive`  defaults to `False`

pymatgen/io/vasp/outputs.py, tests/files/.pytest-split-durations, tests/io/vasp/test_outputs.py
VASP will sometimes print "***********" when there's a float overflow. There's already a function in here to interpret these as `np.nan`, but it looks like it wasn't applied everywhere. I found one place where it wasn't used (ie just using Python's `float` function) that helped me process a large batch of `vasprun.xml`s correctly, but maybe the same function can be used elsewhere.
=> Fix Vasprun not interpreting float overflow as nan

pymatgen/analysis/structure_prediction/substitutor.py, pymatgen/core/composition.py, tests/analysis/structure_prediction/test_substitution_probability.py, tests/analysis/structure_prediction/test_substitutor.py, tests/analysis/test_local_env.py, tests/core/test_composition.py, tests/transformations/test_advanced_transformations.py
c47cf6d6c breaking: add `Substitutor.charge_balanced_tol: float = 1e-9` used in `_is_charge_balanced()`, prev had to be strictly 0
5945e95d5 refactor
723a56209 `Composition` add properties `charge` and `charge_balanced`
c5f8c7b71 Add `TestComposition.test_is_charge_balanced`
=> Add `Composition.charge and `charge_balanced` properties

pymatgen/analysis/structure_prediction/substitution_probability.py
Just saw this inconsistency by chance. The doc string claims the input are structures but then `get_el_sp` is used on the object.
=> Improve doc strings substitution_probability.py

pymatgen/io/aims/parsers.py, tests/io/aims/test_aims_parsers.py
Previously used voigt
Major changes:
- fix 1: all stresses are 3x3 now
=> Convert all FHI-aims stresses to be 3x3 instead of Voigt notation

pymatgen/ext/matproj.py
add trailing slash to all MPRester requests to avoid unnecessary redirects
=> Avoid redirects in `MPRester` requests

.pre-commit-config.yaml, pymatgen/analysis/adsorption.py, pymatgen/core/composition.py, pymatgen/electronic_structure/dos.py, pymatgen/symmetry/analyzer.py, pymatgen/symmetry/kpath.py, tests/analysis/solar/test_slme.py, tests/analysis/test_molecule_matcher.py, tests/analysis/test_structure_matcher.py, tests/core/test_structure.py, tests/io/abinit/test_inputs.py, tests/io/abinit/test_pseudos.py, tests/io/feff/test_inputs.py, tests/io/feff/test_sets.py, tests/io/test_res.py
5fe1c8e86f update ruff-pre-commit to v0.1.7
aa89d614e1 fic doc str indent
571f33e5c7 improve test_get_neighbor_list
0ffd0c9743 improve test_ebands_input
fd23063b88 improve asserts in test_get_feff_pot
=> Test improvements

pymatgen/io/vasp/sets.py, tests/io/vasp/test_sets.py
This implements the fix proposed in and closes #3492.
=> fix reciprocal_density in MPHSEBSSet and tests

pymatgen/core/structure.py, pymatgen/io/cif.py
This gets rid of unnecessary warnings where the user or `pymatgen` internal code is passing in `primitive=True` or `False` to `CifParser.parse_structures` explicitly and so doesn't need to be warned about a change in default value.
=> `CifParser` only warn about `primitive` default value change to `False` if not passed to `parse_structures` explicitly

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, pymatgen/phonon/plotter.py, tests/core/test_structure.py
90a26c5bfd bump actions/setup-python to v5
4d739850b4 add **kwargs to get_plot_gs() to customize ax.plot()
6e56052f00 rename single-letter vars
4e08e01165 add label kwarg PhononBSPlotter and to plot_compare method to show in legend
fe3973805b fix PhononDosPlotter.get_plot dropping default font size when passing **kwargs
=> `PhononBSPlotter.plot_compare()` add legend labels

pymatgen/phonon/dos.py, pymatgen/phonon/plotter.py, tests/phonon/test_dos.py
b98e12f21a `PhononBSPlotter.plot_compare()` add keyword `on_incompatible: Literal["raise", "warn", "ignore"] = "raise"`
314512682c add return type to `PhononDos` method doc strings
6072af8b2a define arithmetic dunder methods for `PhononDos` `__add__` `__sub__` `__mul__` `__neg__` `__eq__`
47addacb70 test `PhononDos` arithmetic ops and equality in
=> Define arithmetic ops `__add__` `__sub__` `__mul__` `__neg__` `__eq__` for `PhononDos` with tests

pymatgen/phonon/dos.py, pymatgen/phonon/plotter.py
669568ba48 make temp optional to allow falling back to t if temp not passed
cb7f2bc4d7 allow passing arbitrary kwargs into PhononDosPlotter.add_dos for use in e.g. color customization
64cd6ced61 change default line colors of PhononDosPlotter and PhononBSPlotter to tab:10
6deff781bd fix overlapping an non-symbol band struct x-labels
=> Equalize `Phonon(Dos|BS)Plotter` colors, allow custom plot settings per-DOS

pymatgen/analysis/chemenv/connectivity/connected_components.py, pymatgen/phonon/bandstructure.py, pymatgen/phonon/plotter.py, pymatgen/util/string.py, tests/analysis/chemenv/connectivity/test_connected_components.py, tests/files/.pytest-split-durations, tests/phonon/test_gruneisen.py
LaTeX ignores bold surrounding text for subscripts in math mode so need to specify `\mathbf` explicitly to get bold subscripts.
**Before**
**After (with `bold=True`)**
f91c0195c7 better var names
97cb2efc9b add bold flag to latexify to support bold subscripts
8952c923ab simplify tick generation in PhononBSPlotter._make_ticks
44233e327b add n_bands property to PhononBSPlotter
=> Add bold flag to `latexify`

pymatgen/core/composition.py, tests/core/test_composition.py
Controlled by new `strict: bool = True` parameter to `_parse_formula`.
=> `Composition` raise `ValueError` if `formula` string is only numbers and spaces

pymatgen/core/composition.py, tests/core/test_composition.py
=> Raise `ValueError` for `float('NaN')` in `Composition`

pymatgen/electronic_structure/bandstructure.py, pymatgen/phonon/bandstructure.py, pymatgen/phonon/dos.py, pymatgen/phonon/plotter.py, tests/phonon/test_bandstructure.py, tests/phonon/test_dos.py
@JaGeo Would be great to get your review on this, esp. the new `PhononDos.mae()` and `PhononBandStructure.has_imaginary_gamma_freq()` methods.
=> Add `PhononDos.mae()` and `PhononBandStructure.has_imaginary_gamma_freq()` methods

pymatgen/io/qchem/inputs.py
Documents the `svp` and `pcm_nonels` kwargs of `QCInput`. Closes #3432
=> QCInput: add docstrings for svp and pcm_nonels

pymatgen/phonon/dos.py, tests/electronic_structure/test_dos.py, tests/phonon/test_dos.py
47fc96b6fd PhononDos.get_smeared_densities add special case for 0 Gaussian smearing
7079c6134c remove unnecessary assignment in test_dos.py
c3681eafa1 test sigma=0 in TestPhononDos.test_get_smeared_densities
=> `PhononDos.get_smeared_densities` return density unchanged for `sigma=0`

pymatgen/phonon/dos.py, tests/phonon/test_dos.py
New method to find the last peak in the phonon DOS defined as the highest frequency with a DOS value at least `threshold` * height of the overall highest DOS peak. In case no peaks are high enough to match, the threshold is reset to half the height of the second-highest peak.
A peak is any local maximum of the DOS as a function of frequency. Use `dos.get_interpolated_value(peak_freq)` to get density at `peak_freq`.
8f6315dbc9 add PhononDos.get_last_peak()
e3b47947f1 add TestPhononDos.test_get_last_peak
=> Add `PhononDos.get_last_peak()`

pymatgen/core/structure.py, tests/core/test_structure.py
Hi all, another small PR that makes sure labels are passed when a `Symmetry.from_spacegroup` is used. This follows-up on an earlier PR: https://github.com/materialsproject/pymatgen/pull/3183
Major changes:
- fix 1: Fix label propagation in `Symmetry.from_spacegroup`
```sh
```
=> Fix label propagation in `Symmetry.from_spacegroup`

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
This pull request addresses suggestions made in issue #3449 by adding two new issue templates.
Major changes:
- Added a new issue template for "Bug Report."
- Included an issue template for "Feature Request," aligning it with the original issue template format.
Please feel free to provide any suggestions or feedback.
=> Add GitHub Issue Templates

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, docs/apidoc/conf.py, pymatgen/apps/battery/plotter.py, pymatgen/electronic_structure/plotter.py, pymatgen/vis/plotters.py, tests/apps/battery/test_plotter.py, tests/vis/test_plotters.py
**Original `SpectrumPlotter` in `pymatgen.vis.plotters`**
```python
def add_spectra(self, spectra_dict, key_sort_func=None):
"""
Add a dictionary of doses, with an optional sorting function for the
keys.
Args:
dos_dict: dict of {label: Dos}
key_sort_func: function used to sort the dos_dict keys.
"""
keys = sorted(spectra_dict, key=key_sort_func) if key_sort_func else list(spectra_dict)
for label in keys:
self.add_spectra(label, spectra_dict[label])
```
**Issue 1:** 
The original docstring suggests using the Dos object, but attributes x and y were already overridden to energies and densities in Dos, which caused the error:
```
AttributeError: 'Dos' object has no attribute 'x'
```
Although the `DosPlotter` is available to plot DOS, I think this function shouldn't be deprecated because it …
=> Bug fix: SpectrumPlotter.add_spectra

pymatgen/io/exciting/inputs.py, pymatgen/phonon/bandstructure.py, pymatgen/phonon/dos.py, pymatgen/phonon/plotter.py, tests/phonon/test_bandstructure.py
6087d5d90 PhononDos.get_last_peak reduce threshold value from 10% to 5%
8649e793a PhononBandStructure add max_freq() equivalent to min_freq() method
0dd35274e i->idx
d92f0e748 test_bandstructure.py add new test cases for (min|max)_freq
f77779c25 refactor symbol mapping in ExcitingInput and PhononBandStructure
dddd81e8b add get_gamma_point() method to PhononBandStructure
d16e6efa2 add test_get_gamma_point
878ef99b9 big improvement to has_imaginary_gamma_freq: check for negative frequencies at all q-points close to the gamma point, not just the gamma point itself
141679141 fix test_has_imaginary_freq in test_bandstructure.py
ac38d6572 PhononBandStructure add width() method
2b70e03d4 add test_width for PhononBandStructure
=> Improve `PhononBandStructure.has_imaginary_gamma_freq()` by checking for negative freqs at all q-points close to Gamma

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
Add default issue template labels, as I notice most recent issues are not assigned a label by the raiser, and also the prefix was removed as suggested by @janosh in #3528.
- Add default label "bug" for `Report a Bug`.
- Add default label "enhancement" for `Feature Request`.
=> Add default issue template labels 

.github/workflows/release.yml, .github/workflows/test.yml, .pre-commit-config.yaml, pymatgen/electronic_structure/plotter.py, pymatgen/phonon/dos.py, pymatgen/transformations/advanced_transformations.py, setup.py
I commented out BoltzTraP2 in `setup.py` util broken install is fixed, hopefully following merge of https://gitlab.com/sousaw/BoltzTraP2/-/merge_requests/18.
Pinging @esoteric-ephemera who helped troubleshoot this issue.
<details><summary>Install logs</summary>
```python
Collecting BoltzTraP2>=22.3.2 (from pymatgen==2023.12.18)
Downloading BoltzTraP2-22.12.1.tar.gz (81.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 MB 44.5 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [20 lines of …
```
=> Fix failing CI due to broken BoltzTraP2 install

pymatgen/core/structure.py, tests/core/test_structure.py
Closes #3551.
1a39d626f accept Path objects as filename in IStructure.to()
5afdf01c7 add test case for saving structure to pathlib.Path
=> Accept `Path` objects as `filename` in `IStructure.to()`

pymatgen/core/structure.py, pymatgen/io/abinit/abiobjects.py, pymatgen/io/abinit/variable.py, tests/core/test_structure.py, tests/io/abinit/test_inputs.py
734a8d24e retain Structure.properties in structure_from_abivars()/structure_to_abivars() round trip
4cd59493a test_structure.py add self.struct.properties["foo"] = "bar" for test_to_from_abivars()
=> Retain `Structure.properties` in `structure_from_abivars()`/`structure_to_abivars()` round trip

pymatgen/core/structure.py, tests/core/test_structure.py
96bbf50eb fix Structure.to(fmt='yml'), add Structure.FileFormats to ensure consistent format support and value err msg in Structure.to and Structure.from_file
02593cd21 test_structure.py cover fmt='yml' in test_to_from_file_string
=> Fix `ValueError: Invalid fmt` with `Structure.to(fmt='yml')`

pymatgen/core/lattice.py, pymatgen/core/structure.py, pymatgen/io/abinit/abiobjects.py, pymatgen/io/cp2k/sets.py, pymatgen/io/shengbte.py, pymatgen/io/vasp/sets.py, tests/core/test_structure.py, tests/io/abinit/test_inputs.py, tests/io/vasp/test_sets.py
f202b7970 deprecate Structure.ntypesp replaced by Structure.n_elems
8b893efb0 fix structure_to_abivars() for non-hexagonal structures
=> Deprecate `Structure.ntypesp` replaced by `Structure.n_elems`

pymatgen/core/structure.py, tests/core/test_structure.py, tests/electronic_structure/test_plotter.py
=> Lazy import `pandas` in `Structure.as_dataframe()` to improve startup speed

pymatgen/core/composition.py, tests/core/test_composition.py
Closes #3559.
9896133d3 fix highly-nested formula parsing in Composition
aca351cb4 add failure cases from gh-3559 as tests
=> Fix highly-nested parens when formula parsing in `Composition`

pymatgen/analysis/transition_state.py, tests/analysis/test_transition_state.py
closes #3523.
doesn't look like anything's actually broken in #3523 but still good to add a test.
=> Add test for `NEBAnalysis.get_plot()`

pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/ferroelectricity/polarization.py, pymatgen/analysis/graphs.py, pymatgen/analysis/structure_analyzer.py, pymatgen/analysis/surface_analysis.py, pymatgen/core/composition.py, pymatgen/core/ion.py, pymatgen/io/abinit/inputs.py, pymatgen/io/adf.py, pymatgen/io/lammps/data.py, pymatgen/io/vasp/outputs.py, tests/analysis/test_eos.py, tests/analysis/test_structure_matcher.py
5c1df065a breaking: remove PolarizationLattice which inherited from Structure (antipattern) and refactor get_same_branch_polarization_data()
e17322125 rename d|s vars
=> Breaking: remove single-use `PolarizationLattice` which inherited from `Structure` (antipattern)

.github/ISSUE_TEMPLATE/bug_report.yaml
The "Current behavior" section is formatted as Python code by default, which is super annoying since it should be text (and you don't see the Python formatting until after you post). I fixed it.
=> Fix text formatting in `bug_report.yaml`

.pre-commit-config.yaml, docs/assets/metadata.yml, pymatgen/analysis/bond_valence.py, pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/phase_diagram.py, pymatgen/io/abinit/netcdf.py, pymatgen/io/aims/sets/base.py, pymatgen/io/aims/sets/core.py, pymatgen/io/cp2k/utils.py, pymatgen/io/nwchem.py, pymatgen/io/qchem/outputs.py, pymatgen/transformations/site_transformations.py, pymatgen/util/graph_hashing.py, pymatgen/util/testing/__init__.py, tests/analysis/chemenv/coordination_environments/test_weights.py, tests/io/aims/test_aims_parsers.py
Adding the FHI-aims developers to the developers list
=> Adding FHI-aims inputs developers

pymatgen/analysis/chemenv/utils/scripts_utils.py, pymatgen/analysis/magnetism/analyzer.py, pymatgen/analysis/magnetism/jahnteller.py, pymatgen/analysis/xas/spectrum.py, pymatgen/core/structure.py, pymatgen/entries/entry_tools.py, pymatgen/io/feff/inputs.py, tests/alchemy/test_materials.py, tests/core/test_structure.py, tests/ext/test_matproj.py, tests/io/feff/test_inputs.py, tests/io/lammps/test_data.py, tests/io/test_jarvis.py, tests/io/vasp/test_outputs.py
just a convenience method to shorten frequently occurring
```py
struct.composition.reduced_formula -> struct.reduced_formula
```
=> Add `SiteCollection.reduced_formula` property

pymatgen/ext/optimade.py, tests/ext/test_optimade.py
Major changes:
- fix 1: 
- Fix URL joining in OptimadeRester. The original os.path.join function is not the correct function to use for joining URLs. It's designed for joining file paths, and its behavior depends on the operating system. On Windows, it uses a backslash (\) as the separator, while on Unix-based systems, it uses a forward slash (/). 
- This is a small fix, so no tests were added to 'test_optimade.py'
- This fix should resolve the issue reported at: https://matsci.org/t/could-not-retrieve-information-from-optimade/39469
None
- [N/A] Google format doc strings added. Check with `ruff`.
- [N/A] Type annotations included. Check with `mypy`.
- [N/A] Tests added for new features/fixes.
- [N/A] If applicable, new classes/functions/modules have …
=> Fix URL joining in OptimadeRester

pymatgen/core/structure.py, pymatgen/core/surface.py, tests/core/test_structure.py, tests/core/test_surface.py, tests/files/.pytest-split-durations
Non-breaking change but makes for a more functional API since modification methods can now be chained.
E.g. frequent use case of loading a file from disk/memory and directly applying an in-place modification previously required 2 lines:
```py
struct = Structure.from_file("path/to/file")
struct.add_oxidation_state_by_guess()
```
but can now be shortened to
```py
struct = Structure.from_file("path/to/file").add_oxidation_state_by_guess()
```
=> Return `self` from all `SiteCollection/Structure/Molecule` in-place modification methods

docs/installation.md
Closes #3629. I have always found the POTCAR setup instructions to be incredibly confusing, in part because some parts were never defined (e.g. `<MY_PSP>`) and in other parts because things are quite out-of-sync with the POTCAR structure offered by VASP as of the last several years. This is an attempt to make it clearer.
=> Make the POTCAR setup instructions clearer

pymatgen/command_line/bader_caller.py, tests/command_line/test_bader_caller.py
=> Fix `bader_analysis_from_path` using warning as file path and reinstate test

pymatgen/io/lobster/lobsterenv.py, tests/io/lobster/test_lobsterenv.py
=> [WIP] Lobsterenv improvements

pymatgen/analysis/local_env.py, pymatgen/core/structure.py
`_get_image` and `_get_original_site` do not need to recompute site and index when `site` is a `PeriodicNeighbor` which has them as attributes.
When there are several sites, this makes a significant difference on speed for `get_nn_info`
Alternative implementation would have been `try/except` and `hasattr`. `try/except` is much slower when most of the sites are not `PeriodicNeighbor`.
Major changes:
- feature: image and site index are not recomputed when they are already an attribute of the site
=> Speeding up `get_nn_info` in local_env.py

pymatgen/io/vasp/sets.py, tests/files/.pytest-split-durations, tests/io/vasp/test_sets.py
Closes #3633. Relaxing a metal with ISMEAR = 0 is fine, as noted in the VASP manual, provided SIGMA is sufficiently small (< 0.05 is the recommendation in the VASP manual).
> If you have no a priori knowledge of your system, for instance, if you do not know whether your system is an insulator, semiconductor or metal then always use Gaussian smearing ISMEAR=0 in combination with a small [SIGMA](https://www.vasp.at/wiki/index.php/SIGMA)=0.03-0.05.
=> Modify `BadInputSetWarning` logic for relaxations of a likely metal

pymatgen/io/ase.py, tests/io/test_ase.py
Hopefully closes #3644. Not sure if this is the approach you want to take.
It would be nice to add a test or linter rule that would have caught the initial issue.
=> Guard `MSONAtoms` definition behind ASE package availability

pymatgen/electronic_structure/bandstructure.py, pymatgen/phonon/bandstructure.py, pymatgen/phonon/plotter.py, tests/electronic_structure/test_bandstructure.py, tests/phonon/test_bandstructure.py
2231ec528c plotter.py and phonon band structure: improve doc strings + refactor
7c47053e32 Add Kpoint.__eq__ method
50efc02308 Add test for Kpoint equality
8b63b10640 Add PhononBandStructureSymmLine.__eq__ method
=> `Kpoint.__eq__` and `PhononBandStructureSymmLine.__eq__` methods + tests

.github/workflows/test.yml, pymatgen/command_line/bader_caller.py, tests/command_line/test_bader_caller.py
- Clean up `__init__` of `BaderAnalysis`
- Mark `parse_atomic_densities` in `BaderAnalysis` as deprecated, to be removed on 26 Feb 2025, as discussed in #3652.
=> Deprecate `_parse_atomic_densities` in `BaderAnalysis` and fix `Bader` test setup

pymatgen/analysis/surface_analysis.py, pymatgen/core/lattice.py, tests/core/test_lattice.py
Major changes:
- fix 1: I found a bug at `pymatgen/core/lattice.py::Lattice::get_niggli_reduced_lattice`.
- After updating lattice parameters at A1, variables `A, B, ...` also need to be updated.
- Otherwise, condition checking would be wrong at A2 or later.
- Therefore, I added a line for updating `A, B, C, E, N, Y`.
- This is not minimal, but the simplest I think.
- Also, added a test that fails before the fix and succeeds after the fix.
- Correct values were calculated by spglib.
If this is work in progress, what else needs to be done?
```sh
```
=> Fix `get_niggli_reduced_lattice` if entering A1 case

docs/installation.md
There was a missing ```, making the public docs look awful. I was the culprit. Oops. All patched!
=> Fix installation.md formatting

.pre-commit-config.yaml, dev_scripts/potcar_scrambler.py, pymatgen/analysis/chemenv/utils/scripts_utils.py, pymatgen/analysis/ferroelectricity/polarization.py, pymatgen/analysis/functional_groups.py, pymatgen/analysis/thermochemistry.py, pymatgen/apps/battery/plotter.py, pymatgen/cli/pmg_potcar.py, pymatgen/io/aims/outputs.py, pymatgen/io/aims/parsers.py, pymatgen/io/aims/sets/base.py, pymatgen/io/aims/sets/bs.py, pymatgen/io/aims/sets/core.py, pymatgen/io/cif.py, pymatgen/io/feff/outputs.py, pymatgen/io/lammps/utils.py, pymatgen/io/lmto.py, pymatgen/io/pwmat/__init__.py, pymatgen/io/vasp/inputs.py, pymatgen/symmetry/groups.py, pymatgen/util/io_utils.py, tests/analysis/diffraction/__init__.py, tests/apps/borg/test_queen.py, tests/command_line/test_bader_caller.py, tests/io/aims/test_sets/test_bs_generator.py, tests/io/aims/test_sets/test_gw_generator.py, tests/io/aims/test_sets/test_static_restart_from_relax_generator.py
A `BadPoscarWarning` was recently added to `pymatgen.io.vasp.inputs.Poscar` when the elements in the POSCAR are identified by the order of elements in the POTCAR file. Reading in the element names from POTCAR is valid VASP input, and it's [even permitted to omit the species names in POSCAR](https://www.vasp.at/wiki/index.php/POSCAR) because VASP reads them from POTCAR:
```This line lists the species of the present ions. The given order should match the order of species appearing in the POTCAR file. This line is optional, if omitted the species names are taken from the POTCAR file.```
This PR just removes the warning.
=> Remove BadPoscarWarning when POSCAR elements set by POTCAR

pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py, pymatgen/analysis/elasticity/elastic.py, pymatgen/analysis/ewald.py, pymatgen/analysis/graphs.py, pymatgen/analysis/interface_reactions.py, pymatgen/analysis/local_env.py, pymatgen/analysis/molecule_matcher.py, pymatgen/analysis/molecule_structure_comparator.py, pymatgen/analysis/phase_diagram.py, pymatgen/command_line/bader_caller.py, pymatgen/core/structure.py, pymatgen/entries/computed_entries.py, pymatgen/io/cif.py, pymatgen/io/cp2k/utils.py, pymatgen/io/lobster/outputs.py, pymatgen/io/vasp/optics.py, pymatgen/io/vasp/outputs.py, pymatgen/io/vasp/sets.py, pymatgen/symmetry/analyzer.py, pymatgen/transformations/advanced_transformations.py, pymatgen/vis/structure_vtk.py, tests/analysis/test_interface_reactions.py, tests/command_line/test_bader_caller.py, tests/io/vasp/test_outputs.py
we have a major problem with how deprecation removal reminders are currently setup for CI causing other package CI runs to fail. [in this case with](https://github.com/CederGroupHub/chgnet/actions/runs/8105153971/job/22153023416)
```py
E   RuntimeError: remove the change of default primitive=True to False made on 2023-10-24
```
this will affect any package using `pymatgen` in CI.
this PR solves the issue in two places `CifParser.parse_structures()` and `BaderAnalysis._parse_atomic_densities()`.
i'll make a hot-fix release right after this is merged. thanks @BowenD-UCB for reporting!
this poorly written code was added by me in https://github.com/materialsproject/pymatgen/commit/9e27ca89b01de23c0088b3d631f85f489a4a5fb7 and released in …
=> Fix RuntimeError triggered in CI of downstream packages

pymatgen/io/ase.py, tests/io/test_ase.py
Closes https://github.com/materialsproject/pymatgen/issues/3668.
The `Atoms.info` dictionary can be populated with all kinds of goodies that are challenging to deal with from a (de)serialization perspective. Oftentimes, this is from users hacking things into `Atoms.info`. For instance, in #3668, I put a `Structure` object in the `Atoms.info` dictionary, which then broke things during serialization. In order to ensure `MSONAtoms` plays nice with the (de)serialization routines in `monty`, it is better to split off the `Atoms.info` metadata into its own entry in the `.as_dict()` dictionary that we can sanitize ourselves. That's what I've done in this PR.
The following toy example now works in a round-trip fashion:
```python
from pymatgen.core import Structure
from monty.serialization import …
```
=> Ensure `MSONAtoms` is indeed `MSONable` when `Atoms.info` is loaded with goodies

pymatgen/io/res.py, tests/io/test_res.py
This PR fixes two bugs in the res writer:
- Fix 1: Add a blank line at the end of the file
- Fix 2: Do not write a blank line if REMS is empty
Closes #3636
```sh
```
=> Fix blank line bug in `io.res.ResWriter`

pymatgen/analysis/phase_diagram.py, pymatgen/core/sites.py, pymatgen/core/structure.py, tests/core/test_sites.py, tests/core/test_structure.py
This PR resets the label on any site changed by `Structure.replace_species()`. `Site.label` will fall back to use the default label instead (the species string).
Closes #3658
```sh
```
=> Reset label for sites changed by `Structure.replace_species()`

.github/workflows/release.yml, .github/workflows/test.yml, pymatgen/transformations/advanced_transformations.py, tests/core/test_structure.py, tests/transformations/test_advanced_transformations.py
hoping the migration to `uv`, besides being faster than `pip`, can also fix the CI import errors for `matgl` and `pydantic` that started 2 days ago. not optimistic about `pydantic` which shouldn't be imported by pymatgen or any of its deps anyway but maybe `matgl`.
related PR: https://github.com/CederGroupHub/chgnet/pull/133
=> Migrate CI dependency installation from `pip` to `uv`

pymatgen/analysis/pourbaix_diagram.py, pymatgen/analysis/reaction_calculator.py, pymatgen/apps/battery/conversion_battery.py, tests/analysis/test_reaction_calculator.py
- Replace a hard coded hash `7` with proper hash method, see #3673.
The necessity of such method is unclear meanwhile.
=> Add hash for BalancedReaction

pymatgen/io/phonopy.py, tests/io/test_phonopy.py
Major changes:
- fix 1: Change key in  get_pmg_structure from magnetic_moments to magmom
- fix 2:  add unit test `assert struct_pmg_round_trip.site_properties["magmom"] == struct_pmg.site_properties["magmom"]`
```sh
```
=> Fix `phonopy.get_pmg_structure` `site_properties` key for magmoms

.github/workflows/jekyll-gh-pages.yml, .github/workflows/test.yml, pymatgen/cli/pmg_config.py
`.github/workflows/jekyll-gh-pages.yml` run on forked repository, and caused CI fails if the forked repository is not set up  for GitHub Pages (e.g. https://github.com/lan496/pymatgen/actions/runs/8325702971).
As the CI for testing is already disabled on forked (https://github.com/materialsproject/pymatgen/commit/531561d8d1dd55b3104d923c585861340c2223f0), I think it will be reasonable to disable CI for Github Pages as well.
=> Prevent GitHub Actions from running document related CIs on forks

pymatgen/io/xcrysden.py, tests/io/test_xcrysden.py
XSF allows you to append a vector after the positions (usually forces). This makes it easier to visualize phonons with VESTA.
=> Support appending vectors to positions in XSF format

pymatgen/core/structure.py, tests/core/test_structure.py, tests/files/.pytest-split-durations
allows chaining these methods which returned `None` before. updated tests to `assert returned is self` and added a new test for `Structure.replace()` which was missing coverage
=> Return `self` from `Structure` methods `replace`, `substitute`, `remove_species`, `remove_sites`

.github/workflows/jekyll-gh-pages.yml, .github/workflows/test.yml, pymatgen/core/lattice.py, pymatgen/util/typing.py, tests/core/test_lattice.py, tests/util/test_typing.py
define new type `PbcLike = tuple[bool, bool, bool]`. improve tests for `typing` module
=> `Self` return type on `Lattice` methods

pymatgen/phonon/gruneisen.py
I have clarified the description of the average Grüneisen paramter.
=> Update to average Grüneisen documenation

pymatgen/core/lattice.py, tests/core/test_lattice.py
=> Homogenize return type of `Lattice.get_points_in_sphere` to always be `np.array`(s)

pymatgen/apps/borg/queen.py, pymatgen/electronic_structure/bandstructure.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/adf.py, pymatgen/phonon/plotter.py, pymatgen/symmetry/kpath.py, pymatgen/transformations/site_transformations.py, tests/electronic_structure/test_bandstructure.py, tests/electronic_structure/test_plotter.py
closes #3760
**before**
**after**
there were multiple issues in `BSPlotterProjected.get_projected_plots_dots`: all subplots were plotted into the 1st axes. the large axis labels from `pretty_plot` were applied to the whole figure, not the individual subplots
ran out of time on this fix but noticed that the fat lines in the `Cu d` still look off. like it's still overlaying multiple band structures. maybe someone else has time to take a look @DanielYang59 @JaGeo? also @HERTZCAI could you comment on what output you're expecting and share the `vasprun.xml` file you were plotting in #3760
=> Fix overlayed subplots in `BSPlotterProjected.get_projected_plots_dots()`

pymatgen/command_line/chargemol_caller.py, tests/command_line/test_chargemol_caller.py
Major changes:
- fix 1: _get_dipole_info was previously getting the y and z component and the magnitude instead of x,y and z. The only test case was 0,0,0 so it was never noticed.
Previously the dipole was only checked for the spin unpolarized structure with no dipoles (I added some extra spaces to make it more readable what is dipole and what is dipole_magn):
```
atom number,   atomic symbol,      x,           y,           z,     _ net_charge,     dipole_x,   dipole_y,     dipole_z, dipole_mag, Qxy, Qxz, Qyz,Q(x^2-y^2), Q(3z^2 - R^2), three eigenvalues of traceless quadrupole moment tensor
1                     Na     0.000000     0.000000     0.000000     0.843200     0.000000     0.000000    -0.000000     0.000000    -0.000003    -0.000003    -0.000003     0.000000     0.000000 …
```
=> Fix `_get_dipole_info` for DDEC6 `ChargemolAnalysis` and add test case

pymatgen/core/composition.py, pymatgen/core/periodic_table.py, tests/core/test_periodic_table.py
Major changes:
* This PR adds an `is_radioactive` property to the `Element` class which allows users to check if an Element is radioactive.
* The `contains_element_type` method in the `Composition` class has radioactive as a possible category added, so users can check if a composition contains radioactive elements.
Feature motivation:
Motivated by a recent publication (https://pubs.acs.org/doi/10.1021/acs.chemmater.4c00643) which identifies that some of the discovered compounds in the GNoME database (https://github.com/google-deepmind/materials_discovery) contain radioactive elements, it would be useful to be able to screen out compositions containing radioactive elements or to be able to characterise how many radioactive compositions exist in a dataset of compositions/structures.
* Agree …
=> Add `is_radioactive` property to Element class

.pre-commit-config.yaml, pymatgen/analysis/eos.py, pymatgen/analysis/transition_state.py, pymatgen/core/sites.py, pymatgen/electronic_structure/plotter.py, pymatgen/io/abinit/inputs.py, pymatgen/io/abinit/pseudos.py, pymatgen/io/aims/inputs.py, pymatgen/io/ase.py, pymatgen/io/feff/inputs.py, pymatgen/io/lobster/inputs.py, pymatgen/io/pwmat/inputs.py, pymatgen/io/xcrysden.py, pymatgen/util/provenance.py, pymatgen/util/testing/aims.py, pymatgen/vis/structure_vtk.py, tests/analysis/test_interface_reactions.py, tests/analysis/test_molecule_matcher.py
simplified code plus some minor logging fixes
=> `ruff` 0.4.3 auto-fixes

pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py, pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py, pymatgen/analysis/ferroelectricity/polarization.py, pymatgen/analysis/magnetism/analyzer.py, pymatgen/command_line/gulp_caller.py, pymatgen/command_line/mcsqs_caller.py, pymatgen/core/composition.py, pymatgen/core/ion.py, pymatgen/core/lattice.py, pymatgen/core/molecular_orbitals.py, pymatgen/core/operations.py, pymatgen/core/periodic_table.py, pymatgen/core/sites.py, pymatgen/core/spectrum.py, pymatgen/core/structure.py, pymatgen/core/tensors.py, pymatgen/core/xcfunc.py, pymatgen/io/cp2k/inputs.py, pymatgen/io/cssr.py, pymatgen/io/fiesta.py, pymatgen/io/qchem/outputs.py, pymatgen/io/xr.py, pymatgen/io/zeopp.py, pymatgen/phonon/bandstructure.py, pymatgen/transformations/advanced_transformations.py, tests/core/test_operations.py, tests/core/test_structure.py, tests/core/test_trajectory.py, tests/core/test_units.py, tests/io/test_cif.py
- Add/improve types for `core`
- Replace hard-coded class call with `type(self)`
- Replace all `[0:x]` with `[:x]`
- Use `type(self)` to avoid hard-coded class name in `__eq__` and similar methods
=> Add types for `core.(molecular_orbitals|operations|sites|spectrum|tensor|xcfunc)`

docs/installation.md
See https://github.com/materialsproject/pymatgen/issues/3830 for more details.
=> Fix the minor document error in `POTCAR Setup`.

pymatgen/io/lammps/data.py, pymatgen/io/lammps/outputs.py, pymatgen/io/xyz.py, pymatgen/util/provenance.py
Major changes:
- fix 1: Replace deprecated `delim_whitespace=True` with `sep="\s+"` (see https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)
=> `pandas.read_csv`: replace deprecated `delim_whitespace=True` with `sep="\s+"`

pymatgen/io/cif.py, setup.py, tests/io/test_cif.py
- Fix a mistake in #3819, where the `filter` condition is incorrect, and also cast `filter` to `list`.
- Add unit test for this error message
=> Fix filter condition for warn msg of unphysical site occupancy in `io.cif`

.github/workflows/test.yml, pymatgen/io/vasp/inputs.py, tests/io/vasp/test_inputs.py, tests/io/vasp/test_sets.py
the current `PotcarSingle.functional_dir` hard-codes the subfolder structure of `PMG_VASP_PSP_DIR`. e.g. the subfolder containing the `PBE_64` POTCARs _must_ be named `POT_PAW_PBE_64`. this causes problems e.g. in cases where the POTCARs are shared across an HPC cluster and users don't have permissions to rename shared files (just happened to me).
https://github.com/materialsproject/pymatgen/blob/232fa1f842d1078dd69d8d1631b4dd19a9b35c2f/pymatgen/io/vasp/inputs.py#L1757-L1779
the new setting is read from `.pmgrc.yaml` and overrides the `PotcarSingle.functional_dir` names (leaving unspecified ones as is). example:
```yaml
PMG_VASP_PSP_DIR: /path/to/pseudo-potentials
PMG_VASP_PSP_SUB_DIRS:
PBE_64: MY_PBE_64_DIR
LDA_64: MY_LDA_64_DIR
```
this PR implement the new setting, adds tests for it …
=> Add new `.pmgrc.yaml` setting `PMG_VASP_PSP_SUB_DIRS: dict[str, str]`

pymatgen/core/periodic_table.py, tests/core/test_periodic_table.py
Simple bug fix for when elements have non-integer oxidation states assigned to them. Pymatgen can assign non-integer charges to sites, but when trying to initialize `Species` with non-integer oxidation state:
```
from pymatgen.core import Species
Species("C0.25+")._oxi_state
```
this raises an `AttributeError`.
This PR fixes that bug and adds test cases to `tests/core/test_periodic_table.test_symbol_oxi_state_str`.
=> Bug fix: handle non-integer oxidation states in `Species`

pymatgen/io/ase.py
Broader context: This PR basically impacts nobody and is just a marginally safer way to index the `MSONAtoms` info key when parsing the dictionary representation.
Technical details: As noted by @samblau, if for some reason your `MSONAtoms.as_dict()` representation no longer has an `atoms_info` key, then doing `MSONAtoms.from_dict()` will crash. In virtually all cases, the user will have an `atoms_info` key, but it's pretty trivial to fix this by doing `.get(dct["atoms_info"], {})` instead of `dct["atoms_info"]`, so I've done that here.
=> Slightly more robust `MSONAtoms` handling

pymatgen/entries/compatibility.py, tests/entries/test_compatibility.py
This PR relates to the `MaterialsProject2020Compatibility` scheme, and cases in which structures might be heavily over-stabilized in error, leading to unrealistic structures potentially being placed on the convex hull.
In brief,
* Anion corrections are applied in cases where an element may not be an anion.
* This can happen either because (1) oxidation states are not known, and it is assumed to be an anion based on the element being the most electronegative element present or (2) `oxi_state_guesses` might give a very small fractional oxidation state in the range (-1, 0).
* Case (1) was decided as a conservative choice due to unreliability of oxidation state guessing.
* Case (2) I think was not considered, since this is not typically encountered in realistic materials.
During exploratory …
=> Add `strict_anions` option to `MaterialsProject2020Compatibility`

pymatgen/io/vasp/outputs.py
Major changes:
- This PR solved the issue in #3780 
`pymatgen` automatically converts the input `ALGO` to the leading capitalized format, e.g. `GW0` will be converted to `Gw0` and written to `vasprun.xml`. In such case, `Vasprun` would fail to parse the results. In this PR, I fixed this bug. 
Tagging @mkhorton for awareness.
=> Bug fix: fixed the leading capitalized ALGO in Vasprun

pymatgen/core/structure.py, pymatgen/symmetry/analyzer.py, tests/symmetry/test_analyzer.py
`spglib` will not raise if symmetry cannot be determined, but will instead return `None`. This is not currently handled in `SpacegroupAnalyzer`.
As a result, a common issue encountered is calling `Structure.get_space_group_info` for a structure  where symmetry cannot be determined leading to an opaque `ValueError` from a non-sensical subscript (`None["international"]`). With this change, an error will now be raised which can be handled appropriately by the end user.
=> Add `SymmetryUndetermined(ValueError)` exception type

pymatgen/entries/computed_entries.py, tests/entries/test_computed_entries.py
In `pymatgen.entries.computed_entries`, `ComputedEntry` takes three optional fields: `energy_adjustments`, `parameters`, `data`, which are not correctly read in by its `from_dict` method. This is because, for example:
```
parameters = {k: MontyDecoder().process_decoded(v) for k, v in (dct.get("parameters", {})}
```
will throw `AttributeError: 'NoneType' object has no attribute 'items'` if the input `ComputedEntry` dict has `parameters = None`.
Because the typing of `ComputedEntry` suggests that these fields can be `None`, this PR ensures that the `from_dict` can properly handle null fields and also ensures correct param defaults (`energy_adjustments` incorrectly defaults to an empty `dict` instead of `list`).
Also added a test for this behavior. cc @tsmathis who found this behavior
=> Bug fix for ComputedEntry from_dict

src/pymatgen/phonon/plotter.py, tests/phonon/test_gruneisen.py
This new functionality was initially implemented as part of ongoing workflow development for computing the Grüneisen parameter in atomate2, see https://github.com/materialsproject/atomate2/pull/752
As it mainly relies on the pymatgen code with minor additions, I think it would be appropriate if the code resides here. 
1. Added an option to get phonon bandstructure colored based on Grüneisen parameter values along the K-path in `GruneisenPhononBSPlotter`. 
2. Added `plot_ph_bs_with_gruneisen`  arg to `save_plot_gs `and `get_plot_gs` methods
3. Added tests to ensure the functionality works as expected
=> add option to color phonon bands as per gruneisen parameter value

src/pymatgen/analysis/phase_diagram.py, tests/analysis/test_phase_diagram.py
- modularize the keep redundant spaces code, and fix the algorithm which previously didn't get rid of all the redundant spaces.
=> Improve Keep Redundant Spaces algorithm for PatchedPhaseDiagram

pyproject.toml, tests/core/test_structure.py
- A hot fix for #3928, where the `setuptools` in not configured to include the complete `pymatgen` package (all subpackages are missing) after moving to the src layout.
- Turn off `include-package-data`, which [is `true` by default](https://setuptools.pypa.io/en/latest/userguide/datafiles.html), meaning `package-data` is not having any effect and all data files would be included into the package.
- Remove resolved skip tag: https://github.com/materialsproject/pymatgen/blob/02341828b94a001b4f3cbdae6b24eaeeb0df7d7d/tests/core/test_structure.py#L1771
To reliably recreate this issue, one might need to [completely clear build cache](https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#caching-and-troubleshooting) (removing `build/`, `dist/` and `*.egg-info`), otherwise you might …
=> [Hot Fix] Fix `setuptools` for pymatgen packaging

src/pymatgen/analysis/magnetism/jahnteller.py, src/pymatgen/core/periodic_table.py, tests/core/test_periodic_table.py, tests/io/vasp/test_inputs.py
This is a follow up to #3902 to address an inconsistent behavior I encountered. The major change in this PR is that `full_electronic_structure` is now always returned as a sorted list according to the Madelung rule, so that the final element is always the valence shell. Prior to this PR, this was sometimes but not always the case, as I elaborate below.
Major changes:
- `Element` and `Species.full_electronic_structure` are now sorted by increasing energy level according to the Madelung rule
- Updated and expanded unit tests to ensure `valence` and `full_electronic_structure` both work as expected
- Minor changes to crystal field methods and associated unit tests to accommodate the sorting.
- (indirectly related): added a `n_electrons` property to `Species` and `Element`
As we discussed in …
=> Element/Species: order full_electron_structure by energy

.pre-commit-config.yaml, src/pymatgen/io/vasp/outputs.py
- Correct method `get_projection_on_elements` docstring of `Procar` class, where the band index and kpoint index is reversed.
https://github.com/materialsproject/pymatgen/blob/27d90b777cedc80593d93b6e8b66dee04c167460/src/pymatgen/io/vasp/outputs.py#L3915-L3916
=> Correct method `get_projection_on_elements` docstring under `Procar` class

src/pymatgen/core/__init__.py, tests/core/test_settings.py
the hard-coded settings path in the user's home directory poses a problem when running on compute nodes that only have access to the scratch file system, not the `/home` fs. this PR provides an escape hatch for such cases
=> Allow custom `.pmgrc.yaml` location via new `PMG_CONFIG_FILE` env var

src/pymatgen/analysis/graphs.py, tests/analysis/test_graphs.py
Refer to #3888 
The `StructureGraph` object assumes that periodic images of the edges will added twice in the graph so the coordination number algorithm assumes that all self-connections are double-counted.
However, we have updated the definition of the graph such that periodic images of the same edge will only appear once (ie. if `SiteA[0,0,0]--SiteA[0,0,1]` is an edge, we should not see another edge from  `SiteA[0,0,0]--SiteA[0,0,-1]`)
I have also removed the double counting from MoleculeGraph under the assumption that self-connection should never show up in a molecule.
The two of the edges added here are redundant:
https://github.com/materialsproject/pymatgen/blob/98c57888cc4f17ef4d8692d777ad0d1806ee7ae9/tests/analysis/test_graphs.py#L53-L56
But the coordination number should still be …
=> Fix coordination number bug

src/pymatgen/core/tensors.py
an attr access interface change was missed in Tensor when spglib was upgraded to >=2.5.0 (#3923)
spglib throws the following deprecation warning currently:
`DeprecationWarning: dict interface (SpglibDataset['transformation_matrix']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead`
=> switch to attr access interface for transformation matrix

.github/workflows/issue-metrics.yml
Major changes:
- `issue-metrics` should not be run on forks because it can't create a new issue on the fork anyway.
=> Don't run `issue-metrics` on forks

.github/workflows/test.yml, pyproject.toml, src/pymatgen/io/vasp/incar_parameters.json, src/pymatgen/io/vasp/inputs.py, tests/core/test_structure.py, tests/io/vasp/test_inputs.py
- Fix Incar `check_params` for `Union` type, to fix #3957, changed `incar_parameters.json` of Union type to use `isinstance` syntax directly. Otherwise Python 3.9 Windows don't support type checking with `isinstance(data, Union[str, float])`.
**Would appreciate it if anyone has smarted way to resolve this!**
- Bump `palettable` version to remove dependency of `setuptools` https://github.com/jiffyclub/palettable/pull/46
=> Fix Incar `check_params` for `Union` type 

src/pymatgen/core/trajectory.py, tests/core/test_trajectory.py
When indexing a trajectory the site properties would be assigned to the structure/molecule but the frame properties would not be propagated down to the structure/molecule in question.
=> Assign frame properties to molecule/structure when indexing trajectory

src/pymatgen/analysis/structure_prediction/substitution_probability.py, src/pymatgen/core/periodic_table.py, src/pymatgen/entries/compatibility.py, src/pymatgen/entries/mixing_scheme.py, src/pymatgen/io/packmol.py, src/pymatgen/symmetry/analyzer.py, src/pymatgen/transformations/site_transformations.py, src/pymatgen/util/io_utils.py
- Fix `mypy` errors on master branch, to fix #3976
- Docstring tweaks
=> Fix `mypy` errors on master branch

src/pymatgen/core/ion.py, tests/core/test_ion.py
My recent PR #3942 contained two bugs that were revealed by testing in downstream code (see [pyEQL PR](https://github.com/KingsburyLab/pyEQL/pull/169#issuecomment-2278396689)). This PR fixes those and expands the unit tests to catch them.
```
>>> Ion.from_formula('CO2-').reduced_formula
'C2O4[-0.5]'
>>> Ion.from_formula('CO2--').reduced_formula
'C2O4[-1]'
```
```
>>> Ion.from_formula('I3-').get_reduced_formula_and_factor()
('I3', 1.0)
>>> Ion.from_formula('I-').get_reduced_formula_and_factor()
('I3', 0.3333333333333333)
```
=> Ion: fix CO2- and I3- parsing errors; enhance tests

src/pymatgen/io/pwscf.py, src/pymatgen/util/io_utils.py, tests/io/test_pwscf.py
Add optional keyword argument `format_options` of type `dict`, which specifies
- `indent`: # of spaces for indentation (defaults to 2)
- `kpoints_crystal_b_indent` # of spaces for indentation in `K_POINTS` card with `crystal_b` option (defaults to 1)
- `coord_decimals`: # of decimal digits for structure information (atomic position coordinates, lattice vector coordinates; defaults to 6)
- `atomic_mass_decimals`: # of decimal digits for atomic mass under `ATOMIC_SPECIES` card (defaults to 4)
- `kpoints_grid_decimals`: # of decimal digits for k-point reciprocal lattice coordinate values in `K_POINTS` card with `crystal_b` option (defaults to 4)
as keys. The default values are chosen to maintain the same output format as before the change.
This PR aims to close #4000
=> Formatting customization for `PWInput`

src/pymatgen/io/vasp/inputs.py, src/pymatgen/io/vasp/sets.py
This is a small patch improving error message when writing VASP input without VASP installation.
The original message thrown by Potcar constructor is very generic and sounds like VASP _must_ be installed:
pymatgen.io.vasp.inputs.PMG_VASP_PSP_DIR_Error: No POTCAR for H with functional='PBE' found. Please set the PMG_VASP_PSP_DIR in .pmgrc.yaml.
The new message highlights the existance of `potcar_spec` argument:
ValueError: PMG_VASP_PSP_DIR is not set.  Please set the PMG_VASP_PSP_DIR in .pmgrc.yaml or use potcar_spec=True argument.
(used pre-commit hook)
=> VaspInputSet.write_input: Improve error message

.pre-commit-config.yaml, tests/core/test_xcfunc.py, tests/entries/test_mixing_scheme.py, tests/io/aims/test_aims_parsers.py, tests/io/qchem/test_outputs.py, tests/io/test_openff.py, tests/test_cli.py
- Fix failing ruff `PT001` on master
- Bump `ruff` version in pre-commit
@shyuep please review this, thanks!
=> Fix failing ruff `PT001` on master

pyproject.toml, tests/io/vasp/test_optics.py
https://github.com/scipy/scipy/issues/21052 has been fixed and released in scipy 1.14.1. This PR removes the skip mark.
If this is work in progress, what else needs to be done?
- feature 2: ...
- fix 2:
```sh
```
=> Remove the skip mark for test_delta_func

tests/analysis/chemenv/coordination_environments/test_coordination_geometry_finder.py, tests/analysis/test_molecule_structure_comparator.py, tests/analysis/test_surface_analysis.py, tests/command_line/test_critic2_caller.py, tests/core/test_structure.py, tests/electronic_structure/test_boltztrap.py, tests/electronic_structure/test_boltztrap2.py, tests/electronic_structure/test_dos.py, tests/ext/test_matproj.py, tests/io/lobster/test_lobsterenv.py, tests/io/vasp/test_inputs.py, tests/io/vasp/test_sets.py, tests/phonon/test_dos.py
- Recover commented out code in tests and mark with `pytest.mark.skip` instead (with `TODO: need someone to fix this` message for easy search), though currently [`ERA`](https://docs.astral.sh/ruff/rules/commented-out-code/) is ignored: https://github.com/materialsproject/pymatgen/blob/c06abf1a3c8d1507d9b128a91b51babbca650ab9/pyproject.toml#L192
Commented out code ages badly if not covered by any linter, perhaps we should mark them with `pytest.mark.skip` instead until someone come and fix them (hopefully).
=> Recover commented out code in tests and mark with `pytest.mark.skip` instead

src/pymatgen/io/lobster/outputs.py
- Fix incorrect attribute name in `Lobster.outputs.Cohpcar` docstring, `orb_cohp` -> `orb_res_cohp`
https://github.com/materialsproject/pymatgen/blob/edcd4654cc5048d7f0f00417d82755d98b03b739/src/pymatgen/io/lobster/outputs.py#L261
```python
from pymatgen.io.lobster.outputs import Cohpcar
cohp = Cohpcar(filename="COHPCAR.lobster")
print(dir(cohp))
```
```['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get_bond_data', 'are_cobis', 'are_coops', 'are_multi_center_cobis', 'cohp_data', …
```
=> Fix incorrect attribute name in `Lobster.outputs.Cohpcar` docstring

src/pymatgen/io/vasp/inputs.py, src/pymatgen/io/vasp/sets.py
`PMG_VASP_PSP_DIR_Error` is a class and hence should use PascalCase.
no downstream effects expected from this (strictly speaking) breaking change. 
`PMG_VASP_PSP_DIR_Error` was only added 3 weeks ago in https://github.com/materialsproject/pymatgen/pull/3999 and [the last release](https://github.com/materialsproject/pymatgen/releases/tag/v2024.8.9) was a month ago.
=> Pascal-case `PMG_VASP_PSP_DIR_Error`

src/pymatgen/io/vasp/inputs.py, tests/io/vasp/test_inputs.py
=> Fix in-place `VaspInput.incar` updates having no effect if `incar` is dict (not `Incar` instance)

src/pymatgen/io/aims/inputs.py
As recommended by @janosh in #3878
Major changes:
- Make AimsSpeciesFile a dataclass
=> Make AimsSpeciesFile a dataclass

src/pymatgen/core/structure.py, tests/core/test_structure.py
`Structure.apply_operation()` fails when using the `fractional=True` operation.
The issue is that the ``SymmOp`` is applied to the site frac coords (in the original lattice), but then these new frac coords (in the old basis) are used directly with the new (transformed) lattice, giving a 'doubled' transformation and messing with the output.
Fix added here, matching the implementation in [`doped`](https://github.com/SMTG-Bham/doped/blob/develop/doped/utils/symmetry.py#L211) (which also has a couple more options and a cleaner implementation).
MWE:
(Notebook and structure being used attached too as always 😉 , with more examples)
[Pymatgen_SymmOp_Fix_PR.zip](https://github.com/user-attachments/files/16934325/Pymatgen_SymmOp_Fix_PR.zip)
=> Fix `apply_operation(fractional=True)`

.github/workflows/test.yml
- [Use `setup-uv` in CI tests workflow](https://docs.astral.sh/uv/guides/integration/github/), to close #4044
The following word "native" refers to package installed by native github action setups: `setup-Python/micromamba/uv`
**NOTE**: `setup-uv` installer might provide caching function, so the run time might be slower for the first run
Time (in seconds)  is reported on the `Install pymatgen and dependencies` stage for "split 1", excluding conda and optional Ubuntu dependencies 
|                           | Ubuntu 22.04 | Windows 11 | MacOS |
|---------------------------|--------------|------------|-------|
| native mamba + pip        |        88      |      235      |   26    |
| native mamba + uv         |         85     |      150      |    28   |
| native mamba + native uv (first …
=> (Not) Use `setup-uv` in CI tests workflow

src/pymatgen/analysis/phase_diagram.py
This PR fixed the break of phase diagram plot caused by commit 41e6d99 which made changes not only to syntax but also plotting logic without careful review. This is a small fix but did require human hour to track down the issue, and caused downstream breakage on MP website and for pymatgen users who plot phase diagrams.
=> fix phase diagram break from 41e6d99

src/pymatgen/analysis/chempot_diagram.py
A strange behavior was caught for chemical potential diagram where the planes were crossed. 
Using the in-place [assignment expression](https://github.com/materialsproject/pymatgen/blob/150f816c55be80dd146cb20ebbf5f930633c8aeb/src/pymatgen/analysis/chempot_diagram.py#L649), the plot shows below: 
It it not obvious how it could cause the breakage. I spent sometime debugging but with no luck, it could be something much deeper. For now I suggest we revert it to the original form till we have a real solution. Would much appreciate a quick release due to breakage for MP...
=> fix chempot_diagram

src/pymatgen/io/vasp/outputs.py
Major changes:
This PR fixes the bug when parsing non-self-consistent calculation done with `ALGO=Exact` and `NELM=1`. In such senario, the electronic step of the calculation will never truly converge. However, this is what we expect in non-self-consistent calculations, as we only have one electronic step. In this PR, I hacked the `converged_electronic` method of the `Vasprun` class, which will return `True` in this senario.
=> Fix: fixed electronic step check with algo = exact and nelm = 1

src/pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py, src/pymatgen/analysis/ewald.py, src/pymatgen/analysis/structure_matcher.py, src/pymatgen/core/structure.py, src/pymatgen/core/surface.py, src/pymatgen/core/tensors.py, src/pymatgen/phonon/bandstructure.py
The return signature of this function is currently `np.bool_` which can cause serialization problems with older atomate1 workflows.
Changed to `bool` instead.
=> return `bool` instead of `np.bool_`

src/pymatgen/io/cp2k/outputs.py, tests/io/cp2k/test_inputs.py, tests/io/cp2k/test_outputs.py
- Fix usage of `strict=True` during `zip` in `cp2k.outputs`, to fix #4079
- Rename and clean up some tests 
I have to revert to `strict=False` for now, but **it's better if we could know the reason for such mismatch**. Anyone experienced with CP2K please feel free to comment.
=> Fix usage of `strict=True` for `zip` in `cp2k.outputs`

src/pymatgen/core/sites.py, src/pymatgen/util/misc.py, tests/core/test_sites.py, tests/util/test_misc.py
- Fix dict equality check with numpy array, to fix #4085
- Added a helper function to compare two dicts because I have a feeling some other parts of the code might need it as well
Turns out  `np.testing.assert_equal` is much slower than `np.array_equal` for each value. See the following benchmark:
<details>
<summary>Script (by GPT)</summary>
```python
import numpy as np
import time
def dicts_equal_np_test_assert(d1, d2):
"""Compare two dictionaries using np.testing.assert_equal."""
try:
np.testing.assert_equal(d1, d2)
return True
except AssertionError:
return False
def dicts_equal_array_equal(d1, d2):
"""Compare two dictionaries by using np.array_equal."""
if d1.keys() != d2.keys():
return False
for key in d1:
if not np.array_equal(d1[key], d2[key]):
return False
return True
def …
```
=> Fix dict equality check with numpy array

docs/addons.md
I'm the maintainer of [ramannoodle](https://github.com/wolearyc/ramannoodle), an new API for calculating off-resonance Raman spectra from first principles calculations. The API includes an interface with pymatgen, and I wish to add it to pymatgen's list of external packages. 
Cheers,
Willis
=> added ramannoodle external package to addons.md

src/pymatgen/core/structure.py, src/pymatgen/io/aims/inputs.py, tests/io/aims/test_inputs.py
This pull request adds support for reading and writing files in FHI-aims `geometry.in` format to the `Structure` objects.
Major changes:
- Support for reading `geometry.in` file in `Structure.from_file` and `Structure.from_str` methods
- Support for writing FHI-aims formatted file in `Structure.to` method
```sh
```
=> Support to aims format from Structure instance

src/pymatgen/core/ion.py, tests/core/test_ion.py
My recent changes to `Ion` in #3991 introduced a problem in which the `reduced_formula` of `CO2(aq)` would incorrectly be shown as `C2O4(aq)`. Other properties such as `composition` etc were not affected.
```
>>> from pymatgen.core.ion import Ion
>>> Ion.from_formula('CO2').composition
Composition('C1 O2')
>>> Ion.from_formula('CO2').formula
'C1 O2 (aq)'
>>> Ion.from_formula('CO2').reduced_formula
'C2O4(aq)'
>>> Ion.from_formula('C2O4[-2]').composition
Composition('C2 O4')
>>> Ion.from_formula('C2O4[-2]').formula
'C2 O4 -2'
>>> Ion.from_formula('C2O4[-2]').reduced_formula
'C2O4[-2]'
```
This PR fixes the CO2(aq) problem and adds tests.
=> Ion: bugfix for CO2(aq) reduced formula

src/pymatgen/io/ase.py, tests/io/test_ase.py
The `get_atoms()` and `get_structure()` methods of the `pymatgen.io.ase.AseAtomsAdaptor` class now preserve PBC value of their input.
Intended to close #4120
=> Bugfix: Preserve PBC info in `AseAtomsAdaptor`

CONTRIBUTING.md
The most common usual workflow with `pytest` is just `pip install . && pytest`, but this doesn't apply to pymatgen because of the test files.
Since I had to dig (just a bit) in the sources to get `pytest` to run I figured I could help the next contributor by making it clear how to point to the files using an environment variable.
=> doc: make the test procedure explicit

src/pymatgen/io/pwscf.py, tests/io/test_pwscf.py
A quick regexp fixes + strengthened test cases to close #4114
=> Bugfix: Parsing bugs in `io.pwscf.PWInput`

src/pymatgen/io/aims/sets/base.py, tests/io/aims/sets/test_static_generator.py
This PR adds support of `use_structure_charge` keyword to a base FHI-aims input generator to make it more consistent with VASP and `atomate2` common defect workflows.
Major changes:
- support of `use_structure_charge` keyword to a base FHI-aims input generator
```sh
```
=> Add support for `use_structure_charge` keyword in FHI-aims input generator

src/pymatgen/io/aims/inputs.py, tests/io/aims/test_inputs.py
As of now, the basis set for the site in FHI-aims input files got chosen according to the site element. This PR enables the support of Species object when present in the structure, which should make setting up heterogeneous calculations with FHI-aims and Pymatgen easier.     
Major changes:
- Support for `species_string` in `SpeciesDefaults` class added
- Simplified creating string representation for `geometry.in` file, adding support for `species_string` there as well
=> Support Pymatgen Species object in aims

src/pymatgen/symmetry/analyzer.py, tests/symmetry/test_analyzer.py
Correct value is 2.
Example is H2. Also see See, for example, Table 10.1 and Appendix B of C. Cramer “Essentials of Computational Chemistry”, 2nd Ed.
=> Correctly compute rotational symmetry number for D*h point group

src/pymatgen/core/lattice.py, src/pymatgen/optimization/neighbors.pyx
- Minor clean up `neighbors.pyx` variable name, remnant from #4028, **I don't expect any functional changes**
- Use `unsigned int` (`npy_uint32`) over `int` for variables that we're certain would not be negative (counter, index when looping through "number of points/dimensions")
=> Clean up `neighbors.pyx` variable name

src/pymatgen/io/packmol.py, tests/io/test_packmol.py
Major changes:
- fix 1: One could not do packmol_input_set.run("randomdirectory"). Code would fail.
This PR fixes this small issue. Added (actually adapted) a unit test to make sure it continues to work.
=> Fixed execution of packmol in relative path.

src/pymatgen/io/vasp/help.py
* src/pymatgen/io/vasp/help.py (VaspDoc.get_incar_tags): Use Mediawiki API instead of parsing the HTML source directly.  The old approach is not stable against changes in the tag list because of the way URLs are constructed.  pagefrom= parameters start from certain tag, which is not guaranteed to provide the complete tag list as the new tags are added before that tag given in pagefrom=.  At the moment of writing this commit, PRECFOCK tag is already missed using the old approach.
Following up:  https://github.com/materialsproject/pymatgen/issues/4119#issuecomment-2439617604-permalink
=> VaspDoc.get_incar_tags: Use Mediawiki API

.github/workflows/test.yml
- I don't think we need `PMG_VASP_PSP_DIR` in editable mode
- [`matplotlib` test use non-interactive `agg` backend](https://matplotlib.org/stable/users/explain/figure/backends.html), as the [tk install for github windows runner seems pretty flaky](https://github.com/matplotlib/matplotlib/issues/29119#issuecomment-2469406065)
> The last, Agg, is a non-interactive backend that can only write to files. It is used on Linux, if Matplotlib cannot connect to either an X display or a Wayland display.
> The names of builtin backends are case-insensitive; e.g., 'QtAgg' and 'qtagg' are equivalent.
The tk backend might [emit intermittent failures](https://github.com/materialsproject/pymatgen/actions/runs/11771540044/job/32785607964?pr=4159) like:
```
>       self.tk = _tkinter.create(screenName, …
```
=> `matplotlib` test use non-interactive `agg` backend 

src/pymatgen/util/string.py, tests/io/test_cif.py, tests/util/test_string.py
- Clarify `util.string.formula_double_format` return type as `Literal[""] | float`
- Add types for `util.string`
- **Bug fix**: `int` would not round to nearest int (but truncate decimal part): https://github.com/materialsproject/pymatgen/blob/bd9fba9ec62437b5b62fbd0b2c2c723216cc5a2c/src/pymatgen/util/string.py#L136-L137
https://github.com/materialsproject/pymatgen/blob/bd9fba9ec62437b5b62fbd0b2c2c723216cc5a2c/src/pymatgen/util/string.py#L129
- **Two minor behavior changes** for `formula_double_format`:
1. Use `isclose` to round float very close to `1`:
```diff
- if ignore_ones and afloat == 1:
+ if ignore_ones and math.isclose(afloat, 1, abs_tol=tol):  
```
2. `tol` now includes the boundary (unit test added):
```diff
- if abs(afloat - int(afloat)) < tol:
+ if math.isclose(afloat, …
```
=> Clarify `util.string.formula_double_format` return type, fix using `int` to round to nearest int

src/pymatgen/transformations/standard_transformations.py, tests/transformations/test_standard_transformations.py
The situation we have in mind is `AutoOxiStateDecorationTransformation` -> `OrderDisorderedStructureTransformation` pipeline.
The `OrderDisorderedStructureTransformation` expects oxidation numbers to help rank the structure guesses.  However, if you have metallic systems, the sequences of transformation breaks.  In those cases it's not super clear how the ordered structures should be ranked anyways unless you start invoking more sqs-type logic.  For the simple case I think we can allow the users to come up with some quick and dirty guess for ordered structures so they can start computing stuff before they might move on to more fine-grained structure selection.
Added a new `zeros_on_fail` flag.
If True and and  the `BVAnalyzer` fails to come up with a guess for the oxidation guess, we will …
=> Added new Flag for `AutoOxiStateDecorationTransformation`

src/pymatgen/symmetry/analyzer.py
After pulling my hair out for a little while, trying to figure out why I was getting `SymmetryUndeterminedError`s when trying to initialise `SpacegroupAnalyzer` with a particular structure (which currently don't come with any message), I realised that `spglib.get_error_message()` can be called to get an error message for why no result was obtained. 
This is a small update to include the `spglib.get_error_message()` message in `SymmetryUndeterminedError`, so the user has some idea why it failed.
In action:
=> Add informative error message to `SymmetryUndeterminedError`

src/pymatgen/io/vasp/inputs.py
`NUPDOWN` key in Incar can be set to floating point values in VASP (see https://gitlab.com/ase/ase/-/merge_requests/2580). 
However, it is current treated as an int in `Incar.proc_val`. 
This PR treats `NUPDOWN` as a float instead.
=> Moved NUPDOWN from int_keys to float_keys

src/pymatgen/analysis/xas/spectrum.py, tests/analysis/xas/test_spectrum.py
The XAS spectrum class used to not throw a `ValueError` when more than 5% of the user-input intensities are non-positive (cverified this was still the behavior as of v2020.4.29).  More, the warning that is thrown is misleading, as it suggests that the majority of intensities are non-positive.
This change in behavior has led to issues with MP's API users, see [here for an example](https://matsci.org/t/avoiding-value-error-double-check-the-intensities-most-of-them-are-nonpositive/58748/2)
Changed this to throw a warning only when more than 5% of the intensities are ***negative***. Zero intensity shouldn't be penalized since this is physical (there's no absorption in that range, e.g. if a transition is forbidden)
Also added an option to zero out negative intensities (false by default)
=> Change XAS behavior under negative frequencies

src/pymatgen/core/composition.py, tests/core/test_composition.py
Often in alloy literature we get composition strings given in weight rather than molar quantities. This PR extends upon the `from_weight_dict` method to give a more general `from_weights` method that will take strings as well as CompositionLike
=> Compositions from weight str

src/pymatgen/util/testing.py, src/pymatgen/util/testing/__init__.py, tests/analysis/test_graphs.py, tests/core/test_structure.py, tests/symmetry/test_maggroups.py, tests/util/test_testing.py
- Fix `assert_str_content_equal` not raising `AssertionError` 
- Add unit tests for `util.testing` as it's intended for public usage (and [quite some external code use `PymatgenTest`](https://github.com/search?q=%22%28PymatgenTest%29%3A%22&type=code))
- More human-readable error messages for assert methods in `PymatgenTest`
- [**NEED CONFIRM**] Simplify single-file module `testing/__init__.py` to `testing.py`
---
> [!WARNING]  
> [**NEED CONFIRM**] Simplify single-file module `testing/__init__.py` to `testing.py` (**Is this intended for some purpose?**), I don't think this would be breaking (though the definition of `MODULE_DIR` would change from `util/testing` to `util`, but no code import this AFAIK as the `util/testing` has nothing else, I believe it's intended for `STRUCTURES_DIR` and …
=> Fix `assert_str_content_equal`, add tests for testing utils

src/pymatgen/core/composition.py, src/pymatgen/core/periodic_table.py, src/pymatgen/core/structure.py
- Remove redundant `total_ordering` decorator usage, as `total_ordering` is already applied on superclasses and child classes did not redefine any rich comparison operations.
- Clean up comment of  equality definition of `core.IStructure`
- Minor import clean up (avoid `from io import StringIO` when it's used only twice as `io` is already imported)
- Minor docstring clean up
=> Remove redundant `total_ordering` decorator usage

.github/workflows/test.yml
- Fix `uv pip install` from binary distribution (wheels) usage, https://github.com/astral-sh/uv/issues/8155#issuecomment-2506014815
- Use `uv` to build wheel, https://docs.astral.sh/uv/guides/integration/github/
- [**REVERTED**] Test `mcsqs` install in 3f63f4b341674e31d597506de4e6a64de4ed5ea3, it's way too slow ~90 s
=> Fix `uv pip install` from binary distribution (wheels) usage

src/pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
- Fix NumPy array indexing in 32-bit system, to close #4161
> https://numpy.org/doc/1.21/reference/arrays.scalars.html
I may use `intp` instead of `uintp` as I'm not 100% sure if the indexes could be negative or not in the code design.
Test platform: 
- `Linux debian32bit 6.1.0-27-686-pae #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) i686 GNU/Linux`
- Python 3.11.2
I don't think those three test failures are related to this PR.
```
.....................................ss...................................................................................................... [  4%]
.................................s.............................sss.......................................F........sssss.....s..s............. [  9%] …
```
=> Fix NumPy array indexing in 32-bit system in `analysis.chemenv.coordination_environments`

.github/workflows/test.yml, tests/io/test_phonopy.py
Skip another failing `phonopy` test in Windows after NumPy bumped to 2 in CI
- https://github.com/phonopy/phonopy/issues/476
I could recreate this in my Windows PC, all four tests failing for the same reason:
```
Python 3.10.0
phonopy==2.33.0
numpy==2.0.2
```
```
$ pytest tests/io/test_phonopy.py 
....FFFF...                                                                                                                                                       [100%]
=============================================================================== FAILURES ===============================================================================
_______________________________________________________ TestGetDisplacedStructures.test_get_displaced_structures …
```
=> Skip another failing `Phonopy` test in Windows after NumPy bumped to 2 in CI

src/pymatgen/transformations/standard_transformations.py, tests/transformations/test_standard_transformations.py
The current implementation assume some oxidation and tries to evaluate and Ewald energy to get the ordered representation with the lowest energy.
https://github.com/materialsproject/pymatgen/blob/da607e86f9ce8aec942067c6c1a4fda6e04915dd/src/pymatgen/transformations/standard_transformations.py#L558-L559
For large cells this has some disadvantages:
```python
matrix = EwaldSummation(struct).total_energy_matrix  # <<- This can run out of memory for cells with ~2000 atoms
ewald_m = EwaldMinimizer(matrix, manipulations, n_to_return, self.algo) # <<- This takes hours for cells with ~200 atoms
```
We need some way to indiscriminately generate random structures without Ewald evaluation. Since for larger cells the value proposition of explicitly enumerating all the ordered representations and …
=> [Feature] Added Pure Random Algo to `OrderDisorderedStructureTransformation`

pyproject.toml, tests/io/test_phonopy.py, tests/util/test_typing.py
- Bump `phonopy` to apply fix for NumPy 2 in Windows:
- https://github.com/phonopy/phonopy/issues/476
- Drop Python < 3.10 check
=> Bump `phonopy` to apply fix for NumPy 2 in Windows

src/pymatgen/io/exciting/inputs.py, tests/io/exciting/test_inputs.py
- Fix CI failure for `io.exciting.inputs` owing to `scipy` constant update https://github.com/scipy/scipy/pull/21605 https://github.com/materialsproject/pymatgen/blob/1abc45936f839369854399369bc966732f85bf08/src/pymatgen/io/exciting/inputs.py#L61-L62
- Add types
=> Fix CI failure for `io.exciting.inputs` owing to `scipy` constant update

src/pymatgen/core/composition.py, tests/core/test_composition.py
`Composition` objects initialised as e.g. `Composition({"Cd2+": 1, "Cd": 1, "Te2-": 2})` do not behave as expected, giving e.g. `Composition.formula = "Cd3 Te2"` instead of `Cd2 Te2`. This is due to `Composition.__getitem__()` matching all species and elements/non-species of a given input string; so that `Composition["Cd"]` here would return `2` (as desired), but than `Composition.items()` (which is use for `get_el_amt_dict`, `formula` and more) gives `("Cd2+", 1), ("Cd", 2), ("Te", 2)` which is incorrect.
In the end, it's an easy fix to just define the `items()` method to avoid the `Composition.__getitem__()` (which is only needed when the user does `Composition[...]`).
Test added, which failed with previous code and passes now.
Context: Took a while to find what was going on here. Was …
=> Fix `Composition` for mixed species & element compositions

src/pymatgen/entries/mixing_scheme.py, tests/entries/test_mixing_scheme.py
The run_type for entries had been changed from 'R2SCAN' to 'r2SCAN', whereas the `MaterialsProjectDFTMixingScheme()` is still expecting to find 'R2SCAN' entries.
As a result, all r2SCAN entries would be ignored when carrying out GGA(+U)/R2SCAN mixing scheme corrections, thereby affecting the construction of GGA(+U)/R2SCAN mixing phase diagram [^1].
Error message would be:
```
pymatgen\entries\mixing_scheme.py:176: UserWarning: Invalid run_type='r2SCAN' for entry mp-1018134-r2SCAN. Must be one of ['GGA', 'GGA+U', 'R2SCAN']. This entry will be ignored.
```
[^1]: https://docs.materialsproject.org/methodology/materials-methodology/thermodynamic-stability/phase-diagrams-pds#gga-ggau-r2scan
=> Make run_type in mixing scheme consistent with entries

src/pymatgen/core/structure.py, tests/core/test_structure.py
- Update tests to verify reproducible random perturbations with same seed
- Add test cases for different seed values and min_distance parameter
=> Add `seed: int = 0` parameter to `Structure.perturb()` method

pyproject.toml, src/pymatgen/core/structure.py, tests/core/test_structure.py
`moyopy` is a successor to `spglib` that's faster and written in Rust. in my usage so far for analyzing MLFF-relaxed WBM structures for https://matbench-discovery.materialsproject.org/tasks/geo-opt, it seems about 4x faster than `spglib` and gives identical results in nearly all 257k cases. a few exceptions were reported in https://github.com/CompRhys/aviary/pull/96 and resolution tracked in https://github.com/spglib/moyo/issues/54
this PR adds a convenience method for directly accessing `moyopy` symmetry analysis results on pymatgen `Structures`. it also defines a new optional dependency set `symmetry` in `pyproject.toml`
```
symmetry = ["moyopy>=0.3", "spglib>=2.5"]
```
pinging @lan496
related ASE issue: https://gitlab.com/ase/ase/-/issues/1612
=> Add `Structure.get_symmetry_dataset` convenience method

src/pymatgen/core/composition.py, src/pymatgen/io/vasp/outputs.py, tests/core/test_composition.py
This PR extends the existing bracket normalization for square brackets `[...]` to curly brackets `{...}`. Important e.g. for a few of the 8k+ metallic glass compositions reported in Ward et al. (2018) https://doi.org/10.1016/j.actamat.2018.08.002. previously, some of those formulas raised
```py
ValueError: Invalid formula: {[(Fe0.6Co0.4)0.75B0.2Si0.05]0.96Nb0.04}100
```
i added 5 unit tests to ensure they now parse correctly
=> `Composition` support formula strings with curly brackets

src/pymatgen/core/units.py, tests/core/test_units.py
- Remove deprecated memory units from `core`
=> Remove deprecated memory units from `core`

src/pymatgen/transformations/standard_transformations.py, tests/transformations/test_standard_transformations.py
Major changes:
- fix 1:  Fixed incompatibility between `OrderDisorderedStructureTransformation` and `StandardTransmuter`:
- Previously, `occ_tol` was a method parameter in `apply_transformation`, making it unconfigurable when used with `StandardTransmuter` (which only passes transformation and optionally `extend_collection` parameters when calling `append_transformation`)
- Moved `occ_tol` to class initialization to allow proper configuration when used in transformation chains
```sh
```
=> Move `occ_tol` to init in `OrderDisorderedStructureTransformation`

src/pymatgen/analysis/local_env.py, src/pymatgen/electronic_structure/dos.py, src/pymatgen/util/coord.py, tests/util/test_coord.py
This is a small but important fix for the `get_linear_interpolated_value` function in `pymatgen.util.coord`, used in various places within the codebase. 
This function works by finding the first index in `x_values` that is greater than / equal to `x`, and then uses this index and the previous (`idx-1`) with `x_values` and `y_values` to interpolate:
https://github.com/materialsproject/pymatgen/blob/v2025.2.18/src/pymatgen/util/coord.py#L136-L147
The issue is that if the _first_ index in `x_values` is equal to `x`, this causes the ValueError to be thrown (as `indices[0]==0`); where it thinks that the input `x` to interpolate is outside the interpolable range. Changing the inequality to `>` rather than `>=` resolves this issue.
MWE:
```
from pymatgen.util.coord import …
```
=> Update inequality in `get_linear_interpolated_value`

src/pymatgen/analysis/magnetism/analyzer.py
This was previously obscured by a hard-coded `num_orderings` class attribute.
=> `MagneticStructureEnumerator`: Expose `max_orderings` as a keyword argument

src/pymatgen/io/ase.py, tests/io/test_ase.py
This PR resolves #4289. There were bugs in `pymatgen.io.ase.AseAtomsAdaptor` in which `Structure` and `ase.Atoms` objects were modified when converted into one another. Specifically, `Atoms.info` and `Structure.properties` shared memory, leading to side effects. 
Minor changes:
- `AseAtomsAdaptor` now uses `deepcopy` when converting `Atoms.info` to `Structure.properties` and vice versa 3d477472f93b4ee4ad9cc47fe827a59b9e3d912f
- Added tests to check for side effects and check space group dictionary <-> `ase.spacegroup.Spacegroup` interconversion 1730f29eb617f15ce13a8977104d18c3dfb871bb
=> Bugfix: Structure/ase.Atoms interconversion side effects

src/pymatgen/core/structure.py, tests/core/test_structure.py
- `IStructure.to` default to JSON when `filename` not specified, to close #4305
=> `IStructure.to` default to JSON when `filename` not specified

src/pymatgen/ext/matproj.py, tests/ext/test_matproj.py
Remove legacy MPRester tests from `TestMPResterNewBasic`, I believe some test methods (commented out previously, and recovered in #4027) are testing methods from the legacy MPRester (while being inside `TestMPResterNewBasic`), maybe we should remove them altogether?
ping @ml-evs for review?
=> Remove legacy MPRester method tests from `TestMPResterNewBasic`

src/pymatgen/io/qchem/outputs.py
I updated several I/O parsers in `pymatgen.io.qchem.outputs` such that they are properly type-hinted with `str | Path` arguments rather than just `str`.
=> Update type-hinting for `pymatgen.io.qchem.outputs`

src/pymatgen/symmetry/groups.py, tests/symmetry/test_groups.py
- Fix circular import of `SymmOp`, to close #4309
Looks like the import of `SymmOp` was added in #4177, @tpurcell90 do we have a reason to import `SymmOp` at runtime? https://github.com/materialsproject/pymatgen/blob/482ffd01312e7607c58bdd3ed285bf8a45e405bf/src/pymatgen/symmetry/groups.py#L24-L33
=> Fix circular import of `SymmOp`

src/pymatgen/core/lattice.py, tests/core/test_structure.py
- `core.Lattice` cast `pbc` to `bool` (possibly `np.bool_`), to close #4339
=> `core.Lattice` cast `pbc` to `bool` (possibly `np.bool_`)

src/pymatgen/io/vasp/outputs.py
From profiling my `Vasprun` initialisations, I found that one of the main contributions to runtime was repeated `Incar.get()` calls:
https://github.com/materialsproject/pymatgen/blob/31aa2148f85fcd3f01461e269a06b0186f82a22b/src/pymatgen/io/vasp/inputs.py#L847
This can be slow when called many times because of the `UserDict.get()` implementation from `collections.abc` and formatting code. Because `incar.get("ML_LMFF")` was being used in the `Vasprun` parsing loop, this method was called e.g. 1e4 - 1e6+ times in my vasprun parsing. Changing this so that `incar.get("ML_LMFF")` is only called once to determine if the vasp run is an ML run, means `incar.get` only gets called ~20 times and reduces the vasprun parsing time by ~20-50% (depending on choices of `parse_dos` and …
=> Avoid repeated `Incar.get()` calls which slow down vasprun parsing by ~20-50%

src/pymatgen/io/vasp/outputs.py
Me again.
From further profiling and playing around, I found I could speed up `_parse_vasp_array` (one of the main bottlenecks when using `parse_dos = True` (default), `parse_eigen = True` (default) and/or `parse_projected_eigen = True` (False by default)), using `numpy`'s parse from string function.
e.g. parsing a SOC defect supercell vasprun via [`doped`](https://doped.readthedocs.io/en/latest/) with these updates (with `parse_projected_eigen=True` to get eigenvalues/magnetisation) decreases parsing time from ~8.5s to ~4.8s.
All changes here should be covered by tests already in the codebase.
=> Speed up `Vasprun` parsing some more

src/pymatgen/io/vasp/outputs.py, tests/io/vasp/test_outputs.py
Just a minor fix; after #4360 the format of `actual_kpoints_weights` was changed from `list[float]` to `list[np.ndarray[float]]` (where these were `np.ndarray[float]` with a single value). Minor thing but this changes the format back to what it was before, and adds a quick test for this.
=> Ensure `actual_kpoints_weights` is `list[float]` and add test

src/pymatgen/io/vasp/sets.py, tests/io/vasp/test_sets.py
When `auto_dipole=True`, `MVLSlabSet` was passing a NumPy array into the INCAR’s DIPOL tag, causing pymatgen to serialize it with brackets (e.g. `DIPOL = [0.1 0.2 0.3]`). VASP expects three space‑separated floats without any brackets: https://www.vasp.at/wiki/index.php/DIPOL. 
This PR converts the computed center‑of‑mass array into a plain Python `list[float]` (via `.tolist()`), ensuring the INCAR writes
`DIPOL = 0.1 0.2 0.3`
instead of
`DIPOL = [0.1 0.2 0.3]` 
which errors out with the recent VASP 6.4. 
Major changes:
- fix 1: In `MVLSlabSet.incar_updates`, replace `center_of_mass` (a NumPy array) with a pure python list = `com.tolist()` 
```sh
```
=> fix(MVLSlabSet): convert DIPOL vector to pure Python list before writing INCAR

src/pymatgen/core/structure.py
Major changes:
- fix 1: If I'm not mistaken, #4270 added a random seed parameter to Structure.perturb() but ended up setting the same random vector for all atoms. This should probably be fixed by pulling the seed-setting line out of the get_rand_vec() function.
=> fix perturb bug that displaced all atoms equally

.github/workflows/release.yml, .github/workflows/test.yml, pyproject.toml
- Python 3.13 support (previously #4100), to close #4284
```
wget https://vampire.york.ac.uk/resources/release-5/vampire-5.0-linux.tar.gz
--2025-04-18 10:45:13--  https://vampire.york.ac.uk/resources/release-5/vampire-5.0-linux.tar.gz
Resolving vampire.york.ac.uk (vampire.york.ac.uk)... 144.32.124.80, 2001:630:61:17c::1:50
Connecting to vampire.york.ac.uk (vampire.york.ac.uk)|144.32.124.80|:443... connected.
ERROR: cannot verify vampire.york.ac.uk's certificate, issued by ‘CN=Sectigo ECC Organization Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
Unable to locally verify the issuer's authority.
To connect to vampire.york.ac.uk insecurely, use `--no-check-certificate'
```
=> Python 3.13 support

src/pymatgen/io/jdftx/jdftxinfile_ref_options.py
Beginning process of merging over stress-test updates, starting with missing options for JDFTx input files
- Added missing DFT functional names
- Added missing subtags for elec-minimize
=> Adding missing reference options to JDFTx inputs submodule

src/pymatgen/io/jdftx/_output_utils.py
Major changes:
- function `get_colon_var_t1`
-- Renaming to `get_colon_val`, but keeping an alias until renaming is updated outside this module
-- Returning `np.nan` instead of `None` when "nan" is the value
- updating `correct_geom_opt_type` for working with JDFTx AIMD out files
- updating typing on array-construction functions
- correcting ordering and syntax of orbital labels to exactly match JDFTx
=> Update JDFTx IO output utils private module

src/pymatgen/analysis/molecule_matcher.py, tests/analysis/test_molecule_matcher.py
This is a small PR to add a `break_on_tol` option to `BruteForceOrderMatcher`, which allows one to massively speed up the molecule matching in cases where one just cares _if_ the molecules match within a given RMSD (rather than screening over _all_ possible permutations, to get the lowest possible RMSD). 
The speedup factor can be anywhere from 0% to several orders of magnitude, depending on the number of possible permutations and when a matching permutation is found.
Also includes a small typo fix that for an error message that reference the original class name (in https://github.com/materialsproject/pymatgen/pull/1938) which was later renamed. 
I've also added some tests for this.
=> Brute force order matcher speedup

src/pymatgen/io/jdftx/generic_tags.py, tests/io/jdftx/test_generic_tags.py
Major changes:
- Phasing out use of redundant `TagContainer.multiline_tag` attribute
-- (this change may cause problems without the corresponding changes in `jdftxinfile_master_format.py`, but all the tests still pass. Just in case, I will be prioritizing finishing merges for the JDFTx inputs module to avoid any untested consequences)
- Fixing indentation on output of `TagContainer.write`
- Removing the warning (and the test for this warning) on special constraints for "ion" tag
-- Support for special constraints has been implemented on my fork and a PR for this support will soon be created
=> Updates to JDFTx inputs `generic_tags` helper module

tests/files/io/jdftx/test_jdftx_out_file_sections/ex_out_slice_latmin, tests/files/io/jdftx/test_jdftx_out_files/example_latmin.out, tests/files/io/jdftx/test_jdftx_out_files/latticeminimize_different.out, tests/files/io/jdftx/test_jdftx_out_files/partial_lattice_init.out
Many of the example out files were obtained during a brief period of time where a bug in JDFTx caused the printed value of the "fluid-ex-corr" tag to contain an un-string-able value, that was replaced by the string "(null)" to allow parsing. In an upcoming change to the outfile parser, JDFTXInfile objects are created from this portion of the out file, and will fail parsing these files as "fluid-ex-corr (null) lda-PZ" is an invalid JDFTx input tag.
=> Fixing "(null)" in JDFTx example out files

src/pymatgen/io/jdftx/jdftxoutfileslice.py, src/pymatgen/io/jdftx/outputs.py, tests/io/jdftx/shared_test_utils.py, tests/io/jdftx/test_jdftxoutfile.py
- Fixing an error in `pymatgen/io/jdftx/outputs.py` that causes construction of a `JDFTXOutfile` to fail if none_on_error is turned on and the final `JDFTXOutfileSlice` in `slices` is None (ie a very common issue when parsing an interrupted job that hasn't restarted yet).
-- Fix tested in `tests/io/jdftx/test_jdftxoutfile.py`
-- Expanding function `assert_same_value` of `tests/io/jdftx/shared_test_utils.py` to work when encountering numpy arrays (needed for testing this fix)
- Removing missed commented out code
=> JDFTXOutfile `none_on_error` oversight fix

src/pymatgen/analysis/reaction_calculator.py, src/pymatgen/entries/compatibility.py, src/pymatgen/entries/computed_entries.py, tests/analysis/test_reaction_calculator.py
=> Use `np.nan` instead of 0 for no uncertainty with `ufloat`, to avoid unnecessary warnings

src/pymatgen/io/jdftx/inputs.py, tests/io/jdftx/test_jdftxinfile.py
Major changes:
- fix 1: `pymatgen.io.jdftx.inputs.JDFTXStructure`
-- `JDFTXStructure.from_jdftxinfile` no longer assumes 'lattice' tag is provided in 3x3 matrix format
-- Testing in `tests/io/jdftx/test_jdftxinfile.py` for `Structure <-> JDFTXStructure <-> JDFTXInfile` conversion for `JDFTXInfile` with newly implemented special case values for 'lattice' tag
TODO:
-  Implement `JDFTXStructure.from_jdftxinfile` for JDFTXInfile with special case tag 'lattice' value and non-identity value for 'latt-scale' tag
=> JDFTXStructure - partial fix for special case lattice tags

src/pymatgen/transformations/standard_transformations.py, tests/transformations/test_standard_transformations.py
Close #4402 by ensuring that structures are always symmetrized when `symmetrized_structures = True` in `OrderDisorderedStructureTransformation`. Also allow for passing distance/angle precision kwargs to do on-the-fly symmetrization. Add tests
=> Ensure structure symmetrization in OrderDisorderedStructureTransformation

src/pymatgen/entries/compatibility.py, src/pymatgen/entries/computed_entries.py
This is a minor addition to https://github.com/materialsproject/pymatgen/pull/4400.
I found that there were some cases where an energy adjustment of `UFloat(0, 0)` were already present in `ComputedEntry.energy_adjustments`, avoiding the updated handling of setting `std_dev` to `np.nan` when it is 0 (and avoiding the `UFloat` warning about `std_dev` being 0).
When accessing the MP database and pulling ozonide structures (for which the MP Anion Correction is set to 0, with std_dev 0), it throws the `UFloat` warning again.
MWE:
```python
from pymatgen.ext.matproj import MPRester
with MPRester() as mpr:
entries = mpr.get_entries_in_chemsys("Na-O")
for entry in entries:
print(entry.name, entry.energy_adjustments)
```
where one of the outputs is:
```
NaO3 …
```
=> `UFloat` update

src/pymatgen/symmetry/analyzer.py, tests/symmetry/test_analyzer.py, tests/symmetry/test_kpath_sc.py
This issue is related to https://github.com/materialsproject/pymatgen/issues/1929 (for which a patch solution was added that fixed one case of this occurrence, but not in general).
When handling monoclinic symmetry within `SpacegroupAnalyzer`, the standardisation attempts to reorder the lattice vectors depending on whether the alpha angle is >90 degrees or <90 degrees. If it is exactly 90 degrees, it defaults to the original lattice, however there was an issue with this implementation where it assumed that the beta and gamma angles were also 90 degrees (and so set the lattice matrix as `[[a, 0, 0], [0, b, 0], [0, 0, c]]`), which may not (and in most cases should not) be the case.
This was causing weird behaviour for me where the volume of the primitive structures being returned by …
=> Monoclinic Symmetry Handling Fix

src/pymatgen/io/jdftx/inputs.py, tests/io/jdftx/test_jdftxinfile.py
Changing addition method - now infiles with shared keys will either concatenate their inputs if the key is for a repeatable tag, or change to whatever value is in the second infile if it is not a repeatable tag. A bare minimum `if subval in params[key]` check is done to avoid adding duplicate values. This seems like something the `set` built-in could help with, but since the sub-values are dictionaries, using `set` is a little more difficult
Major changes:
- fix 1: Addition of two JDFTXInfiles (`jif1 = jif2 + jif3`) no longer requires each `jif2` and `jif3` to have a unique set of tags
-- For a non-repeatable tag 'key', `jif1['key'] == jif3['key']`
-- For a repeatable-tag 'key', `jif1['key'] = jif2['key'] + [val for val in jif3['key'] if not val in jif2['key']`
-- implemented in …
=> JDFTXInfile addition (`__add__`) method tweak

src/pymatgen/io/jdftx/generic_tags.py, src/pymatgen/io/jdftx/inputs.py, src/pymatgen/io/jdftx/jdftxinfile_ref_options.py, src/pymatgen/io/jdftx/jdftxoutfileslice.py, src/pymatgen/io/jdftx/outputs.py, tests/io/jdftx/test_jdftxinfile.py
Major changes:
- feature 1: Method `to_jdftxinfile` for JDFTXOutfile(Slice)
-- Uses internal `JDFTXInfile` and `Structure` to create a new `JDFTXInfile` object that can be ran to restart a calculation
- feature 2: Method `strip_structure_tags` for `JDFTXInfile`
-- Strips all structural tags from a `JDFTXInfile` for creating equivalent `JDFTXInfile` objects with updated associated structures
- fix 1: Changing 'nAlphaAdjustMax' shared tag from a `FloatTag` to an `IntTag`
- fix 2: Adding an optional `minval` field for certain `FloatTag`s which prevent writing error-raising values
-- Certain tag options in JDFTx can internally be the minimum value, but trying to pass the minimum value will raise an error
- feature 1: Testing for the `to_jdftxinfile`
-- I know the function works from having …
=> `to_jdftxinfile` method for JDFTXOutfile

src/pymatgen/io/jdftx/generic_tags.py, src/pymatgen/io/jdftx/inputs.py, src/pymatgen/io/jdftx/jdftxinfile_ref_options.py, src/pymatgen/io/jdftx/jdftxoutfileslice.py, tests/io/jdftx/test_generic_tags.py
Major changes:
- feature 1: Revised boundary checking for input tags
-- Added a `validate_value_bounds` method to `AbstractTag`, that by default always returns `True, ""`
-- Added an alternate `AbstractNumericTag` that inherits `AbstractTag` to implement `validate_value_bounds` properly
--- Changed boundary storing to the following fields 
---- `ub` and `lb`
----- Can either be `None`, or some value to indicate an upper or lower bound
---- `ub_incl` and `lb_incl`
----- If True, applies `>=` instead of `>` in comparative checks on upper and lower bounds
-- Switched inheritance of `FloatTag` and `IntTag` from `AbstractTag` to `AbstractNumericTag`
-- Implemented `validate_value_bounds` for `TagContainer` to dispatch checking for contained subtags
-- Added a method `validate_boundaries` to …
=> JDFTx Inputs - boundary value checking

src/pymatgen/core/periodic_table.py
This PR speeds up the instantiation of `Structure` objects by preventing hash collisions in the `lru_cache` of `get_el_sp` and increasing its `maxsize`. The issue is that currently `Element` objects are hashed to the same value as the integer atomic numbers (e.g., `Element[H]` maps to the same hash as `int(1)`). This forces the `lru_hash` to perform an expensive `__eq__` comparison between the two, which reduces the performance of instantiating many `Structure` objects. Also here we increase the `maxsize` of `get_el_sp`'s `lru_cache` to 1024 for further performance improvements.
This reduces time taken to instantiate 100,000 `Structure` objects from 31 seconds to 8.7s (avoid hash collisions) to 6.1s (also increase `maxsize` to 1024). Test snippet:
```python
from pymatgen.core import …
```
=> speed-up Structure instantiation

src/pymatgen/io/jdftx/_output_utils.py, src/pymatgen/io/jdftx/outputs.py, tests/io/jdftx/test_jdftxoutput.py
Major changes:
- feature 1: Added 'kpts' storable variable to JDFTXOutputs
-- Currently only able to obtain from the 'bandProjections' file
- feature 2: Added `bandstructure` attribute to JDFTXOutputs
-- Standard pymatgen `BandStrucure` object
-- Request-able as a `store_var`, but functions slightly differently
--- Ensures 'eigenvals' and 'kpts' are in `store_vars` and then is deleted
-- Initialized if JDFTXOutputs has successfully stored at least 'kpts' and 'eigenvals'
-- Fills `projections` field if also has stored 'bandProjections'
- feature 3: Added `wk_list` to `JDFTXOutputs`
-- List of weights for each k-point
-- Currently doesn't have a use, but will be helpful for `ElecData` initializing in [`crawfish`](https://github.com/benrich37/crawfish)
- feature 1: Add reading 'kpts' from …
=> `JDFTXOutputs.bandstructure: BandStructure`

src/pymatgen/core/structure.py, tests/core/test_structure.py
In `Molecule.get_boxed_structure`, when `reorder=False`, in the current version of the code does not use the processed new coordinates, but the initial ones of the Molecule. This usually results for example in a Molecule not being centered in the box.
Unless I am missing something there should be no reason not to use the modified coordinates in the case of `reorder=False`. This PR switches to use the same coordinates independently of the final sorting.
I added a test based on the coordinates that would have failed in the previous implementation due to the molecule not being centered in the box.
=> Fix Molecule.get_boxed_structure when reorder=False

src/pymatgen/io/common.py, tests/io/vasp/test_outputs.py
Minor changes:
- Added ```__radd__``` method to VolumetricData to avoid errors associated with operations like `sum([chgcar1, chgcar2, ... etc] )` 
- Added test in `test_outputs.py` to check if method works
All tests passing 
`125 passed, 9 warnings in 69.04s (0:01:09)`
=> adding radd dunder method to Volumetric data + test_outputs

src/pymatgen/cli/pmg_config.py, src/pymatgen/core/composition.py, src/pymatgen/io/vasp/inputs.py, tests/io/vasp/test_help.py
Modifies the pymatgen CLI to use the same POTCAR library directory structure as in `pymatgen.io.vasp.inputs` to close #4430. Possibly breaking from the CLI side (the directory structure will change)
Pinging @mkhorton since #4424 was probably motivated by similar concerns?
=> Single source of truth for POTCAR directory structure

.github/workflows/_install_opt_unit_deps.sh, .github/workflows/test.yml, pyproject.toml, src/pymatgen/command_line/mcsqs_caller.py, src/pymatgen/io/zeopp.py, tests/analysis/chemenv/coordination_environments/test_coordination_geometry_finder.py, tests/analysis/test_graphs.py, tests/analysis/test_molecule_structure_comparator.py, tests/analysis/test_piezo_sensitivity.py, tests/analysis/test_surface_analysis.py, tests/command_line/test_gulp_caller.py, tests/command_line/test_mcsqs_caller.py, tests/command_line/test_vampire_caller.py, tests/core/test_structure.py, tests/core/test_surface.py, tests/core/test_xcfunc.py, tests/electronic_structure/test_boltztrap.py, tests/electronic_structure/test_boltztrap2.py, tests/electronic_structure/test_plotter.py, tests/io/qchem/test_outputs.py, tests/io/test_zeopp.py, tests/io/vasp/test_inputs.py, tests/io/vasp/test_sets.py, tests/transformations/test_advanced_transformations.py
Current we have a few issues with the optional ubuntu/macos dependency install in CI pipeline:
- [Replace some `skip` marks with `xfail`](https://docs.pytest.org/en/stable/how-to/skipping.html), personally I think with `xfail` mark it's easiler to find tests that we want to do something about it (broken test to be fixed and so on), while for `skip` it's something we expect we work as is (skip windows for non-windows compatible function, or skip when dependency not available):
> An xfail means that you expect a test to fail for some reason. A common example is a test for a feature not yet implemented, or a bug not yet fixed.
=> Cache macos/ubuntu optional dependency install in CI pipeline, enable `mcsqs/pyzeo` tests

src/pymatgen/io/gaussian.py
Major changes:
- Patches ReDOS vulnerability mentioned in #2755
```sh
```
=> patch ReDOS vulnerability in GaussianInput.from_string

.github/workflows/test.yml, src/pymatgen/io/jdftx/outputs.py, tests/io/abinit/test_netcdf.py
[Fix the following 3.11+ only syntax](https://docs.python.org/3/reference/expressions.html?utm_source=chatgpt.com#subscriptions):
> Changed in version 3.11: Expressions in an expression list may be starred. See [PEP 646](https://peps.python.org/pep-0646/).
```
E     File "/home/yang/pmg/src/pymatgen/io/jdftx/outputs.py", line 328
E       projections[spins[i]][:, :, *u_to_oa_map[u]] += proj_sjku[i, :, :, u]
E                                   ^
E   SyntaxError: invalid syntax
```
cc @benrich37
=> Fix jdftx.outputs usage of 3.11+ only syntax

src/pymatgen/io/jdftx/BaseJdftxSet.yaml, src/pymatgen/io/jdftx/sets.py, tests/io/jdftx/test_sets.py
Following a request by @utf in an atomate2 [PR](https://github.com/materialsproject/atomate2/pull/955), I am moving our input set from atomate2 to pymatgen.
This PR adds a `sets.py` file with one new class, `JdftxInputSet`, which does little more than wrap the other JDFTx I/o classes. The only minor change to the original atomate2 code is that the `__init__` method now accepts a pymatgen `Structure` instead of a `JDFTXStructure`. 
A yaml defining the base input set, `BaseJdftxSet.yaml` was also moved from atomate2.
I added two basic tests to check that both loading from an input file and from a `JdftxInfile` are working and that the file written by the input set yields the expected `JdftxInfile`.
=> Move JDFTx sets from atomate2 to pymatgen

src/pymatgen/transformations/site_transformations.py, tests/transformations/test_site_transformations.py
There was a bug in the `TranslateSitesTransformation` class. Both index variables in `apply_transformation` are named identically. The test case did not capture this error. I changed the existing test case to fail when run with the old code and renamed the variables.
=> Fix TranslateSitesTransformation

.github/workflows/jekyll-gh-pages.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
fix #4509
tested in my fork: https://github.com/DanielYang59/pymatgen/actions/runs/18279908313/job/52040659228
```diff
dist/pymatgen-2025.6.14-cp313-cp313-macosx_10_13_x86_64.whl
dist/pymatgen-2025.6.14-cp312-cp312-win32.whl
dist/pymatgen-2025.6.14-cp310-cp310-win_amd64.whl
dist/pymatgen-2025.6.14-cp313-cp313-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
dist/pymatgen-2025.6.14-cp311-cp311-win_amd64.whl
dist/pymatgen-2025.6.14-cp311-cp311-macosx_10_9_x86_64.whl
dist/pymatgen-2025.6.14-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
dist/pymatgen-2025.6.14-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
dist/pymatgen-2025.6.14-cp311-cp311-win32.whl …
```
=> Fix missing sdist from PyPI
